### ISSUE TITLE
Actual dependencies instead of devDependencies

### ISSUE THREAD

**Issue by vincentsels** [ericgio/react-bootstrap-typeahead#1]
It looks like all of your dependencies are set as devDependencies, however you use several of them in your lib code. Shouldn't those be included as actual dependencies? I've identified these, but there might be more:

    "dependencies": {
      "lodash": "^3.10.1",
      "react": "^0.14.2",
      "react-dom": "^0.14.2",
      "react-input-autosize": "^0.6.2",
      "react-onclickoutside": "^4.1.1",
      "classnames": "^2.2.0"
    },

**Comment by ericgio** [comment]
Thanks @vincentsels I'll take a look and update the package.

**Comment by ericgio** [comment]
Published version 0.1.4 with updated dependencies
