### ISSUE TITLE
Let's have the removable token not be a <button> 

### ISSUE THREAD

**Issue by CHedgren** [ericgio/react-bootstrap-typeahead#10]
In firefox buttons capture all events so children cannot be interactive, this is according to spec.
The official examples http://ericgio.github.io/react-bootstrap-typeahead/ are also broken in Firefox. 
I propose that instead of rendering a button we render a div aria role button, etc. 
PR incoming.

**Comment by ericgio** [comment]
Thanks for the report and the PR.

**Comment by ericgio** [comment]
Fixed in v0.3.2
