### ISSUE TITLE
Add `renderMenu` prop

### ISSUE THREAD

**Issue by ericgio** [ericgio/react-bootstrap-typeahead#102]
I get lots of requests for the ability to have more control over rendering and behavior of the menu. Users should have a way to pass their own menu component, ideally composed of smaller pieces also provided by the module. Something like:

``` jsx
<Typeahead
  ...
  renderMenu={(results, props) {
    <MyCustomMenu
      {...props}
      results={results}
    />
  }}
/>
```
- `results` are the filtered options
- `props` are all the props that are currently passed to the Menu internally, like `activeIndex`, etc.

**Comment by xiaonongshishui** [comment]
I have updated to the latest version but this prop can not be used ...

**Comment by ericgio** [comment]
Correct, it has not been implemented yet. That's why the issue is still open :)

**Comment by xiaonongshishui** [comment]
..............so if I want to add a title to the menu,is there any way to achieve???

**Comment by ericgio** [comment]
Not currently, no. Sorry.

**Comment by xiaonongshishui** [comment]
Thanks for responding,I'm looking forward to this new prop.........

**Comment by mumumumu** [comment]
👍  I'm trying to add something like [optgroups](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) and I think this would help a lot with that.

**Comment by ericgio** [comment]
Try out the latest beta version of v1.0.0, which includes this functionality. The live example uses v0.10.x, but if you clone the 1.0 branch, that includes the functionality you're talking about. Here's the implementation: https://github.com/ericgio/react-bootstrap-typeahead/blob/1.0/example/components/CustomMenu.react.js

**Comment by ericgio** [comment]
v1.0.0 is now available, with the `renderMenu` prop. See [example](http://ericgio.github.io/react-bootstrap-typeahead/#rendering) for usage.
