### ISSUE TITLE
cross to clear the input box

### ISSUE THREAD

**Issue by aferrandi** [ericgio/react-bootstrap-typeahead#103]
Hei,

if I open your live site http://ericgio.github.io/react-bootstrap-typeahead/ with Edge, after I selected a state, if I click again on the input box a cross symbol appears on the left of the input box, giving me the possibility to clear it.
If I open it with Chrome there is no cross symbol, therefore I have to delete the content of the input box manually.
The same thing happens with the application I developed using react-bootstrap-typeahead, with two different versions of chrome on two different pcs.
Did I do something wrong?

**Comment by ericgio** [comment]
You didn't do anything wrong, that just sounds like Edge adds its own features to form inputs:

http://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs
