### ISSUE TITLE
How to close filter when the input change

### ISSUE THREAD

**Issue by xiaonongshishui** [ericgio/react-bootstrap-typeahead#105]
Hi,I just don't want it to filter my options ,but to ajax data from server when the input change,how can I close this function?

**Comment by ericgio** [comment]
Thanks for your question. In the future, please be sure to read through the [documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/README.md) and [contribution guidelines](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/CONTRIBUTING.md) before opening an issue.

- The documentation includes [a section about data fetching](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/README.md#data-sources) (tldr; you need to handle this yourself).
- Others have asked similar questions, and there's [an issue open to address this](https://github.com/ericgio/react-bootstrap-typeahead/issues/78) with some examples.
- Finally, please ask questions like this on StackOverflow, which helps limit the issue tracker to bugs and feature requests, and is a much more appropriate forum for getting help.
