### ISSUE TITLE
Allow 'labelKey' prop to take a function

### ISSUE THREAD

**Issue by kav** [ericgio/react-bootstrap-typeahead#106]
if my options data comes back from the server looking like this
```javascript
[{ id:1,
  firstName: 'James',
  lastName: 'Joyce'
},{ id:2,
  firstName:'Robert'
  lastName:'Faulkner'
}]
```
I'd love to show _lastName, _firstName__ in the label.

I'd like to set labelKey to a function that takes an option and returns the typeahead for that option in a similar fashion to the function for rendering children.

Today I can pre-parse data and add a `label` property, but that's rather error prone and puts some ui formatting pretty far away from the rest.

What do you think? I can work on a PR here if this sounds reasonable.

**Comment by ericgio** [comment]
What you're asking for is already doable in other ways. As you mention, you can easily iterate over your data and add a `label` or `name` field. You can also use `renderMenuItemChildren` to specify what you want to display. Ultimately, you're using essentially the same callback while iterating over the same data. Given that, I'm not sure I understand what your solution provides that these other solutions don't.

**Comment by kav** [comment]
I use a different render function for renderMenuItemChildren, in that case I blow the object out to show additional details (say address or email) that don't make sense in the token list. But as you note, it can be worked around. It's not the end of the world but it seems like something that could fold nicely into the existing props pattern

**Comment by ericgio** [comment]
I guess I had forgotten about rendering the selection(s), so `renderMenuItemChildren` only gets you part of the way there. So yeah, currently you'd have to pre-process your data, which I think is reasonable. That said, your solution of passing a callback to `labelKey` could actually work pretty well. Something like
```
<Typeahead labelKey={o => `${o.firstName} ${o.lastName}`} ... />
```
Feel free to take a stab at a PR if you're up for it. I'm not sure when I'd get to something like this.

**Comment by ericgio** [comment]
I'll publish this as v0.10.4. Thanks for the contribution!
