### ISSUE TITLE
have option to hide dropdown menu

### ISSUE THREAD

**Issue by letranloc** [ericgio/react-bootstrap-typeahead#107]
How can I hide dropdown menu when there is no matches found? (like autosuggest feature)

**Comment by ericgio** [comment]
There's not really a clean way to do that, unfortunately. #102 would address this use case, though.

**Comment by hyzhak** [comment]
@ericgio definitely lack of this feature. For example you can test match here https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/Typeahead.react.js#L419 as you do for `text.length >= minLength`. so it could be: `this._getFilteredResults() > 0`

**Comment by ericgio** [comment]
You can get the behavior you want by setting `emptyLabel=""`
