### ISSUE TITLE
onFocus issue

### ISSUE THREAD

**Issue by daschi** [ericgio/react-bootstrap-typeahead#108]
I'm having an issue with getting the `onFocus` property working. Here's an example of what I'm trying to do within a React component with no result:

```
onFocus() {
  console.log("Focused typeahead")
}

render() {
  return (<Typeahead
          ref='typeahead'
          labelKey="name"
          options={this.state.options}
          onChange={this.onChange.bind(this)}
          selected={this.state.selected}
          onFocus={this.onFocus.bind(this)}        
  />)
}
```

Let me know if I can give more information that would be helpful and if you have any suggestions! Thanks!

**Comment by ericgio** [comment]
Are you using ES6 classes? If so, you might want to try binding your methods in `constructor` rather than inline. As far as I can tell, the `onFocus` prop is working fine.

**Comment by daschi** [comment]
I've tried binding it in the constructor, and also inlining a function directly like this:

`onFocus={() => {console.log('focus')}}`

and it still doesn't seem to work for me

**Comment by ericgio** [comment]
Can you post the full code?

**Comment by daschi** [comment]
Ah my bad, I just updated the package to 0.10.3 and it's working now!
