### ISSUE TITLE
Make display of `emptyLabel` optional

### ISSUE THREAD

**Issue by andersonvom** [ericgio/react-bootstrap-typeahead#109]
Currently there's no way to disable displaying the `emptyLabel`.  It feels overkill to completely write the rendering of all items just to toggle this behavior on/off.

It would be nice to be able to toggle the "empty item" on/off either through an option (e.g. `displayEmptyLabel=false`) or through some sort of convention (e.g. `emptyLabel=""` means don't display it).

**Comment by ericgio** [comment]
Additional context would be helpful here, but pretty sure this is covered by #102.

**Comment by andersonvom** [comment]
While #102 allows for complete control over how things get rendered, what I meant above is to have a way to toggle `emptyLabel` on/off, either through an option (e.g. `displayEmptyLabel=false`) or through some sort of convention (e.g. `emptyLabel=""` means don't display it). It feels overkill to have to completely write the rendering of all items just to toggle the existing behavior.

I'll edit the description accordingly, but I'd like to hear your thoughts on it.

**Comment by ericgio** [comment]
Suppressing display when you pass an empty string seems pretty reasonable. It would help me to understand your use case; in what situations would you not want to let the user know that there are no results?

**Comment by andersonvom** [comment]
Apologies for the delayed response. The use case is: I want to suggest options to the user, but not necessarily treat these options as "a list of valid inputs". So if the user types "Some long string" and I have no good options to show them, then it would be nice to have a way not to display anything, instead of displaying the exact "Some long string" again.

Especially so if "Some long string" is not on my list of options, but will rather be created once the user submits the form, for example.

**Comment by ericgio** [comment]
This is available in v1.0.0
