### ISSUE TITLE
Make `preventDefault` on Typeahea configurable to allow forms to be submitted on `ENTER`

### ISSUE THREAD

**Issue by andersonvom** [ericgio/react-bootstrap-typeahead#112]
The change that added [these lines](https://github.com/ericgio/react-bootstrap-typeahead/blob/f023a5f/src/Typeahead.react.js#L391-L393) now prevent any forms that contain the Typeahead component from being submitted when the user presses `ENTER`.

Since this is a generic component, it seems this behavior should be configurable. An example of use case is when the user types something that does not match any items in the `options` list but still wants to submit the form any by pressing `ENTER`.

**Comment by ericgio** [comment]
Please be sure to read through the [documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/README.md) and [contribution guidelines](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/CONTRIBUTING.md) before opening an issue.

Code examples and/or a thorough description of your use case help me to understand why you’re requesting a feature, whether there’s already a way to do what you’re asking, and if not, to assess whether it would be a valuable thing to add.

Please feel free to re-open this issue with additional context provided.

**Comment by andersonvom** [comment]
I have edited both the title and the description of this issue with more details and I'd love to hear your thoughts on it.

**Comment by ericgio** [comment]
Thanks for the additional description.

> The change that added these lines now prevent any forms that contain the Typeahead component from being submitted when the user presses ENTER.

Just to clarify, that only happens when the input is focused. Otherwise the form should behave normally. If that's not the case it's a bug.

As far as whether it should still allow a submission while focused, can you describe your use case? Why would a user want to submit a form after not finding any results in a search?

**Comment by andersonvom** [comment]
Correct, that happens when the Typeahead component is in focus. We're using it to make suggestions as to what the user can choose, without restricting them to those options alone. While not my specific case, some examples of this would be google's search bar or tag suggestions: in both cases, the user may not want to choose any of the suggested options and might still want to submit the form right from that box by pressing `enter`.

**Comment by gsccheng** [comment]
I too am looking for this functionality. Right now, whether the input is focused or not, pressing the Enter key does not submit anything or trigger any callback I see. Shall we add this feature in? Perhaps just have this disabled case be a default and let it be configurable in the props?

So to be more specific in a use case: Supposedly typing in `turtles` into the `Typeahead` component returns `turtles in Madagascar` and `turtles in Malaysia`. The user decides that she only wants to search for turtles in general and so would just want to hit the Enter key at this point. Right now it doesn't seem like this is possible. Thanks! 

S

**Comment by ericgio** [comment]
@gsccheng: I think you're talking about a slightly different issue. I believe @andersonvom is referring to the fact that while focused, the Typeahead swallows keyboard "enter" or "return" events and therefore doesn't allow forms to be submitted unless the input is blurred.

It sounds like you just want to allow users to select options besides those you provide. In that case, you can use the `allowNew` prop for that.

**Comment by gsccheng** [comment]
@ericgio Hi Eric, the `allowNew` props gives me access to the new option (the search text in the input box). However, I still couldn't find a way to link that new option with the pressing of the Enter key with any configuration in this library.

What I ended up doing was adding a `keydown` event listener and handling what to do if `Enter` was pressed, and taking the new option from my `state`. Looks like there's also a [library](https://github.com/erikras/react-native-listener) to help with this.

Is there a better or easier way to do this instead?

**Comment by hyzhak** [comment]
@ericgio I'm trying to reproduce google search like behaviour when Enter not only select option from drop down list but also close drop down list when nothing was selected. It will be great if we could disable ```e.preventDefault();``` here https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/Typeahead.react.js#L538. Or you can disable it when nothing was selected or menu was closed

**Comment by hyzhak** [comment]
@ericgio I have just push small PR  with needed option

**Comment by ericgio** [comment]
Thanks again to @hyzhak for the PR! This was added in v1.2.0.
