### ISSUE TITLE
Allow autoFocus prop

### ISSUE THREAD

**Issue by elitan** [ericgio/react-bootstrap-typeahead#114]
... to set focus on the input element.

This is how I solved it now:

```
    componentDidUpdate() {
        if (this.props.auto_focus) {
            this.refs.typeahead.getInstance().focus();
        }
    }
````

Maybe that is enough?

**Comment by ericgio** [comment]
I imagine this is a pretty common need, so seems worth adding an easy way of doing it. It probably belongs in `componentDidMount` rather than `componentDidUpdate` though.

**Comment by rpedela** [comment]
I think having both would be great. I agree ```autoFocus``` should only be effective in ```componentDidMount```. However I have needed to call ```focus``` on elements in ```componentDidUpdate``` too. I think exposing a prop and a function would be great.

**Comment by ericgio** [comment]
@rpedela: You should be able to use the existing methods for that.
- [Documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md)
- [Example](http://ericgio.github.io/react-bootstrap-typeahead/1.0/#public-methods)

**Comment by ericgio** [comment]
v1.0.0 is now available, including the `autoFocus` prop.

**Comment by sahilvicesoftware** [comment]
> @rpedela: You should be able to use the existing methods for that.
> 
> * [Documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md)
> * [Example](http://ericgio.github.io/react-bootstrap-typeahead/1.0/#public-methods)

is this example available now?
