### ISSUE TITLE
onChange Shouldn't fire up onInputChange

### ISSUE THREAD

**Issue by prakharsingh** [ericgio/react-bootstrap-typeahead#117]
I have a use case where I want to either choose from existing or create a new record. If I choose from existing then only its Id is needed and if not then I need to create a new record upon form submit. But when I choose an existing data element first OnChange and OnInputChange fire up respectively. Thus, I always get a string instead of an existing data element object.

P.S. I am using a timer delay to fire up onChange slightly after onInputChange.

**Comment by ericgio** [comment]
It doesn't sound like you're handling the change events correctly. You shouldn't care about `onInputChange` here. Code examples would be helpful.

**Comment by ericgio** [comment]
I'm unable to repro based on the info you provided. Feel free to reopen with more detailed steps.
