### ISSUE TITLE
Filterable select box

### ISSUE THREAD

**Issue by TrejGun** [ericgio/react-bootstrap-typeahead#119]
hi there, thanks for awesome component)
I'd like to know if there is a way to convert it to filterable select box?

in example http://ericgio.github.io/react-bootstrap-typeahead/
I can see flag `allowNew` which doesn't allow to create new tokens
which is almost what I want but not yet
when user types "Ala" he can see both "Alaska" and "Alabama"
then click on "Alaska" and erase few letters, so input reads "Ala" again
I'd like to prevent this and allow only to choose from options

**Comment by ericgio** [comment]
I'm a little confused as to what you're asking for. `allowNew` allows the creation of new tokens. So if you simply don't set that (it's `false` by default), the user can only choose from the available options. Feel free to reopen with additional explanation if I misunderstood.

**Comment by TrejGun** [comment]
@ericgio 
probably the best way to explain what i mean is to show you an example

go to http://bootstrap-combobox-test.herokuapp.com/
type `ala` in the second input
then click outside of dropdown
tadam! input field looses its value

I'd like to have exact same behaviour with your widget

**Comment by ericgio** [comment]
It sounds like you're asking for the first option to be highlighted by default so the user can just hit enter to select. See https://github.com/ericgio/react-bootstrap-typeahead/issues/77, which I believe addresses what you want.

**Comment by TrejGun** [comment]
@ericgio 
I was asking for exact same behavior as bootstrap-combobox has but I'm ok with selecting first option too? is there a chance to have it?

**Comment by ericgio** [comment]
Ok, I think I see what you're saying. You want to clear the text if there's no selection and the user blurs the input. That should already be possible if you call the [`clear`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md#clear) method from within an `onBlur` handler:

```
<Typeahead
  onBlur={(e) => {
    this.refs.typeahead.getInstance().clear();
  }}
  ref="typeahead"
/>
```

**Comment by TrejGun** [comment]
this looks good, thanks

**Comment by denysonique** [comment]
> Ok, I think I see what you're saying. You want to clear the text if there's no selection and the user blurs the input. That should already be possible if you call the clear method from within an onBlur handler:

@ericgio Actually it is not possible to clear the text this way. `onBlur` gets called before `onChange` where one usually assigns the set value

**Comment by ericgio** [comment]
It's entirely possible, try it :)
