### ISSUE TITLE
Auto adjust typeahead dropdown position based on visible window area

### ISSUE THREAD

**Issue by naren-rana** [ericgio/react-bootstrap-typeahead#125]
Is it possible to configure this component to auto adjust its dropdown position based on visible window area.  In our case we are using this component at bottom of our application and once we try to search it render options downward and user have  to scroll down window scroll bar to see all option. Once user scroll down window focus from typeahead get removed and user has to enter again to see all option.

**Comment by ericgio** [comment]
You can use the `dropup` prop to make the menu open up instead of down. There's currently no built-in way to auto-position the menu based on the window bounds, but you could probably add that functionality yourself.

**Comment by ericgio** [comment]
Could use [PopperJS](https://popper.js.org/) for this, per #281

**Comment by ericgio** [comment]
This functionality was added in v3.0.0 via the `flip` prop.
