### ISSUE TITLE
Adding selected or defaultSelected only adds single letter to typeahead not the entire word

### ISSUE THREAD

**Issue by codeismine** [ericgio/react-bootstrap-typeahead#130]
Code:
         

```
  <Typeahead      selected={this.props.motionPictureName}
                            onInputChange={this.props.handleUpdateMotionPictureName}
                            onChange={this.props.loadMotionPictureDetails}
                            placeholder="Enter movie name"
                            options={motionPictureNames}
                            labelKey="title"
                                    /> 
```

Please let me know if you need any more information or logs to replicate this issue. Thanks.

**Comment by ericgio** [comment]
Can you provide an example of what `this.props.motionPictureName` is? Also, which version are you using? Thanks.

**Comment by codeismine** [comment]
It's the value that is passed from the parent to child. We can also replace it with the string like "The Godfather", still only letter "T" will be shown in Typeahead.
Version: "^0.11.1"

Thanks

**Comment by ericgio** [comment]
I haven't released a v0.11.1. Are you using someone else's fork?

**Comment by codeismine** [comment]
I have changed to following:
    "react-bootstrap-typeahead": "^0.9.4",
and provided defaultSelected="The Godfather" property to Typeahead, still I can only see "T" in Typeahead. Thanks

**Comment by ericgio** [comment]
You need to pass an array, not a string.
