### ISSUE TITLE
Pre-populate the input text

### ISSUE THREAD

**Issue by hyzhak** [ericgio/react-bootstrap-typeahead#132]
Is there any way to prepopulate input text (not one of options item)?

**Comment by ericgio** [comment]
Yes, just pass it into `selected`:

```jsx
<Typeahead
  options={['Value 1', 'Value 2', 'Value 3']}
  selected={['Value 4']}
/>
```

Note that this will not add it to the `options` array.

**Comment by hyzhak** [comment]
thanks it works great! 👍

**Comment by Gc04346** [comment]
Is there any way to prepopulate input text (not one of options item) using AsyncTypeahead?
When I use the "selected" prop, i get a warning saying that I whouldn't change a controlled component to be uncontrolled. Using defaultSelected clears the warning, but the prepopulation doesn't work.
