### ISSUE TITLE
Setting "selected" prop to [] won't show blank input

### ISSUE THREAD

**Issue by jper92** [ericgio/react-bootstrap-typeahead#133]
I'm using react-bootstrap-typeahead controlled, this is how I render my item

```jsx
<Typeahead
  options={values}
  onChange={this.onChange.bind(this)}
  onBlur={this.keyup.bind(this)}
  allowNew={this.props.allowCreate}
  selected={selected ? [selected] : []}
/>
```

right now `selected` is a prop, formatted as an object `{label:some_label, id: some_id, item:some_custom_data}` or null. It's changed based on some logic in onChange and keyup methods.

In a use case, I'm trying to clean up my item by setting "selected" prop to null, but I doesn't seem to clean up the input, I verified the prop sent to Typeahead is `[]` for that case, I think I'm doing everything as it is in the documentation.

Any help or suggestion is welcome, thanks a lot!

**Comment by ericgio** [comment]
Use the [`clear`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md#public-methods) method.  [See example](http://ericgio.github.io/react-bootstrap-typeahead/1.0/#public-methods) for more.

**Comment by ericgio** [comment]
More context on why simply passing in an empty array didn't work: https://github.com/ericgio/react-bootstrap-typeahead/pull/34

**Comment by jasxir** [comment]
Though this issue has been closed. I want to know it there's a controlled way of clearing the inputs. calling the clear method is the uncontrolled way(in react terms). Calling the clear method changes the selection which in-turn triggers onChange, but on the other hand what I simply want is to just to clear the input when there's no selection, it would be nice if we can have another attribute just for the value of input.

**Comment by ericgio** [comment]
If there's a selection, you can pass an empty array to clear the selection/input value. However, this won't work if there's text but no selection. I don't currently have plans to allow changing the input's value.
