### ISSUE TITLE
set arbitrary default value

### ISSUE THREAD

**Issue by thg303** [ericgio/react-bootstrap-typeahead#137]
Hi there
I am using this component as a search box. I need it to accept some default value (previous searched keyword) in case user redirected from another route. any idea how may it be done?

**Comment by ericgio** [comment]
Please help me limit the issue tracker to actual issues like bugs and feature requests by posting questions like this on StackOverflow or similar forums.

The [documentation](https://github.com/ericgio/react-bootstrap-typeahead/tree/master/docs) and [examples](http://ericgio.github.io/react-bootstrap-typeahead/1.0/) should answer your questions.
