### ISSUE TITLE
Fail snapshot test after including the typeahead

### ISSUE THREAD

**Issue by davidyu85** [ericgio/react-bootstrap-typeahead#139]
Although I am able to make the typeahead function in browser, but it mysteriously failed the snapshot test. It shows this error message.

Invariant Violation: getNodeFromInstance: Invalid argument.

Need help on this one as the error messages aren't that helpful pin pointing me the issue.

**Comment by ericgio** [comment]
I'm going to need more info: version? code sample?

This doesn't sound on the surface like an issue with the component, though.

**Comment by davidyu85** [comment]
version: 1.0.0-beta5

Code sample: 
DatePicker.js (shorterned but working example):

```
import React, { Component } from 'react';
import { Typeahead } from 'react-bootstrap-typeahead';

export default class DatePicker extends Component {
  render() {
    return (
      <div className="date">  
        <Typeahead
          labelKey={option => `${option.label}`}
          placeholder="Day"
          options={ 
            (function() {
              var arr = [], i;
              for(i=1;i<=31;i++) {
                arr.push({
                  name: 'day',
                  value: i, 
                  label: i
                });
              }
              return arr;
            })()
          }
        />
        <br /><br />
      </div>
    )
  }
}
```

Snapshot test:

```
import React from 'react';
import DatePicker from './DatePicker';
import renderer from 'react-test-renderer';

describe('DatePicker', function() {
  test('renders correctly', function() {
    const component = renderer.create(<DatePicker />).toJSON();
    expect(component).toMatchSnapshot();
  });
})
```

**Comment by ericgio** [comment]
Your date picker code looks correct to me.  I'm not familiar with how to write tests using Jest, though, so I can't tell you what's wrong there.

**Comment by ericgio** [comment]
Looks like the test-renderer [might not work](https://github.com/facebook/react/issues/7371) with refs or `findDOMNode`?

**Comment by davidyu85** [comment]
Looks like this is the case, since I've seen findDOMNode used in the typeahead component.

https://github.com/facebook/react/issues/7371

**Comment by ericgio** [comment]
Seems like it, unfortunately.
