### ISSUE TITLE
Warning: React.__spread is deprecated

### ISSUE THREAD

**Issue by barbalex** [ericgio/react-bootstrap-typeahead#14]
I get this message when focus enters the Typeahead component:

    Warning: React.__spread is deprecated and should not be used.
    Use Object.assign directly or another helper function with similar semantics.
    You may be seeing this warning due to your compiler.
    See https://fb.me/react-spread-deprecation for more details.

I am using:

- node 5.10.1
- react 15.0.1

**Comment by ericgio** [comment]
This is just a deprecation warning in React 15. For now, `react-bootstrap-typeahead` has v14 as a dependency, so I'll fix this eventually when I upgrade to 15.

**Comment by barbalex** [comment]
thanks
