### ISSUE TITLE
`background-color: transparent` on `input.form-control.bootstrap-typeahead-input-main`

### ISSUE THREAD

**Issue by bdkent** [ericgio/react-bootstrap-typeahead#141]
The `Typeahead`'s main `<input />` (ie, `input.form-control.bootstrap-typeahead-input-main`) appears to get a `background-color: transparent` set manually by the `style` attribute.

Is there any way to disable that?

**Comment by ericgio** [comment]
Not currently, no.

**Comment by ericgio** [comment]
The transparency is needed for the hinting functionality.

**Comment by bdkent** [comment]
Would it be possible to give the hint the background color of the real input to achieve both?

**Comment by ericgio** [comment]
Fixed in v1.1.0
