### ISSUE TITLE
AsyncTypeahead "default" search results 

### ISSUE THREAD

**Issue by bdkent** [ericgio/react-bootstrap-typeahead#144]
Is there a way to provider real "default" options for a `<AsyncTypeahead>`? The `onSearch` handler is not called initially or when input text is empty string. 

I can fake it by doing a search initially in the `componentDidMount`, but that doesn't work if the input is deleted back to empty string. (ie, user types "x" and hits backspace so back to "").

Am I missing something obvious? And if this isn't currently supported, can it be?

**Comment by ericgio** [comment]
Did [passing options](http://ericgio.github.io/react-bootstrap-typeahead/#controlling-selections) to `selected` not work?

**Comment by bdkent** [comment]
I am using `onSearch` to update the `options` value. The `onSearch` handler does not appear to be called initially when the input text is empty string or later on if the user types something and then deletes back to empty string.

So for example, if the user types "x", `onSearch` is called and `options` is populated, but if the user hits delete so the input text becomes "", then `onSearch` is not called and the `options` remain what they were.

So in this way, I cannot achieve "default" options when no input text is provided.

**Comment by ericgio** [comment]
There are several ways to do this, but you need to handle it yourself in the parent. `Typeahead` tries to be relatively dumb in that sense and just displays whatever is passed to it. So you could do something like:

```jsx
const defaultOptions = [...];

<Typeahead
  onInputChange={text => this.setState({text})}
  onSearch={query => {
    // Handle async code here...
    
    this.setState({options});
  }}
  options={this.state.text ? this.state.options : defaultOptions}
/>
```

**Comment by bdkent** [comment]
That did the trick!  Thanks!
