### ISSUE TITLE
AsyncTypeahead doesn't work with 'multiple'

### ISSUE THREAD

**Issue by gordonk** [ericgio/react-bootstrap-typeahead#145]
First selection works successfully. Executes search.

Subsequent searches in the input box don't reexecute the onSearch callback but will look within the original search results.  Once the query has no matches in the cached result set, the promptText "Type to Search" is displayed.

**Comment by ericgio** [comment]
I'll take a look, thanks.

**Comment by ericgio** [comment]
Can repro, thanks.

**Comment by ericgio** [comment]
Fixed in 1.2.0

**Comment by gordonk** [comment]
Also Implemented works great thanks.
