### ISSUE TITLE
Feature Request: handler for when `activeIndex` changes

### ISSUE THREAD

**Issue by bdkent** [ericgio/react-bootstrap-typeahead#146]
Is it possible to add a handler for when the `activeIndex` changes?

I think ideally it would have arguments for the next index and the option value for that index.

**Comment by ericgio** [comment]
What are you trying to do? `activeIndex` is an implementation detail as far as I'm concerned and not intended to be part of the public API. Also note that since it's based on user behavior, I'm not sure how providing `nextIndex` would be possible.

**Comment by bdkent** [comment]
I am trying to be able to show a "preview" before the user commits to actually selecting an option in the event a user arrows over a selection or hovers with the mouse, but before they hit enter or click.

**Comment by ericgio** [comment]
What type of preview and where does it appear? Code example or screenshot would be helpful. Without knowing more about what you're trying to do, it sounds like you probably just want to customize the the rendering of the menu items to display more than just a simple string. Seems like that would largely solve your problem.

**Comment by bdkent** [comment]
It would be too much information to display inline in the menu.

In the UI I am building the typeahead options are populating a big data display. Ideally I would like to display a preview that is effectively a diff of the current vs potentially new display information before the user commits to actually selecting something. I was thinking I could achieve this if the typeahead provided a `onHighlighted` event with some information about what was then highlighted (either the index or the actual item data).

**Comment by ericgio** [comment]
This sounds like highly specific behavior. I'd recommend using the `renderMenu` hook to have complete control over the look and feel of the menu and menu items. You can either use the provided `MenuItem` component or wrap your own with `menuItemContainer`. The container provides an `active` prop that you can use for your purposes.

Example: http://ericgio.github.io/react-bootstrap-typeahead/#rendering

**Comment by petervojtek** [comment]
I have following use case -- when user did mouseover over an item in dropdown, the item is previewed in our app (the item is not fully selected, just sort of previewed). We would like to achieve the same preview feature when user is using up/down keys to move along the dropdown items.. it seems like being able to observe `activeIndex` would help us to achieve this goal. our intention is to keep the drodown menu as is, thus I am not sure if

> using the renderMenu hook to have complete control over the look and feel of the menu and menu items

is what we actually need.

**Comment by ranyadshalom** [comment]
I found myself needing to do the same thing. While it can be achieved using the `renderMenu` hook, this is hacky and forces my code to depend on the internal state of the Typeahead:
```
<Typeahead
    multiple
    renderMenu = {
        (items,
        {
            renderMenuItemChildren,
            ...menuProps
        } ,
        state) => {

        if (state.activeIndex !== -1) {
            let activeRecord = items[state.activeIndex]
                setCurrentlyHighlighted(activeRecord)
        } else {
            if(currentlyHighlighted) {
                setCurrentlyHighlighted(null)
            }
        }
```

Would have been really nice to have an `onHighlight` event to hook into.
