### ISSUE TITLE
AsyncTypeahead odd with allowNew

### ISSUE THREAD

**Issue by gordonk** [ericgio/react-bootstrap-typeahead#147]
Adding the allowNew prop disrupts the normal flow of messages (Type to search, searching...) and for the duration of the async request displays the 'Add a new item: query' 'result' in the dropdown list.

Would seem consistent that the 'Add a new item:..' behavior only occurs when isLoading is false?

Great component by the way.  Thanks for all your hard work.

**Comment by ericgio** [comment]
Thanks for the report. I can repro and agree it's weird. Will try to fix this and #145 asap.

**Comment by ericgio** [comment]
This should be fixed in v1.2.0. Thanks again for the report and please let me know if you see additional weirdness.

**Comment by gordonk** [comment]
Implemented works great thanks.
