### ISSUE TITLE
Missing onKeyChange prop

### ISSUE THREAD

**Issue by kamalbennani** [ericgio/react-bootstrap-typeahead#148]
Is there any way we can pass `onKeyChange` to the `AsyncTypeahead` Component.
The use case, is that when the user search for something It displays a list of suggestions with `maxResult` limited to 5 and when he hit ENTER he will be redirect to a page with all results returned by the API. But as I Understood from the code, there is no way to pass onKeyChange as a prop.

**Comment by ericgio** [comment]
I'm not sure I understand how an `onKeyChange` prop fits in here. It sounds like you might be looking for what's described in #112, and the page would redirect on `submit`.
