### ISSUE TITLE
Adding CSS styling guide to docs

### ISSUE THREAD

**Issue by Tauka** [ericgio/react-bootstrap-typeahead#150]
I did not find any explicit information on how to style `Typeahead`. It would've been nice to have some class names underlying `Typeahead`, and may be some examples of styling it. Anyway, great component, thanks.

**Comment by ericgio** [comment]
Anything in particular you had trouble with?

Generally speaking, this component is meant to be compatible with [Bootstrap](http://getbootstrap.com/) CSS and uses that framework's classnames, similar to [React-Bootstrap](https://react-bootstrap.github.io/). For the most part, you can drop in Bootstrap themes and they should work, though you may need to tweak a few things with the multi-select version.

**Comment by Tauka** [comment]
You're right, for most of cases I can work with Bootstrap classes. I did not have much of a troubles, but for example, I noticed `.active` class attached to items selected using arrows, is it Bootstrap behavior? It's just I had to look up some things in devs for your examples, which is totally ok, but I also expected to see them in API reference. Other than that, works perfectly

**Comment by adrianocola** [comment]
I'm struggling to style the new selection section. A simple class in that element would do the job!

[src/TypeaheadMenu.react.js](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/TypeaheadMenu.react.js)
```js
    if (option.customOption) {
      return (
        <MenuItem {...menuItemProps} className="bootstrap-typeahead-new">
          {newSelectionPrefix}
          <Highlight matchClass={MATCH_CLASS} search={text}>
            {option[labelKey]}
          </Highlight>
        </MenuItem>
      );
    }

```

**Comment by ericgio** [comment]
@adrianocola: Your issue is more or less what's described in https://github.com/ericgio/react-bootstrap-typeahead/issues/104. Basically, there isn't a great API at the moment for specifying props/attributes for the lower-level pieces of the typeahead.

**Comment by ericgio** [comment]
Closing this out, as there isn't a clear action item. Most of the lower-level elements now have classnames attached to them and can thus be styled as desired.
