### ISSUE TITLE
Lodash dependency

### ISSUE THREAD

**Issue by isaachinman** [ericgio/react-bootstrap-typeahead#152]
Just wondering if it's truly necessary for this component to depend on lodash, especially when a lot of similar methods are natively available in ES6/7 and can be transpiled?

For reference, it looks like Lodash makes up over _half_ of this lib's total footprint.

![screen shot 2017-03-01 at 16 22 50 2](https://cloud.githubusercontent.com/assets/10575782/23466467/8233b062-fe9b-11e6-86af-2320daa77bdf.png)

I'm happy to look into a PR to remove this dep if @ericgio thinks it's possible and would merge such a thing.

**Comment by ericgio** [comment]
There are a few lodash methods I could probably do without, but several (debounce, throttle, isEqual) are necessary. I could probably include just those as individual modules, though it's not clear to me how significant the size reduction would be; minified and gzipped, the entire typeahead lib is around 36k, while lodash is around 4k.

All that said, if you want to take a stab at a PR with before and after stats, feel free.

**Comment by blunatic** [comment]
@isaachinman What tool is that image from? Curious to check out some other package footprints I'm currently using.

**Comment by isaachinman** [comment]
Ah sorry for not coming back to this sooner.

@blunatic It's [this tool](https://chrisbateman.github.io/webpack-visualizer/), based on disc (originally for browserify).

Take it with a grain of salt though, this original issue stemmed from the fact that the tool was interpreting webpack's stats incorrectly, and was reporting that, for instance, `react-bootstrap-typeahead`'s total footprint was 3x larger than it actually was.
