### ISSUE TITLE
Feature Requests: add prop to show typeahead list independent of input focus

### ISSUE THREAD

**Issue by bdkent** [ericgio/react-bootstrap-typeahead#154]
I would like to be able to show the typeahead dropdown option list while retaining input focus elsewhere.

ie, I do not want the typeahead input box to steal my potential hotkey keyboard input until the user deliberately focuses on the typeahead input box.

**Comment by ericgio** [comment]
Why do you want to do this?

**Comment by ericgio** [comment]
Or perhaps a better question: Why would others need this feature?

**Comment by bdkent** [comment]
I want a user to be able to see some of the default options without having to engage the typeahead, much like a `<select>` box can be made tall to show more than one option.

**Comment by ericgio** [comment]
It feels like you're asking for a different component entirely here, a bit like a filterable table or list. That's not really the way a typeahead search box behaves, so I'm not convinced this is a valid use case for the component.
