### ISSUE TITLE
Set Value of the Typeahead Input

### ISSUE THREAD

**Issue by Caf131** [ericgio/react-bootstrap-typeahead#155]
Is there a way to set the value of the typeahead input?

e.g. Controlled Input e.g. https://facebook.github.io/react/docs/forms.html

**Comment by ericgio** [comment]
This is covered in the [docs](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Usage.md#controlled-vs-uncontrolled) and [examples](http://ericgio.github.io/react-bootstrap-typeahead/#controlling-selections).
