### ISSUE TITLE
feature request: allow setting input attributes, i.e for validation

### ISSUE THREAD

**Issue by simoneb** [ericgio/react-bootstrap-typeahead#158]
It would be nice to be able to use standard attributes on the main input element. In my case I would find it useful for setting validation attributes: `required`, ... so that I can leverage html validation.

I'm thinking of a new property accepted on the typeahead element and proxied to the main input.

Right now I'm working around this by getting a reference to the input element via its name property and setting the `required` attribute using the JavaScript DOM API, which is not very react-ish.

**Comment by ericgio** [comment]
I think this is covered by #79, but let me know if I'm missing something. I think the easiest thing to do is provide an `inputProps` prop or something like that, which just gets passed on to the input.

**Comment by simoneb** [comment]
I think so, thanks.
