### ISSUE TITLE
Typeahead dont updating defaultSelected with new value when rendering again.

### ISSUE THREAD

**Issue by joaopauloctga** [ericgio/react-bootstrap-typeahead#159]
Hi guys.
I trying update defaultSelected values but dont applaing changes on the element, i updated state object correctly, but dont updating values defaultSelected.

Only first time, when he been created.

My Code:

Code of element:

    <Typeahead options={this.state.options.meusContatos} defaultSelected={this.state.form.membros} multiple name="contatos" placeholder="Digite o nome do contato" onChange={this._set} />

Code for updated:

    componentWillReceiveProps(props){
        this.setState({form:props.grupoUpdate});
    }

**Comment by ericgio** [comment]
[Use `selected`, not `defaultSelected`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Usage.md#controlled-vs-uncontrolled).

**Comment by dfagan2** [comment]
@ericgio - just ran into this same thing and found this old bug. using `selected` would change this to a "controlled" component. What if we want to keep it as an "uncontrolled" component, but would like to just reinitialize it with a new `defaultSelected` when that information becomes available, say, from an asynchronous request finally resolving?

**Comment by ericgio** [comment]
@dfagan2: The behavior you're describing is that of a controlled component, so `selected` is the right prop to use. I'm not sure why it needs to be uncontrolled in your case, but to get the behavior you want you'd need to re-instantiate typeahead with the new selection. One way to do this is by [updating the typeahead's `key` prop](https://medium.com/@albertogasparin/forcing-state-reset-on-a-react-component-by-using-the-key-prop-14b36cd7448e). Again, though, this seems more prone to bugs and performance issues than simply using a controlled component.

**Comment by shandou** [comment]
My use case is that I have many options for the users for a downstream operation and they might only need to delete a few before proceeding to the next step (whereas choosing them one by one gets tedious). It would be great to be able to both update and access `defaultSelected` for state updates.

**Comment by ericgio** [comment]
@shandou like the other cases above, it sounds like you should be using `selected` not `defaultSelected`.

**Comment by shandou** [comment]
Yeah @ericgio I ended up using `selected`. With `selectHintOnEnter` enabled, it is a manageable amount of keyboard operations that should be fine for the users :) Thanks!!

**Comment by prameshb87** [comment]
@ericgio I have the following use case for multiple typeaheads inside a modal. What would you suggest is the best way to approach this?
**Use Case** - TypeaheadA is empty and TypeaheadB has defaultSelected on load. User can change entry in TypeaheadB and make a different selection. Now they make a selection in TypeaheadA and decide this is the same entry they want in TypeaheadB. So they use the checkbox. How can this behavior be implemented with 'selected' or 'defaultSelected'
