### ISSUE TITLE
Tab navigation is not as it should be

### ISSUE THREAD

**Issue by CHedgren** [ericgio/react-bootstrap-typeahead#16]
The suggestion boxes for purposes of tabbing work as keyboard traps. I'll PR, real soon(tm)

**Comment by ericgio** [comment]
Thanks. What's your suggested behavior here?

**Comment by CHedgren** [comment]
If you go to the demo page, click the jumbotron and tab to the dropdown and select something, it's really hard to continue keyboard navigation. I suggest that Tab is not used to navigate elements in the dropdown and that arrow keys are used for this purpose instead, sorta like a select element.

**Comment by ericgio** [comment]
Sounds reasonable and should be a pretty easy fix.

**Comment by ericgio** [comment]
I updated the behavior in v0.4.1. Let me know if you still think it's wrong for some reason.

**Comment by CHedgren** [comment]
You are a wonder of a man! 
I got caught up in work stuff and had totally forgotten about this. 
Thank you so much.
(Haven't looked yet though, may come back and whine about how it doesn't exactly fit my use case :P )

**Comment by ericgio** [comment]
No problem, sorry it took awhile to get to this.
