### ISSUE TITLE
Add prop to receive status messages

### ISSUE THREAD

**Issue by web2wire** [ericgio/react-bootstrap-typeahead#161]
When using the async version of this component the dropdown area of the control gets populated with messages such as "Searching..." or "No matches found". In my form this looks ugly and I already have a status area which is used to display properly formatted other messages or validation issues.

It would be useful to be able to provide a property which receives these messages so they can be handled by the parent. This would also disable their display in the control by default so this would only ever display actual valid options.

At the moment the only way I can see this would be possible would be to set all of the various message options to empty strings and then construct equivalent messages in the various handlers. However this is quite a clunky solution even if it worked.

**Comment by ericgio** [comment]
The typeahead component shouldn't be aware of, or control the parent. You can just pass empty strings to disable the messages. Since the parent passes the `onSearch` callback, it already has everything it needs to know when requests stop/start, and whether or not any results were found.

**Comment by ericgio** [comment]
I'm going to close this out as a non-issue, but feel free to re-open with more info.
