### ISSUE TITLE
Issues on AyncTypeHead with IE while fast typing

### ISSUE THREAD

**Issue by ajeeshraj56** [ericgio/react-bootstrap-typeahead#169]
i have used AsyncTypeahead in my application. It is working perfectly with chrome browser.
But in IE am facing issue while type fast in the input box.

In TypeAheadInput.react.js i have changed the onChange event in the input box to onInput as below

This is the existing code
<TextInput
          {...inputProps}
          autoComplete="off"
          className={cx('bootstrap-typeahead-input-main', {
            'has-selection': !!selected.length,
          })}
          onBlur={this._handleBlur}
          **onChange={this._handleChange}**
          onKeyDown={this._handleKeydown}
          ref={input => this._input = input}
          style={{
            backgroundColor: !disabled && 'transparent',
            display: 'block',
            position: 'relative',
            zIndex: 1,
          }}
        />

<TextInput
          {...inputProps}
          autoComplete="off"
          className={cx('bootstrap-typeahead-input-main', {
            'has-selection': !!selected.length,
          })}
          onBlur={this._handleBlur}
          **onInput={this._handleChange}**
          onKeyDown={this._handleKeydown}
          ref={input => this._input = input}
          style={{
            backgroundColor: !disabled && 'transparent',
            display: 'block',
            position: 'relative',
            zIndex: 1,
          }}
        />

After this modification my issue is solved.. kindly fix this issue as soon as possible

**Comment by ericgio** [comment]
I'm not sure exactly what your issue is here. It seems like you expect `onChange` to reflect the input's change event, but if you read the documentation, you'll see that `onChange` handles the overall component's change event (ie: changes in selection). For the input change event, use `onInputChange`.
