### ISSUE TITLE
Async query cache is shared between instances, which may have completely different backends

### ISSUE THREAD

**Issue by boutell** [ericgio/react-bootstrap-typeahead#170]
Currently the async query cache feature is shared between instances. This led to considerable confusion as they may be looking up completely unrelated data.

I think correcting the cache to be specific to the instance would be the proper fix. A feature to share a named cache by passing the same "cache" string prop from various instances could then be added without breaking code that would reasonably be expected to work "out of the box."

However cache={false} is an effective workaround, once you figure out what's going on.

Thanks for the module!

**Comment by ericgio** [comment]
Thanks for the report @boutell. I think making the cache an instance variable is the right move and shouldn't be too hard.

**Comment by ericgio** [comment]
Fixed in v1.4
