### ISSUE TITLE
Need the onChange to return an event

### ISSUE THREAD

**Issue by kamarajuPrathi** [ericgio/react-bootstrap-typeahead#174]
Is there a way OnChange method returns an event ?

**Comment by ericgio** [comment]
Why do you need this?

**Comment by kamarajuPrathi** [comment]
I actually have a HOC function which needs the name of the field and the value of the field to update when ever i change the value in the store .

**Comment by ericgio** [comment]
Can you post some code? You can pass the `name` attribute to the component, so you should have that. The `onChange` event will give you the value, so you should have everything you need.

**Comment by kamarajuPrathi** [comment]
Sure , 
          <AsyncTypeahead
            caseSensitive
            ignoreDiacritics={false}
            allowNew
            name="name"
            options={[]}
            id="tagCategory"
            value={tag.name}
            onChange={(e) => {
              this.props.updateProperty(e.target.name, e.target.value)
            }}
            onSearch={this.addTag}
          />
Some this like this , and do we have option to only send the selected Text rather than an object ?

**Comment by kamarajuPrathi** [comment]
@ericgio And why am i getting onChange an array of selected , Cant i get just one value

**Comment by ericgio** [comment]
Couldn't you just do the following?
```
<AsyncTypeahead
  ...
  name="name"
  onChange={(selected) => {
    this.props.updateProperty('name', selected)
  }}
  onSearch={this.addTag}
/>
```

**Comment by kamarajuPrathi** [comment]
@ericgio yeah , i could that .. just thought of asking ? and regarding the selected value can i just have one value ?

**Comment by ericgio** [comment]
Not currently, no. That was an explicit decision to normalize the API and always return an array of selected values whether using the multi-select version or not. You can just pass `selected[0]` or something like that, though.

**Comment by kamarajuPrathi** [comment]
ok thanks

**Comment by bloodykheeng** [comment]
> 

<AsyncTypeahead
  ...
  name="name"
  onChange={(selected) => {
    this.props.updateProperty('name', selected)
  }}
  onSearch={this.addTag}
/>

hei what does this line mean this.props.updateProperty('name', selected)
is it the same as this this.props.updateProperty(e.target.name, e.target.value)
