### ISSUE TITLE
Warning :Menu deprecated

### ISSUE THREAD

**Issue by kamarajuPrathi** [ericgio/react-bootstrap-typeahead#178]
Its shows a warning when i use Menu in renderMenu method.
<img width="321" alt="screen shot 2017-04-26 at 11 20 22 pm" src="https://cloud.githubusercontent.com/assets/25597219/25467862/f48c4702-2ad6-11e7-905e-00903abd2bdd.png">

Its mentions as deprecated HTML tag , but it works fine .

**Comment by ericgio** [comment]
I don't know what this means; can you please provide more context? How can I repro this? Thanks.

**Comment by kamarajuPrathi** [comment]
When i use it Intellij IDE or the Jslint(with air-bnb-standards) shows it as a Deprecated HTML tag.

**Comment by ericgio** [comment]
This sounds like an issue with your linter and not a bug with the component. You most likely need to relax some lint rule.
