### ISSUE TITLE
this.setState and this.refs

### ISSUE THREAD

**Issue by cidevant** [ericgio/react-bootstrap-typeahead#179]
### Version
^1.3.0

### Steps to reproduce

```jsx
onTypeaheadChange = (items) => {
  this.setState(
    { selectedItemsInState: items }, 
    this._typeahead.getInstance().clear
  );
};

<AsyncTypeahead
  onChange={this.onTypeaheadChange}
  onSearch={this.onTypeaheadSearch}
  options={options}
  ref={ref => this._typeahead = ref}
/>
```

### Expected Behavior
`onTypeaheadChange` should add `items` to `selectedItemsInState` by `this.setState` function, and after that it must clear typeahead input field

### Actual Behavior
Browser crash because of endless loop in setState

**Comment by ericgio** [comment]
Indeed, `this._typeahead.getInstance().clear()` will trigger the `onChange` event, which leads to an infinite loop. This seems like a problem with your code, not the component.

**Comment by cidevant** [comment]
You are right. I had to fix my code. Maybe you should mention in doc, that you can`t use `this._typeahead.getInstance().clear()` in `onChange` callback.

Solved

**Comment by ericgio** [comment]
Fair point, I'll call the out in the docs.

**Comment by asogani1** [comment]
I want input to be clear on some button click in my website?

`			            <Typeahead
						  	labelKey='title'
						  	onChange={store.changeJobTitleText}
						  	options={this.state.jobTitle}
						  	ref={ref => this._typeahead = ref}
						/>`
i have added ref and doing this `this._typeahead.getInstance().clear` on button click but it dosent work, please help.
