### ISSUE TITLE
How to read input?

### ISSUE THREAD

**Issue by phamj88** [ericgio/react-bootstrap-typeahead#180]
Hi!

I am having an issue reading the input if using defaultSelected.
Normally if I type in the typeahead I can read the input value by using this:
`this.refs[typeahead].getInstance().refs.input.props.text`

However if the typeahead has a defaultSelected. I can visually see the value in the input box, but doing a .getInstance.refs.input.props.text gives me a "".

Am I handling this incorrectly? Is there a way to be able to read the value with the code above for both when defaultSelected is used or when a user types in the input.

Maybe this is fixed in a newer version
`"react-bootstrap-typeahead": "^0.10.4"`

**Comment by ericgio** [comment]
Don't use refs to get the input value. Use [`onInputChange`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#oninputchangetext).
