### ISSUE TITLE
When selected property is [""] it is using a cached value

### ISSUE THREAD

**Issue by alleroux** [ericgio/react-bootstrap-typeahead#182]
### Version
1.3.0

### Steps to reproduce
I did this with the Asynctypeahead.
Pass in a selected property with an array that contains an empty string.
Where in some cases selected = [""].
I'm using this inside of an ES6 React component class.
The code is contained inside of a modal that loads a new set of data when the user clicks next.  If the value of the data for the typeahead is an empty string then it is displaying a previous value.

### Expected Behavior
Input should contain an empty string

### Actual Behavior
Input is displaying cached value

I was able to work around the problem by passing in an object with a label of empty string rather than an array containing only an empty string [{id:0, label: ""}].

**Comment by ericgio** [comment]
I'm not sure exactly what you're trying to do, but you can't clear the input text by passing a selection like that. To clear the component, use the [`clear`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md#clear) method. Let me know if that addresses your issue.

If you're interested, see #34 for why simply passing an empty array (or an array with empty string) won't work.

**Comment by alleroux** [comment]
In my case the user is loading a new set of data and so the inputs are being filled with the new data.  The data is being passed via redux from a parent object that has no visibility into the react class that loads the typeahead.  When the user clicks the Next button there's no way for that object to know whether it should clear the text or not.  Then redux does it's thing and passes all of the data to the form and typeahead which happily populates the fields.  I can probably check the value in componentWillMount and call clear there but my workaround seems to be working fine.

**Comment by ericgio** [comment]
Can you post some code examples? I'd like to understand if there's actually a bug here or if you simply need to structure your code differently. You shouldn't need that workaround.

**Comment by ericgio** [comment]
Feel free to re-open with more info, but as far as I'm concerned there's no bug here.
