### ISSUE TITLE
autoFocus in overlay effects scroll position

### ISSUE THREAD

**Issue by bdkent** [ericgio/react-bootstrap-typeahead#183]
I have a `<Typeahead/>` that appears inside an [overlay](https://react-bootstrap.github.io/react-overlays/). If I set the `autoFocus`, the screen repositions to the top of the page, regardless of where the scroll position may be.

I have recreated the issue in a [fiddle](https://jsfiddle.net/bkent/wkkrnak6/).

**Comment by ericgio** [comment]
This looks to be a bug with react-bootstrap or react-overlays. Try substituting a normal text input with autofocus and the same thing happens.

**Comment by Tracis** [comment]
I have the same problem.
