### ISSUE TITLE
onInputChange not working properly when multiple is true

### ISSUE THREAD

**Issue by bradeac** [ericgio/react-bootstrap-typeahead#184]
Hello,

I'm using react-bootstrap-typeahead with redux-forms. onInputChange works perfectly if multiple is set to false.

The code:
```javascript
<Typeahead
                    clearButton
                    emptyLabel="No matches found !"
                    multiple
                    options={field.options}
                    onInputChange={(value) => {
                            // do something ...
                        }
                    }
                    {...field.input}
/>
```
The problem is that value will always be an empty string.

Thank you and have a nice day :)

**Comment by ericgio** [comment]
Works fine for me. I'm guessing it has something to do with the way you hooked the typeahead up to redux-forms. Can you provide a repro?

**Comment by bradeac** [comment]
Hi Eric,

You can find my code here: https://bitbucket.org/bradeacamil/servicecloud_tool

I'm using your component in src/components/requests_new.js.

Thank you :)

**Comment by ericgio** [comment]
I'm unable to access your repo. If you can provide a publicly accessible repro case, I can try to have a look, but closing out for now.

**Comment by bradeac** [comment]
Hi Eric,

It's me again :). The thing I described above still doesn't work (I managed to make a work around), but now I really need the onInputChange to work when multiple=true.

Just to refresh your memory, I am using redux-forms. onInputChange works perfectly when multiple=false, but when multiple=true, the parameter I pass to onInputChange remains undefined.

`<div className={className}>
                <label>{field.label}</label>
                <Typeahead
                    clearButton
                    emptyLabel="No matches found !"
                    multiple
                    options={field.options}
                    onInputChange={(label) => {
                            try {
                                console.log("label", label); // label is undefined
                                field.input.onChange(label.split('-')[1].replace(/ /g, ''));
                                //other code
                            }
                            catch (e) {
                                field.input.onChange(label);
                            }
                        }
                    }
                    {...field.input}`

Does label have to be an array, or why does the same code work on multiple=false ?

I have the 1.3.0 version. Does the latest version have some fix regarding this ?

Thanks.

**Comment by ericgio** [comment]
There's no issue with `onInputChange` as far as I can tell, and I can't think of a scenario where the text would be undefined. I'm guessing there's some weird interaction between redux-forms and the typeahead, where it's trying to take control of the input in a way that is unexpected. It's really hard for me to say without a repro case, though.

**Comment by scuerda** [comment]
@ericgio @bradeac fwiw, I had a similar issue that was resolved by changing `onInputChange` to `onChange` when using multiple. Thank you @ericgio for a very nice library.

**Comment by ajhurliman** [comment]
I ran into the same problem and the solution proposed by @scuerda worked for me. Thanks everyone!

**Comment by bloodykheeng** [comment]
@ericgio hei eric i read your documentation on react type ahead but i failed to see onInputChange and on change so i would like to get to know the difference between the two and when should we use one over the other

**Comment by ericgio** [comment]
Please see [API documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/main/docs/API.md#props):

### onChange
Invoked when the set of selections changes (ie: an item is added or removed). For consistency, selected is always an array of selections, even if multi-selection is not enabled.

```tsx
(selected: Array<Object|string>) => void
```

### onInputChange

Invoked when the input value changes. Receives the string value of the input (text), as well as the original event.

```tsx
(text: string, event: Event) => void
```
