### ISSUE TITLE
ReferenceError: requestAnimationFrame is not defined

### ISSUE THREAD

**Issue by markbrown4** [ericgio/react-bootstrap-typeahead#185]
### Version
1.3.0

I'm using mocha / enzyme / jsdom to run tests which incude the `<Typeahead>` and am getting 

> ReferenceError: requestAnimationFrame is not defined at Object.componentDidMount (node_modules/react-bootstrap-typeahead/lib/Overlay.react.js:71:37)

I tried faking it with `global.requestAnimationFrame = function(cb) { cb(0) }` but looks like there's other issues, the test just hangs and I haven't found the cause yet.

I haven't found a version of jsdom which polyfills `requestAnimationFrame`, have you got a test using these packages to work?  The previous versions of the package did run correctly.

There's also three warnings from this package:

> Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
> Warning: Portal: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by ericgio** [comment]
The use of `requestAnimationFrame` was added in v1.3.0 to help smooth out scrolling. I don't currently have a working test for it, so I don't have a helpful answer for you at the moment.

> There's also three warnings from this package:

Thanks. This is being tracked in #168 and should be fixed by #181. I just haven't had time to merge yet.

**Comment by markbrown4** [comment]
requestAnimationFrame is just one issue, I tried running my test suite against all of the `1.x.x` releases and couldn't get any of them to run with these packages so I'm back to `0.10.4`.

```
    "react": "^15.3.1",
    "react-bootstrap": "^0.30.3",
    "react-bootstrap-typeahead": "^0.10.4",
    "enzyme": "^2.4.1",
    "jsdom": "9.12.0",
    "mocha": "^2.5.3"
```

**Comment by ericgio** [comment]
If you can post a test repo, I'll try to take a look when I have some time.

**Comment by joaoreynolds** [comment]
following so I can upgrade to 1.3.0 when this is resolved. Thanks!

**Comment by ozzyogkush** [comment]
I am seeing this as well using 1.4.0

**Comment by ericgio** [comment]
If someone can provide a test case that would help. Otherwise there's not much I can do here.

**Comment by ericgio** [comment]
After some further investigation, I'm going to close this out, since it's not an issue with the typeahead library itself. As noted in the original post, jsdom doesn't provide `requestAnimationFrame`, so you need to polyfill the test environment yourself. Everyone's environment is different, so it's beyond scope for me to figure out how to do that.

Further discussion: https://github.com/facebook/jest/issues/1644
