### ISSUE TITLE
onKeyUp/Down

### ISSUE THREAD

**Issue by BillOTei** [ericgio/react-bootstrap-typeahead#186]
Feature requests
=======================
Correct me if I am wrong but it would be nice to be able to use event such as onKeyUp or Down as 
it would provide a great way implement input mask regex for ex.

**Comment by ericgio** [comment]
If your goal is to restrict the user input, this is being tracked in #33. Do you have other use cases for `onKeydown`/`onKeyUp` hooks?

**Comment by stevenqzhang** [comment]
One use case that I need for this: pressing the enter key while focused/typing in the input box triggers a function

**Comment by ericgio** [comment]
@stevenqzhang: can you elaborate a bit? What would the function do?

**Comment by stevenqzhang** [comment]
@ericgio Actually, I solved my use case with submitFormOnEnter, but I imagine this feature request would be useful for when someone wants an input box that submits on shift/ctrl+enter, or something

**Comment by ericgio** [comment]
I think this falls under #79, which would allow developers to set both component-specific and general input-related props. Closing this issue in favor of the other one, but let me know if I'm missing something.
