### ISSUE TITLE
Erase text in field by typing after item is selected

### ISSUE THREAD

**Issue by spetex** [ericgio/react-bootstrap-typeahead#19]
Hi,
I have encountered that when you preselect item from the list and then double-click the text in the field, it is not possible to rewrite the query just by typing. You first need to erase the query and then start typing.

I think this is not intended and it breaks the ux of the component.

**Comment by ericgio** [comment]
Thanks for raising this issue, I'll look into how best to fix it.

**Comment by ericgio** [comment]
Fixed in v0.5.3
