### ISSUE TITLE
Add onSelect prop to be invoked when the user selects an option

### ISSUE THREAD

**Issue by tommy5dollar** [ericgio/react-bootstrap-typeahead#190]
Apologies in advance if this is already supported but I've checked the docs and the code and can't see anything relevant.

I'm building a search bar and would like to be able to display a number of options in the dropdown and then navigate to the display page for the options when the user selects it.

To achieve this I'd expect something along the lines of an onSelect prop that will be invoked when the user selects an option.

Thanks in advance,

Tommy

**Comment by ericgio** [comment]
`onChange`

**Comment by tommy5dollar** [comment]
Thanks Eric,

Apologies for not spotting this myself! It works great, however I do think the documentation could be slightly improved around this though to avoid buffoons like me troubling you again in the future with the same question.

1. onChange - "Invoked whenever items are added or removed" - it's not obviously clear what this means
2. it didn't leap out to me from the documentation (props and API pages) that onChange was available for AsyncTypeahead, rather than just on Typeahead

**Comment by ajhurliman** [comment]
You might want to consider changing onChange to onSelection or something like that. When I hear onChange I think of the options available to choose from changing, not the selection.

**Comment by ericgio** [comment]
I understand the confusion, but the use of `onChange` here is consistent with its use for standard HTML components (`<select>` being an analogous case). `onSelect` fires "[when text inside a text input or textarea is selected](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onselect)" and therefore doesn't seem appropriate.
