### ISSUE TITLE
Prevent tokens from being removed from the options list.

### ISSUE THREAD

**Issue by ayaniv** [ericgio/react-bootstrap-typeahead#191]
The default behavior of *multiple* state is to remove the selected items from the options list. is there an API to prevent this from happening? after reading the docs I can not see any way to do so. So if not, I think you should set a flag for that case. I can do so if you want, and open a PR.

**Comment by ericgio** [comment]
What is the use case for selecting the same item more than once?

**Comment by ericgio** [comment]
Feel free to re-open with more information.
