### ISSUE TITLE
Hook for onKeyDown() to add value in input text to be rendered as token

### ISSUE THREAD

**Issue by pmk2429** [ericgio/react-bootstrap-typeahead#195]
The default behavior of `TypeAhead` when multiple is enabled is to render tokens on keyDown(enter) of selected item supplied via options.

Now, if the entered value(lets consider `email` as value in input for sake of discussion) is not existing the `options`, even when the value is valid then in that case, I'd like to allow user to hit Return(Enter) and render a token for that value(email).

Is there any hook to handle `onKeyDown(e)`, take in the value from input text and render the value as token?

**Comment by ericgio** [comment]
The [`allowNew`](http://ericgio.github.io/react-bootstrap-typeahead/#custom-selections) prop should work for you.

**Comment by pmk2429** [comment]
Thanks! Works like a charm.
