### ISSUE TITLE
Weird clear button in production environment

### ISSUE THREAD

**Issue by bradeac** [ericgio/react-bootstrap-typeahead#196]
Hello,

For some reason, the clear button looks like this in production (app is deployed to an azure web app):

![capture](https://user-images.githubusercontent.com/15371260/27034938-33bf162c-4f88-11e7-8ec9-c490a91320f4.JPG)

The styling didn't work out of the box (or I wasn't doing something correct), so I copied the .css files into the project and used them in the index.html file like this:
`<link rel="stylesheet" href="/style/Typeahead.css">`
`<link rel="stylesheet" href="/style/ClearButton.css">`

Is this because my 'original' way of using the .css files or am I missing something here ?

P.S. When starting the app on my machine, the clear button looks as expected.

Thank you.

**Comment by bradeac** [comment]
Just had to add `@charset "UTF-8";` to .css files
and `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />` to .html files.

**Comment by asogani1** [comment]
please let me know how can I clear input on some other button hit on my wesite?
Thanks in advance
