### ISSUE TITLE
Usage with browserify fails on require of css

### ISSUE THREAD

**Issue by vincentsels** [ericgio/react-bootstrap-typeahead#2]
In our development workflow, we use gulp + browserify + babelify. This fails hard (without stacktrace even) on the lines which require css files, e.g. in `lib/Token.react.js`:

`require('../css/Token.css');`

Commenting all these lines makes browserify/babelify pass. Is it possible to package the library in a way that it works out-of-the-box with browserify?

**Comment by vincentsels** [comment]
Ok, so adding `https://www.npmjs.com/package/browserify-css` as a transformer does the trick.

**Comment by ericgio** [comment]
Thanks for the feedback, and glad you got it to work. I required the css inline since that seemed easier and more convenient than having to separately include files. I'll consider breaking these out, though.
