### ISSUE TITLE
Ability to add classname to dynamically generated div

### ISSUE THREAD

**Issue by ejfrancis** [ericgio/react-bootstrap-typeahead#205]
The `className` option is used on the input form that this component creates, but then the actual typeahead suggestions are rendered inside a new div that's appended to the `<body>` itself, and that new div does not provide a way to add a class name to it. Because of this, if you have more than one `<TypeAhead/>` on a page it's not possible to namespace your styles and style both differently. 

For example, if I have this app html:

```html
<html>
  <body>
    <div id="react-root">
        <-- app renders here -->
    </div>
   <div>    <!-- this is generated by react-bootstrap-typeahead -->
       <ul data-react-root class="dropdown-menu bootstrap-typeahead-menu ...">
       ...
      </ul>
   </div>
</html>
```

since the div wrapping `.dropdown-menu` attached right to `<body>`, you can't namespace styles to it. Ideally something like this would be possible:

```html
<html>
  <body>
    <div id="react-root">
        <-- app renders here -->
    </div>
   <div class='some-configurable-class'>    <!-- this is generated by react-bootstrap-typeahead -->
       <ul data-react-root class="dropdown-menu bootstrap-typeahead-menu ...">
       ...
      </ul>
   </div>
</html>
```

**Comment by ericgio** [comment]
Does the classname need to be on the `div` or could it just be added to the menu itself (`<ul>`)? The latter option is easier and more universal.

**Comment by ericgio** [comment]
v2.0.0-alpha.2 adds the `rbt-body-container` class name to the containing div and also passes the top-level `className` prop down for further customization.
