### ISSUE TITLE
Custom tabIndex prop

### ISSUE THREAD

**Issue by haxxxton** [ericgio/react-bootstrap-typeahead#206]
Feature request
=======================
When other input fields (outside of react-bootstrap-typeahead) have a tabindex of >0 the order that rbt is positioned within the form makes it no longer tabbable in sequential order. It would be great to be able to specify the tabindex that the rbt should use, thus making it tabbable in the correct/logical sequential order.

[Example JSFiddle](https://jsfiddle.net/wkkrnak6/14/)

I would expect this prop to likely remain `tabIndex`, however something like `inputTabIndex` may also suffice. This value would make sense to be restricted to >= 0, however, i can anticipate a use case for allowing -1 to exist.

**Comment by ericgio** [comment]
This should be covered by #79.

**Comment by haxxxton** [comment]
@ericgio from have a quick look at the code, simply setting the tabindex on the input is likely to cause issues with then tabbing to tokens and leaving the input.

This likely needs to be a more integrated solution to modify the tabindexs of elements within the typeahead too.
