### ISSUE TITLE
Skip `isPlainObject` check if `labelKey` is a function in `getOptionLabel`

### ISSUE THREAD

**Issue by guntiso** [ericgio/react-bootstrap-typeahead#213]
isPlainObject(option) in getOptionLabel returns false for Scala.js objects. If labelKey is function, this check should be skipped.

**Comment by ericgio** [comment]
I'm not in favor of special-casing the code for various frameworks. If you have suggestions for a general solution, I'm open to it, but otherwise it's up to the developer to convert the data before passing it into the component.

**Comment by ericgio** [comment]
Unless you're simply suggesting I move the `isFunction` check out of the `isPlainObject` check?

```
if (isFunction(labelKey)) {
  optionLabel = labelKey(option);
}

if (isPlainObject(option) && typeof labelKey === 'string') {
  optionLabel = option[labelKey];
}
```

**Comment by guntiso** [comment]
Yes, that was the idea.

**Comment by RichardBradley** [comment]
I have the same problem.

I am not using Scala.js, but I am using Typescript. My option objects are classes, so "isPlainObject" returns false. This means that I can't construct a typeahead dropdown using a collection of these objects, whether my "labelKey" is a string (for a property) or a function. In both cases I get a "One or more options does not have a valid label string." error.

I can work around this for now by copying the typed option objects into untyped "plain objects".

**Comment by exinferis** [comment]
This is actually great, since this is a show stopper for us as well. Any plans when to release a new Alpha containing this fix?

**Comment by ericgio** [comment]
Updated in v2.0.0-alpha.3
