### ISSUE TITLE
Deletion of token disables menu expanding by mouse

### ISSUE THREAD

**Issue by dmytro-shchurov** [ericgio/react-bootstrap-typeahead#217]
Go to the "Basic Example", check on "Multi-Select", so typeahead control is in `multiple` mode.
Select at item, and then delete it by clicking on a token `x`.
Selected item is removed, but when you click inside the control to open a menu with options again, nothing happens.
This occurs when mouse clicks on the placeholder ("Choose a state..." in this particular example). 
When the control looses focus, or mouse clicks inside the control but _outside of the placeholder_, everything works fine.

**Comment by ericgio** [comment]
Thanks for the report. It seems like this is only happening when the last token is removed, but not an issue when there are multiple tokens and one of those is removed.

**Comment by ericgio** [comment]
It looks like this actually only happens when trying to click on the actual `<input>` element (ie: the placeholder text); clicking elsewhere in the component will display the menu.

**Comment by ericgio** [comment]
Fixed in v2.0.0-rc.1
