### ISSUE TITLE
After Text Typed, mouse not clickable in dropdown list

### ISSUE THREAD

**Issue by gopinath-sixt** [ericgio/react-bootstrap-typeahead#218]
### Steps to reproduce
I have used 
<Typeahead
        labelKey={option => `${option.firstName} ${option.lastName}`}
        options={[
          {firstName: 'Art', lastName: 'Blakey'},
          {firstName: 'John', lastName: 'Coltrane'},
          {firstName: 'Miles', lastName: 'Davis'},
          {firstName: 'Herbie', lastName: 'Hancock'},
          {firstName: 'Charlie', lastName: 'Parker'},
          {firstName: 'Tony', lastName: 'Williams'},
        ]}
        placeholder="Who's the coolest cat?"
/> 

### Expected Behavior
When i text typed as "Art"  should be clickable in text from dropdown menu list

### Actual Behavior
When i text typed as "Art"  not clickable in text from dropdown menu list

**Comment by ericgio** [comment]
The code you posted is the same as the [labelKey example](http://ericgio.github.io/react-bootstrap-typeahead/#labelkey), which works fine. I suspect there's something else going on with your implementation; if you can post a fiddle or test case that repros the issue I can try to help you.

**Comment by ericgio** [comment]
Ok, so it turns out that clicking on the highlighted text in the menu item doesn't work, but clicking anywhere else does. Thanks for the report.

**Comment by gopinath-sixt** [comment]
Thank @ericgio. I am looking solution through #219
