### ISSUE TITLE
newSelectionPrefix isn't passed to menu

### ISSUE THREAD

**Issue by jlai** [ericgio/react-bootstrap-typeahead#22]
`<Typeahead newSelectionPrefix="New: ">` doesn't change the displayed prefix because [it doesn't pass it to TypeaheadMenu](https://github.com/ericgio/react-bootstrap-typeahead/blob/v0.5.0/src/Typeahead.react.js#L177-L188).

**Comment by ericgio** [comment]
Nice catch, thanks.

**Comment by ericgio** [comment]
Fixed in v0.5.1

**Comment by gravitymedianet** [comment]
@ericgio , I cannot set newSelectionPrefix in my TypeaheadInput. It seems it is only a property of TypeaheadMenu per the docs. Has this changed?

**Comment by ericgio** [comment]
@gravitymedianet: I'm not sure I understand your question. The `newSelectionPrefix` is indeed rendered in the `TypeaheadMenu` component.

**Comment by ericgio** [comment]
@gravitymedianet: Can you please post an example of your code?
