### ISSUE TITLE
Multiple selected input are not placed inline

### ISSUE THREAD

**Issue by minhkuheo** [ericgio/react-bootstrap-typeahead#220]
Hello Ericgio

I'm new to react-bootstrap-typeahead and im trying to use it. I have been googled around both her inside and Stack-Overflow but could not find the answer. 

**The issue** is:  

- _at the result of using `<Typeahead multiple>` tag, the selected inputs are not listed inline, but each one of them jumps down to a new line and therefore push down the mouse cursor, so the cursor appears outside of the input field._

What i have done is completely standard:

1. create a new project using Create-React-App
2. npm install --save react-bootstrap-typeahead
3. npm install --save react react-dom
4. npm install --save react-bootstrap
5. npm start
6. I now edit the App.js and use the very first example from the [docs](https://ericgio.github.io/react-bootstrap-typeahead/) as seen following:

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import {Typeahead} from 'react-bootstrap-typeahead';

class App extends Component {
  render() {
    return (
      <div>
        <Typeahead
          labelKey="name"
          multiple
          options={['options','Minhkuheo','Kumiheo']}
          placeholder="Choose a state..."
        />
      </div>
    );
  }
}
export default App;
```

Typeahead function works, but the result is not as same as in the documentation (as described above). Therefore I do not know if it is default or I need to style it myself or it is actually an issue. Would you please guide me with this?

I apologize if my post should not have been here. :( 
Thank you in advance
Minh Xuan Ho

**Comment by ericgio** [comment]
You need to include the CSS provided with the package:

```
import 'react-bootstrap-typeahead/css/Typeahead.css';
```

**Comment by EzequielBurg** [comment]
First, congratulations for your job @ericgio . It's very useful.
Second, thanks for your question @minhkuheo , it saved me.
I am implementing a multiple select with this, but don't worked.
Now when I see your solution (importing CSS file), it solved my issue.
Thank you a lot. 🚀
