### ISSUE TITLE
Focus on the typehead input using a click handler on a button

### ISSUE THREAD

**Issue by usman-maavan** [ericgio/react-bootstrap-typeahead#222]
Hi,

Is there a way i can use a click handler on a button to focus on Typehead. In current version there is no way to add the id in the input so i can't use document.getElementById('typeHeadId').focus()
So is there any alternative to do this?

Thanks,

**Comment by ericgio** [comment]
Yes, please [read the docs](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md) and [see the examples](http://ericgio.github.io/react-bootstrap-typeahead/#public-methods) for how to do this.

**Comment by usman-maavan** [comment]
Thankssss
