### ISSUE TITLE
What is the correct way to get the value of the Typeahead field?

### ISSUE THREAD

**Issue by Bandit** [ericgio/react-bootstrap-typeahead#223]
New to React so this is probably super obvious, but what's the correct way of retrieving the value of a Typeahead instance?

I see that `element.getInstance().state.selected` has the value(s) I need, but I feel like this isn't the right way to get it?

**Comment by tomislavhren** [comment]
Typeahead component has onChange property. You can pass your function that accepts argument which is selected value.

e.g.:
`<Typeahead onChange={ (selectedValue) => console.log(selectedValue) }/>`

**Comment by Bandit** [comment]
So recommended way to capture value on a form submission is to have already stored it elsewhere via the onChange event? Hmmm

**Comment by tomislavhren** [comment]
My preferred way for dealing with forms is redux-forms library. Check it.

However, if you don't have any intention using some library for forms, you can change your state (within onChange method) which contains your form data. 

Suppose you have state like:
`
...
this.state = { firstName: '', lastName: '', email: '' };
...
`
and you have 3 input fields, one for each property, first, last name and email.
And suppose you pass list of emails to typeahead component and onChange function like:
`
onChange = (value) => {
   const { email } = this.state;
   this.setState({ email: value }); // value is selected value from typeahead, in this case new email
}

<Typeahead 
 options={[ 'mail@mail.com', 'mail2@mail2.com' ]} 
 onChange={this.onChange}
/>
`

This way you could handle your forms. Same way with firstName and lastName, you would pass onChange methods and update your state.

**Comment by ericgio** [comment]
@tomislavhren: thanks for jumping in with an explanation. I'm going to close this out since it's not an issue with the component.
