### ISSUE TITLE
Cursor jumping to the end when editing in the middle

### ISSUE THREAD

**Issue by aguo777** [ericgio/react-bootstrap-typeahead#229]
When editing the text in the middle of the input, the cursor jumps to the end (I guess due to the `componentDidUpdate` logic in `TypeaheadInput`). Is there any reason this behavior is desirable? It'd be great if this weren't the case, or at the very least specifiable via a prop. Thanks!

**Comment by ericgio** [comment]
Thanks for the report. It's a bug, just not trivial to fix.

**Comment by arvinx** [comment]
+1 Also experiencing the same issue

**Comment by ericgio** [comment]
This seems to be [a known behavior](https://github.com/facebook/react/issues/955) with React, though not considered a bug.

**Comment by ericgio** [comment]
Fixed in v2.0.0-alpha.5
