### ISSUE TITLE
onSelected method

### ISSUE THREAD

**Issue by jmuffat** [ericgio/react-bootstrap-typeahead#233]
First of all, thanks for this very useful component, works great !

I am trying to have my UI do something specific when the user selects a value from the menu.
I have had reasonable success by adding an onClick to the MenuItem, unfortunately that's not enough as it doesn't work if the user selects an item using the keyboard : the [enter] key doesn't trigger onClick. Is there any known way of getting called back at the point when the MenuItem value is transferred to the main input field ?

```
<Typeahead
            options={this.state.options}
            labelKey={option=>option.name}
            renderMenu={(results, menuProps) => {
              return (
                <Menu {...menuProps}>
                  {results.map((result, index) => (
                    <MenuItem option={result} position={index} onClick={ev=>this.Found(result)}>
                      <strong>{result.name}</strong>, {result.comment}
                    </MenuItem>
                  ))}
                </Menu>
              );
            }}
            value={this.state.value}
            placeholder="Your option"
            onInputChange={value=>this.onInputChange(value)}
          />
```

(sorry, don't know how to preserve code formatting here)

**Comment by ericgio** [comment]
Use `onChange`

**Comment by jmuffat** [comment]
Thanks for your quick answer, I misunderstood the documentation.
Keep up the great work.
J.
