### ISSUE TITLE
Tab completion coverage

### ISSUE THREAD

**Issue by solace** [ericgio/react-bootstrap-typeahead#234]
Hi,

At the moment tab completion works if the entered characters match the start of an option, eg. tab on the following will select "Medical - hospital"

<img width="239" alt="screen shot 2017-09-26 at 15 59 58 pm" src="https://user-images.githubusercontent.com/374583/30849106-d6026594-a2d3-11e7-9562-fba9ddf89587.png">

However, if you type "hos", tab leaves the entered value as "hos":

<img width="240" alt="screen shot 2017-09-26 at 16 00 08 pm" src="https://user-images.githubusercontent.com/374583/30849142-f5b2db26-a2d3-11e7-9c92-461d40720a16.png">

I have been able to reproduce this with your live examples by typing "Hamp" into the Basic Example.

Should this scenario work, or is there a way to make this scenario work?

Thanks

**Comment by ericgio** [comment]
What you're describing is the expected and intended behavior. The hint implies that tab-completion is possible; the absence of the hint, therefore, indicates that tab-completion won't work.
