### ISSUE TITLE
Updating peer dependencies for react and react-dom 

### ISSUE THREAD

**Issue by shashankraider** [ericgio/react-bootstrap-typeahead#239]
We are using react-bootstrap-typeahead in our project , recently we upgraded to react 16.0 ,Post that we are getting peer dependency error 
"npm ERR! code EPEERINVALID"

**Comment by ericgio** [comment]
Thanks for the report. Please note that I haven't upgraded the peer dependencies yet because not all the of the dependencies support React 16 yet. When that happens, I'll update this package.

**Comment by ericgio** [comment]
Support for React 16 added in v2.0.0-alpha.5. Please note that the dependency `react-highlighter` still doesn't support React 16, so NPM > 4 will warn you about this,  and NPM <=4 will error.
