### ISSUE TITLE
Cannot read property 'value' of undefined error... 

### ISSUE THREAD

**Issue by arn95** [ericgio/react-bootstrap-typeahead#24]
With ES6 you gotta do this:

```
constructor(props){
        super(props);
        this.state = {
            searchValue: ''
        };
        randomClass.context = this;
}
```
then

`handleTextFieldChange(key, event){
       randomClass.context.setState({[key]: event.target.value});
 }`

and finally in render()

`<Typeahead onInputChange={this.handleTextFieldChange.bind(this,'searchValue')} labelKey="name" options={myData}/>`

But its still giving me the error... 
The solution above if applied to another input works just fine.
Why is event.target undefined when I call handleTextFieldChange in the component?

**Comment by arn95** [comment]
Ok I fixed it but its counter intuitive... apparently the value of the field is stored in event not event.target.value so this line in handleTextFieldChange() works: `randomClass.context.setState({[key]:event});`
What I had before was : `randomClass.context.setState({[key]: event.target.value});`

**Comment by ericgio** [comment]
I'm a little unclear on how your code is structured, but `onInputChange` receives the text string as the callback param, not an event. So your code above should actually be:

```
handleTextFieldChange(key, textString) {
  randomClass.context.setState({[key]: textString});
}
```

That may be my fault for not making it clear in the documentation.

**Comment by ericgio** [comment]
Sorry, I think I basically just repeated what you said. I just wanted to clarify that there's no event being passed.

**Comment by arn95** [comment]
Yeah I read the docs more carefully this time and it said right there that it gets a text value. Sorry, I thought it works just like a normal react component that receives an event in the callback. Thanks! Lovely library mate :)

**Comment by ericgio** [comment]
I updated the docs yesterday due to your confusion, so that wasn't there the first time around. You're not crazy :) And thanks for the kind words.
