### ISSUE TITLE
multiple allows duplicate tokens in some situations

### ISSUE THREAD

**Issue by bugzpodder** [ericgio/react-bootstrap-typeahead#242]
Hi Eric,

### Version
2.0.0 alpha-3
### Steps to reproduce
Problem: Able to add duplicate tokens during multi-select.
There are two ways:
1. via defaultSelected, then enter any token.  
2. via custom create, 
3. AsyncTypeahead seem to allow you to select a duplicate for a short period of time 
### Expected Behavior
ideally multiple would not allow the same token to be selected twice
### Actual Behavior
<img width="908" alt="screen shot 2017-10-06 at 12 27 35 pm" src="https://user-images.githubusercontent.com/14841421/31295135-38f19aba-aa92-11e7-919d-159bd4b3705a.png">

-Jack

**Comment by bugzpodder** [comment]
Just to clarify, there are three ways to repro:
1. defaultSelected contains token A, then the typeahead will allow the user to select the same token A.
2. if token A was already selected by the user, if allowNew is used the user can create a new token with the same key.
3. I was able to get the github user typeahead to list and select my user ID multiple times by partially entering the ID, as shown.

**Comment by ericgio** [comment]
Thanks @bugzpodder. I'll need to investigate #1 & #3 further to see if these are indeed bugs.

For #2, this is a known behavior and I don't consider it a bug. The label in the token is duplicated, but each item has a unique id. Ultimately, the component works with the data that is passed to it and has no real knowledge about the structure of that data. I consider it the developer's responsibility to de-dupe data and make sure unique items are only passed in (and selected) once.

**Comment by ericgio** [comment]
Did some more investigation into this issue.

In the `defaultSelected` case, it's true that you can pass duplicate items in and the typeahead will display them. I suppose I could de-dupe items [here](https://github.com/ericgio/react-bootstrap-typeahead/blob/2.0/src/containers/typeaheadContainer.js#L15-L17), though my feeling is it should up to the developer to make sure the data being passed in is clean. Let me know if you have further thoughts about this case.

For the async example, I agree that's a bug. The component should receive the new result set on each search and filter out the selection.

**Comment by ericgio** [comment]
Actually, the async example is technically not a bug. The filtering code compares the option to the selections to see if they are equal. In this particular case, it's the same user, but the `score` field that comes back in the results is different, so the component thinks they're different. I'll try to update the example to omit this field and it should work correctly.

One potential solution for some of these issues is to allow the developer to specify a `uniqueKey` —
 similar to how `labelKey` works — so the component could do comparisons on that value.

**Comment by bugzpodder** [comment]
Thanks for the thoughts Eric.  I don't have strong feelings about these as you indicated the developer could always do filtering outside of the typeahead.

**Comment by ericgio** [comment]
I've updated the async example, so the behavior should now be correct. I'll consider this issue resolved for now.
