### ISSUE TITLE
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

### ISSUE THREAD

**Issue by sanoop-jose** [ericgio/react-bootstrap-typeahead#245]
After upgrading to the latest version (2.0.0-alpha.4), I am getting the following warning

Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

React Version: 16.0.0

**Comment by ericgio** [comment]
It's not coming from the typeahead code; I don't use `getDefaultProps` anywhere. Can you check the stack trace to see where that's actually being called?

**Comment by ericgio** [comment]
Are you using npm or yarn?

**Comment by sanoop-jose** [comment]
I am using npm (5.0.3), webpack (3.8.1)

In the stack trace, I can see that it's being called from react-bootstrap-typeahead.min.js

**Comment by ericgio** [comment]
Hmmm, I think the dist file for v2.0.0-alpha.4 may not have been generated correctly. I'll need to release a new version with the correct build.

**Comment by ericgio** [comment]
v2.0.0-alpha.5 should have all the correct packages now.
