### ISSUE TITLE
Infinite loop when using renderMenu

### ISSUE THREAD

**Issue by derwaldgeist** [ericgio/react-bootstrap-typeahead#246]
I am trying to group my menu items along a `type` attribute. This is the code for doing this:

```js
  renderMenu(results, menuProps) {
    const groupItems = type => {
      const filteredResults = _.where(results, {type});
      return filteredResults.map((result, index) => (
        <MenuItem key={result.id} option={result} position={index}>
          {result.label}
        </MenuItem>
      ));
    };
    return (
      <Menu {...menuProps}>
        {groupItems('type1')}
        {groupItems('type2')}
        {groupItems('type3')}
        {groupItems('type4')}
      </Menu>
    );
  }
```

If I only have `{groupItems('type1')}` inside `<Menu>`, everything works as expected. But as soon as there's a second call to `groupItems`, `renderMenu()` runs into an infinite loop. Do you have any idea what may cause this behaviour?

**Comment by derwaldgeist** [comment]
The problem seems to be caused by `menuItemContainer()`. If I render a plain item (just a div), it works. But as soon as I wrap it with `menuItemContainer()`, the loop runs infinitely.

**Comment by derwaldgeist** [comment]
I have a suspect for the root cause. I guess this line is causing the infinite recursion:
https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/containers/menuItemContainer.js#L59

**Comment by ericgio** [comment]
One issue with your code is that the position/index of each item is not unique; it starts over each time you call `groupItems`. This value needs to be unique (and sequential, unlike react keys) for the menu to behave correctly.

**Comment by ericgio** [comment]
Yup, that's the issue. Try this:

```jsx
renderMenu(results, menuProps) {
  let position = -1;

  const groupItems = type => {
    const filteredResults = _.where(results, {type});
    return filteredResults.map((result) => {
      position++;
      return (
        <MenuItem key={result.id} option={result} position={position}>
          {result.label}
        </MenuItem>
      );
    });
  };

  return (
    <Menu {...menuProps}>
      {groupItems('type1')}
      {groupItems('type2')}
      {groupItems('type3')}
      {groupItems('type4')}
    </Menu>
  );
}
```

I'll update the docs to clarify the requirements for the `position` prop.
