### ISSUE TITLE
React 16 compatibility issues

### ISSUE THREAD

**Issue by sanoop-jose** [ericgio/react-bootstrap-typeahead#247]
react-bootstrap-typeahead is not working properly with React 16(CSS issues).

Steps I followed
`npm i --save react-bootstrap-typeahead`

In app.js
`import {Typeahead} from 'react-bootstrap-typeahead';`

`<Typeahead
          multiple
          onChange={this._handleChange}
          options={options}/>`

**Comment by ericgio** [comment]
I don't think this is a React 16 issue. You just need to include the CSS file from the package.
