### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by katerberg** [ericgio/react-bootstrap-typeahead#251]
### Version
0.4.1

### Steps to reproduce
Have React 16 installed

### Expected Behavior
No warnings on installation

### Actual Behavior

```npm WARN react-highlighter@0.4.1 requires a peer of react@^0.14.0 || ^15.0.0 but none is installed. You must install peer dependencies yourself.```

**Comment by ericgio** [comment]
This is an issue with `react-highlighter` not yet supporting React 16. See #239 for more.
