### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by CentaurWarchief** [ericgio/react-bootstrap-typeahead#259]
Hey @ericgio — just a heads up that react-highlighter was republished (0.4.1) featuring React 16 on its `peerDependencies`. We good to go?

**Comment by ericgio** [comment]
react-highlighter@0.4.1 doesn't add React 16 as a peer dependency. That change was merged after the release. Maintainer has yet to publish a new release.

**Comment by ericgio** [comment]
Resolved in v2.0.0-rc.3

I ended up just writing a stripped-down version of react-highlighter and removing that dependency entirely. Given that I'm only using a specific subset of features, this solution provides more control over the development cycle.

**Comment by CentaurWarchief** [comment]
@ericgio https://github.com/helior/react-highlighter/commit/d171e6c24f6d89fbfdb9e3267f746b65b8df569f

**Comment by ericgio** [comment]
As noted above, react-highlighter is no longer a dependency as of v2.0.0-rc.3.
