### ISSUE TITLE
Don't allow blank field

### ISSUE THREAD

**Issue by generak13** [ericgio/react-bootstrap-typeahead#260]
Hi. I want to use your component with autocomplete instead of standard dropdown (select html tag). But blank value must be forbidden. Can it be implemented?
Thanks.

**Comment by ericgio** [comment]
Is this a feature request or are you asking how to implement what you want?

**Comment by generak13** [comment]
One of these

**Comment by ericgio** [comment]
I'm sorry, I don't understand what you're asking for. Please re-open with an additional description, code examples, etc. Thanks.

**Comment by generak13** [comment]
Now Typeahead component allow the value to be blank. I think that it is good to implement feature like http://alxlit.name/bootstrap-chosen/. So we can write somethink like this:
`
<Typeahead
  onChange={this._handleChange}
  options={myData}
  **allowBlankValue=false**
/>
`

So one element from myData **must** be selected (just implement standard *select* html tag with autocomplete).
What do you think?

**Comment by ericgio** [comment]
I don't currently have plans to add a feature like that, but might consider it in the future.
