### ISSUE TITLE
Combobox Feature

### ISSUE THREAD

**Issue by knnemade99** [ericgio/react-bootstrap-typeahead#265]
Initially when no item is selected , all the items were shown in the drop down list of react bootstrap typeahead,
But if I select some item from the list and again click on typeahead it shown only the item which is selected, so if i want to change the selected item i need to first delete or clear the previous selected item.

What I want is that even if a item is selected, all items should be shown in the drop down of the list of react bootstrap typeahead.

I am attaching the screenshot to make this problem more clearly visible.

** Before selection all items were shown in the drop down**
![capture](https://user-images.githubusercontent.com/20987636/32886112-a98e0006-cae5-11e7-8b56-dd1f3f471cf7.PNG)

**After Selection Only 1 item is shown in the drop down**
![capture2](https://user-images.githubusercontent.com/20987636/32886111-a9520ed4-cae5-11e7-9718-101f9ccf28e8.PNG)

Please let me know if anyone knows the solution to this problem

Thanks in Advance

**Comment by ericgio** [comment]
It sounds like what you want is combobox functionality, which is possible to achieve with the component, but not available out of the box. See [this StackOverflow answer](https://stackoverflow.com/questions/46184159/allowing-mouse-re-selection/46899180#46899180) for more.

**Comment by ericgio** [comment]
As noted above, this is possible through the use of a custom `filterBy` callback:

```jsx
<Typeahead
  filterBy={(option, props) => {
    if (props.selected.length) {
      // Display all the options if there's a selection.
      return true;
    }
    // Otherwise filter on some criteria.
    return option[props.labelKey].toLowerCase().indexOf(props.text.toLowerCase()) !== -1;
  }}
  ...
/>
```
