### ISSUE TITLE
Ability to set is-invalid additionally to form-control

### ISSUE THREAD

**Issue by peterbe** [ericgio/react-bootstrap-typeahead#267]
### Version
2.0.0-rc.4

### Steps to reproduce
n/a
### Expected Behavior
n/a
### Actual Behavior
n/a

I do something like this:
```javascript
{useTypeahead ? 
  <Typeahead onChange={....} options={...}/>
  :
  <input className={isInvalid ? 'form-control is-invalid' : 'form-control'} .../>
}
// THIS GETS rendered to the DOM but hidden by Bootstrap because the 
// previous DOM element only has class="form-control" and NOT class="form-control is-invalid"
{isInvalid ? <div className="invalid-feedback">error</div> : null}
```

In the case of the value being invalid (due to server validation for example) I want to render the form control with a child of `<div class="invalid-feedback">`.

Basically, I need to pass to `Typeahead` that the default className needs to be `'form-control is-invalid'` and not just `'form-control'`.

The way I solve this now is:
```
  componentDidUpdate() {
    [...document.querySelectorAll('div.invalid-feedback')].forEach(el => {
      el.style.display = 'block'
    })
  }
```

**Comment by ericgio** [comment]
Thanks for the report. Unfortunately, there is currently no way to set an arbitrary classname on the pseudo-input (ie: 'form-control') element. Note that the validation you're applying is for Bootstrap 4, which this component does not yet officially support. Closing this issue in favor of #131.

**Comment by swrobel** [comment]
I still don't see a way to achieve this in 3.x, correct me if I'm wrong...
