### ISSUE TITLE
inputProps not passed through to <input />

### ISSUE THREAD

**Issue by geoffRGWilliams** [ericgio/react-bootstrap-typeahead#269]
### Version
`v2.0.0-rc.4`

### Steps to reproduce
Upgrading an existing implementation of `AsyncTypeahead` from `v1.3.2` to `v2.0.0-rc.4`.

We want to be able to set `id="address"` on the *visible* `<input />` element, so that the associated `<label htmlFor="address" />` is semantically linked, for accessibility purposes. Historically we've also been setting the `name` attribute so that it gets applied to the `<input />`, but this is now deprecated in favour of `inputProps`.

Which is great! `inputProps` seems a perfect way to apply both the `id` and the `name`.

However, using `AsyncTypeahead` we found that the props weren't getting applied to the `<input />`. We decided to try a simple `Typeahead` instead:

`<Typeahead inputProps={{name: "hamster", id: "golden", rabbits: "brown", title: "smash it!"}} ... />`

### Expected Behavior
The visible `<input />` element rendered by the `Typeahead` should receive the attribute pairs:

- `name="hamster"`
- `id="golden"`
- `rabbits="brown"`
- `title="smash it!"`

### Actual Behavior

The `inputProps` are not applied to either of the `<input />` elements generated by the `Typeahead`:
![image](https://user-images.githubusercontent.com/21004338/32927976-7f1bfbfa-cbb4-11e7-8fa2-4ca90205058b.png)

**Comment by ericgio** [comment]
It looks like you're still using the old version, which is why the props aren't propagating to the input. Try removing the react-bootstrap-typeahead directory from your node modules and installing the latest version.

**Comment by geoffRGWilliams** [comment]
Yeah, thanks Eric, was just about to close this myself. Appears to have been an npm caching issue. Sorry for the hassle!
