### ISSUE TITLE
no user input

### ISSUE THREAD

**Issue by rpedela** [ericgio/react-bootstrap-typeahead#27]
For my use case, I get all options from the server on the fly. When the textbox is focused and there is no user input yet, the options list is empty and it displays "no matches found". For my use case, that is very confusing to the user. In the case where there is no user input, how can I have it display nothing? I tried setting ```emptyLabel = null``` but it still renders an empty box of options. How can I make it render absolutely nothing for the options?

**Comment by ericgio** [comment]
Seems like a similar issue to the one described in https://github.com/ericgio/react-bootstrap-typeahead/pull/26.

Sounds like you want to just hide the dropdown by default until there is actually user input, which sounds reasonable.

**Comment by rpedela** [comment]
Yes, exactly.

**Comment by ericgio** [comment]
Added `minLength` prop in v0.6.0 so you can now specify how many characters the user must enter before the component will display the filtered results.
