### ISSUE TITLE
Breaking change in 2.0.0 (labelKey and selected props)

### ISSUE THREAD

**Issue by hectorsabina** [ericgio/react-bootstrap-typeahead#270]
There was a breaking change for me after updating from 2.0.0-alpha-3 to 2.0.0.

I was using a Typeahead like this:
```jsx
<Typeahead
          labelKey='value'
          selected={ [this.props.selectedCategory] }
          options={ this.props.categories }
          onChange={ this.onSelectCategory }
          />
```

The `selected` prop started with a value of `[ null ]` (array with a null element). After I bumped the version, an error started to show up:

"One or more options does not have a valid label string. Check the `labelKey` prop to ensure that it matches the correct option key and provides a string for filtering and display."

It seems that now when setting the initial state, the `labelKey` is used to set the input's value when it wasn't previously taken into account (#1d5a8b). I could fix it easily by changing it to `selected={ this.props.selectedCategory? [this.props.selectedCategory]: [] }`.

I thought I would give you a heads up, although it's probably a fault on my side as I shouldn't be passing the `selected` prop like I was doing before.

**Comment by hectorsabina** [comment]
Sorry, I closed it by accident :)

**Comment by ericgio** [comment]
Yeah, you shouldn't be passing an array of null values to the component. I'm not sure why you weren't seeing errors before, but it's probably a bug that you *weren't*. Just pass an empty array as you suggested.

**Comment by ericgio** [comment]
v2.0.1 makes the proptypes for `selected` and `defaultSelected` the same as those for `options`, so you'll now get a warning about invalid proptypes if you pass an array with null or undefined items.
