### ISSUE TITLE
bodyContainer prop replaces body class instead of adding to class list

### ISSUE THREAD

**Issue by pinksynth** [ericgio/react-bootstrap-typeahead#273]
When the `bodyContainer` prop is set to `true`, opening the typeahead input replaces the `<body>` element's class attribute with `rbt-body-container`. Instead, should it not append that class to `<body>`'s class list?

First time question-asker here, thanks for your time.

### Version
2.0.0 / latest

### Steps to reproduce
Set `bodyContainer` prop to `true`, open typeahead input.

### Expected Behavior
`<body>` element's class list gets _appended_ with ` rbt-body-container`.

### Actual Behavior
`<body>` element's class list gets _replaced_ by `rbt-body-container`.

**Comment by ericgio** [comment]
Yeah, that sounds right. Thanks for the report.

**Comment by ericgio** [comment]
Fixed in v2.0.1

**Comment by pinksynth** [comment]
Awesome, thank you!
