### ISSUE TITLE
AsyncTypeahead -> allowNew

### ISSUE THREAD

**Issue by cidevant** [ericgio/react-bootstrap-typeahead#275]
`allowNew` property doesn't work

### Steps to reproduce

```
<AsyncTypeahead
  labelKey="name"
  allowNew={true}
  isLoading={this.state.isLoading}
  newSelectionPrefix="New: "
  selected={this.state.selected}
  options={this.state.options}
  onChange={this.onSelect}
  onSearch={this.onSearch}
/>
```

### Expected Behavior

<img width="868" alt="screen shot 2017-12-01 at 14 59 39" src="https://user-images.githubusercontent.com/7719146/33485885-58a3c4fe-d6a8-11e7-986a-2d56f44a5f01.png">

### Actual Behavior

<img width="580" alt="screen shot 2017-12-01 at 15 00 43" src="https://user-images.githubusercontent.com/7719146/33485915-6ff9deae-d6a8-11e7-9542-7fe287bb56fd.png">

**Comment by cidevant** [comment]
`this.onSearch` must have 2 state transitions: `{loading: true}` -> `{loading: flase}`

**Comment by yaziderman** [comment]
> {loading: true}

As per the [documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#asynctypeahead), The attribute is isLoading, and not loading, right?!
Anyway, this does not work either for me.

**Comment by ericgio** [comment]
> The attribute is isLoading, and not loading, right?!

Correct.

`allowNew` is disabled when `isLoading` is `true`. You can override this by passing a function to `allowNew` that returns a boolean.
