### ISSUE TITLE
Long options overflow input border while user walks down over menu items

### ISSUE THREAD

**Issue by abudarevsky** [ericgio/react-bootstrap-typeahead#276]
### Version
2.0.0-rc4
### Steps to reproduce
Create bootstrap list-group item with AsyncTypeahead inside as column. Create options with long enough labelKey 
```
<div class="container">
  <div class="row">
        <div class="col-lg-3">
            <li className="list-group-item list-group-item-action flex-column align-items-start">
        <div className="d-flex w-100 justify-content-between">
        <h6 className="mb-1">Typeahead title</h6>
        <button onClick={() => this.stopEdit()} className="btn btn-link btn-sm">x</button>
        </div>
        <AsyncTypeahead
          bsSize='small'/>
      </li>
     
        </div>
  </div>
</div>
 ```
### Expected Behavior
When traverse thru menu items selected option text in input truncated by width of rendered input
### Actual Behavior
Selected option text overflow
![2017-12-03 1 13 57](https://user-images.githubusercontent.com/618069/33520290-10b9f3da-d7c9-11e7-98c3-873be7042f62.png)

**Comment by ericgio** [comment]
Thanks for the report. I don't repro this in the latest version (v2.0.2), but feel free to re-open with additional repro steps if I'm missing something.

**Comment by abudarevsky** [comment]
Great! I tested with 2.0.2 and can confirm that it works

**Comment by abudarevsky** [comment]
that's strange. I have updated the version ("react-bootstrap-typeahead": "^2.0.2",) and at the very first moment I was sure it got fixed (I saw '...' in the end of the line). But after big refresh I still can see overflowed text

**Comment by openciti** [comment]
Hi,

Anybody know how to set max-width and ellipsis overflow for this component? 

Thanks.
