### ISSUE TITLE
allowNew item is not visible when lots of options are matched

### ISSUE THREAD

**Issue by bayoung** [ericgio/react-bootstrap-typeahead#277]
First of all, I've had great success with this component, thanks for the hard work!

However, I am using a Typeahead with data that can sometimes result in a large number of matching options for the value that is typed in. For example, the value might be a prefix for 20 existing options, but the user intent is to add it as a new value. Unfortunately only 12 options are shown, and the item with the newSelectionPrefix value is at the bottom of this list so it is invisible. This makes it challenging to discover and get the desired behaviour.

It is made worse by the fact that the list with the matching options does not show a scrollbar or any other graphical treatment that indicates there are more items that aren't currently visible.

For my purposes I think it would work better if the item that allowNew puts in the list is always visible, perhaps by putting it at or towards the top. e.g. a new attribute "allowNewIsAtTop", or a new attribute value for "allowNew" of "top"?

**Comment by ericgio** [comment]
Thanks for the feedback. The case you're describing strikes me as relatively uncommon, so it's unlikely I'll add this functionality out of the box. However there are a couple ways you could solve your problem:

1. Increase the `maxHeight` value to display more results without scrolling (quick fix)
2. Use `renderMenu` to render your own custom menu with the new option at the top.
