### ISSUE TITLE
Integrating Popper.js to manage menu position

### ISSUE THREAD

**Issue by Guymestef** [ericgio/react-bootstrap-typeahead#281]
Feature requests
=======================
Integrating Popper.js to manage menu position as bootstrap do, would be a better idea than using the dropup prop.
Good or bad idea?

**Comment by Guymestef** [comment]
Popper.js lib: https://github.com/FezVrasta/popper.js/#react-vuejs-angular-angularjs-emberjs-etc-integration

**Comment by ericgio** [comment]
The main thing this would address is #125.

> a better idea than using the dropup prop

Note that Bootstrap still incorporates an explicit [dropup version](https://getbootstrap.com/docs/4.0/components/dropdowns/#dropup-variation).

**Comment by ericgio** [comment]
Closing this as more or less a dupe of #125.

**Comment by ericgio** [comment]
As of v3.0.0 the component uses Popper.js (via `react-popper`) for positioning. Thanks for the suggestion!
