### ISSUE TITLE
render all options menu on match value

### ISSUE THREAD

**Issue by guilleCM** [ericgio/react-bootstrap-typeahead#282]
### Expected Behavior
I would like all available options to be shown if the input value is an exact match to one of them. I mean if the user writes a value that matches with one of the options I want to display all the options (and make the matched one active) instead the only one that already is matching. 
I tried with the renderMenu prop of Typeahead but I can't get him to have the behavior expected.
This is my code:
```
    render() {
      let options = this.state.options;
      let optionsValues = this.state.options.map(v => v.value);
      let value = this.state.inputValue;
      if ( optionsValues.includes(value) ) {
        const TypeaheadMenuItem = menuItemContainer(MenuItem);
        return (
          <div className="col-4">
            <label className="form-group has-float-label" name={this.props.name}>
              <Typeahead
                labelKey="value"
                onInputChange={this.updateInputValue}
                selected={[this.state.inputValue]}
                options={options}
                placeholder={this.props.name}
                selectHintOnEnter={true}
                disabled={this.props.disabled}
                renderMenu={(results, menuProps) => {
                  return (
                    <Menu {...menuProps}>
                      {options.map((opt, ind) => 
                        <TypeaheadMenuItem option={opt} key={ind} position={ind} active={opt.value==value}>
                          {opt.value}
                        </TypeaheadMenuItem>
                      )}
                    </Menu>
                  );
                }}
              />
              <span><b>{this.props.name}</b></span>
              <div className="invalid-feedback"></div>
            </label>
          </div>
        )
      }
```
I can see the options but for some reason all the options have the prop active as true.
### Actual Behavior
Here is a sample of how is my component behavior right now
https://gyazo.com/9cbb9842654d681f7ff3e1a2e663e09e

**Comment by ericgio** [comment]
Hi, questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Feel free to post a link to your SO question on this thread and I'd be happy to try and help.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead

Thanks

**Comment by guilleCM** [comment]
I posted my question in SO and I still looking for a solution. I don't know how to implement this feature (on match display all the options as if no filter were applied)
https://stackoverflow.com/questions/47959539/render-all-options-menu-on-match-value
