### ISSUE TITLE
submitFormOnChange

### ISSUE THREAD

**Issue by albertpeiro** [ericgio/react-bootstrap-typeahead#283]
Hi there,
I'd like AsyncTypeahead to submit a form when the menu item is selected (onChange).
Can I achieve this if the form is outside the component in plain html?
I think having this option implemented as `submitFormOnChange` would be interesting as when using this component as a searchbox the use case really calls for it most of the times. This is expected because we're all used to google having such UX.

My component looks like this:
```jsx
render () {
    return (
          <AsyncTypeahead
            {...this.state}
            labelKey="name"
            filterBy={['name', 'meta']}
            bsSize={this.props.size}
            inputProps={this.props.inputProps}
            defaultSelected={this.props.selected}
            placeholder={this.props.placeholder}
            onSearch={this.handleSearch}
            onChange={this.handleChange}
          />
    );
  }
```
And I use it in a form that's not in React.
I'd love to hear your opinions.
Thank you.

**Comment by ericgio** [comment]
Maybe I'm missing something, but can't you just do this in your `handleChange` method?

> Can I achieve this if the form is outside the component in plain html

Sure, just grab the form element and submit it. Wouldn't this work?

```jsx
document.getElementById('my-form').submit()
```

> I think having this option implemented as `submitFormOnChange` would be interesting

I don't see how this would work, given that the typeahead doesn't know anything about the structure of the form (nor should it). This is really up to the developer to implement.
