### ISSUE TITLE
Feature request: Allow attaching the dropdown to a different element so that it can display outside of its container

### ISSUE THREAD

**Issue by atuttle** [ericgio/react-bootstrap-typeahead#284]
This request is inspired by [react-modal](https://github.com/reactjs/react-modal), which offers an `appElement` prop to specify an element in which the modal html is placed. Most of the relevant code seems to be found [here](https://github.com/reactjs/react-modal/blob/master/src/components/ModalPortal.js#L118-L137).

The problem I'm attempting to solve is having my typeahead near the bottom edge of a modal, which results in the menu overflowing and getting cropped:
![image](https://user-images.githubusercontent.com/46990/34391057-9e87ca6a-eb11-11e7-8a6e-a299a37ffc83.png)

I know that I could use `dropUp` but this is a relatively short (small-height) modal and near the top of the screen, so having it drop down and exceed the boundary of the modal would be better UX.

I would like to be able to specify a container for the dropdown portion (but leave the input/etc where it is currently), so that it looks like this:

![image](https://user-images.githubusercontent.com/46990/34391316-cd2c26bc-eb12-11e7-9d93-ff43edd0602f.png)

In order to achieve this I will also need to be able to supply some supplemental CSS to the dropdown UL element as well, to properly align it with the input. It would be nice if I could just supply the CSS to be merged in rather than reimplementing the default behavior with `renderMenu` and `<Menu>`.

**Comment by atuttle** [comment]
Sorry, I got some wires crossed in my brain. react-modal uses `appElement` to hide the rest of your app from screen readers while the modal is open; which is altogether different from what I'm asking for in this feature request.

Instead, I'm hoping that the dropdown can just be appended to `<body>` when a new prop is used. Perhaps this could be accomplished similarly to [portals](https://stackoverflow.com/a/28823590/751).

**Comment by ericgio** [comment]
Try the [`bodyContainer`](http://ericgio.github.io/react-bootstrap-typeahead/#body-container) prop.
