### ISSUE TITLE
Selected text exceeds input boundary

### ISSUE THREAD

**Issue by atuttle** [ericgio/react-bootstrap-typeahead#285]
### Version
2.0.2

### Steps to reproduce
	<div className="col-md-3">
	  <Typeahead
	    selected={"hello world hello world hello world hello world hello world hello world"}
	    options={["hello world hello world hello world hello world hello world hello world"]}
	  />
	</div>

### Expected Behavior

Text gets cut off at the input boundary:

![image](https://user-images.githubusercontent.com/46990/34422933-d32726b4-ebe6-11e7-9a55-c45da485e59f.png)

### Actual Behavior

Text overflows the input boundary:

![image](https://user-images.githubusercontent.com/46990/34422910-a9a387f6-ebe6-11e7-9437-70e64e00e2b7.png)

**Comment by ericgio** [comment]
Examples seem to work fine:

![image](https://user-images.githubusercontent.com/2978513/34423870-19275d72-ebd4-11e7-9f81-961f29f06f22.png)

Please check your CSS to make sure you're not accidentally overriding anything, or post more detailed repro steps.
