### ISSUE TITLE
Incorrect Placeholder Color

### ISSUE THREAD

**Issue by bdjnk** [ericgio/react-bootstrap-typeahead#289]
### Version
2.1.0

### Steps to reproduce
Render a bootstrap `.form-control` with a placeholder next to a `<Typeahead` with a placeholder,
 [**like so**](https://stackblitz.com/edit/typeahead-placeholder-bug?file=index.js).

### Expected Behavior
The placeholder colors should match. More specifically the bootstrap placeholder styling should apply to the Typeahead component.

### Actual Behavior
The browser default placeholder styling is used by Typeahead.

### Further Details
Here are the relevant lines in the latest bootstrap 3, version 3.3.7:
- [placeholder color](https://github.com/twbs/bootstrap/blob/v3.3.7/less/variables.less#L205)
- [placeholder mixin](https://github.com/twbs/bootstrap/blob/v3.3.7/less/mixins/vendor-prefixes.less#L100)
- [placeholder invoked](https://github.com/twbs/bootstrap/blob/v3.3.7/less/forms.less#L132) (applied when the placeholder is a child of `.form-control`).

**Comment by ericgio** [comment]
Awesome, thanks for the detailed report. I'll have a look.

**Comment by ericgio** [comment]
Fixed in v2.1.1
