### ISSUE TITLE
Support defaultSelected in AsyncTypeahead

### ISSUE THREAD

**Issue by richardbenson** [ericgio/react-bootstrap-typeahead#290]
It would be very beneficial to be able to provide `defaultSelected` to `AsnycTypeahead` that is then passed on to the normal `TypeAhead` component.

We use AsyncTypeahed to search for users and add them to various other things.  It would be nice to have the option to pre-fill the current user in that box (we have a number of places where the user would normally want to add themselves but have the ability to add other people or remove themselves).

We'd like just the same syntax as on `TypeAhead` e.g.:

```
            <AsyncTypeahead
                defaultSelected={this.props.defaultSelected}
                clearButton
                multiple={this.state.multiple}
                allowNew={false}
                isLoading={this.state.isLoading}
                labelKey="display_name"
                minLength={2}
                onSearch={this.handleSearch}
                options={this.state.options}
                renderMenuItemChildren={(user, props) => (
                    <UserMenuItem user={user} />
                )}
                onChange={this.props.onChange}
                className="user-selector"
            />
```

I realise this has the potential for someone to pass in the wrong type of object than what the normal search would return, but that's on the implementer.

**Comment by ericgio** [comment]
Using `defaultSelected` on the [Async example](http://ericgio.github.io/react-bootstrap-typeahead/#asynchronous-searching) worked fine for me. Am I missing something about your use case?

**Comment by richardbenson** [comment]
This morning I had an error about invalid propType and an update has solved that, but I get the same error when I tried to manually patch in support for defaultSelected:

```
Error: One or more options does not have a valid label string. Check the `labelKey` prop to ensure that it matches the correct option key and provides a string for filtering and display.
```

Now this morning I assumed it was something in the way I had patched to support defaultSelected so didn't look into it more, I will now however!

**Comment by ericgio** [comment]
Yeah, that looks like a problem with the data you're passing in. I'm going to close this out, but feel free to re-open with a repro case if you think you've found a bug.
