### ISSUE TITLE
Relaxing emptyLabel's PropType requirements

### ISSUE THREAD

**Issue by clayjonesthomas** [ericgio/react-bootstrap-typeahead#292]
It appears that giving `emptyLabel` a React component renders that component just fine. I didn't look too far into the reasoning behind why `emptyLabel` is required to be a string, but I believe React components should be allowed as well. Is there another way to give `emptyLabel` React components that I am missing, or a reason why React components are not accepted?

For convenience, the line with the PropType.
https://github.com/ericgio/react-bootstrap-typeahead/blob/60ea7cec6d497e064b6c23b250bd6ee1307d39c6/src/containers/typeaheadContainer.js#L410

**Comment by ericgio** [comment]
No good reason other than a string seemed like the most likely use case and I hadn't encountered a need for more. I don't see why a component shouldn't be allowed.

**Comment by ericgio** [comment]
As you noted, passing a component to `emptyLabel` now works just fine; the only issue is a React warning, but this is only in developer warning  and shouldn't show up in production or have any other effects on how the component behaves.

**Comment by ericgio** [comment]
Should probably just be

```
emptyLabel: PropTypes.node,
```

**Comment by ericgio** [comment]
This should be resolved as of v2.3.0
