### ISSUE TITLE
Allow dropdown to stay open when multi-selecting

### ISSUE THREAD

**Issue by ryanlynnhorlacher** [ericgio/react-bootstrap-typeahead#294]
When multi-selecting, it would be nice if the dropdown menu stayed open after a selection to allow the user to continue selecting.

**Comment by ericgio** [comment]
Note that you can do this yourself:

```jsx
<Typeahead
  multiple
  onChange={(selected) => {
    this._typeahead.getInstance().focus();
  }}
  options={[...]}
  ref={typeahead => this._typeahead = typeahead}
/>
```

**Comment by ryanlynnhorlacher** [comment]
Thanks for the quick response!  This is a great component.  Thank you for making and maintaining it.

**Comment by nickgrealy** [comment]
TLDR; Old solution didn't work, I had to use `toggleMenu`.

i.e.
```
  const ref = React.useRef()
  const [values, setValues] = React.useState([])
  return (
    <Typeahead
      multiple
      id="properties"
      onChange={(selected) => {
        setValues(selected)
        ref.current.toggleMenu(true)
      }}
      clearButton={true}
      options={options}
      ref={ref}
      values={values}
      placeholder="Choose a property..."
    />
  )
  ```

**Comment by ericgio** [comment]
@nickgrealy great example, thank you! Here's a working sandbox link for anyone else coming across this issue:

https://codesandbox.io/s/rbt-keep-menu-open-during-multi-select-nr2y4
