### ISSUE TITLE
Inline styles added automatically?

### ISSUE THREAD

**Issue by im1dermike** [ericgio/react-bootstrap-typeahead#295]
I have a fairly basic `<Typeahead>` usage and yet the following markup is generated:

    <input type="text" 
        id="filter" 
        placeholder="Search"
        value="" 
        autocomplete="off" 
        class="rbt-input-main" 
        style="background-color: transparent; border: 0px; box-shadow: none; cursor: inherit; outline: none; padding: 0px; width: 100%;"
    >

As you can see, a bunch of inline styles are added automatically.  I'm unclear why this is happening or how to disable it from happening as it is undesirable.  Please advise.

**Comment by ericgio** [comment]
These styles are added by the component and are necessary for it to function correctly. What's the issue?

**Comment by im1dermike** [comment]
Why would eg. removing the border of the typeahead `<input>` be necessary for this library to work?

![Example](https://image.ibb.co/d7MGAc/Untitled.png)

**Comment by ericgio** [comment]
This library is meant to be used with [Bootstrap styles](https://getbootstrap.com/docs/3.3/css/). It looks like you're either not including those or have some custom theme or style that is overriding the `form-control` class.

**Comment by im1dermike** [comment]
Oof.  This (godforsaken) project uses Bootstrap 2.3.2.  This is the only issue I've seen so far.

**Comment by ericgio** [comment]
Sorry, I'm not supporting older (pre-v3) versions of Bootstrap. You could just add the `.form-control` styles you need to get things working correctly.
