### ISSUE TITLE
Suggestion text cut off when using bsSize=large

### ISSUE THREAD

**Issue by alasdairhurst** [ericgio/react-bootstrap-typeahead#296]
### Steps to reproduce
Go to the demo site "input-size" example http://ericgio.github.io/react-bootstrap-typeahead/?#input-size
Select "large"
Start typing "a"

### Expected Behavior
The first suggestion is fully displayed

### Actual Behavior
The first suggestion is cut off

![image](https://user-images.githubusercontent.com/8441810/36023918-03f470a6-0d86-11e8-8e03-c7c64d152b09.png)

**Comment by ericgio** [comment]
Thanks for the report. It's a known bug with react-input-autosize. Closing in favor of #256, which describes the same underlying issue.

**Comment by alasdairhurst** [comment]
Are you sure it's the same? That issue seems to be something specific to hidden fields, but this is an issue is based on the size of the text field (i.e. it works as expected in smaller fields)

**Comment by ericgio** [comment]
The underlying bug is the same, which is that the autosize input doesn't update correctly when new styles are applied. Here's the actual issue: https://github.com/JedWatson/react-input-autosize/issues/73

**Comment by alasdairhurst** [comment]
Thanks. You probably want to tweak the link to a commit for the fix location in that issue since it points to master and master has changed since you posted last :)

**Comment by ericgio** [comment]
This is fixed as of v2.5.1
