### ISSUE TITLE
When the menu is displayed "justified" in the body (bodyContainer=true), it does not take the width of the input

### ISSUE THREAD

**Issue by alasdairhurst** [ericgio/react-bootstrap-typeahead#297]
### Steps to reproduce
Go to the demo site and click on the body dropdown
http://ericgio.github.io/react-bootstrap-typeahead/?#body-container

### Expected Behavior
The full width to be taken up
![image](https://user-images.githubusercontent.com/8441810/36025855-876ff346-0d8c-11e8-98ee-088e39c4e58f.png)

### Actual Behavior
It's slightly smaller than the input width
![image](https://user-images.githubusercontent.com/8441810/36025843-7fa1d936-0d8c-11e8-996c-ef6d3d80f5f1.png)

**Comment by alasdairhurst** [comment]
Additionally, you can see if you set bodyContainer to false in this example, the menu is no longer displayed justified (There's an issue with the selector)

![image](https://user-images.githubusercontent.com/8441810/36026705-2b540be8-0d90-11e8-942c-fd7946dc8dac.png)


Try the same thing on a blank page. I think there's also additional issues with styles which are not surfaced because the styles rely on a .rbt class which is applied to the wrapper, but not in the scope of the menu when it's attached to the body. In your case there are .rbt classes around the page which aren't set by the component by the look of things, which could be hiding styles.

**Comment by ericgio** [comment]
What browser are you using?

**Comment by alasdairhurst** [comment]
Windows 10/Chrome 63

**Comment by ericgio** [comment]
I can repro the first issue, but not the second.

**Comment by ericgio** [comment]
This should be fixed in v3.0.0
