### ISSUE TITLE
Option for menu activation to only happen with user input

### ISSUE THREAD

**Issue by alasdairhurst** [ericgio/react-bootstrap-typeahead#299]
The current functionality always forces the menu to be shown whenever the user clicks on the component. 

My use case:
I would like to defer this menu until the control recieves input from the keyboard
The input is merely a suggestion, and is pre-populated with known "variables". The user can select a variable from the list, or use their own new variable.
When the user clicks on the input to start typing, It would behave similar to many IDEs. The cursor would stay in place and then intellisense would start suggesting when the user types. 
This allows the user to perform actions such as pasting, copying or even tabbing without the menu suggesting something new.

This could be most annoying in the case where the user has typed "foo" (which in this case is perfectly valid), and a suggestion in the list is "foobar" (also valid, but not what the user wants). The current functionality will always prompt the user to pick foobar whenever they click on the component.

I currently have a wrapper which provides this functionality by listening for onInputChange, and setting the component state to "active".
A custom renderer is provided to just display an empty div when the state is not active. (it's an empty div, because it doesn't allow you to return a null node/element with the renderMenu prop.)
Whenever the input blurs, it will reset the active state and require the user to start typing again

**Comment by ericgio** [comment]
Not sure I completely understand the experience you're trying to achieve here, but I believe everything you're asking for is already available.

> I would like to defer this menu until the control recieves input from the keyboard

You can adjust `minLength` for this. If you set it to 1, for example, users will need to type at least one character before they see the suggestions.

> The user can select a variable from the list, or use their own new variable.

Use the `allowNew` prop to [allow arbitrary selections](http://ericgio.github.io/react-bootstrap-typeahead/#custom-selections) by users.

**Comment by alasdairhurst** [comment]
I will try out minLength.. not sure why I didn't think of using it before!

**Comment by alasdairhurst** [comment]
Just an update: It seems minLength only works based on the current length of the input and not what the user typed in after focusing the component.

Example: 
* minLength={1}
* Type "f" - no menu appears
* type "o" (fo) - menu appears - this is ok.
* blur the input and go do something else
* click back in the input and the menu appears because there is at least one character in the input - this isn't what I want/expect in my case. The user should have to make a modification (i.e. anything that causes onInputChange) before the menu appears again.

**Comment by ericgio** [comment]
Based on your example, this feels like pretty uncommon behavior to me — or at least not really what the component was designed to do. I doubt it's something I'd support out of the box, but it looks like you've already managed to get something working on your own.

**Comment by alasdairhurst** [comment]
Ok fair enough, although it's worth thinking about what can be done with the component to allow it to be less opinionated and controlled a bit easier by the user. 
In this case, the smallest change I would suggest would be the option of disabling the menu from rendering by passing in a falsy value to "menu".
Currently, it will try to render anything that is passed in there, and fail if the value is null (even though it is a valid react node).  Possibly check the value and skip rendering the menu in this case?
