### ISSUE TITLE
Clear Input after selecting something an item in Menu.

### ISSUE THREAD

**Issue by jstralko** [ericgio/react-bootstrap-typeahead#30]
I couldn't find a good way to do this in the current code on master.

So as a hack (workaround) I modified the code like:

````javascript
diff --git a/Typeahead.react.js b/Typeahead.react.js
index 27ea850..abafd76 100644
--- a/Typeahead.react.js
+++ b/Typeahead.react.js
@@ -300,6 +300,13 @@ const Typeahead = React.createClass({
       text = selectedOption[labelKey];
     }

+    onChange && onChange(selected);
+    onInputChange && onInputChange(text);
+
+    //clear the text after onChange has been consumed.
+    text = ''
+    selected = [];
+
     this.setState({
       activeIndex: 0,
       selected,
@@ -307,8 +314,6 @@ const Typeahead = React.createClass({
       text,
     });

-    onChange && onChange(selected);
-    onInputChange && onInputChange(text);
````

I know its not perfect but wanted to see what your thought are on a  feature like this.

**Comment by ericgio** [comment]
Can you explain this use case some more or provide an example? Typeaheads and tokenizers typically display the selection(s) in the input, so this would seem to go against that behavior.

**Comment by jstralko** [comment]
I'm building a search box.  So as the user is typing I'm fetching the data and once the user selects the item, I'm then adding that item to a list of selected items. After the selection I want to clear the input so the user can search for another item to be added.

Does that make sense?  I can provide a screenshot if my explanation isn't clear.

**Comment by ericgio** [comment]
That makes sense. Did you try using the `multiple` prop to allow for multi-selection? That supports the general functionality you're looking for, if not the exact behavior.

Alternatively, if you *really* want the exact behavior you're describing, you could write a wrapper for the typeahead that does the following:

- fetches the data
- filters the data based on what has already been selected and passes it into the typeahead
- passes an empty array to the typeahead when the `onChange` callback is fired to clear it

Let me know if that makes sense conceptually.

**Comment by jstralko** [comment]
Thanks for the help.  I will try to do the wrapper idea and let you know.  Thanks for idea.

**Comment by ericgio** [comment]
Cool, I'll consider this issue closed for now unless you let me know otherwise.

**Comment by ericgio** [comment]
I've added a [`clear` method](https://github.com/ericgio/react-bootstrap-typeahead#clear) in v0.7.0 that should allow you to do what you need. Hopefully this fully resolves your issue.

**Comment by jstralko** [comment]
Thank you!  I'll be migrating to 0.7.0 this afternoon.

**Comment by NickBrooks** [comment]
@ericgio - is the `ref="something"` prop available on the `<AsyncTypeahead />`??

Reading the docs and I can't seem to be able to get it to add a ref which I need to perform the `clear()`, which I'll do on option selection.

https://github.com/ericgio/react-bootstrap-typeahead/blob/03c0b7b7f7caa783f908c14eb7955adaa5daa9d1/docs/Methods.md

**Comment by NickBrooks** [comment]
Okay - so I'd done it wrong, had to set ref as per docs which I'd missed:

`ref={ref => this._typeahead = ref}`

I then get the same problem as #193 so I will try and use the workaround suggested for now.
