### ISSUE TITLE
Selected prop should be able to take a string

### ISSUE THREAD

**Issue by alasdairhurst** [ericgio/react-bootstrap-typeahead#303]
The current use of "selected" in a single value (string) input requires a not-so-elegant workaround that could be improved dramatically.
Since selected only takes an array, i need to construct an array of a single value every time like so:
```selected={[props.val]}```
Doesn't look terrible, although it's far from ideal. An additional problem comes in two cases:
* props.val is an empty string: usually a falsy value will not render anything in the selection box, and show the placeholder. This isn't being done for multiselects, and since the length of the selected array is > 0, no placeholder shows even though the value is falsy.
* props.val is null: again, another falsy value which should just be the same as an empty input. This causes errors because the typeahead is trying to use "null" as a selected option and failing when performing operations on the value rather than just ignoring it.

To get around these, i have to do this: ```selected={props.val ? [props.val] : null}``` which is even worse.

The proposal is the following;

* when "multiple" is false, selected can be a string. This will be handled the same as ```selected={["foo"]}``` is currently handled.
* when multiple is false, and selected is an empty string, this should be handled the same as ```selected={null}```

* when multiple is true, and selected is an array that contains falsy values, any falsy values should be detected before rendering and either be ignored, or throw a useful error rather than trying to use the value as if it was a truthy, or had certain string operations.

* when multiple is true, and selected is an array that contains falsy values, these values are ignored (questionable, and worth discussing. Maybe only arrays containing ONLY falsy values are handled the same as no selection, and an array containing a mixture is an invalid prop)

**Comment by PanLydka** [comment]
@alasdairhurst Have you found a solution to get around this problem?

**Comment by alasdairhurst** [comment]
I mentioned my workaround above by manually checking the value. before passing in the property
```selected={props.val ? [props.val] : null}```

 Would be nice to see an improvement though. Don't have time to make a PR

**Comment by ericgio** [comment]
I don't think this is something I'll end up incorporating into the library. I took a look at it and it's actually more involved than it seems at first glance, due to prop validation and how the component updates. It's much simpler if `selected` is normalized *before* being passed to the component. While I understand the proposed approach might be useful for some people, it's also pretty trivial to add yourself if you need or want the functionality:

```js
function normalizeSelected(selected) {
  if (!selected) {
    return [];
  }

  return Array.isArray(selected) ? selected : [selected];
}
```

You could even incorporate the util function into a wrapper to make it more reusable:

```jsx
const MyTypeahead = ({ selected, ...props }) => (
  <Typeahead
    {...props}
    selected={normalizeSelected(selected)}
  />
);
```
