### ISSUE TITLE
Disabled options can be selected on Enter

### ISSUE THREAD

**Issue by hslojewski** [ericgio/react-bootstrap-typeahead#304]
Hello, I understand [how to use disabled options](https://github.com/ericgio/react-bootstrap-typeahead/issues/86), and that disabled options cannot be selected through a mouse cursor. However, they're still "selectable" on keypress/on pressing Enter. 

![giphy-2](https://user-images.githubusercontent.com/13295589/36115075-d136b490-0fe6-11e8-9a5b-34bf57552911.gif)

**Comment by ericgio** [comment]
You're right, thanks. I'll take a look.

**Comment by alasdairhurst** [comment]
Seems like they should also not have hover styles too

**Comment by ericgio** [comment]
Fixed in v2.3.2
