### ISSUE TITLE
AsyncTypeahead doesn't work as a controlled component

### ISSUE THREAD

**Issue by coolkev** [ericgio/react-bootstrap-typeahead#305]
### Version
v2.3.1

### Steps to reproduce
Using Typeahead as a controlled component (by passing in selected prop) works fine with regular Typeahead component. But does not work with an AsyncTypeahead component.

### Expected Behavior
AsyncTypeahead selected props should work just like they do for Typeahead.

### Actual Behavior
The control is unusable.

**Comment by ericgio** [comment]
You're passing a string in the `selected` array, but the options are objects.

**Comment by coolkev** [comment]
@ericgio actually, the non-Async version works as string or object, and that is not the issue with the Async version. I've already got a fix for the Async component, I'm just trying to fix the unit tests since they are relying on the component to raise onChange in the componentWillReceiveProps which is what was breaking the Async controlled component. Would you mind re-opening this issue?

**Comment by coolkev** [comment]
@ericgio the main issue that was causing the Async component to not work as controlled is that the 

componentWillReceiveProps was calling this._updateText (which in turn calls this.props.onInputChange(text)) - since the parent is the one triggering the componentWillReceiveProps, then it shouldn't need to re-raise the props.onInputChanged inside componentWillReceiveProps . 

https://github.com/coolkev/react-bootstrap-typeahead/commit/8a207d379ac564203a510ddb0e6df862e670cacc#diff-dfc6ee56e705f461201154a0c38b7e26

**Comment by ericgio** [comment]
If you're trying to control the value of the input, that's not really possible, as described in #266.

**Comment by coolkev** [comment]
@ericgio it is possible, and I got it working with my changes in the PR #306. I just haven't fixed the unit tests because they are still relying on the onChange event.

onChange events should really not be raised in the componentWillReceiveProps event. Think about the lowest level input component, when you change the value props in a mounted component, it does not call the onChange method. onChange only gets called when the component itself needs to notify the parent of the change (when a user types text). When componentWillReceiveProps is called, its because the parent is letting the child component know about the change.

**Comment by ericgio** [comment]
After trying out both of the examples in #306 again, I still maintain that you're using the component incorrectly and the issue you describe above is not a bug.

As explained [here](https://github.com/ericgio/react-bootstrap-typeahead/issues/266#issuecomment-367241328), using `onInputChange` to update the selected value triggers `onChange` for every keystroke. While that appears to make setting the input value possible on the surface, it's just setting arbitrary selections. The real solution needs to set the value without setting a selection. Hence why I say that the issue described in #266 isn't possible with the current API.

It's possible that there is confusion over what it means for the component to be "controlled". The input itself is not controlled, but the overall component can be controlled by passing in selections.

> onChange events should really not be raised in the componentWillReceiveProps event

I agree with you on this. Others have raised the same issue and I plan on fixing that behavior in an upcoming release.

**Comment by ericgio** [comment]
As of v3.0.0, `change` events are no longer fired in `componentWillReceiveProps`. Thanks for raising that issue.

**Comment by brian-kilpatrick** [comment]
I'm having a related issue trying to use `AsyncTypeahead`. After I make one selection, then **click** anywhere in the input box again, it clears all selections internally, even though it still has `props.selected.length`. Any ideas? 
![image](https://user-images.githubusercontent.com/13888239/59131299-04072480-8940-11e9-8843-d391e2f234aa.png)

**Comment by ericgio** [comment]
@brian-kilpatrick: your issue seems unrelated; can you please file a separate issue with detailed repro steps, and code example or working sandbox? Thanks.
