### ISSUE TITLE
Textarea inputs

### ISSUE THREAD

**Issue by jfengel** [ericgio/react-bootstrap-typeahead#308]
I'd like to be able to specify a multi-line textarea for the input. 

I know it's an unusual use case; ordinarily one only picks from short options. I'm using it to offer a variety of snippets that the user can then edit.

(It would have been nice if CSS made it possible to do this as a matter of styling, but `<input type=text>` and `<textarea>` are fundamentally separate at the HTML level.)

**Comment by ericgio** [comment]
Why not display the user's selection in a separate `textarea`, where they can edit the text however they want, without it affecting the typeahead. Editing the text within the context of the typeahead itself doesn't make sense to me.

**Comment by ericgio** [comment]
At a higher-level, I'd like to eventually add a method to allow more control over how the input is rendered, which would help address issues like #72. I suppose that would theoretically support `textareas`, but I still think the use case and behavior are odd.

**Comment by ericgio** [comment]
Closing in favor of #316
