### ISSUE TITLE
Enable to work with an array of strings

### ISSUE THREAD

**Issue by derekargueta** [ericgio/react-bootstrap-typeahead#31]
If I have an array of strings ready to act as data, I should be able to just pass in the array without having to first transform it into an array of objects

**Comment by ericgio** [comment]
I agree the component should support this case. I'll need to think about a simple (and hopefully elegant) way to implement it with the current code structure. I'm also working on a 1.0 API where the component would be agnostic about data structure.

**Comment by ericgio** [comment]
As of v0.9.0, you can pass an [array of strings](https://github.com/ericgio/react-bootstrap-typeahead#data) instead of objects.
