### ISSUE TITLE
Inconsistent blur event on menu item selection

### ISSUE THREAD

**Issue by alasdairhurst** [ericgio/react-bootstrap-typeahead#310]
### Steps to reproduce
Use the following fiddle:
https://jsfiddle.net/alasdairhurst/wtLgga55/5/

Select a suggestion using the keyboard and press enter
Input does not blur on select

Now select a suggestion with the mouse
Input blurs on select

### Expected Behavior

A consistent behaviour - blur on both or don't blur on select
Personally, I would be for the latter. I feel that blur should only happen when the input loses focus. A different event is used to check if a menu selection is made/changed.

### Actual Behavior

Input blurs inconsistently when using mouse or keyboard for selection

**Comment by ericgio** [comment]
Makes sense. Note that the underlying reason for the difference in behavior is that clicking on a menu item does actually blur the input, while using keystrokes does not. So in this case I'd need to re-focus the input after a menu item has been clicked.

**Comment by alasdairhurst** [comment]
> clicking on a menu item does actually blur the input, while using keystrokes does not

*Should* it behave like this though? What is the reasoning between the different functionality based on the input controller?

**Comment by ericgio** [comment]
> What is the reasoning between the different functionality

That's just default javascript behavior. So like I said, I either need to re-focus the input or prevent the blur.

**Comment by ericgio** [comment]
Fixed in v2.4.0
