### ISSUE TITLE
Expose `TypeaheadMenu` component

### ISSUE THREAD

**Issue by alasdairhurst** [ericgio/react-bootstrap-typeahead#311]
### Steps to reproduce
pass a custom renderMenu() function to Typeahead:
```
renderMenu() {
   return null;
}
```

### Expected Behavior
no menu renders - without error

### Actual Behavior
console error when rendering
![image](https://user-images.githubusercontent.com/8441810/36320062-d4cf2b9c-133c-11e8-809e-c269763018d9.png)

This looks like the location causing the problem
https://github.com/ericgio/react-bootstrap-typeahead/blob/795293e8ef69c303bacda3e1354ab8703b432544/src/Overlay.react.js#L78

The workaround is to return `<div />` instead of null, but it's not ideal since it adds extra crap to the DOM.

**Comment by ericgio** [comment]
Based on this issue and #312, it sounds like what you really want is the ability to control the menu's visibility. Can you describe your use case some more so I can have a better understanding?

**Comment by alasdairhurst** [comment]
Ideally, I would like to control the visiblility based on the options that are filtered. 
I may have an input with "foo" "foobar and "baz", and I have typed "foobar". In this case, since the options have been filtered down to a single value and that value matches the current value in the input field then I will not render the menu since it's unnecessary to render an item which won't have any effect when clicking (since it's not a multi-select)

(see the hideLastMatch property here https://jsfiddle.net/alasdairhurst/myvuvm00/0/)

Obviously, it would be great if there was a prop for that, or the component did a lot of the new features i'm adding out of the box but this seems a little specific, so i don't mind wrapping the renderMenu in this check or any other suggested way.

Controlling the menu's visiblity outside this use case in a controlled or non-controlled way via a showMenu prop or an API would be a little strange since 
1. The existing behaviour showing and hiding the menu based on input and click state would still be going on behind the scenes. I don't think we really want to replace that if a hide/show menu prop is provided
2. Currently the only supported way of getting the current value is through a change callback or from the menuProps in the renderMenu function. This is also the only way I can see that you can get the current options being shown in the menu instead of the array of all the options which i provided to the component.
3. I don't think that using an API to hide/show the menu would work in this case, although i'm currently controlling it by calling setState on the instance for other features (such as using the down arrow to show the menu after it was dismissed).  The best i can think of is listening onKey and then calling hideMenu based on the value, but again, i don't have access to the options that would have been visible, and i don't know if this would cause issues when the menu needs to be shown again.

Now while typing this up, a possible solution is a function prop such as "willShowMenu" which is passed a bunch of state and is called whenever the menu is internally visible. If this function returns (or is resolved with in async cases) true, then the menu shows as normal, otherwise it isn't rendered.
This doesn't exactly solve all my personal cases of showing/hiding the menu (hide on escape, show on down arrow) but it may solve another one where I don't show the menu until the user starts to type. So maybe an API as well as a prop executed on render is the minimal to cover all these cases?

I'm open to anything that makes this easier.

**Comment by ericgio** [comment]
> The workaround is to return `<div />` instead of null, but it's not ideal since it adds extra crap to the DOM.

In your case, I think returning an empty `div` is an acceptable solution. An extra DOM node is a reasonable tradeoff as opposed to potentially adding both API and code complexity, not to mention work on my part.

Sorry I don't have a better answer. Based on what I can gather from the various issues you've opened, you have some highly specific behaviors that you're after. It seems like most of the things you want to do are currently possible, but workarounds are necessary. On the whole, I'm ok with that; I can't account for every single use case out of the box, but I want to provide an API that makes most things, if not everything, possible.

> it's unnecessary to render an item which won't have any effect when clicking

It looks like you're just dealing with strings (and I assume some kind of form submission) so yes, the input value would match one of the options. However, note that in the case you're describing, nothing would actually be selected. For many (most?) people who are passing objects as options, this would not work.

**Comment by alasdairhurst** [comment]
> In your case, I think returning an empty div is an acceptable solution. An extra DOM node is a reasonable tradeoff as opposed to potentially adding both API and code complexity, not to mention work on my part.

Well, in the most simple use case of renderMenu functionality, returning null rather than having to return ```div``` should be valid, since it's a valid react node, and it shouldn't be too difficult to solve this without having to make any major changes.

> you have some highly specific behaviors that you're after. 
> It looks like you're just dealing with strings (and I assume some kind of form submission)
Pretty much. It's a (simple) single value autocomplete field in a form - similar to intellisense, (which seems to be what this component is for - in a non-multiselect mode). I'm not saying every specific functionality i want should be baked in. just something that allows me to get the functionality i need without relying on undocumented/internal stuff and hacky tweaks. That said, the component i'm creating is meant to be "generic" enough to be used in any use case. The additional things i've added can either be controlled by props i've created (such as hiding the last matching item) or enhance the existing functionality. (down arrow to show the menu like a regular multiselect - I could make a feature request for this one)

At the least, allowing any valid react node to be returned from a render function, and exposing the default rendermenu component (and rendermenuchildren component) would simplify things a fair amount.

The ideal behavior/interface would probably be solved by a fully controlled component but it looks like that's a bit far off at the moment.

**Comment by ericgio** [comment]
> it shouldn't be too difficult to solve this without having to make any major changes

PRs welcome :)

**Comment by alasdairhurst** [comment]
Here's one PR: 
https://github.com/ericgio/react-bootstrap-typeahead/pull/313
I could run the tests and linter but couldn't run any of the scripts to get the example environment to properly test it and build it since I'm using Windows.

**Comment by ericgio** [comment]
Added in v2.4.0
