### ISSUE TITLE
maxHeight should accept non-numeric css values

### ISSUE THREAD

**Issue by prystupa** [ericgio/react-bootstrap-typeahead#315]
Why is maxHeight prop typed to be numberic? In my use case I don't need to limit max height, so I pass 'unset'. This works but results in prop type warning.

Thank you!

**Comment by ericgio** [comment]
I made `maxHeight` numeric because I don't see a compelling use case for it to be non-numeric. I'm not sure what your case is, but it seems easy enough to pass in some large enough value if you want to show all the menu items.

**Comment by ericgio** [comment]
Added in v2.4.0
