### ISSUE TITLE
maxlength in 1.3.7

### ISSUE THREAD

**Issue by narendra315** [ericgio/react-bootstrap-typeahead#317]
Hi,

First of all, i want to thank you for this package that you've build.

I want to implement maxlength in version 1.3.7, can this be done?

**Comment by ericgio** [comment]
I don't believe I ever released a v1.3.7, are you sure you have the right version/package?

In any case, adding `maxlength` to the input became possible in v2.0, where you can use `inputProps` to do this:

```jsx
<Typeahead
  ...
  inputProps={{
    maxLength: 10,
  }}
/>
```
