### ISSUE TITLE
Click on button under typeahead element when typehead is selected

### ISSUE THREAD

**Issue by mokkrb** [ericgio/react-bootstrap-typeahead#318]
Bug reports
======================

### Version
"react-bootstrap-typeahead": "^2.0.2"

### Steps to reproduce
```
<Typeahead
    label="country"
    options={['uk', 'ireland', 'france', 'spain', 'italy']}
/>
<button onClick={(e) => console.log(' BUTTON CLICKED')}>
    Click Me
</button>
```

Select the typeahead element to see the list of values in the dropdown menu
When the typeahead element is still selected, click on 'Click Me' button.

### Expected Behavior
Triggers the onClick => should log 'BUTTON CLICKED'

### Actual Behavior
Un selects the typeahead element
A second click on the button will then trigger the button's onClick

### Note
If the button is before the typehead element, it behaves the expected way =>
Once the typeahead element is selected, a click on the button will unselect the typeahead element and will also trigger the button's onClick
```
<button onClick={(e) => console.log(' BUTTON CLICKED')}>
    Click Me
</button>
<Typeahead
    label="country"
    options={['uk', 'ireland', 'france', 'spain', 'italy']}
/>
```

So I looked quite a lot at the docs but couldnt find anything regarding this, so sorry if it has already been covered or it is an expected behaviour, but coudnt find anything about it.

I also tried few things, like adding some other random inputs and selects between the typeahead element and the button and am having some random results as well (such as the button's onClick is triggered on the first click after let say 5 or 6 other inputs in between)

I have noticed that the button is also triggered on first click when the typeahead element and the button are in two different `Col` elements:

```
<Row>
  <Col lg={6}>
    <Typeahead
      label="country"
      options={['uk', 'ireland', 'france', 'spain', 'italy']}
    />
  </Col>
  <Col lg={6}>
    <button onClick={(e) => console.log(' BUTTON CLICKED')}>
      Click Me
    </button>
  </Col>
</Row>
```

**Comment by ericgio** [comment]
I don't reproduce this behavior using the examples. Can you please post a working code example or fiddle?

**Comment by ericgio** [comment]
@mokkrb: I'm going to close this out since I'm unable to reproduce the behavior and having trouble understanding the issue from your description. Please feel free to reopen with more details. Thanks.
