### ISSUE TITLE
Uncaught TypeError: funcs.reverse is not a function

### ISSUE THREAD

**Issue by Pansul** [ericgio/react-bootstrap-typeahead#323]
### Steps to reproduce:
After installing the package, I am calling this import {Typeahead} from 'react-bootstrap-typeahead';

### Actual Behavior
The error below is triggered:

_createFlow.js:31 Uncaught TypeError: funcs.reverse is not a function
    at _createFlow.js:31
    at typeaheadContainer (typeaheadContainer.js:97)
    at Object.<anonymous> (Typeahead.react.js:152)
    at __webpack_require__ (bootstrap 6bba0264a68652353575:71)
    at Object.<anonymous> (AsyncTypeahead.react.js:11)
    at __webpack_require__ (bootstrap 6bba0264a68652353575:71)
    at Object.<anonymous> (index.js:8)
    at __webpack_require__ (bootstrap 6bba0264a68652353575:71)

**Comment by ericgio** [comment]
Can you please post your code that is calling Typeahead? `funcs.reverse` is being called in `_createFlow.js`, which is not part of the package.

**Comment by Pansul** [comment]
Hey, thanks for the quick reply.
`<Typeahead
              multiple={true}
              labelKey="name"
              options={options}
              selected={multiSelectLoc}
              emptyLabel={notFound}
              onChange={this.onMultiChange}/>`

This is how I am using the Typeahead. It seems to be working fine for version 2.0.0 but the latest release seems to be throwing the aforementioned bug. Any thoughts?

**Comment by ericgio** [comment]
It looks like the error is happening in one of the Lodash functions from the UMD bundle. However, I'm still unable to repro the error.

@Pansul: Can you please provide a working repro case? JSFiddle, CodePen, etc.

**Comment by ericgio** [comment]
Closing this out. Please feel free to re-open with more information.
