### ISSUE TITLE
AsyncTypeahead is trimming spaces and lowercasing user input

### ISSUE THREAD

**Issue by yefim** [ericgio/react-bootstrap-typeahead#326]
### Version

2.4.0

### Steps to reproduce

[Watch my video](https://streamable.com/7p6g8)

### Expected Behavior

Preserving user input and not trimming trailing spaces

### Actual Behavior

[Watch my video](https://streamable.com/7p6g8)

Please help if you can.

**Comment by ericgio** [comment]
Note that this is the expected behavior. I agree it's weird though, and will likely remove that code in the next major release.

**Comment by yefim** [comment]
I didn't know that was expected behavior 🤔 Could you please point me in the direction of removing it myself if you have the time?

**Comment by ericgio** [comment]
https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/containers/asyncContainer.js#L121-L124

**Comment by yefim** [comment]
Thanks for all the help! Closing this issue as you've addressed it in 3.0! 🙌
