### ISSUE TITLE
Restricting input to only letters. 

### ISSUE THREAD

**Issue by vhellem** [ericgio/react-bootstrap-typeahead#33]
Hi. 

Any idea on how i could restrict the input to this component to be only letters? So far i have tried connecting it to a redux-form-field that is hooked up to a reducer to remove all fields that are not letters. 

TypeAhead selected={reduxField.value? [{name: reduxField.value}]: []} onInputChange={value=> reduxField.onChange(value)} 

However, I am still able to write in digits in the textfield, although they will get deleted as soon as i type in a valid character it seems a bit odd to me. Any idea on how i could completely restrict the input to the textfield?

**Comment by ericgio** [comment]
Unfortunately there's no way to do this at the moment and it's not something I plan on supporting in the current API. My goal with v1.0 is to provide a much more flexible API that allows developers much more control over the individual pieces of the component, including this use case. I don't currently have a timeline for when I'll release that yet, however.

**Comment by vhellem** [comment]
I managed to workaround the issue by adding a function prop to the component that reduces the input change to only contain valid letters. Would be open to a PR on the new functionality?

**Comment by ericgio** [comment]
This feels like a pretty specific use-case to me, so I'd prefer not to support it in the current API and instead make the component more flexible as mentioned above. Thanks for raising the issue and offering to submit a PR, though.

**Comment by Jock924491** [comment]
There is on thing to consider though, is things like zip code search. We only want 5 numeric values. There good be a regex/function for input verification

**Comment by ericgio** [comment]
Ah crap, I think I found the problem. Not sure why the publish step didn't abort.

**Comment by ericgio** [comment]
Do you mind posting an example of how you'd do it with a raw text input?

**Comment by Jock924491** [comment]
For a react module, I'd create a inputValidation property & if present on text change verify that the input matched the validation (I'd use regex personally). There is also an argument for a masked input usage though as it's clearer for the user to see.

**Comment by ericgio** [comment]
Could you use `onInputChange` and validate inside that?

**Comment by ericgio** [comment]
Closing this out in favor of the broader #79, which should address this use-case. The addition of `inputProps` in v2.0.0-alpha.1 will hopefully solve this issue.
