### ISSUE TITLE
Required Validate on react-bootstrap-typeahead

### ISSUE THREAD

**Issue by darshanawollstra** [ericgio/react-bootstrap-typeahead#331]
I'm getting trouble with react-bootstrap-typeahead. If the  typehead property is not selected any selection, it works properly but once i select a  selection from the typehead and then clear the  selected value on the typehead, it doesn't trigger the required validation on the typehead. Any idea on this?

**Comment by ericgio** [comment]
Can you please post a code example (JSFiddle/Codpen, etc) with a more in-depth description of the behavior you're expecting? Note that the typeahead doesn't have any built-in validation, so I'm not sure what you're referring to.

**Comment by darshanawollstra** [comment]
![screenshot from 2018-04-09 09-19-12](https://user-images.githubusercontent.com/32511059/38478559-26568dda-3bd7-11e8-815a-511e4ab3a1a3.png)

Can you please look on to this?

**Comment by ericgio** [comment]
The validation state should have nothing to do with the typeahead itself; your question is in regards to React-Bootstrap, which is a different library. You need to pass the proper state to the `FormGroup`. See [this example](https://react-bootstrap.github.io/components/forms/#forms).

**Comment by darshanawollstra** [comment]
Got it. Thanks for your immediate response on this.

**Comment by santoshrode19** [comment]
this.typeahead.getInstance()._input.setAttribute("required","true");
The bootstrap validation trigger automatically.

**Comment by rubendinho** [comment]
Here is how accomplished this with a functional component: 
```
let typeahead = useRef()
useEffect(() => {
  typeahead.getInstance().getInput().setAttribute('required', 'true');
})

...

<Typeahead
  ...
  ref={ref => (typeahead = ref)}
</Typeahead>
```

**Comment by ericgio** [comment]
Here's a better way to set the `required` attribute:

```jsx
<Typeahead
  ...
  inputProps={{ required: true }}
</Typeahead>
```

**Comment by rubendinho** [comment]
Ahh - that's much better.  I missed this in the docs.  Thanks @ericgio!

**Comment by ywang04** [comment]
@ericgio I just clone this code sandbox([https://codesandbox.io/s/zen-shtern-w09tb?file=/src/index.js:547-557]) and found that add inputProps is working when clicking submit button for a form validation.
Do we support any customized validation instead of using chrome's default behavior? Thanks in advance.

**Comment by ericgio** [comment]
@ywang04: yes! [Here's an example](https://codesandbox.io/s/rbt-validation-feedback-example-4w01px4z6x) using Bootstrap validation states. It's up to you to add the type of validation you'd like.

**Comment by magdi14** [comment]
hello there,
i've tried all of these solutions and non of them is working, i'm using version 5.1.0, so am i doing anything wrong according to this version?

**Comment by ericgio** [comment]
@magdi14: The example above should work for v5.1.0. What issue are you seeing? A sandbox reproing the problem would be helpful, thanks.

**Comment by magdi14** [comment]
thank you for replying, Solved :white_check_mark:

**Comment by khushmohammad** [comment]
inputProps={{ required: multiSelections && multiSelections == "" ? true : false }}

**Comment by kevinlbatchelor** [comment]
It looks like validation doesn't work with the react-bootstrap support for native validation, the native controls that prevent an invalid form from being submitted are not added to the input. The invalid is also cleared out when a form is submitted. I'll try to mark up an example of the problem soon
