### ISSUE TITLE
"click to close" feature?

### ISSUE THREAD

**Issue by acroyear** [ericgio/react-bootstrap-typeahead#338]
A normal behavior for type-ahead items is that if you click the text field while the menu is showing (or just lick the down-arrow, if you've added one), then the menu closes up again without selecting anything, as if the user clicked outside of it anywhere else on the page.

Can you add that feature (even as optional) or give me some clues as to how to add it myself?

**Comment by ericgio** [comment]
It sounds like you want a combobox component with some kind of toggle control. That's a bit difficult to do with the current API, unfortunately. See also #325 for external control of menu visibility.

**Comment by acroyear** [comment]
we're able to give the down-caret look with just the icon feature already available to the bootstrap input field you're using (mind you, we're still on 1.2.0 or something and need to look to an upgrade in the next year).

**Comment by ericgio** [comment]
Here's [an example](https://jsfiddle.net/n5u2wwjg/151599/) of how to add a custom toggle button to the typeahead. It uses undocumented, private methods, so consider these fragile and subject to change at any time. Also note that the example requires v3.2.0 of the component.
