### ISSUE TITLE
is there any options to Disallow some special characters in input when type?

### ISSUE THREAD

**Issue by gopinath-sixt** [ericgio/react-bootstrap-typeahead#344]
### Version

^3.1.2

### Steps to reproduce
user typing the text|numeric|some special chararter in asynctypeahead input component and getting dropdown value perfectly. Validating the entered text|numeric|some special chararter through InputChange.

### Expected Behavior
Some options for special character shouldn't be allow to enter in input.

### Actual Behavior
There is no restriction.

**Comment by ericgio** [comment]
This seems like a duplicate of #230, but please reopen if you feel I'm misunderstanding something.

**Comment by ericgio** [comment]
You can modify the query when you get it from your `onSearch` method. Unfortunately, [you can't update the input text directly](https://github.com/ericgio/react-bootstrap-typeahead/issues/266).

**Comment by gopinath-sixt** [comment]
Hi @ericgio ,

onKeyDown=(e)=>{
        var a=e.key;
        if(SPECIAL_CHARACTERS_VALIDATOR.indexOf(a)>-1){
            e.preventDefault();          
        }
    }

and yes disallowing key typed... Cheers!!!

**Comment by ericgio** [comment]
@gopinath-sixt: Just so I understand, did the above code solve your problem, or is it just an example of what you're trying to achieve?

**Comment by gopinath-sixt** [comment]
@ericgio yeah working fine
