### ISSUE TITLE
Typeahed is not working after getting deployed on heroku but it is working good on local server ? 

### ISSUE THREAD

**Issue by ssaurabhsdm** [ericgio/react-bootstrap-typeahead#346]
### Expected Behavior: 
Typeahed should work as it is working on my local server but is not working after getting deployed to heroku.

### Actual Behavior

Currently typeahead filed is not getting filled  accoeding to the suggestions after getting deployed on heroku

**Comment by ericgio** [comment]
Sorry, but I'm unable to help you debug this issue. Given that the typeahead works fine locally, it seems that there is some problem with your deployment. Good luck.
