### ISSUE TITLE
Inconsistent `aria-owns="rbt-menu-` on snapshot testing

### ISSUE THREAD

**Issue by goldylucks** [ericgio/react-bootstrap-typeahead#347]
### Version
2.6.0

### Steps to reproduce
1. render  `react-bootstrap-typeahead` in a component
2. Add snapshot testing for the component
3. Run snapshot test more then once

### Expected Behavior
Snapshot should match, test should pass

### Actual Behavior
Snapshot fails due to this error:
```diff
<input
    aria-activedescendant=""
    aria-autocomplete="both"
    aria-expanded={false}
    aria-haspopup="listbox"
-   aria-owns="rbt-menu-gllpwa7abl4"
+   aria-owns="rbt-menu-j0akxdtzh5"

```

Consuming component uses typeahead like this:

```
        <Typeahead
          allowNew
          multiple
          newSelectionPrefix="Add hidden field:"
          onChange={this.updateHiddenFields}
          defaultSelected={this.state.hiddenFields}
          options={this.state.hiddenFields}
          placeholder="Add hidden field"
        />
```

Every time I rerun the snapshot test, this property changes

I've tried passing `menuId` as a prop to the typeahead component, same error appears.

**Comment by ericgio** [comment]
Hi, thanks for the report and the information. If you don't explicitly set `menuId`, it's actually expected that the value will change whenever you re-mount the component. If you pass the same id whenever you run the test, it should be consistent.

**Comment by goldylucks** [comment]
That's why I said:
> I've tried passing menuId as a prop to the typeahead component, same error appears.

Ideas?

The `menuId` doesn't appear in the snapshot.

**Comment by ericgio** [comment]
Without knowing more about your setup, I don't know why you'd be getting an error if you're setting the `menuId`.

> I've tried passing menuId as a prop to the typeahead component, same error appears.

By "same error" do you mean that you still see an id like `rbt-menu-xxxxxxx`? That suggests that whatever `menuId` you set is not being passed down correctly, which I can't reproduce. A couple other obvious questions:

- Are you sure you're setting `menuId` and not `menuid` or `menuID`?
- Are you sure the same `menuId` is being set both times the test runs?

**Comment by goldylucks** [comment]
Sorry, I had two instances of the component, didn't see the second one.
