### ISSUE TITLE
Typehead Clearing Issue

### ISSUE THREAD

**Issue by darshanawollstra** [ericgio/react-bootstrap-typeahead#348]
Type head's selected value is cleanable with its default clear button, when i'm in the parent component of the type-head, i'm not able to clear the type-head value by using a reference to the type-head.
this.typhead.getInstance().clear() method. However it says getInstance() is not a function. Would like to hear an answer.

**Comment by meaton-potatoes** [comment]
@darshanawollstra I'm having the same issue. I see you closed this issue, is that because you were able to resolve it on your own? How did you resolve it?

**Comment by darshanawollstra** [comment]
Hope you've created a separate component with typehead. I made a ref to the typehead named "typehead" and you have only call to {this.typehead.instanceRef.clear()} method. Apart from that you'll have to install 'react-onclickoutside' higher order component and then you need to use {this.Typehead = onClickOutside(Here you should pass your component name)} in the component constructor. You'll be able to solve the problem by following  the  steps.

**Comment by ericgio** [comment]
Can one of you please provide a basic repro case? I'm not seeing this issue in the examples.
