### ISSUE TITLE
Handle null value of labelKey

### ISSUE THREAD

**Issue by shubhamkes** [ericgio/react-bootstrap-typeahead#349]
My options array has an object where labelKey is null and is not handled. 

Code sample -

```
<Typeahead
       selected={value ? [value] : []}
       emptyLabel={searchLabel ? searchLabel : ''}
       labelKey={display_name}
       options={[{display_name: 'Test'}, {display_name: null}]}
/>
```

**Error -** browser.js:38 Uncaught Error: One or more options does not have a valid label string. Check the `labelKey` prop to ensure that it matches the correct option key and provides a string for filtering and display.

### Version 
 ^3.1.3"

### Steps to reproduce  
On clearing search field 

### Expected Behavior 

Should have open the list

### Actual Behavior

Throws error and screen goes blank

**Comment by ericgio** [comment]
This is expected. You need to pass clean data into the component.

**Comment by ericgio** [comment]
The component tries to warn you if there are issues but I don't think it's reasonable for it to anticipate and handle corrupted data. There are just too many ways that can fail. It's therefore the consumer's responsibility to prepare and pass in clean data.

**Comment by shubhamkes** [comment]
Oh ok... Thanks for reply :)
