### ISSUE TITLE
Controlled Typeahead Example

### ISSUE THREAD

**Issue by matgargano** [ericgio/react-bootstrap-typeahead#351]
Sorry if there's a better place to put this but I created an example that helped me out immensely -- it's a component that is controlled by using state and updating the state and component when a valid selection is made and setting it to blank when not... I didn't see any example quite like it in your demo, apologies if I missed something!

https://codesandbox.io/s/yw8587kzmv

**Comment by ericgio** [comment]
Hi and thanks for the example! Just so I understand, this is simply an example of a controlled typeahead, correct?

**Comment by ericgio** [comment]
Controlled vs. uncontrolled is covered [in the documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Usage.md#controlled-vs-uncontrolled), so I'm going to consider the issue closed.

**Comment by matgargano** [comment]
/shrug
i didn't see any example similar to what i was looking for, so i figured this could help someone  else.
