### ISSUE TITLE
How do I get the value of a search string

### ISSUE THREAD

**Issue by nat009** [ericgio/react-bootstrap-typeahead#354]
Is there a way to get the value of the search string passed?
for eg. for Typeahead box something like this

```jsx
<Typeahead
  labelKey='company'
  multiple
  clearButton
  filterBy={['Company', 'Company2', 'value']}
  options={[
    { id: 123, Company: 'Microsoft', Company2: 'test', value: '1000' },
    { id: 245, Company: 'Google', Company2: 'Alphabet', value: '2000000' },
    { id: 345, Company: 'Google', Company2: 'Microsoft', value: '400000000' }
  ]}
  selected={this.selected}
  onChange={this.handleSearchChange}
  placeholder='Search Deal'
/>

handleSearchChange = (selected) => {
    console.log(selected);
    this.setState({ selected });
  }
```
what I am trying to do here is search and pull out the results in a grid. So if i have selected Microsoft, i want to pass the string Microsoft and populate the results to a grid. Similarly i'd like to do the same for Alphabet. how do i know if i searched for Company = Microsoft or Company2=Alphabet

While the handleSearch helps with giving out the search results as a array { id: 123, Company: 'Microsoft', Company2: 'test', value: '1000' }...but it doesn't tell me if i searched for company or company2 or value

**Comment by ericgio** [comment]
From [the documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#oninputchangetext-string-event-event): 

> #### `onInputChange(text: String, event: Event)`
> Invoked when the input value changes. Receives the string value of the input (`text`), as well as the original event.
