### ISSUE TITLE
Allow for custom rending of the "customOption"

### ISSUE THREAD

**Issue by IAPark** [ericgio/react-bootstrap-typeahead#355]
Right now if there is not an exact match a virtual "customOption" is created to allow for that option to be added. This custom option can't be customized, however. Right now we're aiming to make it clear to users that they can add the option. The other option we're investigating is adding our own custom options that exactly match the search term since we can style these.

**Comment by ericgio** [comment]
Would a callback similar to `renderMenuItemChildren` allowing you to customize the contents of the menu item fit your case?

**Comment by IAPark** [comment]
Yes, that's pretty much exactly what I was thinking. Though I also remain unsure if a flag to always show it even if there is a match would also be needed.

**Comment by IAPark** [comment]
I'm going to give a quick shot at implementing this.

**Comment by ericgio** [comment]
Note that what you want is currently possible by rendering a custom menu via `renderMenu`. That gives you full freedom to render the custom option (and any other option) exactly how you want. Given that, I'm going to close out this issue.

**Comment by stcursi** [comment]
I think the problem is different. I can see that in renderMenuItemChildren in options there are also items with customOption present as key. That element are not rendered and I don't understand why. If I have an array of x elements I want to see every x element.

**Comment by ericgio** [comment]
@stcursi: If you feel you've discovered a bug or have a feature request, please open a new issue describing your use case in detail and providing code examples and/or a repro case. Thanks!
