### ISSUE TITLE
Clearbutton is missing when used inside InputGroup

### ISSUE THREAD

**Issue by easel** [ericgio/react-bootstrap-typeahead#356]
### Version
3.1.4

### Steps to reproduce
<InputGroup>
<TypeAhead clearButton=true>
</InputGroup>

### Expected Behavior
Clear button is visible

### Actual Behavior
Clear button is not visible. Z-index is too low

**Comment by ericgio** [comment]
Confirmed the behavior. Thanks for submitting a fix as well!
