### ISSUE TITLE
u.filter not a function error on production 3.1.5 , react 16.4.1

### ISSUE THREAD

**Issue by immunity20** [ericgio/react-bootstrap-typeahead#358]
3.1.5 version
I upgrade to 16.4.1 React and react-dom

While on developing mode typehead input field works corretly on build production if i type 3 letters and try to fetch it throw error

Version
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "react-bootstrap-typeahead@^3.1.5",
    "name": "react-bootstrap-typeahead",
    "escapedName": "react-bootstrap-typeahead",
    "rawSpec": "^3.1.5",
    "saveSpec": null,
    "fetchSpec": "^3.1.5"

Error:
react-dom.production.min.js:188 TypeError: u.filter is not a function
    at n.value (typeaheadContainer.js:448)
    at kn (react-dom.production.min.js:167)
    at On (react-dom.production.min.js:180)
    at Zn (react-dom.production.min.js:202)
    at qn (react-dom.production.min.js:203)
    at pr (react-dom.production.min.js:212)
    at cr (react-dom.production.min.js:211)
    at flushInteractiveUpdates (react-dom.production.min.js:227)
    at J (react-dom.production.min.js:44)
    at Ge (react-dom.production.min.js:89)
Sn @ react-dom.production.min.js:188
Qn.n.callback @ react-dom.production.min.js:195
tn @ react-dom.production.min.js:144
nn @ react-dom.production.min.js:145
dr @ react-dom.production.min.js:220
pr @ react-dom.production.min.js:212
cr @ react-dom.production.min.js:211
flushInteractiveUpdates @ react-dom.production.min.js:227
J @ react-dom.production.min.js:44
Ge @ react-dom.production.min.js:89
br @ react-dom.production.min.js:223
We @ react-dom.production.min.js:89
typeaheadContainer.js:448 Uncaught TypeError: u.filter is not a function
    at n.value (typeaheadContainer.js:448)
    at kn (react-dom.production.min.js:167)
    at On (react-dom.production.min.js:180)
    at Zn (react-dom.production.min.js:202)
    at qn (react-dom.production.min.js:203)
    at pr (react-dom.production.min.js:212)
    at cr (react-dom.production.min.js:211)
    at flushInteractiveUpdates (react-dom.production.min.js:227)
    at J (react-dom.production.min.js:44)
    at Ge (react-dom.production.min.js:89)

Behavior:
on developing mode it works ok
on production it throw error

package.json
  "private": true,
  "dependencies": {
    "auth0-js": "^9.5.1",
    "auth0-lock-passwordless": "^2.2.3",
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "cuid": "^2.0.2",
    "firebase": "^5.1.0",
    "history": "^4.7.2",
    "moment": "^2.20.1",
    "popper.js": "^1.12.9",
    "prop-types": "^15.6.2",
    "rc-slider": "^8.6.0",
    "rc-tooltip": "^3.7.0",
    "react": "^16.4.1",
    "react-addons-css-transition-group": "^15.6.2",
    "react-addons-transition-group": "^15.6.2",
    "react-async-script": "^0.9.1",
    "react-bootstrap-typeahead": "^3.1.5",
    "react-circular-progressbar": "^0.8.0",
    "react-datepicker": "^1.1.0",
    "react-dom": "^16.4.1",
    "react-google-recaptcha": "^0.12.0",
    "react-places-autocomplete": "^7.1.2",
    "react-redux": "^5.0.7",
    "react-redux-firebase": "^2.0.4",
    "react-router-dom": "^4.2.2",
    "react-scripts": "^1.1.4",
    "react-stripe-elements": "^2.0.0",
    "redux": "^4.0.0",
    "redux-thunk": "^2.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"

**Comment by ericgio** [comment]
Thanks for the report. Could you please provide a basic repro case (repo, sandbox, etc.)?

**Comment by ericgio** [comment]
No response after 1 week, closing. Happy to reopen if you can provide the requested info.

**Comment by sivatechversent** [comment]
am also facing the same issue

**Comment by sivatechversent** [comment]
<Typeahead
                        filterBy = {userOptions => (
                        userOptions["Name"].toLowerCase().indexOf(userQuery.toLowerCase()) != -1
                      )}
                      selected={[userQuery ? userQuery: ""]}
                      id = "lgLocation"
                      isLoading = {fetchData}
                      labelKey = "Name"
                      onSearch = {handleSearch} 
                      onInputChange = {handleUserChange}
                      onChange = {handleUserSelect}
                      options={options && options.length && options !==undefined && options !==null  ? options : []}
                      emptyLabel = "No matches found.!"
                      placeholder = "Search a Location..."
                      renderMenuItemChildren = {(option, props) => (
                        <div>
                          {option.Name}
                        </div>
                      )}
                      useCache = {false}
                    />

**Comment by ericgio** [comment]
@sivatechversent: Can you please provide a link to a sandbox with a minimal repro case? Thank you!

**Comment by sivatechversent** [comment]
@ericgio  I resolved this issue. `userQuery ` values came like undefined.

**Comment by sivatechversent** [comment]
Really Appreciated your quick response.
