### ISSUE TITLE
Cannot get ref of actual input field

### ISSUE THREAD

**Issue by swrobel** [ericgio/react-bootstrap-typeahead#359]
### Version

3.1.5

### Steps to reproduce

```jsx
<Typeahead
   inputRef={i => (this.input = i)}
/>
```

### Expected Behavior

`this.input` is the dom `<input>` element.

### Actual Behavior

`this.input` is `undefined`

**Comment by ericgio** [comment]
The behavior you're describing is expected, since `inputRef` is not part of the API. Is this a feature request?

**Comment by swrobel** [comment]
In that case, I guess it is.

**Comment by ericgio** [comment]
You can call `getInput` on the typeahead instance if you need the input node:

```jsx
// In `render`:
<Typeahead
  ...
  ref={typeahead => this.typeahead = typeahead}
/>

// In some handler:
this.typeahead.getInstance().getInput();
```

**Comment by kgonzale** [comment]
@ericgio  Sorry to bring this back up, I can create a new "issue" if need be. 
How can I accomplish this with react hooks?
