### ISSUE TITLE
Issue with Bootstrap 4 nav 'fade'

### ISSUE THREAD

**Issue by peterdutton** [ericgio/react-bootstrap-typeahead#360]
Hi,

I think I can see an issue with using react-bootstrap-typeahead in a nav when the 'fade' class is applied. Basically the width is being altered on one of the DIVs within the typeahead HTML, meaning that when a nav pane has been hidden and then re-shown, the placeholder text cannot be seen until the component is focused.

I have attempted to set up a basic codepen to illustrate, but I can't get the basic example working:

https://codepen.io/soulmedia/pen/pZjZQj?editors=1010

If you have a 'known good' codepen with react-bootstrap-typeahead and bootstrap 4 that I could use as a starting point that'd be really helpful.

Thanks

**Comment by ericgio** [comment]
Here you go: https://codepen.io/anon/pen/vaNzmM?editors=1010

**Comment by peterdutton** [comment]
Thanks for your help @ericgio 

I am unable to recreate the issue within the pen, however it looks like it might be missing some styles for the typeahead component? 
For example if I test selecting multiple options the selected results don't have the 'tag' look that they normally do. Do you know of a CDN from which I can pull in the styles?

Thanks

**Comment by ericgio** [comment]
Yes, please see the [README](https://github.com/ericgio/react-bootstrap-typeahead#css).

**Comment by ericgio** [comment]
No response, closing for now. If you can provide a repro case I'm happy to reopen and investigate.

**Comment by peterdutton** [comment]
Hi @ericgio - finally managed to get back to this one.
The issue only occurs when using `AsyncTypeahead` within a nav pane that is not active when first rendered. Here is a pen demonstrating the issue:
https://codepen.io/soulmedia/pen/eqYxBb

**Comment by ericgio** [comment]
Based on your sandbox, it looks like you're having an issue similar to #423. You're using jquery/bootstrap.js to control the tabs so React no longer re-renders the typeahead and the placeholder appears cut off. Unfortunately, there's nothing I can do about that. I'd recommend using a React-based Bootstrap framework like [react-bootstrap](https://react-bootstrap.github.io/) or [reactstrap](https://reactstrap.github.io/).

**Comment by peterdutton** [comment]
OK - if that is your approach then I can understand why it's not handled, although it isn't clear from the docs that the component depends on a react-based bootstrap framework to function properly (e.g. the [rendering](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md#rendering) page states that "react-bootstrap-typeahead is intended to work with standard Bootstrap components and styles"). I'd suggest updating the docs to make the dependency more clear.
