### ISSUE TITLE
Ref is undefined

### ISSUE THREAD

**Issue by PedramMarandi** [ericgio/react-bootstrap-typeahead#363]
Hello, 

It's been a while that I've worked with Typehead; It's Perfect and thanks y'all; but I've had a problem with ```refs```. 
I tried to name my ref and access by ```this.refs.something```, and also I tried to assign it to the object by calling a function in ref prop but none of them actually worked.

In all cases the reference is undefined and I don't have any clue how even I'm able to find the bug as everything appears to be fine.
It's a bit strange but even in the below example, I don't have anything logged. 

```javascript
<Typeahead
     ref={(ref) => console.log("ref", ref)}
     placeholder="Add media type"
     options={this.getTypeHeadValue()}
     labelKey="name"
     allowNew
/>
```

**Comment by ericgio** [comment]
I'm can't repro this issue using your example. Can you provide a sandbox with a basic repro case?

**Comment by PedramMarandi** [comment]
I've found my problem. So as I'm controlling my input visibility based on the state, I don't have it in the first place and even after re-rendering the ref does not exist for some reasons. Now I'm calling an if statement into my componentDidUpdate to see if this.input (my typehead ref), ```this.forceupdate()``` to have it assigned to my this.input var.

```javascript
     componentDidUpdate() {
        if ( !this.editorInput) this.forceUpdate();
     }
```
