### ISSUE TITLE
action fired when click select value from typeahead

### ISSUE THREAD

**Issue by kunvarsingh** [ericgio/react-bootstrap-typeahead#365]
action should be fired when select a element from typeahead.

**Comment by ericgio** [comment]
Are you looking for [`onChange`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#onchangeselected-arrayobjectstring)?

**Comment by kunvarsingh** [comment]
yes, i want the same function when value will be triggerred

**Comment by ericgio** [comment]
I'm sorry, I don't understand what you're asking.

**Comment by kunvarsingh** [comment]
<Typeahead options={this.state.values}></Typeahead>, so from where i can get the selected value.?

**Comment by ericgio** [comment]
[`onChange`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#onchangeselected-arrayobjectstring)

**Comment by ericgio** [comment]
I'm going to assume this solved your issue.
