### ISSUE TITLE
'Esc' no longer closes container

### ISSUE THREAD

**Issue by plemarquand** [ericgio/react-bootstrap-typeahead#37]
In versions > 0.6.0, Esc no longer closes the container. Tab used to as well, and I can understand why you would want to keep it open on tab (to select items), however Esc should still close the container.

The two lines responsible for closing the component were commented out in this commit:
https://github.com/ericgio/react-bootstrap-typeahead/commit/23260ca7be3304966a628a25d18bff6aa18628f1

See: https://github.com/ericgio/react-bootstrap-typeahead/blob/23260ca7be3304966a628a25d18bff6aa18628f1/src/Typeahead.react.js#L292

**Comment by ericgio** [comment]
Ah crap. Thanks for the report.

**Comment by ericgio** [comment]
Fixed in v0.6.2

**Comment by plemarquand** [comment]
Wow, thanks for the quick turnaround!
