### ISSUE TITLE
How can I override the text input element class or add an additional class?

### ISSUE THREAD

**Issue by mikedevita** [ericgio/react-bootstrap-typeahead#370]
Forgive me if this is in the docs but I couldn't find it... Is there a way to override the bootstrap classNames on the input element or a way to append to the `classname`? I am trying to add `input-lg` to the text box.

Doing something like below, doesn't render the input properly because it adds it to the container and not the TypeAhead input element directly.

```jsx
<AsyncTypeahead
  minLength={3}
  isLoading={isLoading}
  options={lookupOptions}
  onChange={this.handleSelected}
  onSearch={this.handleSearch}
  placeholder='Type an employees last name'
  className='input-lg form-control'
/>
```

**produces this:**
![image](https://user-images.githubusercontent.com/2991640/43915322-35f1749c-9bbf-11e8-9f5d-8ed47d35757b.png)

**This is what i'd expect it to look like:**
![image](https://user-images.githubusercontent.com/2991640/43915288-22ad12ec-9bbf-11e8-81ff-e08c39bed309.png)

**Comment by ericgio** [comment]
This is all in the [docs](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Props.md) and [examples](http://ericgio.github.io/react-bootstrap-typeahead/#input-size).

Use `bsSize` to change the size of the input. To set other input properties, use `inputProps`.

**Comment by mikedevita** [comment]
Bravo! Thank you, apparently I need to go back to school and learn how to read 😊.
