### ISSUE TITLE
Selected Text Not Appearing when Using Redux Form

### ISSUE THREAD

**Issue by blazestudios23** [ericgio/react-bootstrap-typeahead#371]
### Version
React: 16.4.1
react-bootstrap-typeahead: 3.2.1
reactstrap: 6.3.1
redux-form: 7.4.2
redux: 4.0.0

### Steps to reproduce

When the <TypeAhead /> compotent is nested in the <Field component form redux-form it causes an issue. The drop down list works perfectly, I select an item and the label doesn't appear in the input field. The data is set in the Redux state however, so that part is working. I can see it with the Redux DevTools.  

Below is the code that causes this issue: 

```jsx
<Field  name="jobSpec"
  component={this.renderTypeAheadField.bind(this)}
  placeholder="Please enter a collector name"
/>

renderTypeAheadField = ({ input, meta, ...rest }) => (
  <span>
    <Typeahead
      className={meta.touched && meta.error ? 'alert-danger' : ''}
      {...input}
      {...rest}
      labelKey="description"
      options={this.props.searchData}
      valueKey="id"
      clearButton
    />
    { meta.touched && meta.error && <FormFeedback tooltip >{meta.error}</FormFeedback>}
  </span>
);
```

### Expected Behavior

I would expect the input field to show the selected text as it does when not used with Redux-Form.

### Actual Behavior

When one  makes a selection the selected item does not appear in the input field. However the selected item can be seen in the state using Redux DevTools, so the selection is working, the input field is just not populating.

![image](https://user-images.githubusercontent.com/5480874/44230268-8c1d0300-a14f-11e8-9390-8935fa0075d3.png)

![image](https://user-images.githubusercontent.com/5480874/44230299-a35bf080-a14f-11e8-9e53-6580e671ba44.png)

**Comment by blazestudios23** [comment]
Update, if you click the same option twice in a row the value is set. But it clears as soon as another field is clicked on.

**Comment by ericgio** [comment]
I'm not familiar with Redux Form but it seems like it's not passing the expected value to the typeahead. What are the props being passed via `input` and `rest`? The component expects the selected values to be passed in via the `selected` prop, so if Redux Form is using something like `value` or `values` to set the selection(s), it won't work. Also note that `valueKey` isn't a valid prop.

**Comment by blazestudios23** [comment]
Hello Eric, 

Thank you for replying, and I really do like the TypeAhead. I'm surprised no one else has used it with Redux-Forms. 

I did get it to mostly work with the following code:


`  renderTypeAheadField = ({ input, meta, ...rest }) => (
    <span>
      <Typeahead
        className={meta.touched && meta.error ? 'alert-danger' : ''}
      {...input}
      {...rest}
      labelKey="description"
      options={this.props.searchData}
      clearButton
      selected={this.props.jobSpec ? this.props.jobSpec : [{ description: '' }]}
      minLength={2}
      />
      { meta.touched && meta.error && <FormFeedback tooltip >{meta.error}</FormFeedback>}
    </span>
  );

<Field  name="jobSpec"
                        component={this.renderTypeAheadField.bind(this)}
                         placeholder="Please enter a collection name"
                      />

function mapStateToProps(state) {
  return {
    searchData: state.searchData,
    jobSpec: selector(state, 'jobSpec'),
  };
}

const selector = formValueSelector('scheduleCollectionForm');

`

However there are still some desirable behaviors. 

1. The first time one types into the typeAhead field, focus is reset and one has to click on the typeAhead field and again, when does work the second time. 
2. If one deletes one character in the typeAhead, it is cleared and focus is reset. Then 1 above happens all over again.

**Comment by ericgio** [comment]
@blazestudios23: It sounds to me like Redux Form is updating state in a way that resets the component's selections. As mentioned above, I'm unfamiliar with how Redux Form works, so I can't provide much help here, only guess at the underlying issue. In any case, this doesn't seem like a bug in the typeahead though, so I would recommend [filing an issue with Redux Form](https://github.com/erikras/redux-form/issues) or [asking on StackOverflow](https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead,redux-form), where others might be able to help.

One last note: Not sure if this will make a difference, but if `this.props.jobSpec` doesn't exist, you should just return an empty array rather than an object with a blank description:

```
selected={this.props.jobSpec || []}
```

**Comment by blazestudios23** [comment]
@ericgio Change selected as you specified above handled the issue of having to click twice. 

The issue still persists when you delete a character, but I believe that is being caused by Redux emptying out the state. Which does make sense for Redux to do, however it's not desirable in this case.  

Best, 

Andrew

**Comment by ericgio** [comment]
Good to hear at least part of the issue was solved. Not sure what to suggest for the last bit, unfortunately. Maybe some intermediate state to handle whatever is being passed down from Redux Form? In any case, I'm going to consider this issue resolved since there doesn't seem to be an actionable item.
