### ISSUE TITLE
Add more selected items when pressed some key

### ISSUE THREAD

**Issue by savtym** [ericgio/react-bootstrap-typeahead#372]
Hi guys!
I need to select more items when I press some key, for example, `ctrl`
Can you create some functionality for this case?

**Comment by ericgio** [comment]
Hi, please be sure to read the guidelines for submitting a feature request. Once you've provided the necessary information, I'd be happy to consider your request:

> [P]rovide thoughtful commentary *and code samples* on what this feature means for your product. What will it allow you to do that you can't do today? How will it make current work-arounds straightforward? What potential bugs and edge cases does it help to avoid? etc.
