### ISSUE TITLE
Unable to pre-fill autocomplete field during form update

### ISSUE THREAD

**Issue by DieuMerciKIMPOLO** [ericgio/react-bootstrap-typeahead#373]
### Version
1.3.0

Hello, I'm using  AsyncTypeahead to manage the autocomplete of some fields of my form. But I can not pre-fill the AsyncTypeahead fields when updating the form.

The data in my options attribute  are objects.

Can someone help me in this way?

Thanks

**Comment by ericgio** [comment]
> I can not pre-fill the AsyncTypeahead fields when updating the form

Do you mean set the value of the input element? You can only do this during the initial mount, and only as of version 2.3.0. Please see issue #266 for more discussion.

**Comment by ericgio** [comment]
More than one week with no response from OP, closing.
