### ISSUE TITLE
Unable to show menu always

### ISSUE THREAD

**Issue by xyogol** [ericgio/react-bootstrap-typeahead#374]
Feature requests
=======================

Hello, maybe I am missing something in the docs, because I cannot make the Typeahead to be visible always without the input focus, I've tried adding showMenu={true} and isMenuShown={true} props on the Typeahead component, but menu is still not visible.

**Comment by ericgio** [comment]
That's correct, the public API does not currently expose a way to control menu visibility. I'm going to close this a a duplicate of #325. Can you please comment there with more info about your use case?
