### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by peteyycz** [ericgio/react-bootstrap-typeahead#383]
Feature request
=======================
Sort function option. I as a user of the library I would like to sort items. Specifically if `allowNew` option is set, the new value could be moved to the top.

**Comment by ericgio** [comment]
In most cases, this can be done by pre-sorting the options before passing them into the component. In your case, you can use the `renderMenu` prop to receive the results and render them however you want.

**Comment by peteyycz** [comment]
With `renderMenu` don't I have to manually create indexing and `onClick` handlers?

**Comment by ericgio** [comment]
No, in the simplest case, you could do the following:

```jsx
<Typeahead
  ...
  renderMenu={(results, menuProps) => {
    const sortedResults = // Sort the results however you want...

    return <TypeaheadMenu {...menuProps} options={sortedResults} />;
  }}
/>
```
