### ISSUE TITLE
Fuzzy Search

### ISSUE THREAD

**Issue by acostaf** [ericgio/react-bootstrap-typeahead#384]
Hi All

Can we have result filtered by many partial words from input ?

e.g. search for "ne" space "o"
should display **Ne**w Y**o**rk or **Ne**w Mexic**o**

**Comment by acostaf** [comment]
@ericgio 

FilterBy expect a a Boolean to be returned per item passed but fuzzysort, etc will give you an array back.

Is there any way that an event is raised with the criteria to sort and expect a filtered array back?

e.g. of fuzzysort
```
const mystuff = [{file:'Monitor.cpp'}, {file:'MeshRenderer.cpp'}]
const results = fuzzysort.go('mr', mystuff, {key:'file'})
// [{score:-18, obj:{file:'MeshRenderer.cpp'}}, {score:-6009, obj:{file:'Monitor.cpp'}}]
```

**Comment by ericgio** [comment]
You'd need to take the extra step of checking whether the array returned by fuzzysort contains the option passed by `filterBy` and return a boolean based on that.

**Comment by ericgio** [comment]
Closing, as I don't believe there's any action to take here. Fuzzy search is possible with the current API, it just needs to be implemented by the developer. Probably not something I'd want to include out of the box, as it would add weight to the component and each developer would have preferences as far as implementations.
