### ISSUE TITLE
Using backspace in IE11 to delete multi-select Tokens fire browser back action

### ISSUE THREAD

**Issue by NathanTrost** [ericgio/react-bootstrap-typeahead#389]
Steps to reproduce in IE11

1. Select multiple options
2. Use the backspace to remove those options

The browser will go to your previous url

**Comment by tmreay** [comment]
For what it's worth, I was able to fix this with the following override of `onKeyDown`
```javascript
class Selection extends Component {

  onKeyDown = (e) => {
    if (e.keyCode === BACKSPACE &&
        e.target.value === "") {
      // IE Compatibility, don't trigger a "back" in the browser on backspace
      e.returnValue = false;
      e.preventDefault();
    }
    if (this.props.hasOwnProperty("onKeyDown")) {
      this.props.onKeyDown(e);
    }
  }

  render() {
    return <Typeahead
      {...props}
      onKeyDown={this.onKeyDown}
    />;
  }
};
```

It looks like a permanent fix would involve calling `preventDefault()` in `TypeaheadInputMulti._handleKeyDown` ([link](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/TypeaheadInputMulti.react.js#L96))
If I have the right idea, I can open a PR.

**Comment by ericgio** [comment]
@tmreay: Thanks for the additional info. I think I understand what's going on now. Based on the original description of the issue, I think the `preventDefault` actually needs to go in the `Token` component, since that is the focused element when the "back" action is being triggered.

**Comment by ericgio** [comment]
I no longer repro this issue as of v3.3.3. Let me know if you're still seeing it.
