### ISSUE TITLE
Asynchronous Searching: [react-bootstrap-typeahead] Fields passed to `filterBy` should have string values.

### ISSUE THREAD

**Issue by msreddy09** [ericgio/react-bootstrap-typeahead#390]
### Version
"^3.2.4"

### Steps to reproduce
```jsx
<AsyncTypeahead
  {...this.state}
  labelKey="entity.firstNm"
  minLength={3}
  onSearch={this.handleSearch}
  placeholder="Search for a Github user..."
  renderMenuItemChildren={(option, props) => (
    <div>{option.entity.firstNm}</div>
  )}
/>
```

### Actual Behavior
in console.
warning.js:34 Warning: [react-bootstrap-typeahead] Fields passed to `filterBy` should have string values. Value will be converted to a string; results may be unexpected

Searched data is not populating.

**Comment by ericgio** [comment]
1 week with no response, closing.

**Comment by jhoanborges** [comment]
same
