### ISSUE TITLE
selectHintOnEnter does not work correctly with a compound string

### ISSUE THREAD

**Issue by labber** [ericgio/react-bootstrap-typeahead#392]
### Version

3.2.4

### Steps to reproduce

I copied the example you have [here](http://ericgio.github.io/react-bootstrap-typeahead/#labelkey) and added `selectHintOnEnter`

### Expected Behavior

I would expect the enter key to select the value if any part of the compound string matches.

### Actual Behavior

Hitting enter only works if something matches the first name, if it only matches the last name hitting enter does not work.

**Comment by ericgio** [comment]
That's the expected behavior for hinting in general. A hint is only shown if the input string matches the beginning of the first result. So typing in the last name won't show a hint, and `selectHintOnEnter` won't work in that case.
