### ISSUE TITLE
Component is not rendering correctly when used with 'input-group'

### ISSUE THREAD

**Issue by lourenci** [ericgio/react-bootstrap-typeahead#397]
The issue #74 is still present in new versions of the lib.

![image](https://user-images.githubusercontent.com/2339362/49218718-5e835f00-f3b8-11e8-9907-d1cc2839e1b2.png)

Here the codesandbox:
https://codesandbox.io/s/1z9vqzq08q

**Comment by ericgio** [comment]
You need to include the CSS from the package. Works fine once you do that.
```js
import 'react-bootstrap-typeahead/css/Typeahead.css';
```
