### ISSUE TITLE
Passing a long immutable array of objects as options crushes the component.

### ISSUE THREAD

**Issue by laviro** [ericgio/react-bootstrap-typeahead#398]
Hi, awesome work by the way !

While passing a long immutable array as options,
it seem that somewhere in the code a `push` method is invoked on the array,
causing this error: 
`The push method cannot be invoked on an Immutable data structure`
and crushing the component.

Not sure yet what's the reason for that, but it doesn't appear on small arrays.

**Comment by ericgio** [comment]
Hi, thanks for the report. Can you please provide a minimal repro case?

**Comment by ericgio** [comment]
The component conditionally adds a pagination item and/or custom items. The reason a longer array triggers the error is that it reaches the threshold for pagination and tries to add that item. I'm not super-familiar with Immutable, but can you just pass a mutable version of the array with `toJS` or `toArray`?

**Comment by Laviro** [comment]
Thanks, calling `asMutable()` on the Immutable object fixed the problem but we should fix it in this library.

Can you copy the array and than manipulate it however you want?

**Comment by ericgio** [comment]
Sure, if you want to submit a PR with a test case, I'd be happy to merge it.
