### ISSUE TITLE
Asynchronous Searching: Warning when filterBy has array values

### ISSUE THREAD

**Issue by ziaahmad** [ericgio/react-bootstrap-typeahead#399]
### Version
3.2.4

### Steps to reproduce
```js
<AsyncTypeahead
  {...this.state}
  filterBy={["id"]}
  minLength={3}
  onSearch={this.handleSearch}
  onChange={this.handleChange}
  placeholder="Search products..."
  defaultInputValue={this.props.value || ''}
/>
```
And searched data looks like
```js
[
  {id: 1, label: "T-shirt", value: "T-shirt"}
  {id: 2, label: "Glass", value: "Glass"}
  {id: 5682, label: "Hat", value: "Hat"}
  {id: 3869, label: "Umbrella", value: "Umbrella"}
]
```

### Actual Behavior
in console.
warning.js:34 Warning: [react-bootstrap-typeahead] Fields passed to filterBy should have string values. Value will be converted to a string; results may be unexpected

**Comment by ericgio** [comment]
This is the expected behavior. Your id values are numbers, which is why you're seeing the warning. The component should still work, it's just warning you that the value will be cast to a string and the conversion may not be what you expect.
