### ISSUE TITLE
Event prevent default not working for Android

### ISSUE THREAD

**Issue by vivekwolf123** [ericgio/react-bootstrap-typeahead#401]
I am using react-bootstrap-typehead version 3.2.1. I want to use the onKeyDown prop and do the event.preventDefault. This works for iOS and also for my PC running on Windows. However this event.preventDefault does nothing on Android.

This is my code
```js
onKeyDown={(e) => {
  if (this.state.id !== undefined) {
    e.preventDefault();
  }
}}
```

I basically want to prevent the user from entering more than 1 item in the type head. Multiple = {false} does not seem to work for me.

**Comment by ericgio** [comment]
Thanks for the report. I'm not familiar with the Android environment so I'm unable to help you. Assuming you're using React Native, I believe it should work consistently in both iOS and Android so if it doesn't, you might consider filing a bug there.

> Multiple = {false} does not seem to work for me

What do you mean when you say it "doesn't work"? If your ultimate goal is to have a single-select typeahead, then that should do it.

**Comment by ericgio** [comment]
Not much I can do here without more information, closing for now.
