### ISSUE TITLE
Add support for CSS Modules

### ISSUE THREAD

**Issue by rawroland** [ericgio/react-bootstrap-typeahead#409]
# Proposal 
I would like to propose support for [CSS modules](https://github.com/css-modules/css-modules) using the solution from [reactstrap](https://github.com/reactstrap/reactstrap).

# Meaning for Product
We are building a snippet, which can be integrated into any arbitrary website. This has often resulted in the css of the snippet overriding that of the enclosing site or vice versa. A solution for this would be support for [CSS modules](https://github.com/css-modules/css-modules). 

# Solution and code
This could be done by globally setting the CSS Modules as follows:
```javascript
let globalCssModule;

export function setGlobalCssModule(cssModule) {
  globalCssModule = cssModule;
}
```
We could optionally not set the CSS Module globally but rather make it an optional property in the components.

This `globalCSSModule` could then be used to update the *Component classNames* with the following function:
```javascript
export function mapToCssModules(className = '', cssModule = globalCssModule) {
  if (!cssModule) return className;
  return className
    .split(' ')
    .map(c => cssModule[c] || c)
    .join(' ');
}
```
All of these methods were lifted off the [reactstrap](https://github.com/reactstrap/reactstrap) library. Sources:
* [Methods](https://github.com/reactstrap/reactstrap/blob/71f9574a49805099b1acbba025c27061780ffe18/src/utils.js#L48)
* [Example application](https://github.com/reactstrap/reactstrap/blob/71f9574a49805099b1acbba025c27061780ffe18/src/DropdownMenu.js#L40)

# Implementation
I am ready to create a pull request with the proposed implementation.

**Comment by ericgio** [comment]
Hi @rawroland and thanks for the detailed proposal. I haven't used CSS modules extensively, so I'm not totally sure how they'd integrate with this project and what implications that would have more broadly for consumers of the library. For example, would things continue to work correctly for those using the UMD builds or not using modules in their own projects? I understand that style conflicts can be a problem, though I've tried to address that by scoping the styles to the component. Can you explain more about the specific issues you're running into?

**Comment by rawroland** [comment]
@ericgio Thank you for your patience with respect to this issue. I went ahead and created a Pull request #433, since I think it would be easier to discuss the issue through the pull request.

> For example, would things continue to work correctly for those using the UMD builds or not using modules in their own projects?
The change has no effect on those using UMD builds or not using modules, because the additional prop `cssModules` only has an effect if present and the `className` to be replaced is relevant. See [this test](https://github.com/ericgio/react-bootstrap-typeahead/pull/433/commits/fa090c153b23393714ec667f0e9690a816e79fc0#diff-a1884ea73832d6b9c5df0b22a2627c39) for clarification.

**Comment by rawroland** [comment]
Hello @ericgio. Would just like to check if you have gotten around to checking the pull request. Please let me know if I can assist in any way possible and thank you for your time.

**Comment by ericgio** [comment]
Hi @rawroland, thanks for your patience and for submitting the PR, which helped me better understand your request and the proposed implementation. I've been doing some work on the next major version (v4.0) and rethinking how rendering of underlying components is handled. My goal is to expose lower-level components for convenience and out-of-the-box functionality, while also providing a more flexible API to make it easier to use completely custom components. In that world, my sense is that any custom components could make use of css modules as needed, without having to expose the other parts of the component to the extra complexity. Do you have any thoughts on that?

4.0 branch: https://github.com/ericgio/react-bootstrap-typeahead/tree/4.0

**Comment by rawroland** [comment]
Hello @ericgio thank you for your response. Your ideas for version 4.0 align with what I have in mind and I would be happy to experiment with it, to check if it fits into our structure.

**Comment by ericgio** [comment]
Unless there's something I'm really missing here, it's pretty doubtful I'll add this feature. All the underlying components are now customizable, whether it's adding CSS classnames or providing your own markup. I believe that should provide the necessary flexibility and support for theming, but happy to look at improvements if there are cases where it's not working as expected.

**Comment by rawroland** [comment]
@ericgio Sorry for not responding for so long. It is ok to close the issue, since we found a workaround for our problem which really does not belong in the base package. Looking forward to using a new version of the package.
