### ISSUE TITLE
onChange is called on input change on Typeahead

### ISSUE THREAD

**Issue by sneu012** [ericgio/react-bootstrap-typeahead#410]
The [documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#onchangeselected-arrayobjectstring) states that ```onChange``` is invoked when the set of selections changes (ie: an item is added or removed). You have mentioned [in the issue below](https://github.com/ericgio/react-bootstrap-typeahead/issues/320#issuecomment-380176745) that ```onChange``` will be triggered when we hit backspace after making a selection, but don't we already have onInputChange to handle input changes. This only happens once and onChange will not be triggered on subsequent input changes.
This does not happen when multiple is true.

I have created a sandbox to replicate this. Please look into the console and see when onChange is triggered. Make a selection and just press space or any character. 
[![Edit p3z45m8rpq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2povmonk3p)

This would be more of an usability issue. If somebody selected an option and accidently added a space at the end, this would clear the entire input. I don't think that behaviour would be ideal. I wanted to see if you had any input on this. 

@bzashev: I'm not able to reproduce a double change event based on what you're describing.

> press backspace so the "selectHintOnEnter" option is triggered

Not sure exactly what you mean by this. If you've made a selection and hit backspace, then the selection will be cleared, triggering another change event. That's expected.

_Originally posted by @ericgio in https://github.com/ericgio/react-bootstrap-typeahead/issues/320#issuecomment-380176745_

**Comment by ericgio** [comment]
Hi @sneu012, thanks for opening this issue. I apologize, but I don't understand what you're describing or what I should be looking for in your example. As far as `onChange` vs. `onInputChange`, please note that the former is invoked when *selections* change, whereas the latter is invoked when the *input value* changes. Hopefully that clarifies things a bit.

**Comment by ericgio** [comment]
I see, thanks for the explanation. That happens because adding or removing part or all of the text implies a new query. Therefore, the selection is cleared and the new query begins. Hope that makes sense.

**Comment by sneu012** [comment]
Thank you!
The thing that caught me off guard, was the fact that ```onChange``` was called when the *input value* changed, in contrast to what was mentioned in the documentation.
I can see the reason behind doing that, but I am not sure if that is the best way to handle it.
Anyways, thank you for your response! 
I will close the issue.

**Comment by dsmithco** [comment]
Hello, This is an issue still as the behavior is not consistent after the initial selection is made on a single selector component. 
Reproduce like this...
1. Start typing (No onChange triggered...GOOD)
2. Select an option (onChange is triggered...GOOD)
3. Typing some more or delete a character (onChange is triggered...BAD)

1 and 3 here should be the same with NO onChange event. onChange should only trigger when a new selection is made.

**Comment by ericgio** [comment]
@dsmithco: That is the expected behavior. Once the user has made a selection, adding or removing characters clears the selection, thus triggering the change event.

**Comment by Jared-S-Horvitz** [comment]
Is there a way to stop this behavior? My situation has a default selection of a string, and if you change said string once then save, you end up saving an undefined option. changing twice allows for on input change to fire twice and corrects this issue. Basically I want onchange only on selections, and onInputChange only on typing.

**Comment by andywaltlova** [comment]
@Jared-S-Horvitz  Hi, I am not sure if this is your case - but it could be also useful to other people who will run into this issue. When I wanted to actually type custom selection, adding `allowNew={true}` to props was enough - I have defined only `onChange` in props and it works as expected, I can select option or add (type in) new option.

**Comment by normandanielmq** [comment]
Any update on this issue? onChange should not be triggered unless the user has chosen something from the list.

**Comment by bloodykheeng** [comment]
@ericgio How can we enforce  onChange to not be triggered unless the user has chosen something from the list.

**Comment by Sai-t3** [comment]
onchange function is working only for the options we have......how can i take value from the box as regular input box
