### ISSUE TITLE
3.3.0: Missing create-react-context dependency

### ISSUE THREAD

**Issue by himdel** [ericgio/react-bootstrap-typeahead#411]
### Version

3.3.0
No problems with 3.2.4.

### Steps to reproduce

1. depend on `react-bootstrap-typeahead`
2. run yarn
3. run webpack

### Expected Behavior

My build won't fail, same as with 3.2.4.

### Actual Behavior

Build fails:

```
ERROR in ./node_modules/react-bootstrap-typeahead/lib/TypeaheadContext.js
Module not found: Error: Can't resolve 'create-react-context' in '/home/himdel/manageiq-ui-classic/node_modules/react-bootstrap-typeahead/lib'
resolve 'create-react-context' in '/home/himdel/manageiq-ui-classic/node_modules/react-bootstrap-typeahead/lib'
  Parsed request is a module
  using description file: /home/himdel/manageiq-ui-classic/node_modules/react-bootstrap-typeahead/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
 @ ./node_modules/react-bootstrap-typeahead/lib/TypeaheadContext.js 12:49-80
 @ ./node_modules/react-bootstrap-typeahead/lib/containers/menuItemContainer.js
 @ ./node_modules/react-bootstrap-typeahead/lib/index.js
 @ ./node_modules/patternfly-react/dist/esm/components/TypeAheadSelect/TypeAheadSelect.js
 @ ./node_modules/patternfly-react/dist/esm/components/TypeAheadSelect/index.js
 @ ./node_modules/patternfly-react/dist/esm/index.js
 @ ./app/javascript/provider-dialogs/modal.js
 @ ./app/javascript/packs/provider-dialogs-common.js
error Command failed with exit code 2.
```

The failing line in `lib/TypeaheadContext.js` is:

```
var _createReactContext = _interopRequireDefault(require("create-react-context"));
```
(introduced in https://github.com/ericgio/react-bootstrap-typeahead/commit/61591f2ac4b9970d9126b7dc3d84103dc4df2db0)

And that's not really surprising because there is no part of `package.json` that mentions `create-react-context`.

(This *may* only be happening with yarn, but yarn v2 explicitly won't allow you to `require` dependencies of other dependencies directly, without specifying *that* dependency, so, this is definitely a bug.)

**Comment by ericgio** [comment]
You're right, I don't know how I missed that. Thanks for the report and sorry for the hassle. I added the dependency in v3.3.1. Please let me know if you see any further issues.

**Comment by himdel** [comment]
No problem, thanks! :) 

Confirming 3.3.1 works without any workarounds :+1:
