### ISSUE TITLE
Several critical accessibility issues

### ISSUE THREAD

**Issue by senpost** [ericgio/react-bootstrap-typeahead#413]
### Version
v3.3.1
### Steps to reproduce

- Open Chrome
- Install AXE accessibility test extension to test Accessibility
- Navigate to http://ericgio.github.io/react-bootstrap-typeahead/#basic-example
- Open Developer Tools
- Go to AXE tab and click "Analyze"
- You will see bunch of issues listed, select the first issue and click "**Highlight**"
- You will see lot of critical accessibility issues. I will point out few,
- "ARIA roles used must conform to valid values" - For example type ahead includes aria-owns attribute with id that doesn't exist in DOM when the dropdown is closed.
= "autocomplete attribute must be used correctly" - autocomplete attribute is tell browser to show autocomplete text such as email/address. Currently this control displays "nope", it should be changed back to "off". See here https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

Please let me know if you need more info or if I can help somehow.

Thank you

**Comment by ericgio** [comment]
Thanks for the report, I'll take a look. See #350 for more on the `autoComplete` issue. tldr; it's a known issue, but could be considered a breaking change, so may not get fixed until the next major release.

> Please let me know if you need more info or if I can help somehow

Feel free to submit PRs for any of the other individual issues.

**Comment by ericgio** [comment]
These should be fixed, except for the autocomplete error, which I'm considering a breaking change and will go out in the next major release.

**Comment by ericgio** [comment]
Closing this issue in favor of #418
