### ISSUE TITLE
ref in inputProps breaks after updating to 3.3.2

### ISSUE THREAD

**Issue by lourenci** [ericgio/react-bootstrap-typeahead#416]
I need to get the ref of the typeahead's input. 

In 3.2.4 I used to get it with:
```
<AsyncTypeahead
  {...otherProps}
  inputProps={{ ref: this.inputRef }}
/>
```

After I've updated to 3.3.2, I'm getting this error: `Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.`.

What is the proper way to get the input ref?

Isn't this a break change to bump only the minor version?

Thanks for the library.

**Comment by ericgio** [comment]
Hi @lourenci, I'm sorry you ran into this issue; I didn't anticipate anyone would pass a `ref` into the `inputProps`. There's actually a public (but not well-documented) `getInput` method for accessing the input. You can access it as you would other [public methods](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md#public-methods):

```jsx
this.typeaheadRef.getInstance().getInput()
```

**Comment by ericgio** [comment]
v3.3.3 includes a change that again allows refs to be passed to `inputProps` in case others are doing the same thing. I would discourage this, however, and it will be explicitly disallowed in the future. For now, it should be not be considered part of the public API and as such may change unexpectedly.

**Comment by lourenci** [comment]
I tried to use the `this.typeaheadRef.getInstance().getInput()`, but I ran in some issue with `undefined` input.

**Comment by ericgio** [comment]
What issues? Can you provide your code or a basic repro case? What are you trying to do? Information is helpful :)

**Comment by k7paul** [comment]
Hi! I'm trying to upgrade to the latest `typeahead`. I understand that `getInstance()` got deprecated.

I am using `AsyncTypeahead`, and the methods `blur`/`clear`/`getInput` don't seem to be available (at least typescript tells me so) - what should I use to get to the input field?

**Comment by ericgio** [comment]
@k7paul: Please see [the docs](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md) for more on how to access public methods.

**Comment by k7paul** [comment]
@ericgio: Thanks for your reply - although I think this may have something to do with TypeScript?

I'm trying to use the ref (albeit without the hooks); the ref is typed as `AsyncTypeahead<Profile>`, where `Profile` is my own struct. None of the functions in the docs (`blur()`, `getInput()`, `clear()`) are available. And even if I follow click through the props (starting with  `AsyncTypeaheadProps`, then `TypeaheadProps` and so on) in the IDE, I can't find them anywhere. 

What am I doing wrong?

Using the latest versions of packages available:
`react-bootstrap-typeahead@4.2.3`
`@types/react-bootstrap-typeahead@3.4.6`

**Comment by ericgio** [comment]
@k7paul: It looks like the public methods aren't present in [the types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-bootstrap-typeahead/index.d.ts). You or someone else will need to submit a PR adding them.

**Comment by jy2wong** [comment]
@lourenci @k7paul this might be fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51176 ; if not you probably need to do the same thing for AsyncTypeahead as I did for Typeahead.
