### ISSUE TITLE
Disabling `autoComplete`

### ISSUE THREAD

**Issue by ericgio** [ericgio/react-bootstrap-typeahead#418]
This has come up a couple times, so I want to track as a separate issue with more context. Basically, disabling autocomplete works inconsistently in browsers, most notably in Chrome:

https://stackoverflow.com/questions/15738259/disabling-chrome-autofill
https://stackoverflow.com/questions/47775041/disable-autofill-in-chrome-63

https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164
https://bugs.chromium.org/p/chromium/issues/detail?id=587466

#350 attempted to disable autofill by implementing a workaround (using an invalid value), but this still didn't always work and also didn't conform to ARIA standards (#413).

v4.0.0 will default the value back to "off", which may cause browser autocomplete menus to show up again in some cases. It will be up to individual consumers of the library to implement the various known workarounds to disable the feature.

**Comment by thetif** [comment]
If you remove autoComplete all together, it seems to work in Chrome (72.0.3626.109) on Mac and IE11 on Windows 7.

**Comment by jamestewartjr** [comment]
@thetif how did you remove it?

**Comment by thetif** [comment]
@jamestewartjr It's been a while, but I looked back through my code. I've got autoComplete="off" on all of my form tags and then on some of the input tags I also have autoComplete="off". But I do think just removing the autoComplete tag entirely works if "off" doesn't. Hope that helps.

**Comment by jamestewartjr** [comment]
@thetif  Thanks! I removed the attribute completely.

**Comment by rsshilli** [comment]
This is super annoying.  Is there a workaround here? How would I modify the autoComplete flag?

**Comment by ericgio** [comment]
Resolved in v4.0.0
