### ISSUE TITLE
Allow setting the input type

### ISSUE THREAD

**Issue by lars-ewers** [ericgio/react-bootstrap-typeahead#421]
I was just trying to change the type of the underlying input to "email" or "tel". 
I need this to get the corresponding keyboard on iOS. 

I tried to use the inputProps prop, which is working for any prop but not "type". Using the following code, I still get an input type of text. 

`<AsyncTypeahead inputProps={{  type: "email" }} ... ></AsyncTypeahead >`

**Comment by ericgio** [comment]
The type will propagate down on the multi-select component, but you're right that for single-select the type is hard-coded as "text". I think it makes sense to update the single-select component to allow different types.

One thing to call out is that a couple of the component behaviors rely on the `selectionStart` property, [which doesn't work for certain input types like "number" and "email" on Chrome](https://stackoverflow.com/questions/21177489/selectionstart-selectionend-on-input-type-number-no-longer-allowed-in-chrome/24175357). In those cases, the behavior may be a little unexpected.

**Comment by ericgio** [comment]
Fixed in v3.3.5
