### ISSUE TITLE
AsyncTypeahead shows "Searching" even after setting isLoading to false

### ISSUE THREAD

**Issue by Alquemist** [ericgio/react-bootstrap-typeahead#422]
### Version

3.3.4 

### Steps to reproduce

Just using AsyncTypeahead shows searching even after setting isLoading to false in callback.
This is especially problematic with allowNew prop

### Expected Behavior

After callback finishes execution and in setState sets isLoading to false, "Searching" should not be displayed.

### Actual Behavior

Searching is displayed even if isLoading is false.
[TestButton.zip](https://github.com/ericgio/react-bootstrap-typeahead/files/2865864/TestButton.zip)
![asynctypeahead](https://user-images.githubusercontent.com/25740909/52800901-0e45a000-307d-11e9-9f13-5829b9c4c921.PNG)

**Comment by ericgio** [comment]
Thanks for the report. I think this is probably the same issue as #417, but I'll check.

**Comment by Alquemist** [comment]
If I set useCache to false then it works OK, which is also said in #417

**Comment by ericgio** [comment]
This should be fixed in v3.3.6
