### ISSUE TITLE
How to clear input text programmatically? 

### ISSUE THREAD

**Issue by Jekin19** [ericgio/react-bootstrap-typeahead#429]
Use case:
Type ahead search is triggered automatically if user selects some value on another field in the form.
1) We would like to clear the previous selected value, which we do using the selected prop via the parent.
2) We also want to clear the text, for which if we use the method clearValue(). However it calls onChange which triggers our data validation, which we don't want since this is system based auto change and not user change.

Giving us a way to clear only the text will help in this case.

**Comment by ericgio** [comment]
Using the [`clear` instance method](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md#public-methods) does not fire a change event and is the best way to clear the component. It resets both the selections and the input value.`

**Comment by ericgio** [comment]
I'm going to consider this issue closed, given that there's a documented way to achieve your goals. Let me know if I'm misunderstanding something, though.
