### ISSUE TITLE
`react-onclickoutside` generates console warnings

### ISSUE THREAD

**Issue by daschi** [ericgio/react-bootstrap-typeahead#43]
Hi and thanks for your help on the previous issue! 

I've updated to version `^0.7.1` and I'm seeing the following React error (using Rails 4, Webpack 1.13.0, React 15.1.0): 

`Warning: bind(): You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See Typeahead`

It might be related to this [issue](https://github.com/Pomax/react-onclickoutside/issues/89) with `react-onclickoutside` and the error seems to go away when I update the package to version `^5.3.2`.

**Comment by ericgio** [comment]
Yes, this coming from `react-onclickoutside` unfortunately. I'm using v5.3.2 so I don't think there's a fix yet. It looks like [there's a PR](https://github.com/Pomax/react-onclickoutside/pull/112) awaiting merge that might address the issue.

**Comment by ericgio** [comment]
This is fixed in `react-onclickoutside` v5.3.3
