### ISSUE TITLE
Expand the bsSize options to include xs or xsmall

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [ericgio/react-bootstrap-typeahead#430]
Our use case might be rare but we operate in finance where screen estate is vital and everything needs to be as small as possible.  So it would be great if you could expand bsSize to include xs / xsmall.
I appreciate that React Bootstrap FormControl (v.3) also only support small and large but it does have a Style property so we are able to use that in order to reduce the height.  Unfortunately you don't have a style property that we can use - either would be great as its a blocker now for us.

**Comment by ericgio** [comment]
It's doubtful the API will ever explicitly support an xs/xsmall size, given that Bootstrap itself does not include it (as you note). However, it should be pretty trivial to override the existing CSS class declaration and make the input whatever size you want. Would something like that not work for you?

**Comment by ericgio** [comment]
> Unfortunately you don't have a style property that we can use

You can pass styles to the input itself via `inputProps`:

```jsx
<Typeahead
  ...
  inputProps={{
    style : { ... }
  }}
/>
```

You're right that you cannot currently pass styles to the top-level element, however. Thanks for highlighting that!

**Comment by JonnyAdaptableTools** [comment]
Perfect thanks - really appreciate you taking the time and trouble to reply twice.  Very impressive and I think that solution works for us.  Thanks.



Jonathan Wolfson
Chief Technology Officer, Adaptable Tools
W:  www.adaptabletools.com<http://www.adaptabletools.com>
E:   jonny.wolfson@adaptabletools.com<mailto:jonny.wolfson@adaptabletools.com>
T:   020 7078 4141
M:  07961 740136
Follow us on: LinkedIn<https://www.linkedin.com/company/adaptable-tools>, Facebook<https://www.facebook.com/adaptabletools/> & Twitter<https://twitter.com/AdaptableTools>

[cid:EDF00D91-5974-47E4-85D4-839AF506A122@DLink]

On 14 Mar 2019, at 23:10, Eric Giovanola <notifications@github.com<mailto:notifications@github.com>> wrote:


Unfortunately you don't have a style property that we can use

You can pass styles to the input itself via inputProps:

<Typeahead
  ...
  inputProps={{
    style : { ... }
  }}
/>

You're right that you cannot currently pass styles to the top-level element, however. Thanks for highlighting that!

**Comment by ericgio** [comment]
No problem. I'll consider this issue closed, then.
