### ISSUE TITLE
Code editor like view

### ISSUE THREAD

**Issue by sinpank** [ericgio/react-bootstrap-typeahead#434]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**How is this solution useful to others?**
Does your feature address a common use case? Does it provide a more generalized way to solve the type of problem you're encountering?

**Describe alternatives you've considered**

**Additional context**
Add any other context, sample code, or screenshots about the feature request here.

**Comment by sinpank** [comment]
Is it possible to give code editor like view using typeahead js such as:
1. different color to text based tokens
2. for every word you type suggestion box open automatically

**Comment by ericgio** [comment]
Sorry, but I'm struggling to understand what you're asking for here. Are you asking for help implementing something or is this a feature request? Can you provide an example?

**Comment by ericgio** [comment]
No response, closing for now. Please provide more info if you'd like me to reopen this.
