### ISSUE TITLE
Tooltip feature and ID Html tag attribute for options

### ISSUE THREAD

**Issue by ArunRajiv** [ericgio/react-bootstrap-typeahead#435]
Feature requests
=======================
can some enhance this component to have Tooltip for the dropdown options and being selected options?  we have requirement to display tool tip on hover of the menu values. Thanks in advance

**Comment by ericgio** [comment]
You can use the [`renderMenu`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md#rendermenuresults-arrayobjectstring-menuprops-object) prop to render the menu and items however you want, including tooltips.
