### ISSUE TITLE
tree-view data rendering

### ISSUE THREAD

**Issue by baradhili** [ericgio/react-bootstrap-typeahead#436]
I've got an interesting problem. The data I'd like to use in the typeahead is actually a 4 level hierarchy (maybe able to compact to 3 level). I need only to be able to select leaf nodes, but the leafs can be at any level.
Is it possible to do this as an expansion of the category view? Alternatively is it possible to allow taking control of the rendering of the dropdown ?

I know this potentially makes a major change to the typeahead :)

**Comment by ericgio** [comment]
What you want should be possible; check out the [custom rendering examples](http://ericgio.github.io/react-bootstrap-typeahead/#rendering). The custom menu is basically a 2-level hierarchy. I don't see why that couldn't be expanded to 4 (or more) levels. Rendering/styling is up to you, just be sure to wrap the selectable nodes with the menu item container to maintain proper functionality.
