### ISSUE TITLE
When I press tab button while menu is open, the focus doesn't move to next input and I need it to move.

### ISSUE THREAD

**Issue by AkramBadah** [ericgio/react-bootstrap-typeahead#440]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**How is this solution useful to others?**
Does your feature address a common use case? Does it provide a more generalized way to solve the type of problem you're encountering?

**Describe alternatives you've considered**

**Additional context**
Add any other context, sample code, or screenshots about the feature request here.

**Comment by ericgio** [comment]
Please provide a thorough description of the issue and steps to reproduce.

**Comment by greyphilosophy** [comment]
When I open the page and start hitting tab repeatedly, it moves through all the elements until it hits the typeahead field. It does properly select the field, but it does not immediately let me move to the next element. Instead I have to press the arrow down key to select something from the list, and then hit enter. After that it will let me tab to other elements.

This is particularly an issue for people who use screen readers who depend upon using tab to navigate pages.

**Comment by ericgio** [comment]
@greyphilosophy: thanks for providing a better description for the problem. However, when using [the live examples](http://ericgio.github.io/react-bootstrap-typeahead/) I'm able to tab through all the fields just fine. Can you please provide more detailed steps to reproduce the issue, including browser, OS, etc? Thanks.

**Comment by greyphilosophy** [comment]
@ericgio Oh interesting. It works just fine for me on the live examples as well. So it must be a problem with my code. I've posted it below in case you're curious, although I don't expect you to debug it for me. It's in a row inside <div className="d-flex flex-row flex-wrap my-3 justify-content-start">, along with some buttons and other elements.

```            <div className="analytics-organizations">
              <Typeahead
                id="analytics-organizations"
                name="analytics-organizations"
                placeholder="Select or search for an organization"
                selected={[organization.name]}
                options={organizationOptions}
                onChange={([selected]) => this.postAnalytics(selected)}
                onInputChange={(string) => [organization.name]} />
            </div>
