### ISSUE TITLE
AsyncTypeahead onInputChange not being called properly

### ISSUE THREAD

**Issue by vadymrybak** [ericgio/react-bootstrap-typeahead#441]
Library Version
4.0.0-alpha.10

Hi guys,

Not sure if this is bug though, but consider this scenario.  Using AsyncTypeahead 

### Steps to reproduce
1. I type in few characters in the input field.
2. I get few suggestions from my server.
3. Then I start going through them using my keyboard up-down keys.'
4. I would expect onInputChange to get triggered since i need that changed value to update my state.

The reason I need this is because consider this:
1. My server has only two suggestions: Megadeath, and Metallica.
2. I start typing in 'Me'.
3. I get back both of them in a list.
4. I navigate to Metallica one with keyboard down key.
5. I hit enter. In my code I use  AsyncTypeahead onKeyDown callback to track if enter was pressed. 
6. After hitting Enter I'm making API call to server to retrieve all results with Metallica in it.
7. However, i can see that the value that was passed to the server was 'Me'.
8. So if I click Enter one more time - there will be second API call and that one will have full 'Metallica' word in it.
So I'm guessing onKeyDown happens first. Then onChange gets fired.

Do you guys have any suggestions on this one?

**Comment by ericgio** [comment]
Why not just make the API call using `onChange` instead of `onKeyDown`?

**Comment by vadymrybak** [comment]
> Why not just make the API call using `onChange` instead of `onKeyDown`?

I tried it but  I still wanna be able to do API call when suggestion is not found, kinda like a free style search, lets say I have Metallica in the list but  I search for 'Metallica live'

**Comment by ericgio** [comment]
Did you try using the `allowNew` option to allow custom selections?

**Comment by vadymrybak** [comment]
That actually works. Thanks!

The only small thing is I would need to press arrow down, then hit enter rather than just enter without arrow down key. 
But that's ok.

Thanks a lot!

**Comment by ericgio** [comment]
Cool, glad that worked for you.
