### ISSUE TITLE
Allow passing in of `data-*` attrs

### ISSUE THREAD

**Issue by forkerino** [ericgio/react-bootstrap-typeahead#444]
**Is your feature request related to a problem? Please describe.**
We want to run an end to end test using Cypress, where normally we hook onto the `data-cy` attribute of html elements to interact with them.

**Describe the solution you'd like**
Allow `data-*` attributes passed into the Typeahead component

**How is this solution useful to others?**
I guess it is quite common to make sure that typeahead works in (e2e) testing, adding `data-*` attributes would make that much easier.

**Describe alternatives you've considered**
Currently hooking into the placeholder, which is far from ideal.

**Comment by ericgio** [comment]
What elements are you trying to add this attribute to (input, menu, etc.)?

**Comment by forkerino** [comment]
ahhh, the `inputProps` works! Thanks, I'll close this request. I guess the docs could be a little bit clearer, by mentioning 'html attributes' rather than just 'props'.
