### ISSUE TITLE
Uncaught TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by marnenivishal** [ericgio/react-bootstrap-typeahead#445]
I'm trying to use react-bootstrap-typeahed for the 1st time in the application .

I have imported 

import React, { Fragment } from 'react';
import { Grid, Row, Col, Button, Form, FormGroup, FormControl, ControlLabel, Radio, InputGroup, HelpBlock } from 'react-bootstrap';

import { Typeahead, Control } from 'react-bootstrap-typeahead';

I have used the below block of code in my application 
` <Fragment>
                                        <Typeahead
                                            // bsSize={bsSize}
                                            labelKey="name"
                                            //options={options}
                                            placeholder="Choose a state..."
                                        />
                                        <FormGroup>
                                            {radios.map(({ label, value }) => (
                                                <Control
            
                                                    key={value || 'default'}
                                                    onChange={(e) => this.setState({ bsSize: value })}
                                                    type="radio"
                                                    value={value}>
                                                    {label}
                                                </Control>
                                            ))}
                                        </FormGroup>
                                    </Fragment>`
typeaheadContainer.js:493 Uncaught TypeError: Cannot read property 'filter' of undefined
    at WrappedTypeahead.render (typeaheadContainer.js:493)
    at finishClassComponent (react-dom.development.js:14534)
    at updateClassComponent (react-dom.development.js:14489)
    at beginWork (react-dom.development.js:15335)
    at performUnitOfWork (react-dom.development.js:18150)
    at workLoop (react-dom.development.js:18190)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at replayUnitOfWork (react-dom.development.js:17437)

**Comment by ericgio** [comment]
Hi @marnenivishal, usage questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Feel free to post a link to your SO question on this thread and I'd be happy to try and help.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead
