### ISSUE TITLE
TypeError after clicking anywhere on Firefox

### ISSUE THREAD

**Issue by Mcat12** [ericgio/react-bootstrap-typeahead#446]
### Version

react-bootstrap-typeahead: 3.4.3
Firefox: 66.0.5

### Steps to reproduce

- Open Firefox
- Go to http://ericgio.github.io/react-bootstrap-typeahead/
- Open browser dev tools
- Click anywhere on the page
- Look at the console

### Expected Behavior

No error is thrown

### Actual Behavior

```
TypeError: e.path is undefined
```
![image](https://user-images.githubusercontent.com/4417660/58362422-aa84fd00-7e4b-11e9-8c18-596204f80d44.png)

This also occurs in my project, but it is reproducible on the demo site. This error does not appear in Chrome.

**Comment by ericgio** [comment]
Thanks for the report @Mcat12, I can reproduce the issue. I didn't realize `event.path` was non-standard :|

**Comment by ericgio** [comment]
This issue should be fixed as of v3.4.4
