### ISSUE TITLE
Version 3.4.2 maxResults with pagination issue with typeahead component 

### ISSUE THREAD

**Issue by marnenivishal** [ericgio/react-bootstrap-typeahead#452]
Hi,

Currently, we are using react-bootstrap-typeahead version 3.4.2 for doing typeahead. I'm having an issue using maxResults with onPaginate & paginate .

I'm getting max results form the store and updating it for maxresults.

` <Typeahead
                                    options={delayTrainIdSuggestions}
                                    ref={(typeaheadTrainId) => this.typeaheadTrainId = typeaheadTrainId}
                                    onInputChange={this.handleDelayTrainIdChange}
                                    onChange={this.handleDelayTrainIdChange}
                   
                                    onPaginate={this.loadNextPageResultsForDelayTrainId}
                                    paginate={true}
                                    maxResults={trainIdMaxResults}
                                    id="delayTrainIdSuggestionsMenu"
                                    labelKey="delayTrainId"
                                    placeholder="Enter train ID"
                                    emptyLabel={emptyDelayTrainIdLabel}
                                    positionFixed={true}
                                    isLoading={true}
                                    spellCheck={false}
                                    highlightOnlyResult={true} />`

My requirement is like when the user selects the state i need to show the corresponding cities in another input box. 

When i debug it the max results count is updated but the form is not getting rendered. when i click some where it's getting renderd with the maxResults

**Comment by ericgio** [comment]
Hi @marnenivishal, I'm having trouble understanding your issue. Are you reporting a bug? If so, please describe the steps to reproduce in detail, including code (preferably a working sandbox reproducing the issue). If this is a usage question, please post to StackOverflow.

**Comment by ericgio** [comment]
No response from OP, closing.
