### ISSUE TITLE
clearButton onClick triggered when clicking anywhere in the input box

### ISSUE THREAD

**Issue by brian-kilpatrick** [ericgio/react-bootstrap-typeahead#454]
### Version

`3.4.5`

### Steps to reproduce

For the life of me, I can't reproduce in a sandbox, but basically:
```
<AsyncTypeahead
                    multiple={true}
                    placeholder={placeholder}
                    selected={selected}
                    onChange={this.onChange}
                    isLoading={this.state.isLoading}
                    onSearch={this.onSearch}
                    options={this.state.options}
                    name={field}
                    />
```

### Expected Behavior

Clicking in the input to do nothing

### Actual Behavior

After added a selection(s) with `multiple={true}` , clicking anywhere in the input box triggers the most recent selections' `CloseButton`. Having a feeling this may have something to do with how `RootCloseWrapper` is handling clicks in the area from what I can see...
![1](https://user-images.githubusercontent.com/13888239/59227190-b9391700-8ba2-11e9-8c4e-4a4360492eed.gif)

**Comment by ericgio** [comment]
Hi @brian-kilpatrick, thanks for reporting this issue. I apologize, but I'm unable to reproduce what you're describing. Please provide detailed steps to reproduce the issue and, ideally, a minimal repro case.

Based on the screenshot you provided, it looks like this might be a CSS issue. Some part of the token is block-level, which is pushing the cursor down a line. If the clear button is expanding to take up the width of the input, then clicking on the input could trigger a click on the clear button and cause the issue you're describing.

**Comment by brian-kilpatrick** [comment]
Finally figured out the issue was because the input was being wrapped in a `label` tag. Thanks!
