### ISSUE TITLE
Add links to community examples

### ISSUE THREAD

**Issue by Josephaberry54** [ericgio/react-bootstrap-typeahead#455]
I want to be able to trigger events on the async typeahead within my project to test to ensure it is interacting with other components correctly using. I am using react-testing-library and not enzyme

It would be useful to know which events will trigger the onSearch and onChange functions and where to target them, whether that be through passing test-ids in or through label or placeholders etc.

I've passed in a test-id to the inputProps and can insert a value to the input. This triggers the onSearch and I then pass the options back in to typeahead as the options prop. However I cannot get these options to render in the DOM or have a way of passing an id in to the options menu to await them appearing in the DOM.

A working example of this working would be useful if it is even possible

**Comment by ericgio** [comment]
Hi @Josephaberry54, thanks for raising this issue. I agree that such an example would be helpful, but I don't use either library so I can't really help. In general, I'd also say that integrations with other libraries are beyond the scope of this project.

I think the best solution here is to rely on the community to provide such examples. If you're able to get something working it would be great if you could [create a sandbox](https://codesandbox.io/) and submit a PR linking to it. What do you think?

**Comment by ericgio** [comment]
Added a list under "Examples" in the README where the community can add examples via pull request.

**Comment by edanzer** [comment]
@ericgio - would you still be interested in an example for setting up tests for this? I stumbled on this thread today while trying to figure it out myself. I could work up a very simple starting point. This would be for <Typeahead />, not async. If you think it would be helpful, I'll work up a sandbox and prep a pull request. I know you updated the react-bootstrap-typehead to use react-testing-library a while back.

**Comment by ericgio** [comment]
Hey @edanzer, I'd love that! I'm more familiar with RTL now, but still haven't really used Formik. An example showing how to use all three libraries together would be great. Thanks!
