### ISSUE TITLE
The `id` prop will be required in future versions to make the component accessible for users of assistive technologies such as screen readers.

### ISSUE THREAD

**Issue by Angelk90** [ericgio/react-bootstrap-typeahead#456]
### Version

`    "react-bootstrap-typeahead": "^3.4.5"`

### Steps to reproduce

```
users = [
{ 
"id": "5d08f94da9d6d25011d55e87",
"name": "Leo"
},
...
]

                  <Typeahead
                    labelKey="name"
                    options={users}
                    placeholder="Search user..."
                    onChange={this.handleChangeTy('userSelect')}
                  />
```

**Comment by ericgio** [comment]
You need to add an `id` to the component, not the options.

**Comment by Angelk90** [comment]
@ericgio , can I ask you more clarifications?  You can give me an example.

**Comment by ericgio** [comment]
Hi @Angelk90, sure:

```jsx
<Typeahead
  id="my-typeahead-id"
  labelKey="name"
  options={users}
  placeholder="Search user..."
  onChange={this.handleChangeTy('userSelect')}
/>
```

It works like the `id` on any normal element.

**Comment by cameron-martin** [comment]
The id prop doesn't actually get passed through to the input. It isn't in the list of props that are passed through:

https://github.com/ericgio/react-bootstrap-typeahead/blob/74fccbec27338a2c8046c1edd59792a59462217c/src/Typeahead.react.js#L29-L52

**Comment by ericgio** [comment]
> The id prop doesn't actually get passed through to the input

That's correct. The warning doesn't refer to the input's id; it refers to an id for the typeahead component that is ultimately applied to the menu and used for accessibility. If you need to pass an id to the input itself, you would do that via `inputProps`.

**Comment by cameron-martin** [comment]
Why do we need to pass this ID through? The only reason I can think of is for linking the input with the dropdown, but a class name is already automatically generated for this.

What am I missing?

**Comment by ericgio** [comment]
@cameron-martin: It's used for [accessibility](https://www.w3.org/TR/wai-aria/).

**Comment by cameron-martin** [comment]
I got that, but what're you meant to link to that ID externally (from outside the component)?

**Comment by ericgio** [comment]
@cameron-martin I'm sorry, but I don't understand your question.

**Comment by cameron-martin** [comment]
But a random id is generated automatically to use internally, so why do I need to provide one?

**Comment by ericgio** [comment]
The randomly generated id is going away in favor of an explicit, user-defined one. That change is based on what I've seen to be common practice in other libraries, with [react-bootstrap](https://react-bootstrap.netlify.com/components/dropdowns/#accessibility) being one particularly relevant case.

**Comment by cameron-martin** [comment]
Ah makes sense. There seems to be some interest in introducing a method for unique ID generation into React, particularly because the current methods do not work with both SSR & suspense. This would likely change the common practice to being generating these IDs internally. See the open [RFC](https://github.com/reactjs/rfcs/pull/32) and [PR](https://github.com/facebook/react/pull/17322).

**Comment by cameron-martin** [comment]
FYI, the above PR has now landed so should be available in the next version of React :)
