### ISSUE TITLE
With open=false, highlightOnlyResult, component errors on RETURN with only one result

### ISSUE THREAD

**Issue by michaelmwu** [ericgio/react-bootstrap-typeahead#459]
### Version

3.4.5

### Steps to reproduce

With `open=false,highlightOnlyResult`, when there is only one result and RETURN is pressed, the component errors out. Repro: Add `open=false` to the `highlights the only result` test case in TypeaheadSpec.js

### Expected Behavior

Not erroring. Better yet, it should add the invisible first result.

### Actual Behavior

Errors.

**Comment by ericgio** [comment]
Hi @michaelmwu, thanks for the bug report and repro steps, I'm able to confirm the error. Thanks also for submitting a fix! I'll take a closer look when I get a chance.

**Comment by ericgio** [comment]
Fixed in v3.4.6
