### ISSUE TITLE
In Typeahead how can we call submit when click on enter on textbox

### ISSUE THREAD

**Issue by arukumar** [ericgio/react-bootstrap-typeahead#46]
I am not able to hit enter key from textbox

 <Typeahead  labelKey="name" ref="typeahead"  onChange={(selected)=>this.handleChnage(selected)}  
                   onInputChange={(text)=>this.handleInputChange(text)}  placeholder="what are you shopping for today?" 
               options = {TestApp} maxHeight={200}	minLength={3} 
               renderMenuItemChildren ={(props, option, idx) => {          
                   return [
                     <div key="name">
                        <img  src={'/static/images/'+ option.imageUrl} width='5%' height='5%' style={style} />{option.name}
                      </div>    
               ];
               }}
                    />

please suggest, how to acheive this

**Comment by ericgio** [comment]
Hey there, I'm a little unclear on the behavior you're trying to achieve. Can you add a bit more context to your code (and maybe format it?). Based on what you've written, I'm going to take a guess that you're trying to submit a form when you make a selection, is that right?
