### ISSUE TITLE
Multiple typeahead vs display: flex

### ISSUE THREAD

**Issue by dahfazz** [ericgio/react-bootstrap-typeahead#462]
### Version
v3.2.1

### Steps to reproduce
Put a `multiple` typeahead inside a `display: flex` container, then type lot of text inside.

I do not have the bug when I remove `multiple` attribute.

### Expected Behavior
Input should have fixed width and text should progress in it like in native inputs.

### Actual Behavior
The input width extend as lon as I continue to type text.

**Comment by ericgio** [comment]
Hi @dahfazz, and thanks for reporting this issue. I don't consider this a bug. The multi-select component uses flexbox for positioning, so putting it inside a parent flex container can affect the child element styles. That's just kind of how CSS works, as far as I'm concerned. Adding `width: 100%` to the top-level typeahead container should make it behave the way you expect.
