### ISSUE TITLE
Page auto-scrolling to input

### ISSUE THREAD

**Issue by NoureldeanSaed** [ericgio/react-bootstrap-typeahead#463]
### Version
typeahead: ^3.4.3

### Steps to reproduce
1. Get any typeahead input to show its dropdown list
2. go to any selection in the dropdown using arrow keys
3. Try to scroll up or down in the page.

![ezgif-5-e9d090d80eee](https://user-images.githubusercontent.com/28482442/60951809-9ebd9f00-a302-11e9-99fd-8ca8e2def82d.gif)

### Expected Behavior
The page scrolls normally

### Actual Behavior
The page is forced to scroll to that input

**Comment by ericgio** [comment]
Hi @NoureldeanSaed and thanks for reporting this issue. Highlighted menu items use [`scrollIntoViewIfNeeded`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoViewIfNeeded) so if you scroll down the page while a result is highlighted, the page will scroll back up.

**Comment by NoureldeanSaed** [comment]
@ericgio And why would they use that?

**Comment by ericgio** [comment]
When a user keys through results in the menu, it will scroll the overflowing results in the menu so that the highlighted item is visible.

**Comment by NoureldeanSaed** [comment]
Well, yeah, but in that case, the user isn't pressing any keys, and that behavior shouldn't appear.

**Comment by ericgio** [comment]
But they did press a key to navigate to the item and the menu is open, so that's the active item on the page.
