### ISSUE TITLE
Input hint doesn't work in newer versions within an inputgroup

### ISSUE THREAD

**Issue by lourenci** [ericgio/react-bootstrap-typeahead#465]
Hi, thanks for the library.

After I've upgraded the lib from 3.2.4 to 3.4.5, the input hint doesn't work anymore inside a bootstrap 3.3's inputgroup. The input with the hint is there, but some css has broken it.

Codesandbox with the problem:

[![Edit react-bootstrap-typeadhead-issue](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/patient-tdd-9e4io?fontsize=14)

**Comment by ericgio** [comment]
Hi @lourenci and thanks for the report. It seems like the hint's z-index needs to be higher it's in an input group. I'll look into a fix.

**Comment by ericgio** [comment]
Should be fixed in v3.4.6
