### ISSUE TITLE
Show all result

### ISSUE THREAD

**Issue by anishigouri** [ericgio/react-bootstrap-typeahead#468]
I'm filtering the result in the backend, I wanted all the values that were in the result to be displayed, regardless of what I typed in the input. How do I do this?

**Comment by ericgio** [comment]
You can [pass a callback to the `filterBy`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#functionoption-objectstring-props-object) prop. For your case you probably just want a function that returns true.
