### ISSUE TITLE
rbt-input-hint-container class is added automatically when doing multi select option

### ISSUE THREAD

**Issue by marnenivishal** [ericgio/react-bootstrap-typeahead#469]
Team,

I have added typeahead filter with the multi-select option but Hintcontrainer is getting added automatically 

` <Typeahead
                                            clearButton
                                            labelKey="value"
                                            multiple
                                            renderMenu={this._renderMenu.bind(this)}
                                            renderToken={this._renderToken.bind(this)}
                                            options={this.getOptions(this.state.runTimeDetails)}
                                            placeholder="Filter by details"
                                            id="runTimeFilter"
                                            onChange={this.handleRunTimeFilter} />`

![image](https://user-images.githubusercontent.com/50721730/61664449-6621ac00-ac98-11e9-9a6f-36c6e7dc2961.png)

`<div class="rbt-input-hint-container" style="position: relative;"><div style="position: relative; z-index: 1; display: inline-block;"><input aria-activedescendant="" aria-autocomplete="list" aria-haspopup="listbox" aria-owns="runTimeFilter" autocomplete="nope" type="text" class="rbt-input-main" value="" style="background-color: transparent; border: 0px; box-shadow: none; cursor: inherit; outline: none; padding: 0px; box-sizing: content-box; width: 3px;"><div style="height: 0px; left: 0px; overflow: scroll; position: absolute; top: 0px; visibility: hidden; white-space: pre; font-size: 14px; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;"></div></div><div style="left: 0px; pointer-events: none; position: absolute; top: 0px; display: inline-block;"><input aria-hidden="true" readonly="" tabindex="-1" class="rbt-input-hint" value="" style="background-color: transparent; border-color: transparent; box-shadow: none; color: rgba(0, 0, 0, 0.35); box-sizing: content-box; width: 3px; border-style: none; border-width: 0px; font-size: 14px; line-height: 21px; margin: 1px 0px 4px; padding: 0px;"><div style="height: 0px; left: 0px; overflow: scroll; position: absolute; top: 0px; visibility: hidden; white-space: pre; font-size: 14px; font-family: Roboto, Helvetica, Arial, sans-serif; font-weight: 400; font-style: normal; letter-spacing: normal; text-transform: none;"></div></div></div>`

**Comment by ericgio** [comment]
@marnenivishal, that is the intended behavior.
