### ISSUE TITLE
Pagination label prop available

### ISSUE THREAD

**Issue by magmel48** [ericgio/react-bootstrap-typeahead#47]
Hello,

first of all, thank you for great library. Is it possible to add prop for existing Typeahead component like `emptyLabel`, but for pagination sentense `Display next {this.props.initialResultCount} results...`?

I use your library in my cyrillic-based language application and don't have opportunity to change that.

**Comment by ericgio** [comment]
Yep, I'll add that for v0.8, thanks for the suggestion.

**Comment by magmel48** [comment]
is it acceptable if I add that as PR to this library?

**Comment by ericgio** [comment]
I already added it :) Working on a couple other things before I cut a release.

**Comment by ericgio** [comment]
Added in v0.8.0
