### ISSUE TITLE
Property for token color?

### ISSUE THREAD

**Issue by keithrz** [ericgio/react-bootstrap-typeahead#470]
**Is your feature request related to a problem? Please describe.**
There is no good way to set the color for the selected options (aka tokens) in the Typeahead component.

**Describe the solution you'd like**
It would be nice to have a property that can be set to one of the bootstrap options for color scheme, e.g.
```
            <Typeahead
                id="my-typeahead"
                labelKey="name"
                multiple={true}
                options={props.options}
                placeholder="My Search"
                onChange={props.onChange}
                className="mt-5 mb-3"
                tokenColor="primary"
            />
```

Notice the new property 'tokenColor=primary'.  
Possible values include all Bootstrap color schemes that contain foreground & background components: primary, secondary, success, danger, warning, info, light, dark (everything except muted, apparently)

**How is this solution useful to others?**
This provides a way for the Typeahead component to have a similar look & feel to other Bootstrap controls within the same app.

**Describe alternatives you've considered**
I could use custom CSS for this, but that code will have to change whenever changes are made to Typeahead.

**Additional context**
My current version: 4.0.0-alpha.10

**Comment by ericgio** [comment]
Hi @keithrz, thanks for the detailed feature request.

> There is no good way to set the color for the selected options (aka tokens) in the Typeahead component.

Please note that there's a [`renderToken`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md#rendertokenoption-objectstring-props-object-index-number) prop that provides full flexibility for rendering the token. You can use the `Token` component included in the package or create your own, completely custom version.

> I could use custom CSS for this, but that code will have to change whenever changes are made to Typeahead.

The `Token` component has remained fairly consistent over the history of the package. Assuming you added your own classname to it (which you should be doing), you shouldn't have any problems using custom CSS.

One thing to note is that unlike some of the other components in the package, `Token` isn't based on a Bootstrap component and currently doesn't have any variants (primary, secondary, etc.) It might be worth looking at using something like the [badge](https://getbootstrap.com/docs/4.3/components/badge/) component as the basis for the token.

**Comment by keithrz** [comment]
Sure, I saw renderToken in the docs, and I also saw this note:

> Be careful when using renderToken, since you will need to handle things like disabling the tokens and removing them (via props.onRemove) yourself. It is highly recommended that you use the provided Token component.

I'm not sure how to handle either of those things, but I will try.  I'm also worried about the other  Bootstrap-related issues with this tool mentioned in #302, so I may just try another tool instead.

Thanks for the quick response!

**Comment by keithrz** [comment]
I ended up just adding a className like "my-token" to my TypeAhead component and applying some SASS rules like so:

```
.my-token .rbt-token {
  color: $white;
  background-color: $primary;
}
```
