### ISSUE TITLE
Update to React 16.9

### ISSUE THREAD

**Issue by roper79** [ericgio/react-bootstrap-typeahead#472]
### Version

3.4.6

### Steps to reproduce

Have React 16.9 installed

### Expected Behavior

No warnings on installation

### Actual Behavior

Runtime warning:
`react-dom.development.js:11498 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.`

**Comment by ericgio** [comment]
Duplicate of #415
