### ISSUE TITLE
Hint text does not align with input text when container has a fixed width

### ISSUE THREAD

**Issue by ProtectedVoid** [ericgio/react-bootstrap-typeahead#473]
### Version
3.4.6

### Steps to reproduce
https://codesandbox.io/s/react-bootstrap-typeahead-hint-failure-0775h
- Continue typing to force the input field to autoscroll the input text

### Expected Behavior
When using the Typeahead with long strings (when multiple=false), the hint text should always align with the input text, even when the typed text exceeds the defined width of the input field (which triggers the input field to begin scrolling the text left).

Hint text should also not overflow the input field

### Actual Behavior
Hint text does not align with typed text when the parent container has a set width, and the value of the input field exceeds the available space to display the text.

Hint text overflows the input field.

**Comment by ericgio** [comment]
Hi @ProtectedVoid, thanks for filing this issue. I was able to repro the issue using the sandbox you provided. The overflow issue seems like it can be solved relatively easily. The alignment problem is tougher since the text in the input is scrolling independently of the hint. I'm not sure if there's a way to have them sync up, I'll have to look into it.

**Comment by ProtectedVoid** [comment]
Hi @ericgio.  The overflow problem was indeed fairly easy to address.  I just used a css override to handle that.  That was no biggie (calculated width issue).  Scrolling the hint text, I agree, is a tougher cookie to crack, and I'll be honest, I'm not sure how _I'd_ approach that one either.

**Comment by ericgio** [comment]
The overflow bug is no longer an issue as of v4, as far as I can tell. I'm not sure of any good way to fix the hint scrolling issue. It seems like an edge case to me; worst comes to worst, the hint can be disabled if someone feels the experience is really bad.
