### ISSUE TITLE
Hints not showing if input string has space at beginning or end

### ISSUE THREAD

**Issue by atishjain29100** [ericgio/react-bootstrap-typeahead#477]
Let us take the first example of typeahead from your examples :

<img width="886" alt="Screen Shot 2019-08-29 at 1 31 32 AM" src="https://user-images.githubusercontent.com/35028035/63888546-cc6abe80-c9fc-11e9-95e8-aecb00a7d714.png">

It correctly shows the results on typing 'Al'. Let us suppose that the input string is 'Al ' (space at end of 'Al'), it shows no matches found. Ideally it should still display the same options as it should compare the labelKey after trimming it. Attaching the screenshot

<img width="883" alt="Screen Shot 2019-08-29 at 1 34 26 AM" src="https://user-images.githubusercontent.com/35028035/63888723-2e2b2880-c9fd-11e9-8bac-1c0f0ecbce80.png">

This is a concern because while searching, if a space is accidentally entered at the beginning or end of the word, it shows **no matches found** which should not be the ideal case. Could you please add a support of comparing the **trimmed** labelKey with the hints so that options are visible even if space is there at the beginning or end of input string

**Comment by ericgio** [comment]
Hi @atishjain29100! Thanks for filing this feature request and providing a detailed explanation of the issue. Please note that you can pass your own callback function to [`filterBy`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#filterby) to achieve the behavior you're looking for. For example:

```jsx
<Typeahead
  ...
  options={['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California']}
  filterBy={(option, props) => {
    const str = option.label.toLowerCase();
    const search = props.text.toLowerCase().trim();

    return str.indexOf(search) > -1;
  }}
/>
```

**Comment by atishjain29100** [comment]
Thank you @ericgio for the quick response !

**Comment by eugeneborodkin** [comment]
The above code by @ericgio doesn't work anymore. Error: 
_TypeError: Cannot read property 'toLowerCase' of undefined_
By the way, I also want to tell you that the [filter ](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#filterby)documentation is bad. It's just 1 line (lol):
"The filterBy prop can be used in one of two ways: to specify option properties that should be searched or to pass a custom callback."
There are no examples, no mention of `props` (the 2nd argument in your example), or anything of the sort.

**Comment by ericgio** [comment]
Hey @eugeneborodkin, thanks for the feedback. I maintain this library in my spare time and as a result, documentation and examples may sometimes be lacking in detail or become obsolete. Pull requests from the community with suggested improvements are always welcome.
