### ISSUE TITLE
How to set value to typeahead Dynamically in React

### ISSUE THREAD

**Issue by arukumar** [ericgio/react-bootstrap-typeahead#48]
Can any one help, how to set value dynamically  to Typeahead, as there is no any props to set the value as we done in text box.

**Comment by ericgio** [comment]
Use the `selected` prop to control the selected value(s) of the input.

**Comment by longsangstan** [comment]
Hi, how about values that are not in the data array?

**Comment by gkovats** [comment]
Chef's kiss. Thank you years later for your work.
