### ISSUE TITLE
Render tokens outside of the input wrapper

### ISSUE THREAD

**Issue by daschi** [ericgio/react-bootstrap-typeahead#480]
Hello and thank you for this package!! 

**Is your feature request related to a problem? Please describe.**
I need to adjust the design of the typeahead to display the tokens below the input, instead of inside the input wrapper. 

**Describe the solution you'd like**
I am wondering if there is currently a way to achieve this, and if not, if it would be considered as a new feature to allow users to render a tokens container that can be rendered as a child of either the input wrapper (current behavior) or the parent typeahead component (desired behavior).
 
**How is this solution useful to others?**
This would make the component's design more flexible and allow users to decide where the tokens are rendered.  

**Describe alternatives you've considered**
The alternatives I considered were to pass a null function to `renderToken` prop, and then separately render my own tokens outside of the input. This was problematic since it was no longer a part of the typeahead component and I would also need to manage the selected / deselected state of the input and its options. 

**edit** Another alternative I've tried (but not sure if it's the best approach) is to pass a function to `renderToken` that returns a [React Portals](https://reactjs.org/docs/portals.html) wrapped component that appends the tokens to the parent typeahead component. 

**Additional context**
Here is an example of the design I am going for: 
<img width="361" alt="Screenshot 2019-08-30 17 42 12" src="https://user-images.githubusercontent.com/5402804/64057075-8709d680-cb4d-11e9-834c-0ae014f2a199.png">

Thank you any help or suggestions you may have!

**Comment by ericgio** [comment]
Hi @daschi! Thank you for your detailed feature request. v4.0.0 (alpha) of the library adds a `renderInput` prop that allows you to customize the rendering of your input component, including rendering tokens outside of the input. You can see a working example here:

https://codesandbox.io/s/rbt-issue-480-5u9c4

**Comment by daschi** [comment]
Wow awesome! Thanks so much!

**Comment by daschi** [comment]
@ericgio Hello! Thank you for all your progress on this package! Sorry I have been a little out of the loop with the new updates on version 5, I was wondering whether the `onRemove` callback was intentionally removed from the props passed to `renderInput`? Would that just mean I would need to implement that myself by diffing the selections?

**Comment by daschi** [comment]
Nevermind, I see now that renderInput gets `(inputProps, props)` and that onRemove is available in the second argument! thanks 😄
