### ISSUE TITLE
propTypes not being removed in production bundle

### ISSUE THREAD

**Issue by tuananh** [ericgio/react-bootstrap-typeahead#482]
### Steps to reproduce

i use bundle analyzer and run `npm run build:dist`

### Expected Behavior

from babelrc

```
"env": {
    "production": {
      "plugins": [
        "transform-react-remove-prop-types",
      ],
    }
  },
```
i would expect to not see `prop-types` in dist package

### Actual Behavior

in bundle analyzer when i do `npm run build:dist`, i still see `prop-types` package

**Comment by ericgio** [comment]
Hi @tuananh, thanks for filing this issue. You're right: it looks like I'm setting the webpack mode to "production", but need to also set `NODE_ENV` for the babel plugin to work.

**Comment by ericgio** [comment]
Note that this won't remove the `prop-types` package itself, so you may still see that. It simply removes `propTypes = { ... }` type code from the library in the production bundle.

**Comment by tuananh** [comment]
> Note that this won't remove the `prop-types` package itself, so you may still see that. It simply removes `propTypes = { ... }` type code from the library in the production bundle.

Cheer. So this should still reduce the bundle size a little yeah?

**Comment by ericgio** [comment]
> So this should still reduce the bundle size a little yeah?

Yeah, there should be a small (~1%) reduction in bundle size.

**Comment by ericgio** [comment]
Fixed in v3.4.7 via https://github.com/ericgio/react-bootstrap-typeahead/commit/eceb02f1269c8bec90bcdf7938c690c304f587f3

**Comment by ericvergnaud** [comment]
Hi,
thanks for this great control.
Not sure I agree with this approach of removing propTypes in production.
If I import the package in my project, when I type ```<Typeahead ...```my IDE is no longer able to propose a list of properties.
Am I incorrect in thinking propTypes should be removed in the page build, but not the packages build?
Currently the only way I can access propTypes is by building this package locally, and using npm link...
What am I missing?

**Comment by ericgio** [comment]
@ericvergnaud: the library comes with both a development and production bundle. The development bundle retains proptypes and should be used while you're developing. The production bundle is minified and drops proptypes, since those aren't needed in production.

**Comment by ericvergnaud** [comment]
@ericgio thanks, but here is what I'm experiencing. 
Here is my code:
```
import { Typeahead } from "react-bootstrap-typeahead";
const stuff = <Typeahead/>;
```
Using WebStorm, I don't get any suggesting when typing at the end of "Typeahead".
If I build the package locally, not removing propTypes in the build, publish it via ```npm link```and use to via ```npm link react-bootstrap-typeahead```, then I get suggestions.
So looks like the development bundle is not being used (or found)...
Ant thoughts?

**Comment by ericgio** [comment]
This issue refers to stripping proptypes out of the production UMD bundle. If you're using CommonJS/ES modules, the proptypes should be there. I'm not sure why your Webstorm isn't autosuggesting props, but unfortunately that's beyond the scope of what I can help with. I'd recommend asking on StackOverflow or a similar forum where someone more familiar with that IDE can help.

**Comment by ericvergnaud** [comment]
agreed, it's not an issue specific to this package
