### ISSUE TITLE
Deleting words triggers back navigation in Firefox

### ISSUE THREAD

**Issue by webmaster128** [ericgio/react-bootstrap-typeahead#484]
### Version

3.4.6

### Steps to reproduce

1. Open Firefox
2. Visit http://ericgio.github.io/react-bootstrap-typeahead/#public-methods
3. In the right menu, click "Behaviors"
4. Scroll to the "Controlling Selections" section
5. Click into the pre-populated field
6. Press backspace on the keyboard

### Expected Behavior

The first backspace press selectes the last word; another press deletes it.

### Actual Behavior

The browser's history back action is triggered.

**Comment by ericgio** [comment]
Hi @webmaster128, thanks for filing this issue, I can reproduce.

**Comment by ericgio** [comment]
Should be fixed in v3.4.7 via https://github.com/ericgio/react-bootstrap-typeahead/commit/a7512941dc2f36a51160aede6257c2625bca4697

**Comment by webmaster128** [comment]
Works as expected, thanks for the quick fix!
