### ISSUE TITLE
Warning message - use of deprecated ComponentWillReceiveProps 

### ISSUE THREAD

**Issue by KeriganCZ** [ericgio/react-bootstrap-typeahead#488]
Hello, 

I am using react-bootstrap-typeahead version 3.4.7 with react v.16.10.1.
Component is great, but react displays warning in the console

![image](https://user-images.githubusercontent.com/52082883/65982973-cbee9900-e47c-11e9-8988-51a8319b2110.png)

Would it be possible to update component to solve this warning?

Thank you very much.
Best regards
Filip Širc

**Comment by ericgio** [comment]
Duplicate of #415
