### ISSUE TITLE
Display additional results... is not showing when it should when getting async results

### ISSUE THREAD

**Issue by michalzubkowicz** [ericgio/react-bootstrap-typeahead#493]
Steps to reproduce:
1) Start typing, resuts are displayed for first page
2) When you click on "display additional results" only one more result is shown (already downloaded), but not new ones. 
3) When you clean input and start again, everything is working properly. 

I've prepared sample repository:
https://github.com/michalzubkowicz/typeahead-issue

Just npm install && npm run start

**Comment by ericgio** [comment]
Hi @michalzubkowicz and thanks for filing this issue. It's not clear to me from your description and code that there's a bug in this library happening here; it's more likely an issue with your implementation. Please see the [async pagination example](http://ericgio.github.io/react-bootstrap-typeahead/#async-pagination), which may help you solve your problem. If you're stuck, a forum like [StackOverflow](https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead) is good for usage questions like this.

If after further investigation you still believe there is indeed a bug, a more precise description of the problem along with a *minimal* repro case would be helpful so I can investigate. Thank you!

**Comment by michalzubkowicz** [comment]
Hi @ericgio , I've changed implementation to exact as yours and it works, it's strange bacause it's slightly indentical, anyway, thanks.
