### ISSUE TITLE
Disable or remove "Remove Button" one or many selected Items in React Bootstrap Async Typeahead

### ISSUE THREAD

**Issue by linidu** [ericgio/react-bootstrap-typeahead#495]
HI @ericgio ,

I'm using react-bootstrap-typeahead for adding items in to a list. I want to disable remove button of the added items according to a condition.
Or else is there any way to remove that "remove button" of a selected item?

Please refer the attached screenshot. 

![screenshot-ericgio github io-2019 10 11-16_26_14](https://user-images.githubusercontent.com/6526794/66736105-f3cefb00-ee85-11e9-9071-9e13c7288736.png)

**Comment by ericgio** [comment]
Hi @linidu, thanks for your question. Yes, you can use the `renderToken` prop to customize the appearance of the tokens:
```jsx
<Typeahead
  ...
  multiple
  renderToken={(option, props, idx) => (
    <Token
      disabled={idx === 0}
      onRemove={idx === 1 ? undefined : props.onRemove}>
      {option.label}
    </Token>
  )}
/>
```

- [More in-depth answer](https://stackoverflow.com/a/58381563/882638)
- [Working sandbox](https://codesandbox.io/s/react-bootstrap-typeahead-token-customization-495-54gtg)

**Comment by linidu** [comment]
Hi @ericgio,
Thank you very much for the explanation and the example. It was a really helpful explanation. Big thank. (Y)

**Comment by maddieijams** [comment]
Hi @ericgio,
Is there a version of this answer that applies to AsyncTypeahead? I want to still display all results but disable certain rows from being able to be clicked at all. Is this possible?

**Comment by ericgio** [comment]
@maddieijams did you try the solution above? It should work the same for `AsyncTypeahead`.

**Comment by maddieijams** [comment]
@ericgio Would it just take the place of renderMenuItemChildren?

**Comment by ericgio** [comment]
@maddieijams: It sounds like you want to disable certain options in the menu. You do that either by adding a `disabled` property to the individual options you want to disable:

```jsx
<Typeahead
  ...
  options={[
    { id: 1, label: 'Option 1', disabled: true },
    { id: 2, label: 'Option 2', disabled: false },
    ...
  ]}
/>
```

Alternatively, you can use the `renderMenu` prop to manually disable the options you want:

```jsx
<Typeahead
  ...
  renderMenu={(results, menuProps) => {
    const items = results.map((option, position) => {
      const disabled = /* Condition to determine if the item is disabled. */;

      return (
        <MenuItem
          ...
          disabled={disabled}
          option={option}
          position={position}>
          {option.label}
        </MenuItem>
      );
    });

    return (
      <Menu {...menuProps}>{items}</Menu>
    );
  }}
/>
```

**Comment by maddieijams** [comment]
@ericgio Perfect. Thank you!

**Comment by EzequielBurg** [comment]
I have an similar issue. The Update of my CRUD has a lot of Typehead inputs, where I need to load the pre-selections items from the database. I'm using 'selected' prop, passing a data to pre-select ( [{}] ). I my case, I need to allow user to remove items pre-selecteds, or add more items (crUd), but the component not allow to remove the pre-selecteds items, and if I click on input, the dropdown show all the pre-selected items.
