### ISSUE TITLE
Change the order of the selected items using "drag and drop" in the react-bootstrap-typeahead

### ISSUE THREAD

**Issue by linidu** [ericgio/react-bootstrap-typeahead#496]
Hi @ericgio,

I'm developing a component, for that I want to reorder the selected items in the **typeahead**.
Is there any way to get this done in the "[https://github.com/ericgio/react-bootstrap-typeahead]".

**Note:**  we can reorder the added e-mail addresses in the list when we are sending emails using gmail. I want to implement the same functionality in my component and I'm using above example in my project

**Comment by ericgio** [comment]
Hi @linidu, thanks for your question. This functionality is not available out of the box and will not be added to the core library. However, v4.0.0 (currently in alpha) has a `renderInput` prop allowing you to completely customize the rendering and behavior of the input. You'd need to write your own input component that handles mutiple selections and drag-and-drop tokens.

**Comment by linidu** [comment]
Ok @ericgio,
Thank you very much.!
