### ISSUE TITLE
Feature request: support for large data sets

### ISSUE THREAD

**Issue by vincentsels** [ericgio/react-bootstrap-typeahead#5]
We're using the typeahead component for a list of ~2000 cached items. Clicking the control adds all these options to the DOM, which takes some time and resources. Showing a list of more than a couple of dozens of items seems rather pointless.

Do you consider these kinds of large sets of data a valid use case for your component?

As far as a solution concerns, an option might be to set an optional `maxResults` property or something. When set, this number of results is only ever shown at once in the dropdown list. Of course, there should be a way to inform the user that the list is not complete. Adding a dummy item to the top or the bottom of the list is probably easiest. Clicking this could select 'nothing'. Or instead, add a 'load all' option, which does load everything that meets the filter (or in case of no filter, all data). You'd need an additional property to be able to specify this message.

**Comment by ericgio** [comment]
I just ran across this issue yesterday, good timing :) I'll definitely look into a fix for this, hopefully this weekend.

**Comment by ericgio** [comment]
[Fixed Data Table](https://facebook.github.io/fixed-data-table/) solves this issue. I'll see if I can implement some version of what they're doing.

**Comment by ericgio** [comment]
I just added pagination in v0.3.0, let me know if you have thoughts on the interaction and whether it addresses your use case.

**Comment by vincentsels** [comment]
This is great, it more than fixes our problem, thanks a lot!
