### ISSUE TITLE
How to capture removed item in AsyncTypeahead when removing item from the list

### ISSUE THREAD

**Issue by linidu** [ericgio/react-bootstrap-typeahead#500]
@ericgio ,
I'm using react-bootstrap-typeahead for add multiple items to a list.

https://github.com/ericgio/react-bootstrap-typeahead

I need to pick the value, when I remove an item from the list. 
onChange event of the AsyncTypeahead handling the event when removing and adding items to the list.

When an item removed, selected data updating with the existing values in the list. 
Eg: I have 3 items in the list, I am removing an item, Then the selected list containing existing items. (2 items)

In my project I want to get that removed item, at the time of removing.

Is there any functionality for pick that removed value in "onChange" event.

**Comment by ericgio** [comment]
You could do it a couple ways. One is writing your own `onRemove` function and passing it to the `Token` component:

```jsx
<Typeahead
  ...
  renderToken={(option, props) => (
    <Token
      ...
      onRemove={() => {
        console.log(option); // Add your own code here
        props.onRemove();
      }}
    />
  )}
/>
```

Another way is to diff the selections in `onChange`:

```jsx
<Typeahead
  ...
  onChange={(selected) => {
    this.setState((state, props) => {
      // Diff the `selected` arrays to get the removed item.
      const removed = state.selected.filter(s => !selected.includes(s));
      return { selected };
    });
  }}
  selected={this.state.selected}
/>
```

**Comment by linidu** [comment]
@ericgio ,  Thank you very much for the example. It was really helpful. and worked fine with my scenario.
