### ISSUE TITLE
hide menu with display:none 

### ISSUE THREAD

**Issue by Chrisdo82** [ericgio/react-bootstrap-typeahead#502]
Hello,

**Is your feature request related to a problem? Please describe.**
I'm not sure that's already been asked. I added a DropUp that makes it possible to open the menu from outside with a mouse click. On this DropUp I also used the `aria-controls` attribute with the id from the menu. But since the menu is removed from the DOM every time, `aria-controls` doesn't work here. 

**Describe the solution you'd like**
In my opinion it would be better to hide the menu with `display: none` instead of not rendering it at all.

**How is this solution useful to others?**
a11y

Is there perhaps already a possibility to achieve this?

Many greetings
Christian

**Comment by ericgio** [comment]
Hi @Chrisdo82, thanks for the question. I understand the solution you're looking for, but I don't really understand the particular use case you're describing. As far as accessibility, the component should already be handling that correctly; if you believe there's a bug, could you please further describe the issue? Thanks.

**Comment by Chrisdo82** [comment]
Hi @ericgio,

maybe I'm using it wrong. 

The issue I have is that I have defined a DropUp with the attribute `aria-controls` which contains the ID of the menu. Since the menu is only rendered when it is actually opened, I get this warning "ARIA attributes must conform to valid values" because the referenced ID for `aria-controls` does not exist in the DOM and is therefor not valid.

see also https://dequeuniversity.com/rules/axe/3.3/aria-valid-attr-value

**Comment by ericgio** [comment]
> I have defined a DropUp with the attribute aria-controls which contains the ID of the menu

Can you provide a sandbox with your code to help me understand what you're doing? Note that the component has a `dropup` prop, so this isn't something you should need to implement yourself, unless there's something specific you're trying to accomplish.

**Comment by ericgio** [comment]
No response, closing for now. I'd be happy to re-open if you can provide more details. Thanks!

**Comment by LorenzHW** [comment]
In case someone stumbles across this: I have a use case where I integrate [kbar](https://github.com/timc1/kbar) with typeahead and I don't want to show the menu of typeahead cuz we use kbar's components to show results. It is a bit hacky but it works:

```
renderMenu={(results, menuProps) => {
  return (
    <Menu {...menuProps} style={{ height: '0px', width: '0px' }}>
      {results.map((result: Option, index) => (
        <MenuItem option={result} position={index} key={index}>
          {result}
        </MenuItem>
      ))}
    </Menu>
  );
}}
```
