### ISSUE TITLE
Provide functionality to add custom option at the top of list

### ISSUE THREAD

**Issue by atishjain29100** [ericgio/react-bootstrap-typeahead#503]
Hi,

I want to create a new option using allowNew and newSelectionPrefix. The new item get added at the bottom of my list on search. I want the new item to be added at the top of the list. Is there any way to do that ?

**Comment by ericgio** [comment]
Hi @atishjain29100, thanks for your question. You can use the [`renderMenu`](http://ericgio.github.io/react-bootstrap-typeahead/#rendering) prop to customize rendering of the menu, including ordering of menu items.
