### ISSUE TITLE
Async: Trigger Search and selection on render

### ISSUE THREAD

**Issue by WpSlt** [ericgio/react-bootstrap-typeahead#506]
With your grate AsyncTypeahead, I can't figure out how set selected triggering a search to take others infos about the same record.

I can search in database, using your AsyncTypeahead and show some usefull infos from selected record; When I submit the form, id is saved on db.
On render (or form didmount) How can I recall same usefull infos setting AsyncTypeahead field with saved ID like selected?

**Comment by ericgio** [comment]
Hi @WpSlt, thanks for the question. I'm not totally sure I understand what you're asking for; are you trying to pre-select an item when the component renders? If so, you can take a look at [the examples](http://ericgio.github.io/react-bootstrap-typeahead/#controlling-selections), which describe how to do that.

**Comment by WpSlt** [comment]
thank you for the quick reply.
in your example option are already defined in component, in my AsyncTypeahead options are taken from db with onSearch function.
So I think there may be a way to call onSearch function on component render and set the defined (saved on db) value as selected.
it's possible?

**Comment by ericgio** [comment]
If you want to render the typeahead with default selections you'll need to prefetch that data yourself. It probably doesn't make sense to fetch it through the typeahead, though.

**Comment by WpSlt** [comment]
Ok, thank you! I had considered this possibility, I'll follow this way.
