### ISSUE TITLE
Allow aria-label support for input

### ISSUE THREAD

**Issue by aroarian** [ericgio/react-bootstrap-typeahead#508]
I am hoping the Typeahead / AsyncTyphead can allow aria-label as a valid prop which will be added onto the input.

Currently there are no props listed that support this feature and when adding aria-label as a prop the component does not return the attribute to the input or exist in the dom.

ex.

<AsyncTypeahead
     aria-label='string';
/>

**Comment by ericgio** [comment]
Hi @aroarian, thanks for the question. You can use `inputProps` to add an `aria-label`:

```jsx
<AsyncTypeahead
  ...
  inputProps={{
    'aria-label': 'my-label',
  }}
/>
```
