### ISSUE TITLE
select next and previous item on the custom render menu

### ISSUE THREAD

**Issue by vergageorge** [ericgio/react-bootstrap-typeahead#513]
Hi, Thanks for this library it is written well. I'm using `react-bootstrap-typeahead@4.0.0-alpha.10` version.  What my problems are: 

- I want to render a list of items that have links and the user also selects the items with `up` / `down` keys.
- When that menu is opened and the user clicks on it it will redirect to that page instead of putting that item on the input element.
- It is necessary the menu will also not close when the user clicks on the item.

 My data is something like this.

```
[
  {
    title: "Item 1",
    path "http://localhost.com/item1"
  },

  {
    title: "Item 2",
    path: "http://localhost.com/item2"
  },

  {
    title: "Item 3",
    path: "http://localhost.com/item3"
  }
];
```

How I try to solve this problem. By default if we don't add `renderMenu` prop then markup will render like this:

```
<li
  aria-label="Item 1"
  aria-selected="false"
  id="admin-search-item-1"
  role="option"
  class=""
>
  <a class="dropdown-item" href="#">
    Item 1
  </a>
</li>
```

which is also working fine on the `keys` press. But My case is not something like this where my `anchor` has pseudo `href="#"`. My case is that I wanted to render `anchor` which has a link to another page. So what I did is created a custom `renderMenu` function.

```
const renderMenu = (results, menuProps) => {
  let index = 0;
  const items = results.map(item => {
    const itemJSX = (
      <li key={index}>
        <a href={item.path}>
          <span>{item.title}</span>
        </a>
      </li>
    );
    index += 1;
    return itemJSX;
  });

  return <Menu {...menuProps}>{items}</Menu>;
};
```

which generated a markup like this

```
<li>
  <a href="http://localhost.com/item1">
    <span>Item 1</span>
  </a>
</li>;

```

So all my requirements are passed instead of this one.

> The user also selects the items on the menu with `up` / `down` keys.

I think the problem is that the default `MenuItem` will add some extra `props` which help to select the next item or previous item.  I also try to wrap my `anchor` inside `MenuItem`  then `anchor` inside `anchor` will be rendered on the HTML markup. So what you suggest to me. How could I achieve this functionality?

**Comment by ericgio** [comment]
You can pass an `onClick` method to `MenuItem` and use that to open a new window with the URL:

```jsx
<Typeahead
  id="open-window"
  options={options}
  placeholder="Select an item..."
  renderMenu={(results, props) => (
    <Menu {...props}>
      {results.map((result, idx) => (
        <MenuItem
          key={idx}
          onClick={() => window.open(result.path)}
          option={result}
          position={idx}>
          <Highlighter search={props.text}>{result.label}</Highlighter>
        </MenuItem>
      ))}
    </Menu>
  )}
/>
```

Here's a [working example](https://codesandbox.io/s/rbt-open-link-ejnov). Note that for accessibility purposes, you should also add an `onKeyDown` handler with the same functionality. Unfortunately, `MenuItem` doesn't currently accept a custom `onKeyDown` method, so you'd need to write your own `MenuItem` component and wrap it with a `menuContainer` HOC.
