### ISSUE TITLE
Tabbing out of field leaves typed-in value displayed (but not selected)

### ISSUE THREAD

**Issue by jipis** [ericgio/react-bootstrap-typeahead#514]
### Version
3.4.7

### Steps to reproduce
Go to your examples page at https://ericgio.github.io/react-bootstrap-typeahead/.  Start typing gibberish into any of the boxes -- something that doesn't match any of the options in the drop-down. Tab out of the field. The gibberish remains in the field even though it isn't in the selected array.

I've seen some answers online for solving this, but they all require refs and stateful components. I'm building with only SFCs.

### Expected Behavior
In my case, I've got a multi-select with `allowNew`. If you type something and don't actually click the "add new" (or use the arrow keys and enter to choose it) from the drop down, clear out that extra text. The selected array should match (as it does today).

### Actual Behavior
The non-selection stays there, not in a token, just as plain text. It isn't in the selected array.

**Comment by jipis** [comment]
Well, I don't know if this works because it should work or because I'm hacking something at a level lower than I should be playing with...

But, if I set my onBlur
```
<Typeahead
  allowNew
  multiple
  onBlur={e => e.target.value = ''}
  .
  .
  .
/>
```
everything performs as I'd expect it to. Again, bug of a bug or feature? /shrug

**Comment by ericgio** [comment]
Hey @jipis, thanks for taking the time to file this issue. The behavior you describe is the intended behavior for the component, so I don't consider it a bug. However, I do understand why you might find it confusing from an end-user perspective. I think an approach like the one you took of clearing the input on blur is fine. Note that as written, your approach will work for the multi-select case, but for the single-select case, you'd want to check for selections first and only clear if there are none.
