### ISSUE TITLE
Placeholder text is slightly misaligned in Chrome

### ISSUE THREAD

**Issue by rsslldnphy** [ericgio/react-bootstrap-typeahead#515]
### Version

3.4.7

### Steps to reproduce

View basic example at http://ericgio.github.io/react-bootstrap-typeahead/ in Chrome at **150% zoom**. Type something that is an exact prefix match for one of the options, for example `Calif`.

Note that the placeholder text is slightly misaligned with the typed text as shown here:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/1231200/72608915-ad24ed00-391b-11ea-98aa-511fec89d6bc.png">

Changing the font size to 16px makes the misalignment visible at 100% zoom - other combinations of font size, font, and zoom, seem to have similar problems. Here's an example from my own project using 16px Work Sans at 100% zoom:

<img width="487" alt="image" src="https://user-images.githubusercontent.com/1231200/72609016-dcd3f500-391b-11ea-9501-395a5826afc5.png">

### Expected Behavior

The placeholder text and typed text should be exactly aligned.

### Actual Behavior

The placeholder text and typed text are very slightly misaligned at certain font sizes and zooms, giving the appearance of a drop-shadow.

**Comment by rsslldnphy** [comment]
I'm going to have a go and see if I can get to the bottom of what's causing this, but my CSS knowledge probably isn't quite sharp enough. So thought I'd create an issue in case you have any ideas where to look. Thanks!

**Comment by ericgio** [comment]
This seems to be related to the version of Bootstrap being used. v4.1.1 looks ok, but v4.4.1 is off.

**Comment by ericgio** [comment]
Fixed in v4.0.0-rc.1
