### ISSUE TITLE
paginationText not working

### ISSUE THREAD

**Issue by arukumar** [ericgio/react-bootstrap-typeahead#52]
Hi ericgio,
Still i am facing issue.
I have used paginationText="view All" in typeahead tag, but still it display "Display Additional Result".
can we implement click functionality after setting the text in painationText, so that i can navigate to other page?

**Comment by ericgio** [comment]
There was a bug where the prop wasn't being passed to the menu correctly. Fixed in v0.8.1. Thanks for the report!
