### ISSUE TITLE
AsyncTypeahead - useCache not working

### ISSUE THREAD

**Issue by jbialobr** [ericgio/react-bootstrap-typeahead#520]
### Version
3.4.5

### Steps to reproduce
```jsx
        <AsyncTypeahead
          isLoading={this.state.isLoading}
          options={this.state.options}
          minLength={3}
          useCache={true}
          onSearch={query =>
          {
            this.setState({ isLoading: true });
            this.props.service.searchContracts(query, 20).then(res =>
              this.setState({ isLoading: false, options: res?.map(o => o.number + this.contractInfo(o)) ?? [] }));
          }}
          placeholder="Wpisz fragment numeru umowy"
        />
```

Typing first 3 letters:
![image](https://user-images.githubusercontent.com/1003909/75155838-2aa8fd80-5711-11ea-9183-7ea607dd9efb.png)

Typing the 4th letter:
![image](https://user-images.githubusercontent.com/1003909/75155884-40b6be00-5711-11ea-9ecc-5762015f5d5e.png)

Typing more letters:
![image](https://user-images.githubusercontent.com/1003909/75156156-cc304f00-5711-11ea-8311-09b48222b0d2.png)

One more letter:
![image](https://user-images.githubusercontent.com/1003909/75156206-e4a06980-5711-11ea-985d-13782fd24d34.png)

### Expected Behavior

For all the above substrings it should find a match.

### Actual Behavior

It fails to find a match at random prefixes.
It works fine if useCache is disabled.

**Comment by ericgio** [comment]
Hi @jbialobr and thanks for the bug report. I'm unable to reproduce this issue using the [async example](http://ericgio.github.io/react-bootstrap-typeahead/#asynchronous-searching). If you're able to do so, can you please provide more information to help me understand how I can reproduce? Thank you!

**Comment by jbialobr** [comment]
I investigated it further and found that the query result is cached in componentDidMount - which occurs after the render. So it first renders when the `cachedQuery` is an empty array, then it updates the cache, but no more render is invoked, because props do not change anymore.

I put some `console.log` lines:
in `componentDidUpdate`
```js
          if (prevProps.isLoading && this.props.useCache) {
            console.log('prevProps: ' + JSON.stringify(prevProps));
            console.log('currProps: ' + JSON.stringify(this.props));
            this._cache[this._query] = this.props.options;
          }
```
and in `render`
```js
          var allowNew = typeof props.allowNew === 'function' ? props.allowNew : props.allowNew && !props.isLoading;
          console.log('cachedQuery: ' + JSON.stringify(cachedQuery));
          console.log('props: ' + JSON.stringify(this.props));
          console.log('options: ' + JSON.stringify(options));
```

and here is what I got after typing `ug0` (I stripped the localized texts to make it shorter):
```

cachedQuery: undefined
asyncContainer.js: 166 props: { "id": "1111", "isLoading": false, "allowNew": false, "multiple": false, "options": [], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 167 options: []
asyncContainer.js: 165 cachedQuery: undefined
asyncContainer.js: 166 props: { "id": "1111", "isLoading": true, "allowNew": false, "multiple": false, "options": [], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 167 options: []
asyncContainer.js: 165 cachedQuery: undefined
asyncContainer.js: 166 props: { "id": "1111", "isLoading": true, "allowNew": false, "multiple": false, "options": [], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 167 options: []
asyncContainer.js: 138 prevProps: { "id": "1111", "isLoading": true, "allowNew": false, "multiple": false, "options": [], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 139 currProps: { "id": "1111", "isLoading": true, "allowNew": false, "multiple": false, "options": [], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 165 cachedQuery: []
asyncContainer.js: 166 props: { "id": "1111", "isLoading": true, "allowNew": false, "multiple": false, "options": [], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 167 options: []
asyncContainer.js: 138 prevProps: { "id": "1111", "isLoading": true, "allowNew": false, "multiple": false, "options": [], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 139 currProps: { "id": "1111", "isLoading": true, "allowNew": false, "multiple": false, "options": [], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 165 cachedQuery: []
asyncContainer.js: 166 props: { "id": "1111", "isLoading": false, "allowNew": false, "multiple": false, "options": ["UG01/001/JAN"], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 167 options: ["UG01/001/JAN"]
asyncContainer.js: 138 prevProps: { "id": "1111", "isLoading": true, "allowNew": false, "multiple": false, "options": [], "minLength": 3, "useCache": true, "delay": 200 }
asyncContainer.js: 139 currProps: { "id": "1111", "isLoading": false, "allowNew": false, "multiple": false, "options": ["UG01/001/JAN"], "minLength": 3, "useCache": true, "delay": 200 }
```

**Comment by jbialobr** [comment]
After https://github.com/ericgio/react-bootstrap-typeahead/pull/521 the `cachedQuery` is undefined in render when a new search has completed, so it renders using the provided `options`.

**Comment by ericgio** [comment]
@jbialobr: Thanks for taking the time to provide additional information. It looks like the typeahead is being updated several times, which calls `componentDidUpdate` while the request is in progress and thus caches an empty response. I'm not sure why that's happening; it's possible the parent is updating itself or its children for some reason.

I'm still not able to actually reproduce the issue. Could you try editing this sandbox to produce a minimal test case? Thanks.

https://codesandbox.io/s/asynctypeahead-usecache-not-working-520-6okzt

**Comment by jbialobr** [comment]
@ericgio As you said, the parent component rendering while the request is in progress causes this issue. Here is a repro: https://codesandbox.io/s/asynctypeahead-usecache-not-working-520-2xrho?fontsize=14&hidenavigation=1&theme=dark

![image](https://user-images.githubusercontent.com/1003909/75381226-aef9ad00-58d8-11ea-9bac-211830195760.png)

**Comment by ericgio** [comment]
@jbialobr thanks for following up and for the updated example! I really appreciate your help. If you want to update your PR to reflect changes in master, I'd be happy to merge it. Otherwise I'll just go ahead and make the change, since it's pretty straightforward.
