### ISSUE TITLE
I want to hide mobile keyboard when input is completed.How should i do.As i am unable to fiind any workaround.

### ISSUE THREAD

**Issue by pankas** [ericgio/react-bootstrap-typeahead#524]

**Comment by ericgio** [comment]
Hi @pankas and thanks for your question. Unfortunately, it's hard for me to help without additional information. Please follow the issue template and include a thorough description of your problem. Code examples or sandboxes are extremely helpful as well. Additionally, unless this is a bug or feature request, please post your question on a forum like [StackOverflow](https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead). I'll reopen this issue once you've provided more info. Thanks!
