### ISSUE TITLE
need to prevent typeahead component from selecting first option on unmount

### ISSUE THREAD

**Issue by scottschafer** [ericgio/react-bootstrap-typeahead#527]
I'm finding that onChange seems to be called with the first option whenever the component is unmounted. This is not the behavior I want - how can I disable this (or detect it so I can ignore it)?

**Comment by ericgio** [comment]
Hi @scottschafer, thanks for reporting this issue. I'm not aware of this behavior; could you please provide a minimal repro case? Thanks!

**Comment by ericgio** [comment]
I created a sandbox here that mounts and unmounts the typeahead, but I'm not able to reproduce the behavior you describe: https://codesandbox.io/s/rbt-select-on-unmount-527-4fhjx

**Comment by scottschafer** [comment]
@ericgio , thank you for putting together the sandbox. It seems I misdiagnosed the issue. It's really hard for me to figure out the control flow by setting breakpoints and looking at the call stack.

The issue seems to be not with unmount, but with the tab key. We close and unmount our containing component when you tab out of it. But it seems like the "tab" key selects the first match. So open the typeahead in this sandbox, type "C" and press tab. It selects "California". How can I prevent this behavior?

**Comment by scottschafer** [comment]
To give a little more context: I want to be able to handle the user using the arrows or mouse to select an item. For this, I need to use "onChange". But if they type in just a part of the search result and type tab, I don't want "onChange" to be called with the first match. The requirement I have is to ignore the user input unless it unambiguously matches a search result.

**Comment by ericgio** [comment]
@scottschafer: Thanks for the clarification and additional context. You can render your own input component using the `renderInput` prop. I've update the sandbox link above so that it now renders a react-bootstrap `Form.Control` component instead of the built-in version with hinting.

**Comment by scottschafer** [comment]
thanks for the rapid and helpful response! stay well
