### ISSUE TITLE
Add Callback for allowNew to react on the data transformation

### ISSUE THREAD

**Issue by quorak** [ericgio/react-bootstrap-typeahead#529]
**Is your feature request related to a problem? Please describe.**
When using a controlled component with a data provider and want to enable the 'allowNew' functionality, there is no clear callback, to actually create the object wit additional information.

**Describe the solution you'd like**
It would be nice to a hava a `handleNew` callback which would allow me to create a new complex object  and then make it selected in the typeahaead

**Describe alternatives you've considered**
Right now I have to use the firstname as labelKey which would call the onChange handler, than I have to check of the new value is a incomplete object and trigger the object creation, readd it to the datastore and add the new value.

**Additional context**
I want to use it for contacts. so I have the Fields: firstname,lastname,email

thanks a lot. legit component

**Comment by vivibruce** [comment]
is handleNew callback feature implemented?
