### ISSUE TITLE
Bind onClick on paginationText

### ISSUE THREAD

**Issue by arukumar** [ericgio/react-bootstrap-typeahead#53]
Is it possible , that after declare paginationText="View All Result", can we bind onClick event when we click on "View All Result" ?

**Comment by ericgio** [comment]
That's not currently possible, no. Can you explain your use case?

**Comment by arukumar** [comment]
In Typeahead i only want to show 5 result and after click on Display additional results..., i need to redirect to other page

**Comment by ericgio** [comment]
This seems like a fairly narrow use case to me, but I'll keep it in mind for the future.

**Comment by ericgio** [comment]
This should be addressed by allowing custom rendering of the menu.

**Comment by ericgio** [comment]
Should be addressed by #102
