### ISSUE TITLE
Moving through options using arrow keys does not work in strict mode

### ISSUE THREAD

**Issue by evrimfeyyaz** [ericgio/react-bootstrap-typeahead#530]
### Version
5.0.0-alpha.1

### Steps to reproduce

Wrap the Typeahead component in `<React.StrictMode></React.StrictMode>`.

You can see it here: https://codesandbox.io/s/mystifying-sun-de84x

### Expected Behavior

Should allow moving through options using the arrow keys on keyboard.

### Actual Behavior

Does not move through options when using arrow keys.

**Comment by ericgio** [comment]
Hi @evrimfeyyaz, thanks for submitting this issue! I'm able to reproduce the issue you're describing. `StrictMode` [invokes several functions twice to detect side-effects](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects), and it seems like that may be what's happening here. I'll take a closer look.

**Comment by ericgio** [comment]
Also note that the behavior you describe will only happen in development mode.

**Comment by ericgio** [comment]
This was also happening in v4.x and should be fixed in v4.2.0. Coming soon to 5.x branch.
