### ISSUE TITLE
Custom loading Icon in dropdown

### ISSUE THREAD

**Issue by ggepenyan** [ericgio/react-bootstrap-typeahead#531]
**Is your feature request related to a problem? Please describe.**
When the `isLoading` prop is set to true it shows a 'loading' text. I think it would be nice to have an option to show a custom loading icon when `isLoading` is set to true.

**Describe the solution you'd like**
Just to add `loading` prop which could be a node.

**Additional context**
You can take a look at Antd library's dropdown loading. It appears like the empty state of the dropdown (items not found) but shows a spinner instead of text.

**Comment by ericgio** [comment]
Hi @ggepenyan, thanks for the feature request. `emptyLabel`  (and `searchText` in `asyncContainer`) already accepts a `node`, so you can set it to be whatever you want. Is there something else about your use case that I'm missing?

**Comment by ggepenyan** [comment]
Yeah, actually I'm not using asyncContainer and don't need to. I would like to show a custom spinner. But now it's showing a 'loading' text (without any background) when loading is set to true (so emptyLablel is not the one we need for that). And I'm not able to change that.

**Comment by ericgio** [comment]
`asyncContainer` and `AsyncTypeahead` are basically just doing the following:

```jsx
const { emptyLabel, isLoading, searchText } = this.props;

<Typeahead
  ...
  emptyLabel={isLoading ? searchText : emptyLabel}
/>
```
You can do the same thing and pass any node to `emptyLabel`.

**Comment by ggepenyan** [comment]
Does it mean it'll show that node given in emptyLabel while loading?

**Comment by ericgio** [comment]
Yes that's right. So actually you'd also need to pass an empty array to `options` as well so the empty state shows up:

```jsx
<Typeahead
  ...
  emptyLabel={isLoading ? <MyLoader /> : 'No results'}
  options={isLoading ? [] : options}
/>
```

Alternatively, you can use `renderMenu` to handle things however you want.

**Comment by ggepenyan** [comment]
Okay I got that, but I think it would be nice to update the docs, because I couldn't find any way to gain the result I wanted.

**Comment by ericgio** [comment]
Sorry you had trouble finding the information you were looking for. Unfortunately it's impractical to account for every use case in the docs, so I try to cover the more common or general cases there. This case might be a good candidate for the [example section](https://github.com/ericgio/react-bootstrap-typeahead#examples). If you'd like to create a sandbox and submit a PR adding it to the README, I'd be happy to merge it.
