### ISSUE TITLE
"multiple" missing from API docs?

### ISSUE THREAD

**Issue by SachaG** [ericgio/react-bootstrap-typeahead#532]
I didn't see `multiple` mentioned on https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md

Is this an oversight?

**Comment by SachaG** [comment]
Oh I see now that it's in the Props section. I feel that could be a little confusing since it's not clear to me what the difference is, but feel free to ignore this if you feel it's good as it is :)

**Comment by ericgio** [comment]
Hi @SachaG, thanks for raising this issue. There's also [a section dedicated to this topic](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Usage.md#single--multi-selection) under "Usage". If you'd like to submit a PR further clarifying things, though, I'd be happy to review and merge.
