### ISSUE TITLE
unable to populate options dynamically for searched query

### ISSUE THREAD

**Issue by tarunrohila** [ericgio/react-bootstrap-typeahead#533]
I am trying to implement a typeahead searchbox to search airport on the basis of its iata code.

I am not able to call custom method for search query and populate options from what custom method returns.

Eg: when i type BOM i want custom method should call rest api with input BOM and results to be stored in options. 

Thanks in advance. Please help

here is my code: 

```jsx
<Typeahead className="typeahead" id="fromAirport" name="fromAirport"
  onChange={(originAirport) => {
    this.setState({ originAirport });
  }}
  filterBy={['IATA', 'city', 'country']}
  labelKey={option => `${option.city}, ${option.country} (${option.IATA})`}
  options={airportList}
  placeholder="City, Country or Code"
  selected={this.state.originAirport}
  minLength={3}
/>
```

**Comment by ericgio** [comment]
Hi @tarunrohila, try using the `AsyncTypeahead` component included in the library. Please see the [async example](http://ericgio.github.io/react-bootstrap-typeahead/#asynchronous-searching) for details on usage.

**Comment by tarunrohila** [comment]
Many Thanks eric. I am able to fetch it dynamically using 

`<AsyncTypeahead className="typeahead" id="toAirport" name="toAirport"
                                          onSearch={this.handleSearchAirport}
                                          onChange={(destinationAirport) => {
                                            this.setState({
                                              destinationAirport
                                            });
                                          }}
                                          filterBy={['IATA', 'name', 'country']}
                                          labelKey={option => `${option.city}, ${option.country} (${option.IATA})`}
                                          placeholder="City, Country or Code"
                                          selected={
                                            this.state.destinationAirport
                                          }
                                          options={this.state.options}
                                          minLength={3}
                                          isLoading={this.state.isLoading}
                          />`
