### ISSUE TITLE
onChange is triggered when typing in AsyncTypeahead single input

### ISSUE THREAD

**Issue by SachaG** [ericgio/react-bootstrap-typeahead#534]
Hopefully this bug report makes sense! It might also just be me misunderstanding the API, but I managed to set up the multiple input version of the component just fine and so I'm not sure what's going wrong when I try to use the single input version…

### Version

5.0.0-alpha.1

### Steps to reproduce

Use an AsyncTypeahead single input component:

```jsx
<AsyncTypeahead
  multiple={false}
  onChange={selected => {
    console.log('// onChange')
  }}
  onInputChange={text => {
    console.log('// onInputChange')
  }}
  options={autocompleteOptions}
  onSearch={queryString => {
    console.log('// onSearch')
  }}
  selected={selectedItem}
/>
```

### Expected Behavior

When I type in the input, I would expect `onInputChange` and `onSearch` to trigger, but not `onChange` (which I would expect to only trigger once a selection is actually made).

### Actual Behavior

`onChange` is triggered immediately when typing, which updates `selectedItem` and prevents the controlled component from actually changing.

**Comment by ericgio** [comment]
Hi @SachaG, thanks for reporting this issue. I'm unable to reproduce the problem based on the code you've provided. Could you please create a sandbox with a minimal repro case to help me debug? Thanks!

**Comment by SachaG** [comment]
I can reproduce it if I set a value for `selected`: https://codesandbox.io/s/sleepy-austin-oemw2

**Comment by SachaG** [comment]
In the example above with `selected` being hardcoded I would expect that I wouldn't be able to actually change the value of the input, but shouldn't the rest still work? Am I missing something?

**Comment by ericgio** [comment]
You shouldn't be hard-coding `selected` (not sure why you'd want to do that). What's happening is that when text is entered with a selection that selection is cleared, which is why `onChange` is being fired. It should work fine if you set it up as a normal controlled component.

**Comment by SachaG** [comment]
Right, I was just hardcoding it as a quick example. But your reply helped me figure out the issue! In my actual code the flow looks like this:

1. the component receives `selected` from its parent
2. the user types in the component, which should trigger a query to the server
3. when the user picks an option, this then calls a function to update that original `selected` in the parent's state

Basically I was missing a step to update the parent component's state to clear the value. I've added this to the `onChange` and it seems to work:

```
        onChange={selected => {
          if (selected.length === 0) {
            clearValue();
          } else {
            updateValue(selected[0].value);
          }
        }}
```

Thanks for helping me work this out! Great component btw, I'm planning to include it as one of the default [Vulcan.js](http://vulcanjs.org/) components :)

**Comment by ericgio** [comment]
Awesome! Glad you were able to solve the issue :)
