### ISSUE TITLE
Clear button on single Selection

### ISSUE THREAD

**Issue by kocakbaris17** [ericgio/react-bootstrap-typeahead#535]
Hello,
Is there a way to activate clearbutton on single selection?

Because when multiple is false, clear button is showing under the input.

**Comment by ericgio** [comment]
Hi @kocakbaris17, have you included the CSS from the package?

**Comment by kocakbaris17** [comment]
Hi @ericgio thanks for the reply.
I dont think i did but i will try and get back to you.

**Comment by kocakbaris17** [comment]
OK that worked really fine :)
Sorry for bothering.
