### ISSUE TITLE
Allow HTML or react component in newSelectionPrefix

### ISSUE THREAD

**Issue by pszalko** [ericgio/react-bootstrap-typeahead#536]
I would like to customise the menu item with a new added option.
My use case is to use label instead of text string only.

For now I use `newSelectionPrefix` to change the selection prefix to: `<span class="label">..</span>`

I found out that `newSelectionPrefix`  doesn't accept HTML, but if you pass react component, it will render correctly but with a warning message:

```
Warning: Failed prop type: Invalid prop `newSelectionPrefix` of type `object` supplied to `TypeaheadMenu`, expected `string`.
    in TypeaheadMenu (created by InnerPopper)
    in InnerPopper (created by Context.Consumer)
    in Popper (created by Overlay)
    in Overlay (created by RootClose)
    in div (created by RootClose)
    in RootClose (created by TypeaheadManager)
    in TypeaheadManager (created by Typeahead)
    in Typeahead (created by TypeaheadComponent)
    in TypeaheadComponent (created by asyncContainer(TypeaheadComponent))
    in asyncContainer(TypeaheadComponent) (created by ClientNameInput)
    ...
```

Since the react component already works, I think maybe you should allow it as correct option value.

Alternatively maybe you could allow HTML to be rendered?

**Comment by ericgio** [comment]
Yeah, `newSelectionPrefix` and `paginationText` should probably accept nodes rather than strings.

**Comment by ericgio** [comment]
You can now pass a React node to the above as of v4.2.0

**Comment by pszalko** [comment]
That was fast! Thank you.
