### ISSUE TITLE
Allow to customise loader component

### ISSUE THREAD

**Issue by pszalko** [ericgio/react-bootstrap-typeahead#537]
**Is your feature request related to a problem? Please describe.**
I need to change loader icon displayed in the input when state is set to `isLoading`.

**Describe the solution you'd like**
I would like to pass an react component to typeahead to customise the loading state for the input.

**Comment by ericgio** [comment]
The typeahead accepts a child render function that allows you to customize things like the loading component or the close button:

```jsx
<Typeahead
  ...
  >
  {() => isLoading ?
    <div className="rbt-aux">
      <MyLoader />
    </div> :
    null
  )}
</Typeahead>
```

**Comment by pszalko** [comment]
Yes, that would work for me.
I tried to find it in docs, but couldn't. Is this feature documented anywhere?

**Comment by ericgio** [comment]
It's not well documented, you're right. I should probably add it. Going to close out this issue and open a new one for documentation.
