### ISSUE TITLE
New property: groupBy

### ISSUE THREAD

**Issue by Falci** [ericgio/react-bootstrap-typeahead#539]
```javascript
import options from "../example/src/data";

<Typeahead 
  labelKey="name"
  groupBy="region"
  options={options}
/>
```
![image](https://user-images.githubusercontent.com/1330573/79906475-21d65e80-8418-11ea-96c9-21094139a426.png)

**Is your feature request related to a problem? Please describe.**
The current api already supports grouping, but by overriding the default `renderMenu`; I believe this is a common case that could be supported out of the box.

**Describe the solution you'd like**
Add a new property `groupBy`. It should accept a string (`keyof Option`) or a function `(options:Option[]) => {[group:string]:Option[]}`

**How is this solution useful to others?**
I believe grouping is a common use case

**Describe alternatives you've considered**
The documentation already covers an alternative solution: override `renderMenu`.

**Additional context**
> Why I believe this is a common use case?

Because even the native `<select>` has a group option (`optgroup`).

> Why the API should include this property if there's already a way of doing it?

Because it would make the API simpler to use, specially if you are migrating from a native `select/optgroup`

I added this issue to validate that it could be a good feature. If so, I'd like to try to implement it.

**Comment by ericgio** [comment]
I'm pretty hesitant to merge this feature for a few reasons:
- As you noted in the original issue, there is already a way to group options in the current API (via `renderMenu`). I understand that this may be a bit more convenient for the basic use case, but I'm not sure how common that case is to begin with.
- It's pretty inflexible: if someone wants to group options but omit the headers, for example, they need to bail and use `renderMenu` anyway.
- It creates another codepath that I will need to maintain going forward, and also adds more weight to the package.

In general, I'm trying as much as possible to move away from top-level props with relatively specific purposes in favor of an API that provides more flexibility. I understand there is a certain trade-off in terms of ease-of-use for the simplest cases, but I think it's the right one to make.

Another way to approach this problem if you find yourself needing to reuse this functionality is to create your own typeahead component that uses `renderMenu` and exposes a `groupBy` prop to hide the complexity.
