### ISSUE TITLE
Always show newSelectionPrefix

### ISSUE THREAD

**Issue by fmapilis** [ericgio/react-bootstrap-typeahead#54]
Hey there,

I was wondering if it would be possible to have the "New Selection" always appear, or at least have a prop to toggle the behavior. At the moment, if the value in the Typeahead matches part of one of the options, the new selection bit is left off.

**Example:** The word "Carpet" is a possible choice for the Typeahead, but the user would like to enter the word "Car" as a new selection, but is unable to since "Carpet" is the only option.

**Comment by ericgio** [comment]
Thanks for the report/suggestion/request. I see what you're saying. Yeah, I think the current behavior is a borderline bug; it should probably display the new selection option if there's not an exact match, as you describe. I don't think the component should show the option if there is an exact match, though (thus allowing a duplicate entry). Let me know what you think.

**Comment by fmapilis** [comment]
That sounds fair - the new selection should only display if there isn't an exact match found to avoid duplicates.

Thanks for addressing this so quickly!

**Comment by ericgio** [comment]
Fixed in v0.8.4
