### ISSUE TITLE
escape-string-regexp dependency breaking IE11

### ISSUE THREAD

**Issue by mattfrey-gr** [ericgio/react-bootstrap-typeahead#540]
The version specified for the `escape-string-regexp` dependency contains an arrow function which is causing a syntax error in IE11 (https://github.com/sindresorhus/escape-string-regexp/issues/18)  `escape-string-regexp^1.0.5` didn't have this problem so if you're not using the functionality in the newer versions downgrading it would be nice.

**Comment by ericgio** [comment]
@mattfrey-gr: thanks for the report. As noted in the linked issue, shouldn't this be handled by whatever tools the developer is using to transpile their code for the web (eg: webpack/babel)?

**Comment by ericgio** [comment]
Related issue with examples of how to configure webpack/babel: https://github.com/babel/babel-loader/issues/171

**Comment by ericgio** [comment]
Small lib, so just including the function in this package for now :/ Fixed in v4.2.3

**Comment by mattfrey-gr** [comment]
Thank you @ericgio!!
