### ISSUE TITLE
uncertain focus in the menu using the up and down arrow keys 

### ISSUE THREAD

**Issue by Chrisdo82** [ericgio/react-bootstrap-typeahead#545]
### Version

v4.2.2

### Steps to reproduce

go to http://ericgio.github.io/react-bootstrap-typeahead/ and open any typeahead menu

### Expected Behavior

1. press the "down" arrow key until you reach the end of the list
2. press once again the down arrow key
3. the focus jumps back up in the list

### Actual Behavior

1. press the "down" arrow key until you reach the end of the list
2. Keep pressing the down arrow key
3.  the focus disappears from the list and at some point it jumps back up

**Comment by ericgio** [comment]
Whoa, yeah I can reproduce that. Thanks for bringing this to my attention!

**Comment by ericgio** [comment]
Fixed in v4.2.3
