### ISSUE TITLE
With falsey `emptyLabel` and no found matches, pressing ENTER should submit form

### ISSUE THREAD

**Issue by JWess** [ericgio/react-bootstrap-typeahead#546]
### Version
4.2.3

### Steps to reproduce
In the sandbox below, type in `ABC` and press ENTER to attempt to submit the form:

https://codesandbox.io/s/green-resonance-7mvys

I have a use-case where I want to allow users to submit values even if they don't have any type-ahead matches. Because of this, I pass a null `emptyLabel` in order to attempt to hide the menu when no matches exist. However, the menu still shows as an empty white box. If I provide CSS overrides, the menu can be hidden, but the typeahead still seems to prohibit the user from pressing ENTER to submit the form. Only once the user presses ESC or clicks away to close the menu does ENTER submit the form. Is there a way to not show the menu when no matches are found while allowing the user to still submit the form by pressing ENTER? 

### Expected Behavior
When no matches are found, pressing ENTER still submits the form.

### Actual Behavior
The typeahead blocks the form from submitting.

**Comment by ericgio** [comment]
Hi @JWess, thanks for your question. What you're describing is the intended behavior, but there are some workarounds described in #396.

**Comment by JWess** [comment]
Is there any way for me to manually close the menu when there are no matching suggestions?

**Comment by ericgio** [comment]
The best way to suppress the menu is by using [`renderMenu`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md#rendermenuresults-arrayobjectstring-menuprops-object-state-object) and [returning `null` when there are no results](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Upgrading.md#falsy-emptylabel-no-longer-hides-the-menu-when-there-are-no-results).
