### ISSUE TITLE
Need way to pass CSS and/or attributes to inner <input> element

### ISSUE THREAD

**Issue by rjray** [ericgio/react-bootstrap-typeahead#547]
In using this component, I need to be able to pass both a CSS class and a custom HTML attribute down to the `<input>` element that gets created as part of the widget. However, none of the existing props seem to do this. I need something akin to an `innerProps` option that would add its content to the resulting `<input>`. I realize there are actually two `<input>` elements created as part of the overall container, and in this case I'm referring to the text-input one.

**Is your feature request related to a problem? Please describe.**

In this case, my inputs are being decorated by a browser extension (LastPass) because they appear to be a "name" field. To disable this, I need to put the custom attribute `data-lpignore="true"` onto the input itself. I would also like to be able to attach an additional CSS class to the input under certain conditions, but that is less important than the attribute.

**Describe the solution you'd like**

Something like the common convention of an `innerProps` property, that is passed down to the inner input element(s).

**Comment by ericgio** [comment]
Hi @rjray, have a look at `inputProps`.

**Comment by rjray** [comment]
Wow, I totally missed that. Let me try that.

**Comment by rjray** [comment]
That is exactly what I needed, yes. Closing.
