### ISSUE TITLE
And an as= prop to add styles from other componenets

### ISSUE THREAD

**Issue by pedrovrima** [ericgio/react-bootstrap-typeahead#551]
**Describe the solution you'd like**
Add an as= prop, such as the one from React Bootstrap package. This would allow to user other components on top of Typeahead, like Cleave (for input values formatting) and ReactBootstrap (for validation handling)

**How is this solution useful to others?**
It would allow for easier customizing the field

**Describe alternatives you've considered**
I tried using the opposite: Creting a Cleave or Form.Control component and using as=Typeahed, but the way this package is strucutred it renders a field on top of the other.

**Additional context**
From ReactBootstrap docs:

as:  The underlying HTML element to use when rendering the FormControl.

**Comment by ericgio** [comment]
Hi @pedrovrima, thanks for the feature request. This is already possible, eg: with the `renderInput` and `renderMenu` props. Is there something about those that doesn't meet your needs?

**Comment by pedrovrima** [comment]
Hey @ericgio, thanks for the super fast answer. renderInput worked like a charm (actually better than the "as" props from reactBootstrap for what I need). For some reason I got a wrong understanding of that prop. Thanks very much!
