### ISSUE TITLE
Ids are not passing through to HTML elements

### ISSUE THREAD

**Issue by JustinB-dev** [ericgio/react-bootstrap-typeahead#554]
### Version
3.4.7
**Using this version in production app, tested on most current versions as well**

### Steps to reproduce
Add an id to typeahead component. ex: <Typeahead id="example-typeahead"/>
Load onto browser.
Verify typeahead is present.
Inspect element - id should be present but is not.
**Verified that they are not showing up in sandbox either**

### Expected Behavior
Ids passed into Typeahead should appear on HTML elements when inspecting in browser.

### Actual Behavior

Ids are not showing up.

**Comment by ericgio** [comment]
Hi @JustinB-dev, thanks for filing this issue. I'm not sure I totally understand your question, but it sounds like you're expecting the `id` to be passed down to the input, is that right? If so, that isn't the way the top-level `id` prop works. It's ultimately passed down to the menu for accessibility purposes. If you need to add an `id` to the input, you should use `inputProps`.

**Comment by JustinB-dev** [comment]
`<td>
										<Typeahead
											id="user-account-typeahead"
											options={this.accounts}
											defaultSelected={
												this.selectedAccounts
											}
											clearButton
											onChange={this.onAccountChange}
											className="typeahead-field"
											searchable
											multiple={
												this.shouldDisplayAccounts ||
												this.selectedAccounts.length > 1
											}
										/>
									</td>`

So this is the code that we are using, and the className is coming through to the div, but the id is not.
![Screen Shot 2020-05-28 at 10 37 14 AM](https://user-images.githubusercontent.com/50118827/83174500-569c9c00-a0cf-11ea-8e12-923d4279b277.png)

**Comment by ericgio** [comment]
Yes, that's the expected behavior.

**Comment by JustinB-dev** [comment]
Using `inputProps={{id: 'test-typeahead-id'}}` does not work either.  Based on the docs, it should be a bug, no?
![Screen Shot 2020-05-28 at 11 11 47 AM](https://user-images.githubusercontent.com/50118827/83177588-2acfe500-a0d4-11ea-85a8-2a6a2d0cc657.png)

**Comment by ericgio** [comment]
Using `inputProps` allows you to pass an `id` to the `input` element:

```jsx
<Typeahead
  ...
  inputProps={{
    id: 'my-id',
  }}
/>
```

It's not a bug, though perhaps the docs could be clearer. What is your use-case?

**Comment by JustinB-dev** [comment]
From the screenshot inspecting the elements the typeahead comes through as a div, and I am trying to get an id attribute onto that div.

**Comment by ericgio** [comment]
There's no way to add an `id` to the top-level `div`. Why do you need to do that?

**Comment by JustinB-dev** [comment]
Our specific use case is for our QA Team trying to run automation and running into trouble with these specific fields.
Also, it is a field that can determine some important information, so we want to be sure that it is accessible by screen readers.

We found a work-around with adding another wrapper and putting the id tag there, but figured I could bring it to your attention.  The only reason I thought it may be a bug is because the `className`  is able to pass through to the top level, but the `id` isn't.

**Comment by ericgio** [comment]
> Also, it is a field that can determine some important information, so we want to be sure that it is accessible by screen readers

Note that the `div` itself is not intended to be accessible; the `input` and menu are the relevant elements for screen readers. That's great you were able to find a workaround that meets your needs, however. I'll consider this issue resolved.
