### ISSUE TITLE
className props

### ISSUE THREAD

**Issue by IHIutch** [ericgio/react-bootstrap-typeahead#555]
**Is your feature request related to a problem? Please describe.**
Be able to add classes to internal components. eg: `inputClassName`, `optionClassName`, `dropdownClassName`

**Describe the solution you'd like**
Being able to add classes directly to internal components

**How is this solution useful to others?**
Prevents having to write custom CSS where you'd otherwise be able to add classes to the HTML directly

**Describe alternatives you've considered**
Adding className to the prop directly only targets the wrapping div. Right now I need to add an arbitrary class name to the component and target the changes I want to make via CSS

**Comment by ericgio** [comment]
Hi @IHIutch, thanks for opening this issue. You can already customize the lower-level components with the current API. The best way to do this is through the `renderInput` and `renderMenu` props, which give you full control over the rendering of those components. For example:

```jsx
<Typeahead
  renderInput={(inputProps) => (
    <TypeaheadInputSingle
      {...inputProps}
      className={`${inputProps.className} my-classname`}
  )}
/>
```

See the [rendering docs](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md) for more.

Additionally, you can apply a classname to the input via `inputProps`:

```jsx
<Typeahead
  inputProps={{
    className: 'my-classname',
  }}
/>
```

**Comment by IHIutch** [comment]
Ah, great, thanks for the help. New to react so forgive my ignorance. Thanks for the quick response!
