### ISSUE TITLE
with multiple select enabled, can we have maxSelected property as well!!

### ISSUE THREAD

**Issue by vasu084** [ericgio/react-bootstrap-typeahead#556]
With the following code, I cannot remove/modify the selected tokens, if the selected token length is 2. Can we have maxSelected property so that we can ignore disabled in this case or Is there any other option?
 
```jsx
<Typeahead 
  multiple
  disabled={selected.length === 2} 
  options={[...]} 
/>
```

**Comment by ericgio** [comment]
Another approach might be to use `renderMenu` to disable the options and/or display a warning of some sort in the menu.
