### ISSUE TITLE
Dead link in Rendering.md

### ISSUE THREAD

**Issue by foscjos** [ericgio/react-bootstrap-typeahead#558]
### Version
Current version

### Steps to reproduce
[Navigate here](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md#rendermenu-gotchas) and try to click on the link to see the TypeaheadMenu. 

### Expected Behavior
Takes me to TypeaheadMenu component/file, most likely [here](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/components/TypeaheadMenu.react.js)

### Actual Behavior
404.

**Comment by ericgio** [comment]
Fixed. Thanks for the report @foscjos!
