### ISSUE TITLE
Using the up/down arrow keys to select one of the options does not fire onChange

### ISSUE THREAD

**Issue by jhvanderven** [ericgio/react-bootstrap-typeahead#559]
### Version

5.0.0.rc3 and then downgraded to 4.2.3 (both act the same way)

### Steps to reproduce

TypeAhead is filled with an array of objects, labelKey is set to the name property. One mouse click inside focuses the input and the options drop down. Use the arrow keys to select one of the options. Note in console.log (in the onChange handler) that the event does not fire.

```jsx
// this is a snippet
    const onKeyDown = (event: any): void => {
    if (event.keyCode === 13) {
      // TODO: Using the arrow keys to select an item does not fire an onTypeAheadChange
      if(selectedTypeAheadItem!==undefined){
        //use the item and close the popup
        onSelectContext(selectedTypeAheadItem)
      }
    }
  }

  const onTypeAheadChange = (event: any): void => {
    // the selection is an array, but we only want 1
    console.log(event)
    setSelectedTypeAheadItem(event[0])
  }
            <Typeahead
                options={typeAheadOptions}
                labelKey='name'
                clearButton={false}
                id='context-menu-typeahead'
                onKeyDown={onKeyDown}
                onChange={onTypeAheadChange}
                placeholder={t('Search compound by typing')}
              />
```

### Expected Behavior
onChange should be called for each arrow key event

### Actual Behavior
onChange is not called

**Comment by ericgio** [comment]
Hi @jhvanderven, thanks for filing this issue. The behavior you're describing is expected. I think you may be confusing the highlighting behavior with the selection of the items. Using the arrow keys to navigate through the menu and highlight certain items doesn't actually select them, therefore the `onChange` event is not fired. A standard `select` element works the same way.

**Comment by jhvanderven** [comment]
I don't quite agree. The highighted item appears in the input box, just as if it was typed in completely or clicked with the mouse, so whar is the difference between clicking on an item and selecting it with the keyboard? I think this is confusing.

You are probably right that a standard select works the same way. But that does not mean it will not confuse users.

My users have to hit enter twice (or tab once and enter next, even though the complete item is already there), once for the selection and the other (my code, my bad) to actually use the selected item.

**Comment by ericgio** [comment]
> The highighted item appears in the input box, just as if it was typed in completely or clicked with the mouse, so whar is the difference between clicking on an item and selecting it with the keyboard? I think this is confusing

I have to disagree with you, sorry. This is a very common behavior/interaction for typeaheads, eg: Chrome or Google search bars. In both of those cases, as with this component, the input is autofilled with the highlighted option in the menu but no selection is made until the user actually hits enter or clicks the option with the mouse. It doesn't even make sense to select options with the up/down arrow keys, since that would interrupt navigation.

**Comment by jhvanderven** [comment]
I now think you are completely right. I was misled by my use case. I have the typeahead in a context menu and the second enter is needed to indicate that the user wants to use the value in the input rather than one of the other items. Maybe I should rethink my GUI. Sorrry for the trouble and thanks for answering.

**Comment by srigi** [comment]
@ericgio I would like to resurface this issue - in my use case, there is a separate submit button which should submit selected (and not "changed") result. From the UX & accessibility, POV both clicking the button & pressing ENTER on the selected item should fire some handler.

If I don't have access to the currently **highlighted** item, I cannot implement submit button. Any ideas on how to access the currently **highlighted** item?

![Untitled-1](https://user-images.githubusercontent.com/295197/106747013-9f73ff80-6623-11eb-8378-e615a6571a19.png)

**Comment by ericgio** [comment]
@srigi: Can you elaborate on your use case a bit? Presumably, the button submits some kind of form, right? I'm not understanding the relationship between the button and the highlighted item since I'd imagine you need to select an item (via click or enter) before submitting the values. As a counter example, how would your scenario work with a standard `<select>` element?

**Comment by srigi** [comment]
@ericgio the button in example above does not submit form itself. It just adds item to the "basket of items" to be submited later.

This really can be boiled down (solved) with event `onHighlightChange`, same as [Material UI autocomplete component](https://next.material-ui.com/api/autocomplete/). I would very appreciate if this event was implemented in ** react-bootstrap-typeahead**.

**Comment by ericgio** [comment]
> It just adds item to the "basket of items" to be submited later.

I don't understand this interaction; clicking on the menu item or hitting enter accomplishes this. Why is a separate button needed?

**Comment by srigi** [comment]
@ericgio it is a client (UX dept.) decision. Both mouse-clicking (or ENTER key) on the highlighted item, and/or clicking the submit button (labeled "add work to cycle"), adds the **highlighted** item to the queue.

I believe that event `onHighlightChange` which provides the currently highlighted item in the callback would be a very useful addition to the component.

**Comment by ayush-mandowara-bst** [comment]
I am facing a similar issue. When I move up/down on the elements after typing a couple of characters, and press enter I expect that the highlighted item will be fed to my API (which is triggered whenever I press "Enter"), however, what is actually being fed is a partial entry (whatever was searched before pressing the down key).
Ex: I want to access demopackage, so I type in demo, and hit the down key to select demopackage, then I press "Enter" and get served the page meant for "demo", but what I really wanted to see was "demopackage". 
Now, theoretically, I could press "Enter" twice, but, in my use case, if an entry does not exist, a new entry is automatically created in the database (which is junk in the current scenario). 
Isn't there a way I could fetch what is currently present in the input?

**Comment by ericgio** [comment]
@ayush-mandowara-bst: Yours sounds like an unrelated issue. If you think you're encountering a bug, please open a separate issue with relevant code and repro steps. A working sandbox is ideal.

@srigi: As a workaround, you can pass a render function as a child of the typeahead component that receives the internal state. You can use `activeItem` to get the currently highlighted item.

```jsx
<Typeahead ... >
  {({ activeItem }) => {
    // Do something with the value.
  }}
</Typeahead>
```
