### ISSUE TITLE
`allowNew` should default to "New Selection..." when focus is lost

### ISSUE THREAD

**Issue by evantahler** [ericgio/react-bootstrap-typeahead#562]
Hi! We use `react-bootstrap-typeahead` in [Grouparoo](https://github.com/grouparoo/grouparoo) to build some gnarly search interfaces.  It's a great component!  We often use `<AsyncTypeahead />` to build search forms like this:

![output](https://user-images.githubusercontent.com/303226/85805243-a25b5900-b700-11ea-941c-b2db6832698d.gif)

**Is your feature request related to a problem? Please describe.**
This example highlights a feature I'd like to add: **_When focus is lost, and user has typed a selection that has no matches in the list of options, we should assume that they meant to click "New Selection..." and choose whatever they typed._**  To confound the current UX, if you have typed something and haven't clicked "New Selection..." you will /see/ what you typed, but what is saved would be the previously selected value or `null`.  You can see that in the GIF above how the '# profiles' didn't change the first time I typed `%b%` but didn't click "New Selection..."  Once I re-focused the form and chose "New Selection", then my input was saved.

**Describe the solution you'd like**
An option on `<AsyncTypeahead allowNew={true} alwaysAcceptNew={true} />` (and probably the other inputs as well) could allow folks to opt into this behavior.

**How is this solution useful to others?**
... then everyone who uses this library can opt into this behavior! 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by evantahler** [comment]
This behavior can be sort of emulated today with `onBlur` event handlers, but if this is being used, the menu item for "New Selection" probably shouldn't appear.

**Comment by ericgio** [comment]
Hi @evantahler, thanks for the feature request and the detailed description. It's pretty unlikely I'll add this as an out-of-the-box feature since it seems like a fairly narrow use case that is already possible to implement with the current API. I think your solution of adding the value using the `onBlur` handler is the way to go, and gives you full control over the behavior for your particular use case. If you feel there's something you're trying to implement that isn't possible with the current API, however, please let me know.

**Comment by evantahler** [comment]
Thanks @ericgio - perhaps then an option to disable that `New Selection` option on the dropdown (while still allowing new entries `allowNew `) would be helpful.  We could handle the updating of state with onBlur, but that additional option in the dropdown seems to imply the user has to do something...

**Comment by ericgio** [comment]
@evantahler: I don't quite understand the behavior you're after. Selecting arbitrary inputs in the `onBlur` handler seems like a backstop to ensure a selection, with the primary means of selection being the menu item. Removing the menu item essentially renders the underlying `allowNew` functionality useless, so you might as well just turn off the behavior altogether. All that said, if you *really* want to hide that menu item while keeping the `allowNew` functionality, you can filter out the custom option in `renderMenu`.
