### ISSUE TITLE
Id attribute is missing from input

### ISSUE THREAD

**Issue by christopheschwyzer** [ericgio/react-bootstrap-typeahead#563]
### Steps to reproduce

- Go to examples http://ericgio.github.io/react-bootstrap-typeahead/#rendering
- Open dev tools and investigate input 
![image](https://user-images.githubusercontent.com/1888817/85880385-364e2300-b7dc-11ea-8015-d42f0bb1a31d.png)

### Expected Behavior
- `id` is a required property and should be passed.
- `id` attribute should be present.

### Actual Behavior

`id` attribute is not present.

**Comment by ericgio** [comment]
Hi @christopheschwyzer, thanks for the report. This is the expected behavior; the top-level `id` is actually applied to the menu for accessibility purposes. If you need to apply an id to the input itself for some reason, you can use `inputProps` for that.

Related issue: #456, #554

**Comment by christopheschwyzer** [comment]
@ericgio Ah I see. Thank you for the explanation!
