### ISSUE TITLE
Documentation does not imports

### ISSUE THREAD

**Issue by kimfucious** [ericgio/react-bootstrap-typeahead#564]
First, I want to say that I love this!  And thanks for making it! ❤️ 

**Is your feature request related to a problem? Please describe.**

This is a feature request to add some specific detail to the docs.

When reading the docs, there are several code examples.  Let's use the Basic Example as a reference.
```js
const BasicExample = () => {
  const [singleSelections, setSingleSelections] = useState([]);
  const [multiSelections, setMultiSelections] = useState([]);

  return (
    <Fragment>
      <Form.Group>
        <Form.Label>Single Selection</Form.Label>
        <Typeahead
          id="basic-typeahead-single"
          labelKey="name"
          onChange={setSingleSelections}
          options={options}
          placeholder="Choose a state..."
          selected={singleSelections}
        />
      </Form.Group>
      <Form.Group style={{ marginTop: '20px' }}>
        <Form.Label>Multiple Selections</Form.Label>
        <Typeahead
          id="basic-typeahead-multiple"
          labelKey="name"
          multiple
          onChange={setMultiSelections}
          options={options}
          placeholder="Choose several states..."
          selected={multiSelections}
        />
      </Form.Group>
    </Fragment>
  );
};
```
This code refers to imports such as: `Form.Group`, `Form.Label`, etc.  Others, include `InputGroup` and `Button`, which I'd really like to use, but can't figure out how to import.

Nowhere in the docs, can I find examples of how to import these components.  I swear, I've looked, and I've Googled too!

For example:
```js
import { Typeahead, Button } from "react-bootstrap-typeahead";
```
This cannot find Button, nor can this:
```js
import Button, { Typeahead } from "react-bootstrap-typeahead";
```

**Describe the solution you'd like**
I'd love some examples that showed how to import components from `react-bootstrap-typeahead`, like: `InputGroup`.

I've tried:
```js
import { Typeahead, InputGroup } from "react-bootstrap-typeahead";
```

This results in:
```console
Attempted import error: 'InputGroup' is not exported from 'react-bootstrap-typeahead'.
```

**How is this solution useful to others?**
It could be that I'm mentally impaired, however, I've scoured the docs, and cannot see how to import something like `<Button>`.  

Perhaps others may have similar quandaries, and could benefit from some examples that included how to import the components you have in your examples.

**Describe alternatives you've considered**
I **can** sub straight Bootstrap classes in, for example:
```js
...
<div className="input-group">
<Typeahead
  ref={searchRef}
  aria-describedBy="thaiAddressHelper"
  id="search-input"
  labelKey={(option) =>
    `${option.district}, ${option.amphoe}, ${option.province}  ${option.zipcode}`
  }
  minLength={5}
  onChange={handleChange}
  options={items}
  placeholder="e.g. 50200"
  selected={postalCode}
/>
<div className="input-group-append">
  <button className="btn btn-outline-primary">Clear</button>
</div>
</div>
...
```
While this does work, I am insatiably curious as to how to follow the code in the docs.

**Additional context**
I realize that this is probably a "me" problem, but I am at a lost to figure out what "me" is doing wrong.

Any advice here is appreciated.

**Comment by ericgio** [comment]
Hey @kimfucious, thanks for the kind words! I'm sorry you've been finding the docs confusing. All the elements you mention — `Button`, `Form`, `InputGroup` —  are imported from the [`react-bootstrap`](https://react-bootstrap.github.io/) library. I agree that's definitely not clear from the examples and it might be helpful to include the imports in the code sample. I originally omitted them to try and keep the noise to a minimum and focus on the code itself.

**Comment by kimfucious** [comment]
Hi @ericgio,

Thanks for the nice reply.  

Funnily, I hadn't even thought about `react-bootstrap`.  Now that you mentioned it, it makes sense where these imports come from.  

On this project, we're not using `react-bootstrap` or `react-strap`, or any straps except bootstrap.

Now that you've answered my question, I'll keep working plain old bootstrap, so as to not add an additional lib, unless I find I need to.

I agree with trying to keep the noise to a minimum with code examples.  

In hindsight, your package name clearly includes `react-bootstrap` in its title, but I completely glazed over it, thinking "Hey, cool typeahead for bootstrap!"  

Perhaps the best way to go, would be to inform somewhere clearly how to install and/or import `react-bootstrap` if it's a dependency of your super cool library.

Excellent work on this!

Best,

Kim

**Comment by ericgio** [comment]
Glad I was able to clarify and that things make more sense. To further clarify, while this library is intended to work well with `react-bootstrap`, it has no affiliation with, and does not depend on, that library so there's no need to install it if you don't want to. I simply used it in the examples for convenience.

**Comment by kimfucious** [comment]
Good stuff!

I'm really enjoying your library!

Thanks for creating and sharing such a nice product to open source 🎈
