### ISSUE TITLE
Support Tree Data

### ISSUE THREAD

**Issue by linh626688** [ericgio/react-bootstrap-typeahead#565]
Do you have any plans for support tree data feature?

**Comment by ericgio** [comment]
Hi @linh626688, thanks for the question. Can you please elaborate, detailing what exactly you'd like to see and ideally including code samples? Thanks!

**Comment by linh626688** [comment]
![image](https://user-images.githubusercontent.com/8878721/86444500-03a3ad80-bd3b-11ea-9eca-39d8ee0a21da.png)
Cool. thanks for your reply. my meaning is component might support data with the tree structure (look like the image) with the parent node and child node in the options dropdown. Currently, the component just toggles the list elements with a plain array, do you have any plan or feature for list element with the tree structure.

**Comment by ericgio** [comment]
I believe the library already supports something like this, though it would probably require a custom `filterBy` function and a custom menu using `renderMenu`. If you feel your use case is impossible to implement with the current API, please provide a detailed description of what you're not able to achieve, ideally with a sandbox of what you've tried so far. Beyond that, I doubt there will any out-of-the-box support for what is likely a pretty narrow use case.
