### ISSUE TITLE
How to make highlight after remove menu bar when the menu item is empty.

### ISSUE THREAD

**Issue by stefanmatic51** [ericgio/react-bootstrap-typeahead#568]
I am very thanks If you can help me top resolve this.
In order to remove the menu when menu item is empty.
like this.

```jsx
<Typeahead
  selected={selected}
  id={`should-select-${tabIndex}`}
  onChange={(selected) => this.onChangeType(selected)}
  options={options}
  minLength={2}
  ref={this.typeInput}
  renderMenu={(results, menuProps) => {
    // Hide the menu when there are no results.
    if (!results.length) {
      return null;
    }
    return <TypeaheadMenu {...menuProps} options={results} />;
  }}
  labelKey="type"
  onKeyDown={() => this.onChangeValue()}
  onBlur={() => this.onChangeValue()}
  placeholder="Type"
/>
```

But after that, It did not make any highlights text for searching result.
how can I solve this?
![current situation](https://user-images.githubusercontent.com/66953493/87927197-1d572b80-ca83-11ea-9e79-7c9ab5070942.png)
![actual behaviour](https://user-images.githubusercontent.com/66953493/87927250-38c23680-ca83-11ea-99d0-74ec93eee2da.png)

Thanks

**Comment by ericgio** [comment]
Hey @stefanmatic51, thanks for filing this issue. Can you please tell me which version you're using?

**Comment by stefanmatic51** [comment]
Thanks for your reply. @easel 
I am using 0.9.0.

**Comment by ericgio** [comment]
@stefanmatic51: That doesn't seem right. Are you sure that's the version of the typeahead library you're using? The current version is 5.1.

**Comment by stefanmatic51** [comment]
Ah sorry, It was my fault.
![image](https://user-images.githubusercontent.com/66953493/87983074-160e3d00-cad8-11ea-8afa-414a4163118a.png)

**Comment by ericgio** [comment]
@stefanmatic51: You need to also pass in `text` and `labelKey` props to `TypeaheadMenu`:

```jsx
renderMenu={(results, menuProps, props) => {
  // Hide the menu when there are no results.
  if (!results.length) {
    return null;
  }
  return (
    <TypeaheadMenu
      {...menuProps}
      labelKey={props.labelKey}
      options={results}
      text={props.text}
    />
  );
}}
```
See working example: https://codesandbox.io/s/rbt-issue-568-mqb0m

The need for these two additional props in `TypeaheadMenu` are actually poorly documented. I need to add them to the API.

**Comment by stefanmatic51** [comment]
@ericgio 
Nice.
It works on my side well.
Thank you.
