### ISSUE TITLE
`selectHintOnEnter` prop is deprecated. is not shown in the props docs

### ISSUE THREAD

**Issue by ryanmk54** [ericgio/react-bootstrap-typeahead#569]
### Version
5.1.0

### Steps to reproduce

Add the selectHintOnEnter={true} to react-bootstrap-typeahead as show in the sandbox below:

https://codesandbox.io/s/nifty-thunder-gzm25?file=/src/index.js

Look at the documentation for the selectHintOnEnter prop here: 

https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Props.md

### Expected Behavior

It should show the selectHintOnEnter prop is deprecated and what to do instead. A link to the Hint Component and how to use it would be nice. It would be nice to see that it is deprecated before trying to use it. A link to https://stackoverflow.com/questions/62095090/how-to-use-shouldselect-on-hint-for-react-bootstrap-typeahead-to-detect-enter would be nice too.

### Actual Behavior

There is nothing in the docs for the selectHintOnEnter prop indicating it is deprecated.

**Comment by ericgio** [comment]
Hey @ryanmk54, thanks for filing this issue and sorry for the confusion. The deprecation and recommended alternative was documented in the [release notes](https://github.com/ericgio/react-bootstrap-typeahead/releases/tag/v5.0.0), but I agree it would be helpful to mark the prop as deprecated in the docs.

**Comment by ericgio** [comment]
I've updated the docs to call out that `selectHintOnEnter` has been deprecated.
