### ISSUE TITLE
Rewrite in Typescript

### ISSUE THREAD

**Issue by hinsxd** [ericgio/react-bootstrap-typeahead#570]
EDIT: I dived into the code and realized that the types defined in `types.js`, especially function signatures, are often inconsistent with actual usage. It requires much more effort than expected to correctly type and rewrite in typescript.
I will still contribute to `@types/react-bootstrap-typeahead` but I guess I will give up rewriting at this moment.

Again, thanks for the wonderful library!

========================================================================================

I found this gem but I use TypeScript. The `@types/react-bootstrap-typeahead` packages hasn't been updated since v3.4.

This package is written in Flow so it should be fairly easy to rewrite it in TypeScript.

If you don't mind, I will give it a try and perhaps it will be done in a week or two.

As TypeScript is becoming popular with stronger community, I think migrating to TypeScript should be beneficial to more users too.

**Comment by brvaland** [comment]
I am interested in using typescript with react-bootstrap-typeahead, the existing library @types/react-bootstrap-typeahead have some issues with labelKey and ref to access public methods. Is it possible to get an update on this issue ?

**Comment by ericgio** [comment]
I don't have plans to rewrite in Typescript at the moment. I'd recommend submitting a pull request to the `@types` library to fix the issues you mention.

**Comment by atefBB** [comment]
I use typescript and I solve this issue by creating a `react-bootstrap-typeahead.d.ts` file that contains `declare module 'react-bootstrap-typeahead';`. The `@types` library still have the same issue.
