### ISSUE TITLE
Update README to point Props link to the API docs

### ISSUE THREAD

**Issue by mwq27** [ericgio/react-bootstrap-typeahead#571]
**Is your feature request related to a problem? Please describe.**

The Props link in the README brings me to a 404 page.

**Describe the solution you'd like**

The Props docs link could be removed, and the text for API docs can be updated to include Props ("API and Props"). 

**How is this solution useful to others?**
Does your feature address a common use case? Does it provide a more generalized way to solve the type of problem you're encountering?

This solution would get rid of the 404 page, and tell the user that you will find documentation for both API and Props via the API & Props link.

**Describe alternatives you've considered**

We could leave the Props link, but have it also point to the API docs page. 

**Additional context**
Add any other context, sample code, or screenshots about the feature request here.

**Comment by ericgio** [comment]
Hey @mwq27 thanks for catching and fixing this issue! Really appreciate it.
