### ISSUE TITLE
Disable Filtering

### ISSUE THREAD

**Issue by entozoon** [ericgio/react-bootstrap-typeahead#574]
**Is your feature request related to a problem? Please describe.**
Using async typeahead, my endpoint already filters options appropriately before returning so no extra client-side filtering is necessary.

**Describe the solution you'd like**
I would like to wholly disable the automatic filtering of options.

**How is this solution useful to others?**
Useful because currently the options end up being filtered twice, and it's too much - options can go missing.

**Describe alternatives you've considered**
I've tried to have `filterBy` apply itself to multiple keys to be as broad as possible but it's not ideal

**Comment by ericgio** [comment]
Hey @entozoon, thanks for the question/feature request. You can disable filtering by simply returning `true` from your `filterBy` function:

```jsx
<AsyncTypeahead
  ...
  filterBy={() => true}
/>
```

**Comment by entozoon** [comment]
Sweet, I recommend adding that to the docs @ericgio as it's not at all obvious!
