### ISSUE TITLE
Typing doesn't work if initiated with value

### ISSUE THREAD

**Issue by IPWright83** [ericgio/react-bootstrap-typeahead#575]
I'm unsure if this is a bug, or me having mis-understood the correct usage from the docs. If it's the later please forgive me! However due to the significant difference in behaviour depending on if I provide an empty string `""` to an actual value `AB10 1AB` it looks like it may be a bug?

### Version

5.1.0

### Steps to reproduce

Example: https://codesandbox.io/s/serene-yalow-f2wcn

- Select all the text and attempt to type a new postcode (e.g. AB)

### Expected Behavior

That the `AsyncTypeahead` control accepts input and searches for a different postcode rendering the typed text in the input control.

### Actual Behavior

The `AsyncTypeahead` accepts the input and searches but doesn't seem to update the underlying control. Note that if you change the `initialValue` to be an empty string this works as expected. Also when trying to put this example together using the sandbox sample then it worked as expected using the old version of `4.0.0-alpha.6`.

**Comment by ericgio** [comment]
Hey @IPWright83, the problem is in your `onChange` handler:

```jsx
const onChange = postcode => {
  console.log(`onChange(${postcode})`);

  // Commenting out this line and passing `postcode` fixes the issue.
  // const selected = postcode.length > 0 ? postcode[0] : "";
  setValue(postcode);
  onBlur();
};
```

Including the line above means you end up passing an array with an empty string, thus repeatedly setting the string as the selection and preventing any user input.

**Comment by IPWright83** [comment]
@ericgio thanks very much! I thought it'd probably be a mis-understanding but I was feeling very confused by the difference in behaviour.
