### ISSUE TITLE
Allow to pass 'onRemove' on custom made Tokens (withToken/useToken)

### ISSUE THREAD

**Issue by alexferrari88** [ericgio/react-bootstrap-typeahead#576]
**Is your feature request related to a problem? Please describe.**
I created a custom Token using useToken on my functional component. I have no idea how to pass the onRemove function since my custom token is rendered like this (within the `render()` of my main component):
```jsx
{this.state.selected.map((option, idx) => (
  <CustomToken
    key={idx}
    option={option}
    logo={option.logo}
    name={option.name}
  ></CustomToken>
))}
```

This is the CustomToken component:
```jsx
const CustomToken = (props) => {
  return (
    <div
      {...useToken(props)}
      className="row w-50"
      option={props.option}
      onRemove={props.onRemove}
      >
      <div className="col">
        <img src={props.logo} style={{ width: 2 + "rem" }} />
      </div>
      <div className="col">{props.name}</div>
    </div>
  );
};
```
Of course I get `Warning: Unknown event handler property `onRemove`. It will be ignored.`
By the way, in order to have my tokens rendered somewhere else (instead of in the input field), I'm using renderInput to decouple the two as seen [here](https://codesandbox.io/s/5u9c4).
This is my renderInput function:
```jsx
renderInput = ({ inputRef, referenceElementRef, ...inputProps }) => {
  delete inputProps.inputClassName; //removes the not used inputClassName property
  return (
    <div>
      <input
        {...inputProps}
        className="form-control"
        ref={(input) => {
          inputRef(input);
          referenceElementRef(input);
        }}
        type="text"
      />
    </div>
  );
};
```

**Describe the solution you'd like**
Since I'm positioning my CustomToken in a different place than inside the input bar, I would like to pass the onRemove function to a custom token.

**How is this solution useful to others?**
This feature would allow for truly customizable Tokens.

**Comment by ericgio** [comment]
Hey @alexferrari88, thanks for the detailed question/request. The behavior you're asking about should already be achievable. You need to pass `onRemove` to `CustomToken`:

```jsx
<CustomToken
  ...
  onRemove={onRemove}
  option={option}
/>
```

I'm not sure exactly where you're rendering the tokens, but `onRemove` is available in several places: the second argument of `renderInput` and the argument passed to the typeahead's child render function are both objects that contain `onRemove`.

**Comment by alexferrari88** [comment]
thank you for your answer @ericgio .
I tried like this:
```
renderInput = ({ inputRef, referenceElementRef, ...inputProps }, props) => {
		delete inputProps.inputClassName; //removes the not used inputClassName property
		return (
			<div>
				<input
					{...inputProps}
					className="form-control"
					ref={(input) => {
						inputRef(input);
						referenceElementRef(input);
					}}
					type="text"
				/>
				{this.state.selected.map((option, idx) => (
					<CustomToken
						key={idx}
						option={option}
						onClickCustom={(evt) => {
							props.onRemove(evt);
						}}
					></CustomToken>
				))}
			</div>
		);
	};
```

and the functional component like this:
```
const SubredditCard = (props) => {
	return (
		<div
			{...useToken(props)}
			onClick={(event) => {
				event.stopPropagation();
				props.onClickCustom(event);
			}}
			option={props.option}
			className="row w-50"
		>
			<img src={props.option.logo} style={{ width: 2 + "rem" }} />
			{props.option.name}

			<button
				aria-label="Remove"
				className="close rbt-close rbt-token-remove-button"
				type="button"
			>
				<span aria-hidden="true">×</span>
				<span className="sr-only">Remove</span>
			</button>
		</div>
	);
};
```

Yet, it still doesn't work. I get these errors in the console:

- Warning: Unknown event handler property `onClickCustom`. It will be ignored.
- Warning: Received `false` for a non-boolean attribute `active`.
- Warning: Unknown event handler property `onRemove`. It will be ignored.

Any suggestion on what I am doing wrong?

**Comment by ericgio** [comment]
@alexferrari88: You're still trying to pass `onRemove` to the underlying element in your token. Pass it to the token component itself as in my example above.

**Comment by alexferrari88** [comment]
@ericgio: ok, tried like that and now my renderInput looks like this:
```
renderInput = ({ inputRef, referenceElementRef, ...inputProps }, props) => {
		delete inputProps.inputClassName; //removes the not used inputClassName property
		return (
			<div>
				<input
					{...inputProps}
					className="form-control"
					ref={(input) => {
						inputRef(input);
						referenceElementRef(input);
					}}
					type="text"
				/>
				{this.state.selected.map((option, idx) => (
					<CustomToken
						key={idx}
						option={option}
						onRemove={props.onRemove}
					></CustomToken>
				))}
			</div>
		);
	};
```

While the functional component for the custom token is this:
```
const SubredditCard = (props) => {
	console.log(props);
	return (
		<div {...useToken(props)} option={props.option} className="row w-50">
			<img src={props.option.logo} style={{ width: 2 + "rem" }} />
			{props.option.name}

			<button
				aria-label="Remove"
				className="close rbt-close rbt-token-remove-button"
				type="button"
			>
				<span aria-hidden="true">×</span>
				<span className="sr-only">Remove</span>
			</button>
		</div>
	);
};
```
Yet, I still get the same errors:

- Warning: Received `false` for a non-boolean attribute `active`.
- Warning: Unknown event handler property `onRemove`. It will be ignored.

What can be causing this?

**Comment by ericgio** [comment]
@alexferrari88: You're seeing those warnings because you're destructuring the result of `useToken` directly on the div and passing unsupported props (`active` & `onRemove`).

**Comment by alexferrari88** [comment]
@ericgio sorry for the stupid question but where should I use use Token then? Getting the warnings is not a problem, I just would like the element to be removed when clicked. Thank you for your patience

**Comment by ericgio** [comment]
You're using it in more or less the right place, but not all the props should be applied to the div. See [`InteractiveToken`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/components/Token.js#L26) for an example of how the internal token component consumes the props. It's very similar to your custom token component. Most of the props are applied to the top-level div element. The `active` prop is used to conditionally set a classname on the div. `onRemove` is passed to the `onClick` handler of the clear button, so that clicking that button will remove the token. You could theoretically pass `onRemove` to the div's `onClick`, but that would mean the token is removed if a user clicked any part of it. That's probably a longer answer than you were looking for, but I wanted to provide a bit of extra context :) Hope that helps.

**Comment by alexferrari88** [comment]
@ericgio thank you for being so patient and the clear answer.
My code now looks like this:
**renderInput**
```
renderInput = ({ inputRef, referenceElementRef, ...inputProps }, props) => {
delete inputProps.inputClassName; //removes the not used inputClassName property
return (
<div>
   <input
   {...inputProps}
   className="form-control"
   ref={(input) => {
   inputRef(input);
   referenceElementRef(input);
   }}
   type="text"
   />
   <div>
      {this.state.selected.map((option, idx) => (
      <CustomToken key={idx} option={option} onRemove={props.onRemove}>
         {option.name}
      </CustomToken>
      ))}
   </div>
</div>
);
};
```
**Functional component**
```
const CustomToken = (props) => {
return (
<div {...useToken(props)} className="w-50">
<img src={props.option.logo} style={{ width: 2 + "rem" }} />
{props.children}
<ClearButton
   className="rbt-token-remove-button"
   label="Remove"
   onClick={props.onRemove}
   tabIndex={-1}
   />
</div>
);
};
```

I have based it on the InteractiveToken one.

And yet, I still have exactly the same problems as before:
- Warning: Received `false` for a non-boolean attribute `active`.
- Warning: Unknown event handler property `onRemove`. It will be ignored.

And, most importantly, whenever I click the X, the token is not removed.

You clearly have a grasp on this, what would you suggest me to do? Thank you.

**Comment by ericgio** [comment]
@alexferrari88: Now you're not applying `useToken` at all. You had the right idea before, you just weren't handling the props correctly. If you look at [the result of `useToken`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/behaviors/token.js#L86), you'll see it returns a bunch of props. Those need to be properly applied in your CustomToken:

```jsx
const CustomToken = (props) => {
  const { active, onRemove, option, ...rest } = useToken(props);

  return (
    <div className="w-50" {...rest}>
      <img src={option.logo} style={{ width: 2 + "rem" }} />
      {props.children}
      <ClearButton
         className="rbt-token-remove-button"
         label="Remove"
         onClick={onRemove}
         tabIndex={-1}
       />
    </div>
  );
};
```

**Comment by alexferrari88** [comment]
You are the best!!
Thank you so much, it works!!
