### ISSUE TITLE
Clear button not clear the dropdown menu if my min length is 0

### ISSUE THREAD

**Issue by MastersoftGroup** [ericgio/react-bootstrap-typeahead#577]
**Is your feature request related to a problem? Please describe.**
I have implemented the AsyncTypeahead, with min length 0 because i want to show the drop down with an enter key, however after I select the option, then click the clear button, it clears the input but didnt clear the options. when i do a mouse left click to the input box, it will show previous options in the dropdown. I am struggling with finding a way to clear the options when my min length is 0. can you please help

**Describe the solution you'd like**
If there is workaround please provide.

**How is this solution useful to others?**
I think so, why clear button only clear input not dropdown options?

**Describe alternatives you've considered**
N/A

**Additional context**
Any solutions will be appreciated.

**Comment by ericgio** [comment]
Hi @MastersoftGroup, thanks for opening this issue. The behavior you're seeing is intended; the clear button clears the input value and selections, not the options that are passed in. If you want to clear the options, you need to do that yourself by passing an empty array to the `options` prop.

**Comment by MastersoftGroup** [comment]
Thanks for the reply. So when you say I need to clear the options by myself, you mean I can have my own clear button? or there is a way to override behavior of clear button like for onChange etc? can you please give an example if possible?

**Comment by ericgio** [comment]
There isn't a top-level handler for when the component is cleared, so you'll need to implement your own clear button and attach a click handler. [Here's an example](https://codesandbox.io/s/rbt-custom-aux-components-gn3kn) of how to implement a custom button and/or spinner. You can then update the options from the button's click handler.

**Comment by MastersoftGroup** [comment]
Cool, get it. I can start from there. thanks.
