### ISSUE TITLE
Add property to clear contents if no selection made when component loses focus

### ISSUE THREAD

**Issue by jenniferburch** [ericgio/react-bootstrap-typeahead#579]
**Is your feature request related to a problem? Please describe.**
Users sometime type the entire text matching the desired option in the select but don't select it from the list.  It looks right but the onchange() wasn't triggered

**Describe the solution you'd like**
I'd like to pass a prop to the component that when true automatically clears the visible text if no selection is made when the component loses focus.

**Describe alternatives you've considered**
I tried clearing the input in onBlur when no selection has been made, but the onBlur event triggers if you click the scroll bar in the dropdown.  

I tried combining onBlur with onMenuToggle but I couldn't get the timing right because onMenuToggle fires after onBlur.

I also considered using accepting the typed text as a valid selection if it's an exact match but it could be a substring of another option so that is not ideal.

**Comment by ericgio** [comment]
Hi @jenniferburch, thanks for the feature request. I think your approach of using the `onBlur` handler to clear the input is the right one. The menu needs a mousedown handler to prevent the input from blurring when a user clicks the scrollbar. Something similar is already applied to the clear button and the menu items. It's a pretty simple fix, but is probably a breaking change.

**Comment by kokkalidis** [comment]
Hello @ericgio, can you increase the release version, so we can install this fix in our project? npm installs v5.1.1 committed on August 10.

**Comment by ericgio** [comment]
Fixed in v5.1.2
