### ISSUE TITLE
Firefox: Pressing backspace when the clear button is focus clears field

### ISSUE THREAD

**Issue by danifus** [ericgio/react-bootstrap-typeahead#580]
**Is your feature request related to a problem? Please describe.**
In Firefox, pressing backspace when the clear button is focused causes back navigation. I often hit the backspace when attempting to amend a field when quickly moving through a form with tab.

**Describe the solution you'd like**
I would like pressing backspace on the clear button to clear the entry and put focus on the input.

**How is this solution useful to others?**
It may cut down on the number of people accidentally navigating away from the form for others too.

**Describe alternatives you've considered**
Given this is normal behaviour for Firefox when a button is in focus, you could leave as is.

Thanks for your great work!!

**Comment by ericgio** [comment]
Fixed in v5.1.2
