### ISSUE TITLE
clearButton without animation

### ISSUE THREAD

**Issue by GABuryan** [ericgio/react-bootstrap-typeahead#584]
Hi, thanks for component.
When I use the clearButton, it disappears when I delete the text. And the input field changes size. When I type the text, the button appears. it turns out an animation. Is it possible to display an empty button in the absence of text, so that the size of the input field is unchanged? How can this be done? Thanks, good luck

**Comment by ericgio** [comment]
Hi @GABuryan, thanks for the question. The input field shouldn't be changing size depending on whether the clear button is present or not. I don't reproduce that in the examples so if that's the behavior you're seeing, you may have some conflicting CSS. If you need to customize the clear button further, check out [this example](https://codesandbox.io/s/rbt-custom-aux-components-gn3kn).

**Comment by GABuryan** [comment]
thanks for example. It solves my problem.

my version was like this with Bootstrap style:
`<div className='d-flex flex-row' 
   <div> Workshop</div>
   <Typeahead clearButton .../>`
the output of the invisible button through children props helped me. Thanks
