### ISSUE TITLE
inputProps and value of Input

### ISSUE THREAD

**Issue by GABuryan** [ericgio/react-bootstrap-typeahead#585]
If you enter text in the input field but do not confirm your choice and go to another field, the input field remains the value.
selected = []
Can I clear the input field? I tried to use inputProps = {{value:''}} but it didn't help.
what are the options to clear the input field ? Thanks.

**Comment by ericgio** [comment]
You can use the provided [`clear` method](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md) to clear the component.
