### ISSUE TITLE
Warning "can't call "this.setState" on an unmounted component"

### ISSUE THREAD

**Issue by phuoc-huynh-ep** [ericgio/react-bootstrap-typeahead#586]
### Version
react-bootstrap-typeahead v5.1.1
Next.js v9.4.0
Preact.js v10.4.1

### Steps to reproduce
1. I set up the basic Next.js project with the Next's router, e.g. index & about pages
2. Import the react-bootstrap-typeahead v5.1.1 in both pages with a basic example
3. When I navigate from a page to another, I get a warning:
```
Can't call "this.setState" on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
  in RootClose
  in TypeaheadManager
  in Typeahead
  in TypeaheadComponent
  in ForwardRef()
```

### Expected Behavior
- I don't want to see the warning when redirect. How could I fix this?

Thanks for your help! :)

**Comment by ericgio** [comment]
Hi @phuoc-huynh-ep, thanks for opening this issue. Can you please provide a sandbox with a minimal repro of the issue? It's hard to tell what's going on from a stack trace. Thanks!

**Comment by phuoc-huynh-ep** [comment]
Hi @ericgio, I have created a mini example on the sandbox, I used Next.js example "[using-preact](https://github.com/vercel/next.js/tree/canary/examples/using-preact)" then install the react-bootstrap-typeahead package & run in dev mode.
In the console of the sandbox, I don't see the warning but if you access by Chrome or Firefox you will see the warning, I don't know why.
Here is the sandbox: https://codesandbox.io/s/tender-mclean-j9bfn
Put this URL https://j9bfn.sse.codesandbox.io/ in the Chrome or Firefore,  you will see the warning.
Thanks for your response.

**Comment by ericgio** [comment]
@phuoc-huynh-ep: The warning is being displayed whenever the component unmounts. When I downgrade the React version to the latest major release (16.3.1), the warning goes away so it looks related to some change in v17. I'm going to close this issue since the library doesn't support React v17, but will revisit for some future release when support is added.
