### ISSUE TITLE
If first match is not a match-at-the-start then hint the first match which *is*

### ISSUE THREAD

**Issue by gusmoney** [ericgio/react-bootstrap-typeahead#588]
### Version
5.1.1

### Steps to reproduce
Go to first example at http://ericgio.github.io/react-bootstrap-typeahead/
Suppose I want Kansas..
Type 'ka'

### Expected Behavior
..that it would hint 'kansas', being the first (and only) option which starts ka

### Actual Behavior
It shows matching options but hints none.

============
So after typing 'ka' - there are four matches but no hint is retrieved as the first match (Alaska) matches not-at-the-start
Even typing the entire word 'kansas', I have to navigate to the option I want in the dropdown to select it (and for many 'average' users that would mean having to revert to the mouse).

For comparison, if I want Arizona:
Type 'ar' - again there are several matches including not-at-the-start ones. But first one is Arizona and it hints that.

I think that it would be helpful to the user to hint the highest item on the matches list which is an at-the-start match - but it's my understanding that the code is only testing the top item in that way.

As it stands, any option which happens to be a substring of another option which is higher in the list of options will never be hinted.

I appreciate this is similar to [issue 461](https://github.com/ericgio/react-bootstrap-typeahead/issues/461) - but tbh I struggled to follow everything in that discussion - sorry!

=========
Really appreciate your work on this great component - huge thanks!

**Comment by ericgio** [comment]
Hi @gusmoney, thanks for opening this issue. The behavior you describe is expected. The component doesn't re-sort results based on the search, and the hint only works if the search matches the beginning of the first result. If you want to re-sort the results, you can use the `renderMenu` prop and provide your own sorting algorithm there.

**Comment by gusmoney** [comment]
Hi @ericgio, many thanks for your prompt reply (sorry I'm a bit slower!)

Just in case I haven't explained very well, I don't want for the results to be resorted. The point I'm querying is 'the hint only works if the search matches the beginning of the first result.' I think it would be useful if the hint worked if there is one (or more) item with a beginning match - regardless of where it comes in the list of all matches. I.e. if that item happens to be second (say) then couldn't it still be hinted? (And if more than one beginning-match-items then use the first *of those*.)

**Comment by ericgio** [comment]
It sounds like as a user you expect a result that starts with the search term you've typed to be more relevant, which is reasonable. The reason I mention sorting is that the order of the results implies relevance, whereas the hint merely emphasizes the first (most relevant) result and provides autocompletion functionality. I think it would be strange to provide a hint for an item that might be in the middle or at the end of a list of results.

So I'm saying that the real problem is that the most relevant result is not being displayed first, which can (and should) be solved by re-sorting the results after they've been filtered.

**Comment by gusmoney** [comment]
Ah ok I see. I've adjusted my code as you suggest and got the behaviour I want - many thanks for your help!
