### ISSUE TITLE
OnEnter Key nothing happens

### ISSUE THREAD

**Issue by arukumar** [ericgio/react-bootstrap-typeahead#59]
Hi, after clicking on input box and hit enter key nothing happen.
`<form onSubmit={::this.handleSubmit)} >
<Typeahead
  labelKey="name"
  onChange={this._handleChange}
  options={myData}
/>
</form>`

please have a look, in version 0.8.2 its working but upgraed version is not working

**Comment by ericgio** [comment]
This was intentionally added in v0.8.3 to prevent inadvertently submitting forms (or triggering other controls) when hitting enter while the input is focused. This would be fairly common, for example, while keying through the options and hitting enter to select an option.

If you want to submit the form as soon as the selection is made, I suggest doing that within `_handleChange` and not using an `onSubmit` handler attached to a `form`.
