### ISSUE TITLE
Allow the component to be preset to a value.

### ISSUE THREAD

**Issue by tyddynonn** [ericgio/react-bootstrap-typeahead#592]
Just experimenting with this as I move into React; have been using the original Twitter Typeahead for some time.

With the original component, the Bloodhound engine can pre-load a set of data and therefore allows you to preset the state of the input from code.

My use case is a selector that can be typed into to select a value, or that may be preset to a 'preferred' value from code.

The preferred value would be selected by key from the list of items available to the component.

Or am I being dumb about how this component works ? I'm definitely a React newbie ;)

**Comment by ericgio** [comment]
Hi @tyddynonn, thanks for your question. You can set the selections using either [`defaultSelected` (uncontrolled) or `selected` (controlled)](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Usage.md#controlled-vs-uncontrolled). Have a look at [the example](http://ericgio.github.io/react-bootstrap-typeahead/#controlling-selections) to see how it works.

**Comment by tyddynonn** [comment]
Thanks for the prompt reply Eric, and the great work on this component.

 

I’m not having any luck using the selected prop, but it’s more likely my lack of understanding of React.

 

I have a created a component that  that uses yours with a ‘preset’ handler:

 

…

    preset(id) {

        // here we should search the options for a value with the right id

        // if found, set the selected value to that

        //console.log(`'${this.props.id}': preset to ${id}`);

        let sel = this.state.options.find((s) => s[this.props.idField] === id);

 

        //console.log((sel) ? `Found ${sel[this.props.displayField]}` : 'Not Found');

        if (sel) {

            this.setState({ selected: [sel] });

        }

    }

    render() {

        return <div>

            <Typeahead

                id={this.props.id}

                placeholder={this.props.placeholder}

                align='left'

                clearButton

                highlightOnlyResult

                onChange={this.props.onChange}

                isLoading={this.state.isLoading}

                labelKey={this.props.displayField}

                options={this.state.options}

            />

        </div>;

    }

…

 

The preset function runs (accessed from the parent via a ref), finds the right entry from the options list – but the component does not update the displayed value to reflect the ‘preset’ item. 

 

What am I doing wrong?

 

Thanks, Chris

**Comment by ericgio** [comment]
@tyddynonn: It's unclear how you're calling the preset function from your example. If you only want this to run when the component mounts, then do it in `componentDidMount` (or an effect, if using a functional component).There's no need for a ref. More importantly, you're setting `this.state.selected` but not passing it to the typeahead.

**Comment by tyddynonn** [comment]
Many thanks again Eric – 

 

I want to be able to use the preset function after the component is created, hence the ref. In my prototype code, it’s called from a button click in the parent.

 

As to passing in the value: I tried

 

…

    render() {

        return <div>

            <Typeahead

                id={this.props.id}

                placeholder={this.props.placeholder}

                align='left'

                clearButton

                highlightOnlyResult

                onChange={this.props.onChange}

                isLoading={this.state.isLoading}

                labelKey={this.props.displayField}

                options={this.state.options}

                selected={this.state.selected}

            />

        </div>;

…

 

And got an error about changing a controlled component to uncontrolled.

 

So I changed to 

 

                defaultSelected={this.state.selected}

 

which got rid of the error but the component still didn’t display the preset value.

 

Apologies for these newbie questions, but it has got me scratching my head..

 

Best, Chris

**Comment by ericgio** [comment]
@tyddynonn: Usage questions like this are more appropriate on a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Feel free to post a link to your SO question on this thread and I'd be happy to try and help.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead

Thanks

**Comment by tyddynonn** [comment]
Ok will do , after I’ve done some more experiments to make sure I’m not missing something simple 😃

Chris
