### ISSUE TITLE
Should provide `getSelected()` public method when it is used as uncontrolled and multiple.

### ISSUE THREAD

**Issue by heroboy** [ericgio/react-bootstrap-typeahead#593]
**Is your feature request related to a problem? Please describe.**
No problem. Because I can use it as controlled.

**Describe the solution you'd like**
```tsx
const ref = useRef();
function handleClick()
{
    //in single mode, I can use:
    //alert(ref.current.getInput().value);
    alert(ref.current.getSelected().join(','));
}
<Typeahead
    ref={ref}
    multiple
    options={['a','b','c','d']}
/>
```

**How is this solution useful to others?**
see above.

**Describe alternatives you've considered**
Use controlled.

**Additional context**
nothing.

**Comment by ericgio** [comment]
Hi @heroboy, thanks for the feature request. I don't have any plans to add a `getSelected` method. You should use the `onChange` prop to get the selected values when they update.
