### ISSUE TITLE
Click clearButton doesn't trigger `onInputChange`

### ISSUE THREAD

**Issue by heroboy** [ericgio/react-bootstrap-typeahead#594]
### Version
5.1.2

### Steps to reproduce

https://codesandbox.io/s/lucid-pine-0ft8m?file=/src/index.js
### Expected Behavior

I want user can input text that doesn't in the options. And I don't want use `allowNew` becuase this need extra mouse clicking the 'insert xxxx' menu item. I just want use it as a normal input textbox with autocomplete to help complete or fix the word.

Currently, I use the above code to do this. There two problems:
1. When you input some text, the `onChange` is called with empty array.(I solve this by ignoring the empty array)
2. When click the clear button, the `onInputChange` doesn't called.

If you can fix either one of them , you can solve my problem.
For 1, you can add some mechanism and allow when use input text, `onChange` is called with the text. (This maybe not works well when options are object.)
For 2, just call `onInputChange` with empty string. (This is more suitable, it doesn't break other things and actually the input is cleared.)

All above I am thinking in the single mode, not consider the multiple mode.

**Comment by ericgio** [comment]
Hi @heroboy, thanks for filing this issue. It's expected that clearing the input doesn't trigger `onInputChange`, since an input's change handler isn't called when the value is changed programatically. The use case you describe is an edge case, as far as I'm concerned; arbitrary values can be selected using `allowNew`. If you don't like that solution, you can try a workaround using `onKeyDown` as described [in this answer](https://stackoverflow.com/questions/63275021/react-bootstrap-typeahead-handling-enter-key-if-no-menu-item-selected).

**Comment by heroboy** [comment]
hello @ericgio , I agree with you that if a value is changed programatically, it doesn't trigger the event. But the "changed programatically" and the event handler should be the same side. In this issues, the "changed programatically" is happened in your library, but the event handler is in the library user side. As the library user, I don't know when user click the clear button and the value changed.
Another example, the browser internal programatically changed the input value when user press a key, then trigger the event.

**Comment by heroboy** [comment]
(If you accept what I am saying, I may add, if user click the dropdown item, the `onInputChange` also not be triggered.)

**Comment by ericgio** [comment]
@heroboy: Actually, you're right. I can't remember when I originally came to that conclusion, but it's actually inconsistent with a standard input: https://codesandbox.io/s/late-resonance-g2878

So yes for #2 in your post, I agree that clicking the clear button should trigger the input's change handler.

**Comment by ericgio** [comment]
Fixed in v5.2.0
