### ISSUE TITLE
Not trim selected elements

### ISSUE THREAD

**Issue by GABuryan** [ericgio/react-bootstrap-typeahead#595]
Hi, filling in an array(selected) with indents for some elements (making a linear tree).  But when output spaces on the left are removed. can this issue be resolved or will it affect the search ? thanks, good luck.

**Comment by ericgio** [comment]
Hi and thanks for your question. Unfortunately, it's hard for me to help without additional information. Please follow the issue template and include a thorough description of your problem. Code examples or sandboxes are extremely helpful as well. Additionally, unless this is a bug or feature request, please post your question on a forum like [StackOverflow](https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead). Feel free to reopen this issue once you've provided more info. Thanks.
