### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by agarg5** [ericgio/react-bootstrap-typeahead#596]
[TypeaheadMenu](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/components/TypeaheadMenu.react.js) on [the rendering page](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md) is a broken link

**Comment by ericgio** [comment]
Thanks @agarg5! This has been fixed.
