### ISSUE TITLE
Allow shouldSelectHint property to be defined on Typeahead component

### ISSUE THREAD

**Issue by Guymestef** [ericgio/react-bootstrap-typeahead#597]
**Is your feature request related to a problem? Please describe.**
SelectHintOnEnter is deprecated but ShouldSelectHint is not available on Typeahaed component (only avaliable on Multi and Single components)

**Describe the solution you'd like**
Add ShouldSelectHint on typeahead and pass down the property

**Comment by ericgio** [comment]
Hi @Guymestef, thanks for the feature request (and PR!) Please note that `shouldSelectHint` is available on `inputProps` at the top level:

```jsx
<Typeahead
  ...
  inputProps={{
    shouldSelectHint: (shouldSelect) => {
      ...
    },
  }}
/>
```

**Comment by Guymestef** [comment]
While reading the doc, I didn't understand that it was available on inputProps ^_^'

**Comment by ericgio** [comment]
Totally understandable. Please feel free to submit a PR to clarify the docs if you think they could be improved.
