### ISSUE TITLE
Usage with browserify

### ISSUE THREAD

**Issue by saghul** [ericgio/react-bootstrap-typeahead#6]
Hi!

I'm trying to make use of your plugin, but I'm a bit stuck because I'm using browserify with gulp, and I guess I need some transform, because requiring css files blows up otherwise. Any ideas? Thanks a lot!

**Comment by ericgio** [comment]
@saghul you can use `browserify-css` to make it work: https://github.com/ericgio/react-bootstrap-typeahead/issues/2

**Comment by ericgio** [comment]
I also added a note to the readme.

**Comment by saghul** [comment]
Oh, sorry, I should have checked the closed issues. Thanks!

**Comment by ericgio** [comment]
No worries, hope that works for you!
