### ISSUE TITLE
minLength counts leading and trailing spaces also

### ISSUE THREAD

**Issue by ramesh-joshi** [ericgio/react-bootstrap-typeahead#600]
### Steps to reproduce

When we give the minLength props to any number then it is working fine but the problem is its counts spaces also, lets say I have giving minLength=3 then if I am giving 3 spaces without typing any characters, typeahead triggers the action, ideally it should not. 

### Expected Behavior

minLength  should not counts leading and trailing spaces

**Comment by ericgio** [comment]
Hi @ramesh-joshi, thanks for opening this issue. The behavior you describe is intended. If you want to suppress rendering of the menu depending on whitespace, you can use the `renderMenu` prop to trim and check the length of the input value, and conditionally render the menu.

**Comment by ramesh-joshi** [comment]
Thanks @ericgio, my point was if we have whitespace then onSearch should not trigger but anyways I added this code and its working fine as expected.
![Onsearch](https://user-images.githubusercontent.com/11056602/99103924-27062100-2595-11eb-8811-a5c18df7a1ea.PNG)
