### ISSUE TITLE
Change suggested results

### ISSUE THREAD

**Issue by gravitymedianet** [ericgio/react-bootstrap-typeahead#602]
### Steps to reproduce

I have set up my PHP backend server to parse the search string for a react-bootstrap-typeahead request that is async. For example, if I search "bottle black", it will also find "black bottle". The problem is when the results come back to the typeahead, it shows 0 results in the COMPONENT list, even though the JSON response DOES have a result, because the order of the words do not match what the user entered.

### Expected Behavior

0 results, although the JSON response shows results.

### Actual Behavior

The question is how to modify the component so that it will show results based on individual word matches vs. the entire string.

**Comment by ericgio** [comment]
Hi @gravitymedianet, thanks for the question. You can avoid filtering on the client by passing `() => true` to the `filterBy` prop. See the [filtering docs](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Filtering.md#filterby), #578, and #589.

**Comment by gravitymedianet** [comment]
Thanks, I just figured that out. How about to alter the highlighting to select each word present?

**Comment by ericgio** [comment]
@gravitymedianet: You can use `renderMenu` or `renderMenuItemChildren` (see [Rendering docs](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Rendering.md) and [example](http://ericgio.github.io/react-bootstrap-typeahead/#rendering)) to customize how each result is highlighted.
