### ISSUE TITLE
Are multiple async data sources supported?

### ISSUE THREAD

**Issue by slead** [ericgio/react-bootstrap-typeahead#603]
Many thanks for writing this awesome plugin.

**Is your feature request related to a problem? Please describe.**
Using the standard Typeahead with Bloodhound, it's possible to specify multiple data sources:

https://stackoverflow.com/questions/27767038/typeahead-bloodhound-with-multiple-remote-datasources
```
$('#searchField').typeahead({},
  {
    name: 'searchTerms',
    source: termEngine.ttAdapter()
  }, {
    name: 'products',
    source: productEngine.ttAdapter()
});
```

Is this possible using react-bootstrap-typeahead? I would like to search multiple APIs concurrently in a single type-ahead box. I'm using the async approach as documented at https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#asynctypeahead

Many thanks again

**Comment by ericgio** [comment]
It should be possible to search multiple APIs using this library. You can make as many requests as you want in the `onSearch` handler; you'd just need to wait for all of them to resolve before updating the loading and options state.

**Comment by slead** [comment]
Thanks, that makes sense
