### ISSUE TITLE
Set input text

### ISSUE THREAD

**Issue by ankitgoyal100** [ericgio/react-bootstrap-typeahead#604]
How do I manually set the text of the input box? I'd like to display the empty string `''` when an item is selected

**Comment by ericgio** [comment]
Hi @ankitgoyal100 and thanks for your question. Unfortunately, it's hard for me to help without additional information. Please follow the issue template and include a thorough description of your problem. Code examples or sandboxes are extremely helpful as well. Additionally, unless this is a bug or feature request, please post your question on a forum like [StackOverflow](https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead). Feel free to reopen this issue once you've provided more info. Thank you!
