### ISSUE TITLE
Is it possible to separate onChange from "onSelect"?

### ISSUE THREAD

**Issue by sometimescasey** [ericgio/react-bootstrap-typeahead#605]
Hi - I've googled quite a bit so if I've still somehow missed documentation related to this please let me know!

**Is your feature request related to a problem? Please describe.**
The basic example clears `singleSelections` as soon as a user types in the search box. I'd like the user to be able to type in the box without altering `singleSelections`, and only trigger `setSingleSelections` when they actually click or hit enter on one of the hints.

```
<Form.Group>
        <Form.Label>Single Selection</Form.Label>
        <Typeahead
          id="basic-typeahead-single"
          labelKey="name"
          onChange={setSingleSelections}
          options={options}
          placeholder="Choose a state..."
          selected={singleSelections}
        />
      </Form.Group>
```

**Describe the solution you'd like**
Would separate callbacks for onChange (for the user typing in the box) and onSelect (for a keydown or click action) be feasible?

**How is this solution useful to others?**
I don't wish to clear the screen content attached to `singleSelections` until the user has definitively chosen something new (and isn't just searching) - this seems like a reasonable generalized use case

**Describe alternatives you've considered**
Have tried removing `onChange` and `selected`, but now unsure how to trigger a `setSingleSelections` call upon user clicking or hitting enter

**Additional context**
Add any other context, sample code, or screenshots about the feature request here.

**Comment by ericgio** [comment]
Hi @sometimescasey, thanks for the feature request. Generally speaking, what you're asking for should already be possible. You can pass an `onChange` handler that conditionally calls `setSingleSelection` based on your desired constraints.

> Would separate callbacks for onChange (for the user typing in the box) and onSelect (for a keydown or click action) be feasible?

This already exists. `onInputChange` is called when the input value changes, while `onChange` is called when the selected items change (added or removed).

**Comment by sometimescasey** [comment]
Hey Eric, thanks for the reply! I'll try to put up a minimal repro later but somehow the React `useState` hook variable storing the selection is being cleared upon change to input, without a selection actually being made.

I can verify however that onChange does work as expected when I make a selection.

I found this and I'm afraid I'm not sure how the author solved the problem:
https://github.com/ericgio/react-bootstrap-typeahead/issues/534

```javascript
const Search = ({ options, ...props }) => {
    const [ inputEvent, setInputEvent ] = useState(null);
    const [ selectEvent, setSelectEvent ] = useState(["I am selected"]);

    const handleChange = (event) => {
      setSelectEvent(event);
    }

    const handleInputChange = (event) => {
      setInputEvent([event]);
    }
    
    return (
        <div>
        <Form.Group className="search__form_group">
          <Typeahead
            labelKey="name"
            onInputChange={handleInputChange}
            onChange={handleChange}
            options={options}
            maxResults={20}
            paginate={true}
            placeholder="Type to search..."
            selected={selectEvent}
          />
        </Form.Group>
        </div>
    );
  };
```

In this example, `selectEvent` is cleared as soon as I type something in the box, even if I haven't made a selection yet. Am I misunderstanding?

**Comment by ericgio** [comment]
> In this example, selectEvent is cleared as soon as I type something in the box, even if I haven't made a selection yet

@sometimescasey: In your example above, you are setting an initial selection. Typing in the input will clear that selection.

**Comment by sometimescasey** [comment]
Ah ok I've finally got it. Sorry for all the confusion.

Typing in the input (even without making a selection) triggers the onChange handler and passes it an empty value.

So I now have the behaviour I want by writing an `onChange` handler that does nothing when the passed input is empty.

```javascript
import _ from 'underscore';
...
const handleChange = (event) => {
      if (_.isEmpty(event)) {
      // do nothing; selection has been cleared but user has not picked a new thing yet
     } else {
      setSelectEvent(event);
    }
}
```

Thanks for the responses! Closing issue.

**Comment by ericgio** [comment]
@sometimescasey: Glad you found a solution that works for you. Two things:

1) `onChange` doesn't pass an event, it passes an array of selections (or an empty array if the selections are cleared)
2) Be aware of potential bugs if you ignore the updated selections. The component and your external state will be out of sync and may lead to strange behavior.
