### ISSUE TITLE
Adding Custom Styling to Dropdown menu scrollbar

### ISSUE THREAD

**Issue by maharshi365** [ericgio/react-bootstrap-typeahead#607]
**Is your feature request related to a problem? Please describe.**
Is there a way we can set the CSS of the dropdown menu scrollbar. I have a custom scrollbar I use in my theme which I would like to use in the typeahead component.

**Describe the solution you'd like**
A new prop for typeahead that allows me to mention a class name for the dropdown scrollbar.

**How is this solution useful to others?**
Allows for more custom styling.

**Describe alternatives you've considered**
I've looked on StackOverflow for potential solutions but not finding anything.

**Comment by ericgio** [comment]
There's no way to add a classname to the menu from the top-level component, but you can use `renderMenu` to customize the rendering of your menu and add a classname there. Alternatively, you can use the existing classnames on the menu element for scoping and add the CSS you need to your project.
