### ISSUE TITLE
Add typeahead keyboard options & update documentation

### ISSUE THREAD

**Issue by sonnyboy27** [ericgio/react-bootstrap-typeahead#609]
**Is your feature request related to a problem? Please describe.**
After upgrading to the latest version I miss having the selectHintOnEnter the `<Typeahead>` component used to have.

**Describe the solution you'd like**
I'd like to include that previous implementation of `selectHintOnEnter`. 

**How is this solution useful to others?**
Selecting from the keyboard is very convenient as well as intuitive to many users since many search boxes work this way. 

**Describe alternatives you've considered**
We have been using a `<TypeaheadInputMulti>` with a `<Token>` in order to be able to press 'Enter' and select the first element in the available options. But this was quite time consuming and we ran into problems understanding how to pass props to the `<Token>` component until we found a hint in issue #480. Additional documentation in the API & Props documentation would be appreciated if the boolean were not reintroduced.

**Comment by ericgio** [comment]
Hi @sonnyboy27, thanks for the feature request. `selectHintOnEnter` was deprecated in v5 in favor of [`shouldSelect` on the `Hint` component](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#hint) (or `shouldSelectHint` on `TypeaheadInputSingle` and `TypeaheadInputMulti`). You can also apply `shouldSelectHint` on the top-level component via `inputProps`:

```jsx
<Typeahead
  ...
  inputProps={{
    shouldSelectHint: (shouldSelect, e) => {
      ...
    },
  }}
/>
```

If you find the documentation lacking, I'd welcome a pull request to improve it. Thanks!
