### ISSUE TITLE
AsyncTypeahead doesn't display options passed as default values

### ISSUE THREAD

**Issue by bggolding** [ericgio/react-bootstrap-typeahead#610]
5.1.1

When using AsyncTypeahead, initial options passed to it should be shown as the default. In the docs it says:

    Options to be passed to the typeahead. Will typically be the query results, but can also be initial default options.

Instead, when options are passed, they are not displayed.

This does seem to work when using the Typeahead component.

I tried writing a test case which fails which I could submit as a PR but I wasn't allowed to push it because the tests failed. The test I wrote is:

```
  test('displays the default value when the initial options is not empty', () => {
    const defaultOption = 'default option';

    wrapper = mount(
      <AsyncTypeahead
        defaultInputValue="sometext"
        delay={0}
        id="async-empty-label-test"
        isLoading={false}
        minLength={0}
        onSearch={onSearch}
        useCache={false}
        options={[defaultOption]}
      />
    );

    focus(wrapper);
    const menuItems = getMenuItems(wrapper);

    expect(menuItems.length).toEqual(1);
    expect(menuItems.text()).toEqual(defaultOption);
  });
```

### Expected Behavior

The option should be displayed as the default in the input field.

### Actual Behavior

The input field displays empty.

**Comment by ericgio** [comment]
You're not seeing the default option show up because the default input value is filtering it out. Remove the default value and it should work as you expect.

**Comment by bggolding** [comment]
> On 5 Jan 2021, at 14:55, Eric Giovanola <notifications@github.com> wrote:
> You're not seeing the default option show up because the default input value is filtering it out. Remove the default value and it should work as you expect.
> 

Ok, thanks that works for the test script but I wrote a tiny example to try to debug this and it doesn’t work. I was wondering if you could have quick look at this and tell me what I;’ve done wrong? This displays an empty input field and I’d expect it not to be:

import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import {AsyncTypeahead} from "react-bootstrap-typeahead";
import "react-bootstrap-typeahead/css/Typeahead.css";
import './App.css';

interface Item {
    id: number
    name: string
}

const itemLabel = (item: Item) => (
    `${item.id}: ${item.name}`
);

const App = () => {
    const items: Item[] = [{
        id: 1,
        name: "Ben"
    }];
    return (
        <AsyncTypeahead<Item> id="test input"
                              isLoading={false}
                              onSearch={() => []}
                              labelKey={itemLabel}
                              options={items}/>
    );
};

export default App;

**Comment by ericgio** [comment]
@bggolding: As written, an empty input is the expected behavior. Can you please describe your issue in more detail?

**Comment by bggolding** [comment]
> On 5 Jan 2021, at 15:09, Eric Giovanola <notifications@github.com> wrote:
> 
> 
> @bggolding <https://github.com/bggolding>: As written, an empty input is the expected behavior. Can you please describe your issue in more detail?
> 
Sure. What I’m trying to do is use the AsyncTypeahead field to lookup a person’s address from our server, autocompleting as they type the address in. If they have already entered an address, then the initial state of the form should show the existing address. When I pass in a single option to AsyncTypeahead, it doesn’t display their existing address, the field is just empty and I want to show what they’ve already entered.

While I’m asking, I saw in the documentation somewhere that there’s a way of getting an extra entry put at the end of the list of suggestions so that I can include an “Add address …” option. I can’t seem to see that listed in the API documentation though and I haven’t been able to find the page that I saw it on again. Am I imagining things?

Thanks,

	Ben.

**Comment by ericgio** [comment]
> the initial state of the form should show the existing address. When I pass in a single option to AsyncTypeahead, it doesn’t display their existing address, the field is just empty and I want to show what they’ve already entered.

`options` simply specifies the list of possible choices the user can filter. If you want to pre-select one of those options, you need to use `selected` or `defaultSelected` to specify one of those options.

http://ericgio.github.io/react-bootstrap-typeahead/#controlling-selections
https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Usage.md#controlled-vs-uncontrolled

> there’s a way of getting an extra entry put at the end of the list of suggestions so that I can include an “Add address …” option

I believe you're thinking of the `allowNew` option:

http://ericgio.github.io/react-bootstrap-typeahead/#custom-selections
https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#typeahead

**Comment by bggolding** [comment]
> On 5 Jan 2021, at 17:30, Eric Giovanola <notifications@github.com> wrote:
> 
> 
> the initial state of the form should show the existing address. When I pass in a single option to AsyncTypeahead, it doesn’t display their existing address, the field is just empty and I want to show what they’ve already entered.
> 
> options simply specifies the list of possible choices the user can filter. If you want to pre-select one of those options, you need to use selected or defaultSelected to specify one of those options.
> 
> http://ericgio.github.io/react-bootstrap-typeahead/#controlling-selections <http://ericgio.github.io/react-bootstrap-typeahead/#controlling-selections>
> https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Usage.md#controlled-vs-uncontrolled <https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Usage.md#controlled-vs-uncontrolled>I thought I’d tried those but I’ll go back and try again.
> there’s a way of getting an extra entry put at the end of the list of suggestions so that I can include an “Add address …” option
> 
> I believe you're thinking of the allowNew option:
> 
> http://ericgio.github.io/react-bootstrap-typeahead/#custom-selections <http://ericgio.github.io/react-bootstrap-typeahead/#custom-selections>
> https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#typeahead <https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#typeahead>I think the source of my confusion is that the description of allowNew is different on the pages:

	https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md <https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md>
	https://github.com/mesosphere-backup/react-typeahead/blob/master/README.md <https://github.com/mesosphere-backup/react-typeahead/blob/master/README.md>

If I’m displaying a list of objects using labelKey to format them, I’m not sure how I’d use that to put up a (small) form to allow a user to enter a new object. Can you suggest how that might work?

Thank you for your help.

	Ben.

**Comment by ericgio** [comment]
> If I’m displaying a list of objects using labelKey to format them, I’m not sure how I’d use that to put up a (small) form to allow a user to enter a new object. Can you suggest how that might work?

@bggolding: Please limit issues to bugs or feature requests. Usage questions like this are more appropriate for a forum like StackOverflow, where your question can be answered by others and also help those facing the same issue. Thanks!

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead
