### ISSUE TITLE
Disable Dropdown

### ISSUE THREAD

**Issue by ralphvirtucio** [ericgio/react-bootstrap-typeahead#612]
I have a Typeahead component. I'm using it for input component but when I'm typing the dropdown keeps popping up. I put a props of open. Then I got another problem when I put the open in my Typeahead attributes It seems I can't get my data anymore It is not entering in my state. Do the Typeahead have an option of disabling the dropdown but still I get my data?

**Comment by ericgio** [comment]
Hi @ralphvirtucio, thanks for your question. Unfortunately, it's hard for me to help without additional information. Please follow the issue template and include a thorough description of your problem. Code examples or sandboxes are extremely helpful as well. Additionally, unless this is a bug or feature request, please post your question on a forum like [StackOverflow](https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead). Thanks.

**Comment by ralphvirtucio** [comment]
I'm so sorry for that I will post it in the StackOverflow
