### ISSUE TITLE
Typeahead is not picking up changes to defaultValues on an uncontrolled component on serenader

### ISSUE THREAD

**Issue by bggolding** [ericgio/react-bootstrap-typeahead#614]
### Version

5.1.4

### Steps to reproduce

https://codesandbox.io/s/green-cache-9vnx4?file=/src/index.js

### Expected Behavior

When the component is refreshed, the updated defaultValues should be reflected in the selected items in the rendered component.

### Actual Behavior

The selected user at the outset remains selected, updates to the selectedValues in later refreshes aren’t displayed. I would expect the component refresh to update them correctly. This is really biting me in my application where the values to be displayed come back at a later time after an api call returns.

In my sample code, each click on the button adds another user to the list of defaultSelected users which should mean that it is included in the selection. Instead, typeahead component just displays the first selected user and doesn’t include any others that are added. The list of selected users is displayed on the page and the typeahead input should have each of those listed in it.

It looks like the problem might be in core/Typeahead/componentDidUpdate where the “selected” prop is not reflecting up changes that are made to defaultSelected. I can’t quite work my way through the logic there.

**Comment by ericgio** [comment]
Hi @bggolding, thanks for the issue. The behavior you're seeing it expected. [Uncontrolled components](https://reactjs.org/docs/uncontrolled-components.html) don't respond to prop changes the same way as controlled ones do:

> With an uncontrolled component, you often want React to specify the initial value, but leave subsequent updates uncontrolled. To handle this case, you can specify a defaultValue attribute instead of value. Changing the value of defaultValue attribute after a component has mounted will not cause any update of the value in the DOM.

If you use `selected` instead of `defaultSelected`, you should see the behavior you're after.
