### ISSUE TITLE
Clear on blur prop

### ISSUE THREAD

**Issue by caiquecastro** [ericgio/react-bootstrap-typeahead#620]
**Is your feature request related to a problem? Please describe.**
On my app, I want to clear the input if a invalid (no match) value is written. I'm doing it manually for now, but it seems to be a interesting feature.

**Describe the solution you'd like**
Add a boolean prop on Typeahead component, so the input is cleared on blur if it has a invalid value. 

**How is this solution useful to others?**
It seems to be a very common use case, I've seem similar features on other libraries.

**Describe alternatives you've considered**
It's possible to do it nowadays adding an onBlur callback, and calling the clear public method: ref.current.clear();

**Additional context**
N/A

**Comment by ericgio** [comment]
@caiquecastro I think your current approach is the right one. My preference for features like this is to provide a flexible API and let developers add behaviors as needed. This keeps the code simpler and more lightweight, there is less prop pollution, and developers are able to truly customize the behaviors they want.
