### ISSUE TITLE
Customizing hint color

### ISSUE THREAD

**Issue by edemaine** [ericgio/react-bootstrap-typeahead#624]
**Is your feature request related to a problem? Please describe.**
The Hint text color is [currently hard-coded](https://github.com/ericgio/react-bootstrap-typeahead/blob/b12c3f24bda48382c43366e5352194e2c780e8e3/src/components/Hint.js#L158) to `rgba(0,0,0,0.35)`.  While this is often fine, it often doesn't look good in a dark-mode design.  Example where it's nearly invisible:

![image](https://user-images.githubusercontent.com/2218736/108919689-754da600-7601-11eb-93e4-5a71a6834862.png)

**Describe the solution you'd like**
I think it would make sense to move this hard-coded color to the (S)CSS rules. Then it can be overridden by other rules in a standard way (`!important` if necessary). As a `style` rule, it can't be overridden.

**How is this solution useful to others?**
This should help anyone wanting to further customize the look of the widget without having to modify the code itself, just CSS.

**Describe alternatives you've considered**
Another option would be to make the color a prop of `Hint`. But passing it in from all the top-level `Typeahead` etc. widgets seems more complicated? I'd also find it easier to switch the color via CSS rules (using a sometimes-present `.dark` class) than doing it in JavaScript.

If you agree with the CSS approach, I can try writing a PR.

**Comment by ericgio** [comment]
Hey @edemaine thanks for the feature request, seems reasonable to me. For context, the reason the color was originally hard-coded was so the hint would still have basic functionality without any CSS. I suppose the ability to more easily customize the color is the better tradeoff to make. As a workaround, it's possible to create a custom `Hint` component where you could specify the hint color. [Here's a sandbox](https://codesandbox.io/s/rbt-custom-hint-color-624-0y9dd) illustrating how.

**Comment by charleylee** [comment]
I tried something similar, and the color did not render, I think because the inline style that gets applied to the hint field overrides it.

**Comment by charleylee** [comment]
This by the way makes it so you can't make the hint field 508 compliant (the transparency make the color contrast too weak to pass 508 checks.) I use the Axe extension in Chrome to test 508 compliance like this.  This is unfortunately affecting our use of the component.  Fortunately we officially use JAWS to test 508, and not Axe.

**Comment by ericgio** [comment]
> I tried something similar, and the color did not render, I think because the inline style that gets applied to the hint field overrides it.

@charleylee: The sandbox link above includes an example that simply overrides the CSS as described.

**Comment by ericgio** [comment]
I'm going to close this issue, since there are at least 2 existing ways to solve the problem (CSS override or custom component): https://codesandbox.io/s/rbt-custom-hint-color-624-0y9dd
