### ISSUE TITLE
How to restrict MaxSelect in case of multiselect or multiple in AsyncTypeahead?

### ISSUE THREAD

**Issue by ankit2027** [ericgio/react-bootstrap-typeahead#626]
<AsyncTypeahead
                                              emptyLabel={'No options available. Please enter a valid Search Code or Product Name'}
                                              promptText={'Type HS Code or Product Keyword'}
                                              multiple
                                              filterBy={this.filterBy}
                                              id="async-example"
                                              isLoading={this.state.isLoading}
                                              labelKey="label"
                                              minLength={1}
                                              onSearch={e => this.handleSearch(e)}
                                              options={this.state.SearchCodeoptions}
                                              placeholder="Product name"
                                              defaultSelected={SearchCodeoptions}
                                              maxResults={5}
                                              useCache={false}
                                              paginationText={'Load More...'}
                                              // disabled={this.state.searchCodesList.length === 3}
                                              onChange={(e) => {
                                                if (e.length <= 3) {
                                                  this.bindSearchCodeValues(e);
                                                }
                                              }}
                                              selected={this.state.searchCodesList}
                                            />
                                            
                                            
I want to display a error message to the user that selection is not possible for more than 3 items. How can I do that?

**Comment by ericgio** [comment]
Hi @ankit2027, questions like this are more appropriate for a forum like StackOverflow since your question will remain open and potentially help others facing the same issue. Posting there also helps me keep the issues queue manageable and limited to bugs and feature requests. Thanks.

https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead
