### ISSUE TITLE
Add new option for custom match callback

### ISSUE THREAD

**Issue by dmitru** [ericgio/react-bootstrap-typeahead#63]
Now, the way to specify which options should be shown is to pass the `labelKey` prop.

It would be nice if there was an option for passing a callback function that, having received an option, would tell whether it should match the query or not.

Here's my motivation for requesting this feature: suppose I have a list of objects:
```
[
  ...,
  { username: 'Bob', email: 'bob@mail.com' },
  ...,
]
```

and I'd like the matching to occur whenever either username or email matches the query.

Currently, I have to specify another field, say `key: username + email`, and match agains this field.

But now the same key is being shown for selected items! That's ugly, I don't want that, I just want to show the username, but then the matching won't work properly.

--
Another way to solve my particular use-case would be to provide an option for custom rendering (or at least allowing to choose the rendered text) for selected items.

**Comment by ericgio** [comment]
I agree, the component should support this. The way the code is currently structured, what you're asking is a bit tricky to do, so I've been working on refactoring to provide a more flexible API. I probably won't be able to do this one soon, but it's definitely on my radar.

**Comment by dmitru** [comment]
OK, will wait for this in the 1.0.0 release.
Thanks for you effort and keep the great work going. :)

**Comment by ericgio** [comment]
Thank you, and thanks for the great suggestion!

**Comment by ericgio** [comment]
As of v0.9.0, you can use the [`filterBy`](https://github.com/ericgio/react-bootstrap-typeahead#filtering-data) prop to customize how the results are filtered.

**Comment by carlodicelico** [comment]
Ideally, there would be a way to provide a custom match function altogether. In my case, I'd like to be able to use fuse.js instead of the matching function built in here.

**Comment by carlodicelico** [comment]
@ericgio I think that what `filterBy()` is doing is not really the same thing that's being asked for here 🤔

Here, `filterBy()` gets completely replaced by the callback supplied from TypeAhead's props:

```javascript
const callback = Array.isArray(filterBy) ?
      option => defaultFilterBy(
        option,
        text,
        labelKey,
        multiple && !!find(selected, o => isEqual(o, option)),
        {caseSensitive, ignoreDiacritics, fields: filterBy}
      ) :
      option => filterBy(option, text);
```

Personally, I like the default `filterBy()` and would like to benefit from the rest of what it's doing, but just want to replace the `isMatch()` ([here](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/utils/defaultFilterBy.js#L6)) that it's using with my own thing, a call to `fuse.search('foo');`

**Comment by ericgio** [comment]
@carlodicelico: I agree that what you're suggesting is a bit more convenient for some narrow set of use cases. However, given that what you ultimately want — to use your own matching algorithm — is currently possible, I'm not sure it's worth the effort. A lot of the code in `defaultFilterBy` is just checking the data format to understand **how** it should apply the comparison. It doesn't seem to me like you would need that anyway, since I would assume you already know how your data is structured.

**Comment by carlodicelico** [comment]
Okay, gotcha - that makes sense, looking at it more closely. Thanks! 😎
