### ISSUE TITLE
ref.current.clear is not a function

### ISSUE THREAD

**Issue by antoinebattagliotti** [ericgio/react-bootstrap-typeahead#631]
### Version

react-bootstrap-typeahead : ^3.4.7

### Steps to reproduce

const ref = React.createRef();

...

<AsyncTypeahead
    id="async-user"
    labelKey="mail"
    multiple={true}
    options={options}
    **ref={ref}**
    filterBy={filterBy}
    isLoading={isLoading}
    minLength={3}
    onSearch={handleSearch}
    placeholder="Search for a user ..."
    searchText="Searching users ..."
/>

...

<Button onClick={() => ref.current.clear()}>
    Clear
</Button>

### Expected Behavior

It should clear my input when I click on my button.

### Actual Behavior

I have this error : `ref.current.clear is not a function`

When I use a Typeahead the .clear() woks but I need a AsyncTypeahead 

Thanks by advance for any help.

**Comment by ericgio** [comment]
Hi @antoinebattagliotti: thanks for filing this issue. You're using an outdated version of the component and the API has since changed. If you want to continue using v3, you need to call `ref.getInstance().clear()`.

**Comment by pburrows** [comment]
I just came across this too. The bug is in the documentation:
https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md
