### ISSUE TITLE
Is Bootstrap 3.x supported?

### ISSUE THREAD

**Issue by mtosic** [ericgio/react-bootstrap-typeahead#633]
### Version
5.1.4

### Steps to reproduce
Run the sample on:
https://codesandbox.io/s/modest-maxwell-ski6e

I've only replaced bootstrap version from 4.x to 3.3.7 from original sample

### Expected Behavior

I expect to typeahead options render properly in Bootstrap 3.x.
Is it maybe supported in some of the older versions?

### Actual Behavior

Typeahead options not rendering properly:
https://codesandbox.io/s/modest-maxwell-ski6e

**Comment by ericgio** [comment]
Hi @mtosic, thanks for opening this issue. Default support for BS3 was dropped in [v5.0]. You can still make it work by using custom rendering, in this case `renderMenu` to render menu items with BS3 classnames.
