### ISSUE TITLE
AsyncTypeahead truncates queried string at first occurrence of "#"

### ISSUE THREAD

**Issue by tec4** [ericgio/react-bootstrap-typeahead#634]
To start, thank you very much for the package as it is awesome! 

When trying to search for an address, for example, the query string parameter passed to `onSearch` is truncated at the first occurance of the `#` sign. 

Example:  If trying to search `123 Fake St #123` the query parameter passed to the `onSearch` method is `123 Fake St` instead of `123 Fake St #123`.

### Version

5.1.4 (and also on 4.1.0)

### Steps to reproduce

1. Go to Aync Searching section in docs: http://ericgio.github.io/react-bootstrap-typeahead/#asynchronous-searching
2. Open network tab in browser to view API requests that are being made
3. Type `123` in the input and you'll notice the requested API url is: https://api.github.com/search/users?q=123 (as expected)
4. Type `123#omitted` in the input and you'll notice the requested API url is still: https://api.github.com/search/users?q=123 (would have expected the query parameter to contain the full string of `123#omitted` and not `123`)

Also, if you console.log() the query parameter that is passed to the `onSearch` method of `<AsyncTypeahead />` it also returns the truncated version. 

### Expected Behavior

If I type `123#omitted` in the input i'd expect the query parameter to be `123#omitted`. 

### Actual Behavior

The query string is truncated at the first occurrence of the `#` symbol and when I type `123#omitted` I only get `123`.

**Comment by ericgio** [comment]
Hi @tec4, thanks for your question. If I'm understanding you correctly, this doesn't appear to be a bug with the package itself. The reason you're seeing this behavior is that the query string in the example isn't urlencoded, so it's breaking when it gets to the "#". That behavior is determined in the `onSearch` callback by the consumer, however.

**Comment by tec4** [comment]
Hi @ericgio, you are right. It was indeed an issue with not URL encoding the parameter before passing it off to the API request. Thank you very much for your time and direction.
