### ISSUE TITLE
Document renderInput to handle custom input that works with multiple (chip) feature

### ISSUE THREAD

**Issue by charleylee** [ericgio/react-bootstrap-typeahead#636]
### Version
5.1.4

### Steps to reproduce

1. Create a Typeahead component with multiple prop and renderInput prop as documentation shows how. (Optionally wrap it with Hint)
2. Try using the component, notice chips for multi select are not working

### Expected Behavior
I'd like to see some documentation on how to maintain the multiple select features while rendering custom input.  Our reason for needing to customize the input field is so that we can put custom aria labels to support 508 compliance. (Specifically we need the aria-labelledby prop to propagate to the input field, but it'd be nice is all aria labels trickle down to the input field).  This bug could be satisfied with more documentation, or adding more aria features would also satisfy our use case.

### Actual Behavior
Chips for multiple select break using the documented way of using renderInput prop.  Selecting values from the menu does not create a chip for the value. Multiple select appear broken for custom renderInput, at least how it is currently documented it should work.

**Comment by ericgio** [comment]
Hi @charleylee, thanks for opening this issue. You seem to have a couple questions going on here:

> Our reason for needing to customize the input field is so that we can put custom aria labels to support 508 compliance. (Specifically we need the aria-labelledby prop to propagate to the input field

You can pass props directly to the input element via `inputProps`:

```jsx
<Typeahead
  ...
  inputProps={{
    'aria-labelledby': 'some-id',
  }}
/>
```

> Chips for multiple select break using the documented way of using renderInput prop. Selecting values from the menu does not create a chip for the value

I'm not totally sure which example you're referring to, but it's true that [this one](http://ericgio.github.io/react-bootstrap-typeahead/#rendering) only shows the single-select case, which is relatively straightforward. The multi-select case is more complicated, but the best example is probably [the source code](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/components/TypeaheadInputMulti.js) for `TypeaheadInputMulti` as well as [the callsite](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/components/Typeahead.js#L238-L246) in the main Typeahead component.

If you still feel additional documentation would be helpful, I'd encourage you to create a sandbox and submit a PR to add it to [the list of examples](https://github.com/ericgio/react-bootstrap-typeahead#examples).

**Comment by ericgio** [comment]
Unclear what action to take here. Happy to reopen this if OP can provide more information.

**Comment by shekhutsav1962001** [comment]
How we can use paginate with the use of renderMenu for custom MenuItem?
