### ISSUE TITLE
Custom newSelectionPrefix

### ISSUE THREAD

**Issue by mazulo** [ericgio/react-bootstrap-typeahead#637]
**Is your feature request related to a problem? Please describe.**

Yes. I was trying to achieve it with what I figured out to be the wrong approach (more details [here](https://github.com/ericgio/react-bootstrap-typeahead/issues/70#issuecomment-824234394)). So basically my problem is: when I set `allowNew` to true, i need to be able to provide a custom element to be rendered. Even tho the doc says the `newSelectionPrefix`'s type is `string`, I found on the [`code`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/components/TypeaheadMenu.js#L19) that it does accept a node. However, if I pass to it a component with some behavior, it doesn't work properly. So currently I can't:

- Change the element's style
- Change behavior with a custom callback
- Have access to the value of what was typed

**Describe the solution you'd like**

I think we could have something similar with what we have for [`renderMenuItemChildren`](https://github.com/ericgio/react-bootstrap-typeahead/blob/c50cbca4e3f46bfac6e2184e3757d9d6e4884810/docs/Rendering.md#rendermenuitemchildrenoption-objectstring-props-object-index-number) where we would have a callback for customized rendering of this element.

**How is this solution useful to others?**

I believe this would add more customization power to the users that now would be able to fully control the style and behavior on this element. Also would avoid creating a disparity on the design between this specific part and other parts of the component (where we can provide custom components to be rendered).

**Describe alternatives you've considered**

I tried using passing in a custom component with a simple callback for when it's clicked, but it doesn't work properly. Sometimes the callback is called and others it is not called. An example here: https://codesandbox.io/s/rbt-combobox-example-forked-j8ytb?file=/src/index.js

Every time you search for a random word that is not on the list and the `newSelectionPrefix` is rendered, when you click you will won't see the `callback called` showing on every click.

**Additional context**
No additional context to provide, but let me know if I'm missing something that can improve this description.

**Comment by ericgio** [comment]
Hi @mazulo, thanks for the detailed feature request! Can you please help me understand the use case for this feature? In looking at the sandbox example you've provided, I'm not sure what problem embedding a button within the menu item solves.

As far as the behaviors you describe:
> - Change the element's style

You can pass in a custom React node, so it should be fairly straightforward to style that node.

> - Change behavior with a custom callback

The callback you've added to your button works, but the click is also bubbling up to the menu item. You can stop the event from bubbling, but it would seem better to apply the callback to the menu item's `onClick` handler.

> - Have access to the value of what was typed

The value of the input is available from `onInputChange`. Or if they select the item, you can get the selections from `onChange`.

All of these things are also customizable by rendering your own menu using `renderMenu`.

**Comment by mazulo** [comment]
Hey @ericgio thank you for the answer!

Embedding the button might not be the best example, but the idea would be to style it in a way where I would be able to render something like this: " + Add a new color: {value}" - where the `+` would be an icon and the `{value}` is what the user typed being rendered on the side (instead of below it).

From what you're saying, it might be already possible to do what I need with what the lib provides. I might have misunderstood the usage of `renderMenu`. It gave me the impression that it would only apply if I want to change how the menu (or its children through the other functions like `renderMenuChildren`) for the items on the dropdown look like.

Sorry if it sounds dumb, I'm still trying to wrap my head around this whole react world :sweat_smile:

**Comment by ericgio** [comment]
> the idea would be to style it in a way where I would be able to render something like this: " + Add a new color: {value}" - where the + would be an icon and the {value} is what the user typed being rendered on the side (instead of below it).

You can do this using `newSelectionPrefix`: https://codesandbox.io/s/rbt-issue-637-9l4sd
