### ISSUE TITLE
Calling setState() hook seems to clear the field

### ISSUE THREAD

**Issue by cburkins** [ericgio/react-bootstrap-typeahead#639]
When I call "onChange()" and set the state via a React useState() hook, it seems to clear the input hook.  

I created a Sandbox to show a demo of the "bug" (I quote it because I'm guessing I must be doing something wrong here)

https://codesandbox.io/s/vibrant-lehmann-7u7s5?file=/src/App.js

In it's current state, I see the bug, meaning that when I type "choice01" in the box, and hit enter, the input box stays blank.  If I comment out line 30, then it works as expected, meaning that the "choice01" will stay in the input box as a "pill"

**Comment by ericgio** [comment]
Hi @cburkins, you need to pass the new state back into the component using the `selected` prop:

```jsx
<Typeahead
  ...
  onChange={setSearchTerms}
  options={tagListState}
  selected={searchTerms}
/>
```

See [the documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Usage.md#controlled-vs-uncontrolled) for more.

**Comment by cburkins** [comment]
Hmm, yes indeed.  That works.    As I'm learning, I'd love to know why calling a setState() hook causes the TypeAhead component to "forget" it's own state of "selected".

In addition, when I do that, it seems that the TypeAheads component loses keyboard focus, and I must click in it each time I hit enter to complete/select an additional item.

Having previously read the docs, I remember seeing a prop for focus, I'll go read that part again.

**Comment by cburkins** [comment]
I've experimented with a few options include .focus() autoFocus={true} and hideMenu().   Can't quite reproduce the original default behavior that I'm looking for.  Namely, when I click once within the TypeAhead Component, I would like to:

Click in the TypeAhead Component once, then:
1. Type a bit of text
2. Use the arrrow keys to select an option
3. Go back to Number 1

All without having to click in the component again with my mouse.  Something like this animated gif:

![TypeAhead Animated Gif](https://user-images.githubusercontent.com/9342308/115969972-aa954800-a50d-11eb-9768-cf32765f125a.gif)

As soon as I leverage the suggestion of @ericgio , namely using "selected" to feed my new state back into component, I lose keyboard focus.

**Comment by cburkins** [comment]
It feels like when I used the "selected" property to feed the state back into the component, it feels like the component is calling the blur() method.   I  suppose I could counteract that by calling ref.current.focus() within a useEffect(), but that feels sort of hacky ?   Plus, when I do that, the menu is standing open, which doesn't feel great.  Would prefer the menu stay closed until I start typing again.

I can further counteract that by calling current.ref.hideMenu() in the useEffect(), and sure enough, the menu is closed. But then the menu won't open when I start typing for the next suggestion/selection :(

**Comment by cburkins** [comment]
This codesandbox seems to give me the same default behavior, while also being able to update my React useState() hook.  Had to use ref.current.focus() and ref.current.toggleMenu().   Feels a touch complicated, but works.  You have to be slightly careful in codeSandbox since codeSandbox loves to "preview" your code when you pause typing in your source code without saving.   Causes a react compile, which causes a hot refresh, which grabs the keyboard focus from you since .focus() is in your useEffect()
