### ISSUE TITLE
Add new option for custom rendering of selected items inside input field

### ISSUE THREAD

**Issue by dmitru** [ericgio/react-bootstrap-typeahead#64]
It's somewhat related to feature #63, but would be really nice to have on its own.

**Comment by ericgio** [comment]
Can you explain this a bit more? Do you mean instead of simply highlighting the matched text, provide a way for the developer to render matched options however they wish?

**Comment by dmitru** [comment]
Yes, exactly! 

Currently, the component renders selected items either as a labelText strings, and with multiselection, labelText strings enclosed in bootstrap labels with an 'x' button for deselecting.

What I'd love to see here is the ability to render whatever I want in place of those labelText strings. E.g., a user avatar next to his name, another Bootstrap label, a colorized text, etc.

**Comment by ericgio** [comment]
This should already be possible using [`renderMenuItemChildren`](https://github.com/ericgio/react-bootstrap-typeahead#rendermenuitemchildren). Does that not fit your use case? You can try it out in the live example; just check the "Customize menu item children" option.

**Comment by dmitru** [comment]
This is not exactly what I meant. 

Yes, it's possible to customize rendering of available options, but not the already selected options. 
Am I missing something?

**Comment by ericgio** [comment]
Oh I see, you mean a way to control rendering of the selected item(s) within the input, eg: the tokens or even the single-selection state. Yes, that's also on my list. This will probably happen sooner rather than later, at least for multi-selection.

**Comment by dmitru** [comment]
Great! Hope to see this feature then. 
Renamed the issue to make it clearer.

**Comment by ericgio** [comment]
As of v0.9.0, you can use the [`renderToken`](https://github.com/ericgio/react-bootstrap-typeahead#rendertoken) prop to customize rendering of the selected items. Hope that works for your use case.

**Comment by dmitru** [comment]
Perfect, thank you!  👍 
I'll open an issue about custom rendering in single-selection mode, because my use-case requires that too.
