### ISSUE TITLE
newSelectionPrefix does not exist on Typeahead type

### ISSUE THREAD

**Issue by ArturZybin** [ericgio/react-bootstrap-typeahead#640]
### Version

5.1.4

### Steps to reproduce

1. Mount Typeahead component
2. Try to add the "newSelectionPrefix" property to it

### Expected Behavior

Rendered prefix

### Actual Behavior

Typescript shows an error because the property doesn't exist on Typeahead type, it only exists on TypeaheadMenu type

![Screenshot 2021-04-28 173827](https://user-images.githubusercontent.com/57211433/116390895-b607ac80-a848-11eb-8463-7b658aa6a414.png)

**Comment by ericgio** [comment]
Hi @ArturZybin, thanks for filing this issue. Please note that I don't maintain the TS typings; you should file an issue with [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-bootstrap-typeahead)
