### ISSUE TITLE
Not able to add scroll with multi-select

### ISSUE THREAD

**Issue by arvind0364** [ericgio/react-bootstrap-typeahead#643]
Am using a static width and height for the typeahead 
for eg :
.rbt-input-multi .rbt-input-wrapper {
	align-items: flex-start;
	display: flex;
	flex-wrap: wrap;
	width: 92%;
	overflow: hidden;
}
.rbt .form-control {
	height: -webkit-fit-content;
	height: -moz-fit-content;
	height: fit-content;
	max-height: 32px;
	overflow: auto;
	font-size: 13px;
	padding: 3px 7px;
	border-radius: 1px;
}
with this am able to scroll down when I select multiple items.But am not able to scroll up after certain limit.
If I hard press the up arrow of the scroll bar or using the scroll wheel its scrolling to the first added item.
any idea or suggestion to this.?

**Comment by ericgio** [comment]
Hi @arvind0364 can you please provide a sandbox that reproduces your issue? Thanks.

**Comment by ericgio** [comment]
Closing this issue pending additional information.
