### ISSUE TITLE
Multilingual, custom messages

### ISSUE THREAD

**Issue by codinghusi** [ericgio/react-bootstrap-typeahead#647]
**Is your feature request related to a problem? Please describe.**
A more convenient way to translate internal strings / mapping of those strings.
In my provided screenshot you can see whats you get in englisch by default.

**Describe the solution you'd like**
* I'd like something like a global config to change the string mapping
   (I'm not quite sure how to implement that)
* At least providing them all to the top level Typeahead/AsyncTypeahead, so they can propagate proberly.
  (Typeahead Component get the property `translation` that get an object with all string mappings:
`<Typeahead /*...*/ translate={{ notFound: "...", searching: "...",  }} />`

**Images for better understanding**
![typeahead issue](https://user-images.githubusercontent.com/20774263/118862155-a296b100-b8dd-11eb-8306-c3c2a096f0fb.png)

**I researched the codebase and found the following**
"Remove" is located at `components/Token.js` line 40 (It's the only hardcoded string)
"No matches found." is located at `components/Menu.js` line 43
"New selection: " is located at `components/TypeaheadMenu.js` line 42
"Display additional results..." is located at `components/TypeaheadMenu.js` line 43
"Type to search..." is located at `behaviors/async.js` line 59
"Searching..." is located at `behaviors/async.js` line 59

**So at the end you need to propagate the translations through:**
**AsyncTypeahead** provides properties `promptText` for "Type to search..." and `searchText` for "Searching..."
**Menu** provides properties `emptyLabel` for "No matches found."
**TypeaheadMenu** provides properties `newSelectionPrefix` for "New selection: " and `paginationText` for "Display additional results..."

**Comment by ericgio** [comment]
Hi @codinghusi, thanks for your question. I'm not clear on what you're asking for here; the strings you mention all have top-level properties in `Typeahead` or `AsyncTypeahead` that allow you to modify them as you like. I believe the only exception is  the "Remove" label in `Token`. This is included for accessibility, but not actually displayed. There isn't a super-convenient way to modify just the string, but you can pass in your own token component using `renderToken` as a workaround.

**Comment by ericgio** [comment]
Please see the `emptyLabel`, `paginationText` and `newSelectionPrefix` props in the [Typeahead API](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#typeahead) and the `promptText` and `searchText` props in [AsyncTypeahead](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#asynctypeahead).

**Comment by codinghusi** [comment]
Yeah sorry, I didn't do enough research on this project.
Despite that it would be super useful to provide one simple string mapping for all underlying parts.
Sorry for the bad issue description..

**Comment by ericgio** [comment]
@codinghusi: Seems like that should work. Do you have a sandbox reproing your issue?

**Comment by codinghusi** [comment]
Yeah sure, checkout https://github.com/codinghusi/translateable-typeahead
You need to look for `TranslatableTypeahead.js` and `App.js`

**Comment by ericgio** [comment]
I meant a working sandbox on Codesandbox or something similar. Sorry I wasn't more clear.

**Comment by ericgio** [comment]
There's nothing inherently wrong with the code above; the problem would be in your calling code and making sure `onSearch` is properly passed in and handled.

**Comment by ericgio** [comment]
Given that translation is already supported, it's unlikely I'll add a special API for it. Closing for now.
