### ISSUE TITLE
MenuItem overwrites href prop with "#"

### ISSUE THREAD

**Issue by dstop75** [ericgio/react-bootstrap-typeahead#649]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-bootstrap-typeahead@5.1.4` for the project I'm working on.

Problem: MenuItem overwrites href prop with "#". (We want the browser link preview to reflect the link in the menu item, because selecting it will actually navigate there, and not to the top of the current page as indicated by "#".) Please consider including this quick fix.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-bootstrap-typeahead/es/components/MenuItem.js b/node_modules/react-bootstrap-typeahead/es/components/MenuItem.js
index 00c67b6..fdc73f5 100644
--- a/node_modules/react-bootstrap-typeahead/es/components/MenuItem.js
+++ b/node_modules/react-bootstrap-typeahead/es/components/MenuItem.js
@@ -21,7 +21,7 @@ var BaseMenuItem = /*#__PURE__*/React.forwardRef(function (_ref, ref) {
         active: active,
         disabled: disabled
       }, className),
-      href: "#",
+      href: props.href || "#",
       onClick: function onClick(e) {
         e.preventDefault();
         !disabled && _onClick && _onClick(e);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ericgio** [comment]
Hi @dstop75, thanks for filing this issue! Your suggested change seems reasonable; would you mind opening a PR for it?

One thing to note is that `MenuItem` is provided for convenience and isn't necessarily meant to address every use case. For specific behaviors that aren't supported out of the box, consider creating your own menu item using the [`useItem` hook or `withItem` HoC](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/behaviors/item.js).

**Comment by ericgio** [comment]
Added in v5.2.0
