### ISSUE TITLE
Add an option / method for bringing the focus to the component

### ISSUE THREAD

**Issue by dmitru** [ericgio/react-bootstrap-typeahead#65]
Maybe it could be a boolean `defaultFocus` option, or a method of the component that I could call with a React reference to the rendered component.

**Comment by ericgio** [comment]
This should also already be possible with [`focus()`](https://github.com/ericgio/react-bootstrap-typeahead#focus). I suggest reading through the documentation a bit and trying out the example :) Let me know if anything is confusing or could be clarified.

**Comment by dmitru** [comment]
Oh, sorry about this one. Thanks, I'll try that.
