### ISSUE TITLE
Not able to use Tab key to select a result when filterBy option is active

### ISSUE THREAD

**Issue by daniel-carrillo-globant** [ericgio/react-bootstrap-typeahead#653]
### Version
5.1.4

### Steps to reproduce
Having an array as `filterBy` makes tab stop working when selecting an option, and it's not even hinted.
`filterBy={['name', 'abbr']}`

### Expected Behavior
This is how it works if the name is provided. The first option is hinted and it's selected if Tab is pressed.
![image](https://user-images.githubusercontent.com/66327409/123890658-33b96880-d91d-11eb-84eb-ea5a370bedf6.png)

### Actual Behavior
Typeahead input when filtered by state "abbreviation" not being hinted and hitting tab doesn't select option, even if there's only one.
![image](https://user-images.githubusercontent.com/66327409/123890357-aece4f00-d91c-11eb-8d49-4ec44c118692.png)

**Comment by daniel-carrillo-globant** [comment]
@ericgio I'm so sorry for bothering again, but I took the liberty to reach you out again for further questions regarding how Tab works. Again, there's something I might be doing wrong. Thank you in advance!

**Comment by ericgio** [comment]
Hey @daniel-carrillo-globant, that's the expected behavior. The hint only shows up when the input value matches the initial substring of the first result. I'm not sure what the hint would be in your "abbreviation" example, maybe "ncarolina"?

Side note: it looks from your screenshot like you were able to implement BS5 floating labels, which is pretty cool!

**Comment by daniel-carrillo-globant** [comment]
Gotcha, thank you very much @ericgio 

So is there a way you'd recommend to do this if we want Tab completion to work even if you're filtering by another key? Even if it doesn't match the first letters exactly?

**Comment by ericgio** [comment]
I can't think of a great way to achieve the behavior you're after. You could add a keydown handler to the typeahead and check to see if the input value matches any of the abbreviations. You're essentially bypassing the internals of the component though.
