### ISSUE TITLE
Virtual keyboard and Chrome

### ISSUE THREAD

**Issue by GABuryan** [ericgio/react-bootstrap-typeahead#657]
Hi, no one had any problems with the virtual keyboard in Chrome on the tablet? For me, it overlaps the input field if the element is at the bottom of the screen.
Thanks.

**Comment by ericgio** [comment]
Hi @GABuryan, is this issue a feature request or a bug? Can you please provide more information as requested in the issue template? Thanks!

**Comment by ericgio** [comment]
Closing pending additional information.
