### ISSUE TITLE
Diacritics in non-Latin alphabet strings are not stripped

### ISSUE THREAD

**Issue by ianatha** [ericgio/react-bootstrap-typeahead#659]
### Version
5.2.0

### Steps to reproduce

1. Load up [https://codesandbox.io/s/gracious-dust-70ygq?file=/src/index.js](https://codesandbox.io/s/gracious-dust-70ygq)
2. Type "μερα" (note no accent on lowercase epsilon)
3. Note that option `"Καλημέρα"` is not displayed

### Expected Behavior

`"καλημερα"` (charcodes: `[954, 945, 955, 951, 956, 941, 961, 945]`)

should match

`"καλημέρα"` (charcodes `[]`)

when `stripDiactrics` is `true`

### Actual Behavior

`"καλημερα"` did not match `"καλημέρα"`

### Suggestion
Using something like `str.normalize("NFD").replace(/[\u0300-\u036f]/g, "")` may work better than the current `stripDiactrics`, although it's [not supported in Internet Explorer and WebView Android](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize#browser_compatibility).

**Comment by ericgio** [comment]
Addressed in v6.0.0-alpha.1
