### ISSUE TITLE
AsyncTypeahead does not add id attribute to the rendered input element

### ISSUE THREAD

**Issue by norcino** [ericgio/react-bootstrap-typeahead#662]
I am using **AsyncTypeahead**, if I don't provide an "id" argument, I can see a console error in the browser, stating:

> Warning: [react-bootstrap-typeahead] The prop `id` is required to make `Typeahead` accessible for users of assistive technologies such as screen readers.

To remove this warning message which is annoyingly shown as error, I provide an id, and this fixes the problem.
However the dom elements generated by the component do not contain the 'id' attribute, so it is useless to provide it.

I was expecting to see the attribute added to the main input element.

**Comment by ericgio** [comment]
Hey @norcino, thanks for the question. It's not useless; the id is applied to the menu to make the component accessible for users needing screen readers or other assistive technologies. If you need to pass an id to the input itself, you can use `inputProps`:

```jsx
<Typeahead
  ...
  inputProps={{
    id: 'my-input-id',
  }}  
/>
```

**Comment by norcino** [comment]
Thank you @ericgio, the snippet provided did add the id.
But what do you mean with 

> "the id is applied to the menu to make ..."

In the dom I cannot find anywhere the value assigned to "id".

Thanks

**Comment by ericgio** [comment]
As mentioned, it's applied to the menu, which must be open to show up in the DOM:

![image](https://user-images.githubusercontent.com/2978513/129589088-71f3b892-8dad-4c93-a0f7-994de070abc4.png)
