### ISSUE TITLE
When only 1 item available whose length exceeds the menu panel, jagged bottom line shown

### ISSUE THREAD

**Issue by eugeneborodkin** [ericgio/react-bootstrap-typeahead#664]
When only 1 item is available in the React Bootstrap Typeahead menu, and its length exceeds the menu panel's length (the string requires a horizontal bar), there appears to be a jagged line at the bottom of the menu panel running across half the control.

Screenshot:
https://postimg.cc/zH8nXXBK

Note: I also think this is related to other HTML elements *behind* the Typeahead control "seeping through." If the menu box covers some buttons or HR elements, those elements "seep through" the bottom pixels of the menu box, and that could be where this issue comes from.

**Comment by ericgio** [comment]
Hi @eugeneborodkin, thanks for the report. I think this is expected and not a bug. The menu has a translucent border around it, so elements behind the menu may show through:

![image](https://user-images.githubusercontent.com/2978513/132144432-da22c07d-6dd1-4176-beb1-aac90888d973.png)

![image](https://user-images.githubusercontent.com/2978513/132144453-0eb4907e-6e80-4e82-98d0-8bae3c0b0a9d.png)
