### ISSUE TITLE
Typeahead menu displaying options horizontally. 

### ISSUE THREAD

**Issue by wesley3295** [ericgio/react-bootstrap-typeahead#667]
### Steps to reproduce
copy paste from example page "basic typeahead component

### Expected Behavior

Them menu displays vertically
### Actual Behavior

![devtools](https://user-images.githubusercontent.com/67900324/131820400-fee943da-3ca6-41b2-b85e-baabeb10a4f7.png)
![dropdown](https://user-images.githubusercontent.com/67900324/131820401-72bd8cbb-5fbe-4ea4-b741-fb04dd5dae24.png)
![typeahead](https://user-images.githubusercontent.com/67900324/131820403-ef24998e-dd5b-4205-981c-f2f5525a56c4.png)
I am a Junior developer, so this is probably something wrong on my end, but I just wanted to use the component because it was easy to implement. I am currently contributing to an open source project and I was hoping if you could tell me why my options are displaying horizontally rather than vertical. I copied and pasted your exact code from the examples. Thanks for the help!

**Comment by ericgio** [comment]
Hi @wesley3295, thanks for the question! I'm not sure what's going on but it looks like some CSS is not loading correctly. Not sure which version of Bootstrap or the typeahead you're using, but if you're using BS3, then the latest version of this library will not work correctly out of the box. You'll need to use the `renderMenu` prop to customize how the menu items are rendered so they have the right markup and classnames for BS3. Hope that helps!

**Comment by wesley3295** [comment]
I believe I using React Bootstrap 5 and the version that downloads with npm install for Typeahead

**Comment by ericgio** [comment]
Bootstrap 5 doesn't produce that behavior. I'm pretty sure you're using Bootstrap 3.

**Comment by wesley3295** [comment]
![bootstrap 5](https://user-images.githubusercontent.com/67900324/132042919-af2b77af-837c-4e83-ac90-eb00091ec0a2.png)
This is my package-lock im pretty sure this is beta bootstrap 5

**Comment by ericgio** [comment]
You're looking at the React-Bootstrap package, which [doesn't include the Bootstrap CSS](https://react-bootstrap.github.io/getting-started/introduction#stylesheets). The CSS is part of the Bootstrap package, or you may be importing it via CDN.
