### ISSUE TITLE
getInstance() is undefined in ref to component due to outdated react-onclickoutside dependency

### ISSUE THREAD

**Issue by dmitru** [ericgio/react-bootstrap-typeahead#67]
In the docs, it says to use `this.refs.typeahead.getInstance()` to access the component; however this gives an error since `this.refs.typeahead` does not have a method `getInstance`.

**The reason** for it is the outdated dependency on react-onclickoutside: `^4.1.1`. This version doesn't have the method `getInstance` yet.

**Proposed fix**: update dependency version of `react-onclickoutside` to the latest.

PS: Sorry for just opening an issue and not creating a pull-request.

**Comment by ericgio** [comment]
Which version of the package do you have? The dependency was updated to `^5.3.0` in 0.6.4, and then to `^5.3.3` in v0.8.4, so this shouldn't be an issue if you've upgraded.

**Comment by dmitru** [comment]
Sorry, I actually used an older version. It's my bad.
