### ISSUE TITLE
Empty the field if nothing matches

### ISSUE THREAD

**Issue by HugoWeb23** [ericgio/react-bootstrap-typeahead#673]
Hello,

Is it possible to add a prop to allow the field to be emptied if nothing matches?

Because when you leave the field, you might think that Chicaco is selected when he is not.

https://user-images.githubusercontent.com/22978990/134816377-5bcc2cd7-8972-46a7-b442-37282bd515b7.mp4

The field should behave like this

https://user-images.githubusercontent.com/22978990/134816547-8aae3a19-6af1-456b-9055-6f02aac62d2f.mp4

Thanks.

**Comment by ericgio** [comment]
Hi @HugoWeb23, thanks for the feature request! What you want is already possible using the [`clear` method](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md) inside `onBlur`:

```jsx
<Typeahead
  ...
  onBlur={() => {
    if (!selected.length) {
      typeaheadRef.current.clear();
    }
  }}
  ref={typeaheadRef}
/>
```

Try it out: https://codesandbox.io/s/rbt-673-clear-invalid-values-2kmil

**Comment by HugoWeb23** [comment]
Thank you for your reply.

With only one field it works well but with an array of fields it gets complicated. (I am using react-hook-form)

I find that this should be the default behavior or let the developer choose whether or not to implement it via props.

**Comment by saivivek116** [comment]
@ericgio The above logic will not work in the case of multi-select can you suggest an alternative solution in that case?
