### ISSUE TITLE
There is a discrepancy between the typescript types and the actual code usage for Tokens and onRemove

### ISSUE THREAD

**Issue by ctgbarcalow** [ericgio/react-bootstrap-typeahead#680]
### Version
5.2.1

### Steps to reproduce
Passing the onRemove from props of renderToken work fine when when passed directly, but if I try to use an inline function it doesn't work, and all everything I see points to the wrong usage. This might just be a typescript / documentation issue.

![onRemove](https://user-images.githubusercontent.com/85701261/141031766-97d279e8-5e9e-4d28-bade-c71e9bf6880b.png)

**index.d.ts** show that use use onRemove without an argument. This differs from the source code.
[onRemove in index.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/d02f22454c83d8e76cad09aed0c2baaa56205725/types/react-bootstrap-typeahead/index.d.ts#L515)

If you pass onRemove={props.onRemove} things work okay, but if you try to intercept it with an inline function and call onRemove nothing happens, and the object remains.

```
     renderToken={(option, props, index) => {
        return (
          <Token
            key={index}
            //onRemove={props.onRemove} // This line works, the one below does not
            onRemove={() => {
              if (onRemove) onRemove()
            }}
```

### Expected Behavior
I expected the item to be removed after calling 
`props.onRemove()`

### Actual Behavior
Nothing is removed, the solution, is to override `props.onRemove` (in typescript) to a function equivalent to OptionHandler. And then call it with the option. Then, the selected token will be removed
```
      renderToken={(option, props, index) => {
         return (
          <Token
            key={index}
            onRemove={() => {
              let remove: (obj: any) => void | undefined = props.onRemove as any;
              if (remove) remove(option);
```

**Comment by ericgio** [comment]
Hi @ctgbarcalow, thanks for filing this issue! You're absolutely correct that the types are wrong; they're written and maintained by a third-party, so some discrepancies have popped up over time.

`onRemove` actually passes `option` as an arg, so your solution of treating it as an `OptionHandler` is correct. v6 of this package has been re-written in TS and [that's how it's typed](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/src/behaviors/token.tsx#L25).

So the right solution is:

```jsx
<Typeahead
  ...
  renderToken={(option, props, index) => (
    <Token
      key={index}
      onRemove={(option) => {
        props.onRemove(option);
      }}>
      {option.label}
    </Token>
  )}
/>
```

**Comment by ericgio** [comment]
Closing this issue since there's no further action to be taken in this repository. I'd suggest filing an issue or [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request) over at DefinitelyTyped to improve the typings if you want to continue using v5. Otherwise, upgrading to v6 should provide the correct types. Thank you!
