### ISSUE TITLE
useRef().current in Bootstrap v17.* returns HtmlDivElement instead of WrappedTypeahead - *.current.clear() does not work anymore

### ISSUE THREAD

**Issue by Merx** [ericgio/react-bootstrap-typeahead#681]
### Version
"react-bootstrap-typeahead@6.0.0-alpha.4" (same for the 5.7 version)
with react v17.*

### Steps to reproduce
const ref = useRef(null);
<Typeahead type="text" ref={ref} ... /> 
<Button onClick={() => { ref.current.clear() }} />
// When pressing on the button, it does not clear but instead says ref.current.clear is undefined

### Expected Behavior
I want to call ref.current.clear() and this should clear the input.

### Actual Behavior
ref.current.clear() is not a function, because ref.current is now a HtmlDivElement and not a WrappedTypeahead as before

**Comment by ericgio** [comment]
Hi @Merx, thanks for filing this issue! I'm unable to repro the problem as you describe ([see sandbox](https://codesandbox.io/s/admiring-haibt-ynf13?file=/src/index.js)). Can you please provide more detailed repro steps or a sandbox reproing the issue? Thank you!

**Comment by Merx** [comment]
@ericgio  Thank you very much for your fast response and sandbox. In the meantime I found out that the problem seems to be the encapsulating OverlayTrigger of react-bootstrap. Once I remove that OverlayTrigger, everthing works.
Here is the example: https://codesandbox.io/s/priceless-satoshi-qek6b?file=/src/index.js 
See console output of ref.current. Once OverlayTrigger is removed then it works again.
I am not sure if this is an issue with Typeahead or OverlayTrigger and I would leave that to you if this issue should be closed or not. But one more question: Should I raise an Issue with react-bootstrap regarding this matter?

**Comment by ericgio** [comment]
Ah that makes sense now. `OverlayTrigger` [clones its child element](https://github.com/react-bootstrap/react-bootstrap/blob/v2.0.3/src/OverlayTrigger.tsx#L299) and passes a ref, which is why you're seeing the behavior you describe. This seems like the expected behavior and not a bug in either library. One solution is to pass a render function to `OverlayTrigger` instead of a child element so you can control how the ref is applied. Good luck!

**Comment by Merx** [comment]
@ericgio Thank you very much, that seemed to do the trick!
Instead of 
<OverlayTrigger ...><Typeahead ... /></OverlayTrigger>
I now use
<OverlayTrigger children={_ => (<Typeahead ... />) ... />
and the ref is again an Typeahead instead of some HtmlDivElement
