### ISSUE TITLE
Ability to add search icon to the input field

### ISSUE THREAD

**Issue by kandaj** [ericgio/react-bootstrap-typeahead#682]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**How is this solution useful to others?**
Does your feature address a common use case? Does it provide a more generalized way to solve the type of problem you're encountering?

**Describe alternatives you've considered**

**Additional context**
Add any other context, sample code, or screenshots about the feature request here.

**Comment by ericgio** [comment]
Hi @kandaj, the feature you're requesting is already possible in several different ways, including applying a background-image to the input or adding an image element as a child of the Typeahead. If you have something more specific in mind, please complete the template explaining your request in detail. Thanks!

**Comment by kandaj** [comment]
@ericgio Thanks for reply. I'm trying to add search icon inside the input on the left. Is it possible to add it?. if so could you please guide me to the documentation or example?

**Comment by ericgio** [comment]
@kandaj there are multiple ways to do what you want, as noted above. This [example](https://codesandbox.io/s/rbt-custom-aux-components-gn3kn) may be helpful. Good luck!
