### ISSUE TITLE
Loading spinner being placed inside the input causes render issues

### ISSUE THREAD

**Issue by maddieijams** [ericgio/react-bootstrap-typeahead#688]
### Version

^5.2.0

### Steps to reproduce

1. Restrict the width of the async typeahead to something small (300px)
2. Type or paste in a search term that exceeds the width of the typeahead
3. The text overlaps the loading spinner since it is placed inside the input

### Expected Behavior

I would expect that i could use InputGroup.Append from bootstrap to place the spinner outside of the input but this is not successful

### Actual Behavior

Long text search in a small input gets cut off by the loading spinner

**Comment by ericgio** [comment]
Hi @maddieijams, thanks for the report. Can you please provide a working code example reproducing the issue? I'm not able to repro; with a narrow input and long search string, I see the text get cut off by the loader as expected:

![image](https://user-images.githubusercontent.com/2978513/149677008-5f8a3bfd-a4d4-4d01-8661-c229099c8073.png)

**Comment by maddieijams** [comment]
@ericgio My apologies! It turns out we were somehow overriding the .has-aux class. I will close this issue.

Thanks for this awesome library!
