### ISSUE TITLE
Update README to clarify proper way to `import` vs. `require`

### ISSUE THREAD

**Issue by d-kostov-dev** [ericgio/react-bootstrap-typeahead#69]
Hi guys.

I installed the package today (17 Aug 2016) and it was not working for me. I was getting following errors:

Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `MY_COMPONENT_HERE`.

Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `MY_COMPONENT_HERE`.

I was requiring it like this: "**var Typeahead = require('react-bootstrap-typeahead');**"
Changed it to: "**var Typeahead = require('react-bootstrap-typeahead').default;**" and everything is working fine now. 

This may be a problem on my side tho...I am not sure.

**Comment by ericgio** [comment]
Hey, thanks for the report and sorry you had issues with that. You do indeed need to add the `.default` if you're using the `require` syntax. The component is written using ES6 modules and as of version 6, [Babel no longer implicitly selects the default in a CommonJS context](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0).

I'll update the documentation to make that more clear.

**Comment by ericgio** [comment]
Updated in v0.8.5
