### ISSUE TITLE
Editable custom selections

### ISSUE THREAD

**Issue by alexandernst** [ericgio/react-bootstrap-typeahead#690]
**Is your feature request related to a problem? Please describe.**
I saw the "custom selections" in the docs and I'm wondering if there is a way to edit a "selection" once it has been "added" to the list of selected items.

**Describe the solution you'd like**
If there isn't a way to edit the newly created selections, I'd like to propose something like this: https://seawind543.github.io/react-token-input/#example-customize-label 

A single click on the "selection" converts it into an editable input.

**How is this solution useful to others?**
Not being able to edit a selection, but having to delete it and re-create it again (maybe in order to fix a typo?) it a really bad UX. I believe the implementation of this FR will improve UX.

**Describe alternatives you've considered**
N/A

**Additional context**
![Cursor_y_React_TokenInput](https://user-images.githubusercontent.com/89727/150043929-2ed3d008-1dbc-4409-a8ba-0e40c4eba502.png)

**Comment by ericgio** [comment]
Hey @alexandernst thanks for the feature request. Unfortunately, custom tokens aren't something I plan on including as part of the package at this time. I think deleting the token and re-adding it is a reasonable UX for most scenarios. For developers like yourself who may want a different implementation, you can create your own custom token with the [`useToken` behavior](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/API.md#usetoken--withtoken) and [render it using the `renderToken` method](http://ericgio.github.io/react-bootstrap-typeahead/#rendering).
