### ISSUE TITLE
Close button design is breaking!

### ISSUE THREAD

**Issue by ErShakirAnsari** [ericgio/react-bootstrap-typeahead#692]
Hello there,
I'm new ReactJS and may be I missed something not sure!!
But I'm facing some design issues in close button.

![autocompelete-erro](https://user-images.githubusercontent.com/7697097/151696597-08159fb4-0478-4522-a6fb-47e50d24bc10.png)

**Comment by ericgio** [comment]
Hi @ErShakirAnsari, thanks for filing this issue. When opening issues in this, or other repositories, please be sure to provide detailed and relevant information regarding your problem. A sandbox with a minimal working repro case is an ideal solution to help with debugging.

Based solely on your screenshot, it looks like you may be using Bootstrap 5 CSS, which isn't yet fully supported by this library. More specifically, Bootstrap 5 introduced breaking changes to the close button component. Please check out issue #622 for more information. Thanks!
