### ISSUE TITLE
AsyncTypeahead onSearch provides different data on big arrays

### ISSUE THREAD

**Issue by singladno** [ericgio/react-bootstrap-typeahead#694]
### Steps to reproduce

Using AsyncTypeahead with following props:

<AsyncTypeahead
      options={options}
      isLoading={isLoading}
      onSearch={onSearch}
      labelKey={(option) => {
          console.log(option);
          const res = isObject(option) ? option.label : option;
          return res.toUpperCase();
        }}
      className={size}
      renderMenu={renderMenu}
      onInputChange={onTextChange}
    />

This is options I set in onSearch callback:

[
  '9b4462be-a005-4d16-b291-403844f296d5',
  '940678c1-34f8-49f3-a047-9f3dadf509a4',
  '6033a725-6051-4882-86ec-58fbf8404916',
  '44976fd0-3698-4092-b9b3-b6b21b22aa0e',
  '795382c5-abb1-40b2-90fa-964c70ebb8d8',
  '229e13e0-f408-4922-9cb8-64eb4320538f',
  '73215bbb-d4ab-4091-9b3b-ad1b7e399cd7',
  'fe7c6c61-f562-4041-a1b1-a2e5f971ab61',
  '9bf89be6-0c4b-4e2f-b7d5-6f5668a4010d',
  'f94f2da1-2bc2-4051-a9fe-9cc10611fd8c',
  '966c34ae-4023-4ba5-80b0-d25981018d69',
  'ac06fbc5-b0da-4add-bce9-3037b4403cb8',
  '717d0bbf-38d0-40c8-8e1d-8061729a169f',
  '0406beec-6c92-4b88-beb4-46a39f1686d1',
  'ff609709-0ca8-4979-90a9-a16676f840ee',
  '3bd40fb9-0470-4101-b763-382c0a2404bf',
  '846ff0c2-8469-450c-b69c-cb740246a31d',
  'b4a337dd-404b-4d83-a1b0-12273b55e2e7',
  'cef68640-c650-4f0e-94b2-a526cfd54b4c',
  '81ebb057-11ae-4910-9a44-b63f5f0440d2',
  '35e72d40-1f1b-4971-af24-cbceb69c5d23',
  '337efa1c-69fa-4012-b561-096a950e36a4',
  '22250e97-b051-40ea-95fc-a1ba099eae81',
  '5405ab6a-e8e8-4fdd-9777-cc27c4115f64',
  '840a4302-c2b9-42ec-82f4-b1283060e615',
  '02e5cb98-84db-4019-9a06-278e87847e0c',
  '731195af-814e-4aaa-9408-7d0a7a348957',
  '69b532a9-2e69-4035-a969-b9a08b0d05eb',
  '8beb9748-b9db-402b-b070-ec9a8b0e3fb5',
  'c82e888e-8e6c-4610-9a7b-14040996b67c',
  '10b219cb-dd15-40af-bb4c-3b40c4906da6',
  'ec7ecd3b-f940-4d7b-b6c8-4c5e2cb1aefc',
  'cb6de406-984f-44a7-bab5-df88cd3b2270',
  '0bee8266-b9bd-4da6-b254-11f40aa5151c',
  '4047161f-7685-4176-b8f5-0ee1d9673233',
  '0c6c29e6-e87b-409c-92b2-5b31087fbc47',
  '1b8519ac-c19c-40db-ad60-15165d4aadc1',
  '570d87e3-fe79-4068-a3a0-9d842f85bd18',
  'ccb542e2-a484-46f8-ba56-4001b074e5f2',
  'c709d3c7-751b-440e-a979-beb055193c70',
  '551f1d4f-48dd-4c40-851b-8e97e86b7096',
  'cca8c9f1-e9e7-4407-a272-fa8ecabddc9f',
  'bf2b1692-8792-488a-8240-6ae81d4b9852',
  '3404a3cd-80a3-4f54-850c-1464d12b2369',
  'f3a00645-ec89-4140-9866-7cff5d1affea',
  'e6402ae4-2139-4b19-924c-48bd0d6aba21',
  '40499d6b-2d5d-4188-9f62-259f888443d7',
  'd8294c2e-802c-4c38-b95f-4a38bc40a7ec',
  '7fcded4f-15b0-4708-b48f-baf077b2ea40',
  '406714bb-5800-45bd-8381-bc3af136fa40',
  '55485f75-fd40-4ef8-b6d9-6fcedea13742',
  '27e5b20a-d94a-401c-b306-a1c3a71faa1f',
  '6130daa0-9d19-4e08-940f-46b33d4b818d',
  '97412b05-40c8-49f2-a7a1-6dc2954dc14a',
  '4b15ce38-9c88-4086-a631-a11037a1f212',
  '9d978033-2912-4c35-92d0-7c624038a7cf',
  '7407f812-3348-48ec-acd4-3c268873d8f3',
  '07296168-40d2-439e-8e88-04f57ed4ce07',
  'd26af265-d0ba-408e-87c0-37cef18c42ac',
  'd2b56227-691a-4038-b95a-5691cdee36dd',
  'ea88aaa0-2b01-4093-8c68-c2fc50b562fa',
  '9797d3ea-777e-4000-8bf1-76b535b00ad8',
  '717d4052-3d2d-4f43-80f8-8a0bac4f0a63',
  '69722c87-89b1-4a43-bcc2-fcb1940ad8c6',
  'a0cd0a58-7a18-404a-8da7-8ee11122c2cc',
  'c46f7367-403d-4814-8a0a-7383794ec7e3',
  'ce9f2168-1b3f-40df-b27e-dfa1a4317248',
  'afda1d43-4ab1-4728-81bd-5f40ac25ab49',
  'd99406f8-3d35-4d3d-9820-c0465f628925',
  '1c1360b1-40a4-4a6b-af6b-3377503157c9',
  '896340f3-4b02-4fbe-8184-3cdac231f849',
  '687402bc-113b-4c3d-8d30-c11a5f08dd1b',
  'f8d96fff-7f5d-4067-ba4e-e70520e81c8d',
  '435967e9-677e-406a-b6b8-04ca4169fac3',
  '9983a591-6e71-40fd-a30d-8bae54381dbd',
  '00efe3d9-8e62-409a-8b45-4155f9105f04',
  '71f5f401-987c-4216-96e4-8d70778e7844',
  '53103bc2-8693-47ad-8f65-7d0e80664017',
  '1c040609-3b94-4de5-a08e-f4d2d70fb374',
  '789a3409-4377-4e6b-9cb0-00ae6a8caa86',
  'f7d8091c-b44a-47d2-81ba-1002b640b5d4',
  '35fe4d33-d88f-4149-b40e-027ac321f924',
  '5ce24220-ebd6-4779-8352-4a40df0dfc61',
  'c24de6f5-840d-4478-a851-1c122157d007',
  '83e85d2f-78ec-402a-bba6-18bd264ecda9',
  '0e10d96d-8c0f-4125-9407-524449348a10',
  'a76ee814-3bfb-44dc-bb7f-b9164067d7b9',
  '61508249-7406-405d-b91d-837f79e0f4c1',
  '1ed94c0d-ba95-4884-92f2-073e45e89401',
  '11169bec-de3c-40e4-a0d0-57efab56b797',
  'e0538d4d-7978-4057-b7d2-219c12ab422f',
  '12674a50-71e2-440d-85a8-b43c6f6530fc',
  '1be8406f-ed1c-4af0-ae1f-f6e8029e8638',
  'f0400cda-3523-4888-ad08-d98aeb553d76',
  '628441da-1c40-465e-9eb6-edb7c3141d0a',
  '43ce6003-2096-45be-9e40-d9a10ecb63f7',
  '010cb111-4c46-40fb-8b6e-5c8d0d305e9a',
  '1d246c40-db30-46f8-9e57-ab44caac6713',
  '47eec9f3-3456-4407-9e7c-ca2382b2dd2b',
  'f989445c-31db-49dd-b3b1-92cc2963409b',
  'aad0428f-7401-4eb1-8d81-5279c28ebaff',
  'd7a65289-b967-40d6-a7b7-1d493e0427b6',
  '98903857-992f-43a6-8155-1e5beb40a78b',
  '2c26ec1d-4081-4052-bb40-d7b9fff7085a',
  '8e00e530-fa93-4033-b32e-68f59f51e34b',
  '083a3f51-a475-450e-9fe4-bcbc32914073',
  '469f52a2-9ef5-4090-8c9b-055aa86f91f5',
  'bc24019d-cc9d-4bdd-9d5c-534449144a66',
  '3ef12046-b753-40df-8790-ab575548995c',
  '0a16b1e5-3385-40c2-87bb-58d9515637bb',
  '5689cf89-f409-4a58-aa91-ce9c8d330aad',
  'cab0453e-b414-49f0-abf5-de3daf340eca',
  'feb586b8-fcab-4015-8512-658fc177548e',
]

But in labelKey function I have array like this:
<img width="697" alt="Screenshot 2022-02-07 at 17 38 12" src="https://user-images.githubusercontent.com/53875415/152762801-a71f9ef3-7706-4243-9e40-fcbb569dfea3.png">

In the end of array I've got object.

### Expected Behavior

Array provided to onSearch has arrays of strings as they were set in onSearch callback

**Comment by ericgio** [comment]
Hi @singladno, thanks for filing this issue! The object you're seeing in your results is the [pagination option](http://ericgio.github.io/react-bootstrap-typeahead/#pagination). Normally the component will handle this, but you're using `renderMenu` so you need to handle it yourself. You can just filter it out if you want or turn off the pagination functionality with `paginate="false"`.

**Comment by shekhutsav1962001** [comment]
@ericgio 
can you Please tell me how to handle it inside in renderMenu ?????

**Comment by ericgio** [comment]
@shekhutsav1962001: I'd suggest having a look at [`TypeaheadMenu`](https://github.com/ericgio/react-bootstrap-typeahead/blob/main/src/components/TypeaheadMenu/TypeaheadMenu.tsx#L85) to see how it's used there. It should be pretty straightforward as long as you're using the `MenuItem` component provided with the package.

**Comment by shekhutsav1962001** [comment]
> @shekhutsav1962001: I'd suggest having a look at [`TypeaheadMenu`](https://github.com/ericgio/react-bootstrap-typeahead/blob/main/src/components/TypeaheadMenu/TypeaheadMenu.tsx#L85) to see how it's used there. It should be pretty straightforward as long as you're using the `MenuItem` component provided with the package.

@ericgio  Thanks Man !!  It helped me a lot .
