### ISSUE TITLE
Selected value as array of strings instead of objects when array of objects given as options

### ISSUE THREAD

**Issue by saivivek116** [ericgio/react-bootstrap-typeahead#697]
Feature requests
=======================
### Expected Behavior
----------------------------------------------
In multi-select async type ahead,  When I provide options which is an array of objects to the component 
options = [{"id":"1", name:"my name"}, {"id":"2", "name":"his name"} ]
we can use labelKey to show the display name in the UI but when I select, I need selected value as [id1, id2], which is an array
If this is already available can u pls guide me with me the right example. 

### Actual Behavior
--------------------------------------------------
The selected value is stored as array of objects itself

### Version

5.2.1

**Comment by ericgio** [comment]
Hi @saivivek116, `onChange` provides an array of the selected values. You can manipulate that array to get the data you need:

```jsx
<Typeahead
  onChange={(selected) => {
    // `selected` is a subset of the array passed to `options`.
    // You can map over it to manipulate the data as needed.
    const selectedIds = selected.map(({ id }) => id); // ["1", "2", ...]
  }}
  options={[{"id":"1", name:"my name"}, {"id":"2", "name":"his name"}]}
/>
```

**Comment by saivivek116** [comment]
Hi @ericgio  thanks for responding 
I have understood the example you have given.
In this case, can I pass selctedIds to the component as a selected prop.

**Comment by ericgio** [comment]
> In this case, my requirement is to pass selctedIds to the component as a selected prop

@saivivek116, I'm not really sure what your use case is but if eg: you need to initially select some of the options, you can filter your option set based on the selected ids:

```jsx
const selectedIds = ["1", "2"]
const selected = options.filter((o) => selectedIds.includes(o.id));

<Typeahead
  ...
  defaultSelected={selected}
  options={options}
/>
```

**Comment by saivivek116** [comment]
@ericgio 
Actually I am fetching options from API using onSearch on an input value. Options are going to change on every character change. So what if the selectedId is not present in the new options fetched from API, then we are going to lose previously selected values. I need to persist the old values as well. What is the solution?

**Comment by iamcarlo042** [comment]
Hello @saivivek116 , did you find any workaround on this?
I am in the same situation as you.
