### ISSUE TITLE
@ericgio how to handle pagination using renderMenu  ?

### ISSUE THREAD

**Issue by shekhutsav1962001** [ericgio/react-bootstrap-typeahead#698]
@ericgio 
can you Please tell me how to handle it inside in renderMenu  if I don't want to remove pagination functionality?????

_Originally posted by @shekhutsav1962001 in https://github.com/ericgio/react-bootstrap-typeahead/issues/694#issuecomment-1046794869_

**Comment by ericgio** [comment]
Addressed in #694
