### ISSUE TITLE
[Enhancement] Input onChange event for text

### ISSUE THREAD

**Issue by belliAndrea** [ericgio/react-bootstrap-typeahead#7]
I'm new to React. I'm using react-redux.
I have to make async call to server with the input text, so i'd need the value of the input, but i can't find a way to get it. How can i?
Thank you.

**Comment by ericgio** [comment]
There's currently no way to do this, since `onChange` passes back the selected value, not the text changes. I'll need to add an `onInputChange` hook.

**Comment by ericgio** [comment]
I just added support for this in v0.3.0, hopefully that will suit your needs.
