### ISSUE TITLE
Very long typeahead options / input is not truncated with ellipsis

### ISSUE THREAD

**Issue by opqpop** [ericgio/react-bootstrap-typeahead#700]
### Version

+-- react-bootstrap-typeahead@6.0.0-alpha.9

### Repro
```
          <Typeahead
            multiple
            onChange={(selected) => {
              // Handle selections...
            }}
            options={[
              'abc',
              'def',
              'LlanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogochLlanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogochLlanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogochLlanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch',
            ]}
          />
```

https://user-images.githubusercontent.com/5566843/155265374-353b636a-c5ea-487b-9842-296b6a0fbf5d.mov

### Expected Behavior

See video above. Expected:
- Long input to be truncated with ellipsis ..., including when viewport width shrinks
- Long input also shouldnt make the x button wrap to next line?
- Long options should also truncate with ellipsis, including when viewport width shrinks

### Actual Behavior

- neither of above 3. Text is cut off and not immediately obvious it overflows

Note I see this css code with text-overflow: ellipsis, perhaps the original fix got regressed? Let me know if there's also  anything I may have misused!

https://github.com/ericgio/react-bootstrap-typeahead/blob/814f1e83e5d6543d7a3a7c05439159898a56949b/styles/Typeahead.scss#L18

**Comment by ericgio** [comment]
Hi @opqpop, thanks for the report. I'm not able to reproduce the issue in either BS4 or 5. It looks like you're not [including the package CSS](https://github.com/ericgio/react-bootstrap-typeahead#css), which I suspect is why you're seeing the unexpected behavior.
