### ISSUE TITLE
Options autoclose does not work in modal

### ISSUE THREAD

**Issue by keshav-bohr** [ericgio/react-bootstrap-typeahead#703]
### Steps to reproduce

Create a modal.
Create a basic typeahead in the modal.
Focus on the text field.
Unfocus (blur) the text field by clicking somewhere else.

### Expected Behavior
Options list should autoclose

### Actual Behavior
Options list still exists

**Comment by ericgio** [comment]
Hi @keshav-bohr, thanks for opening this issue. Unfortunately, I'm unable to reproduce the problem ([see sandbox](https://codesandbox.io/s/dreamy-bas-sy6k7v?file=/src/index.js)). Can you please post more specific repro steps or ideally working sandbox with the problem you describe? Thanks!

**Comment by keshav-bohr** [comment]
@ericgio 

Sorry for the late reply. Check with reactstrap once. In modal, tab button is triggering the hide menu. But the outside click is not triggering it to close

**Comment by ericgio** [comment]
@keshav-bohr sorry but I'm not able to reproduce with the reactstrap modal either.

**Comment by sidola** [comment]
@ericgio Hey, if you bump react to 17.0.1 it breaks in the way OP describes, see here: https://codesandbox.io/s/wandering-fire-dpsg39?file=/src/index.js

**Comment by ericgio** [comment]
Thanks for the repro @sidola. I'm not really sure what's happening here, but it might have something to do with the use of [`useRootClose`](https://react-bootstrap.github.io/react-overlays/api/useRootClose) from `react-overlays` and how event delegation changed in React v17. I don't have a ton of time to investigate at the moment but maybe someone else can take a closer look.

**Comment by laholstege** [comment]
i'm having the same issue on react 17.0.2, reactstrap 9.1.6, and react-bootstrap-typeahead 6.2.3. same bug, only happens inside of a modal

**Comment by namti** [comment]
I have the same issue.
`react@18.2.0`, `reactstrap@8.10.1` and `react-bootstrap-typeahead@6.2.3`

Workaround
```jsx
<Modal>
  <ModalBody>
    {(() => {
      let ref;
      return (
        <Typeahead 
          { ...restProps }
          onBlur={ () => ref.hideMenu() }
          ref={ el => ref = el }
        />
      );
    })()}
  </ModalBody>
</Modal>
```

**Comment by laholstege** [comment]
@namti thank you, that works!

**Comment by GABuryan** [comment]
@namti, onBlur worked in modal one time, if click first time on modal form. If first clicked  on scrollbar menuItem (onBlur - work), second clicked on scrollBar menuitem  (onBlur - not work )

**Comment by GABuryan** [comment]
This is not a reactstrap issue. This is a react problem. On React version 16.8 - worked. On React version >17 - not worked.

**Comment by namti** [comment]
I made a modified component to make this easier.

Features:
- If `multiple` is `false`, you can still click to re-select and search.
- if `multiple` is `true`, the menu will stay open after selecting an item. It hides after the focus is lost.
- All the usage and props are the same as the original `<Typeahead />` component.

Just import the component and change your existing code from `<Typeahead { ...props } />` to `<TypeaheadMod { ...props } />`

```typescript
import React, { PropsWithChildren, forwardRef, useImperativeHandle, useRef } from 'react';
import { Typeahead, TypeaheadComponentProps, TypeaheadRef } from 'react-bootstrap-typeahead';
import 'react-bootstrap-typeahead/css/Typeahead.css';
import { Option } from 'react-bootstrap-typeahead/types/types';
import _ from 'lodash';

const TypeaheadMod: React.FC<PropsWithChildren<TypeaheadComponentProps>> = forwardRef((props, ref) => {

  const typeaheadRef = useRef<TypeaheadRef>(null);

  useImperativeHandle(ref, () => typeaheadRef.current);

  const {
    onChange = () => {},
    onBlur = () => {},
    multiple,
  } = props;

  const handleChange = (selected: Option[]) => {
    onChange(selected);

    if(multiple) typeaheadRef.current?.toggleMenu();
  };

  return <Typeahead
    {
      ...{
        ...props,
        ref: typeaheadRef,
        onChange: handleChange,
        onBlur: e => {
          onBlur(e);
          typeaheadRef.current?.hideMenu();
        },
        filterBy: (option, state) => {
          if(!multiple && state.selected.length){
            return true;

          } else {
            const selected = state.selected;
            const selectedLabel = typeof(option) === 'string' ?
              option?.toLowerCase()
              :
              (option as Record<string, any>)?.[props?.labelKey as string]?.toLowerCase();
            const keyword = state.text;

            return selectedLabel?.indexOf(keyword.toLowerCase()) > -1 && selected?.findIndex(item => _.isEqual(item, option)) < 0;
          }
        },
      }
    }
  />;
});

export default TypeaheadMod;
```

**Comment by GABuryan** [comment]
this is code incorrect. If you open menu and click scrollbar of menu with options - onBlur close menu with options.

**Comment by GABuryan** [comment]
this problem only on react >17. If react 16 - all worked coorect - menu hide correct
