### ISSUE TITLE
Set Input value programatically

### ISSUE THREAD

**Issue by brancooo1** [ericgio/react-bootstrap-typeahead#708]
Hello dears, 
I went through all the history and found just very old issue on it #266 

UC:
Touch screen kiosk with kiosk keyboard is being used. How can TypeAhead react on HTML native events or how can we at least set input value programatically if we have its reference?

We test a kiosk keyboard (eg [simple-keyboard](https://hodgef.com/simple-keyboard/getting-started/)) and we use "keydown" events with native HTML elements, or bootstrap elements without any problem. 

But we can't find a way to make TypeAhead work. I think would be great if TypeAhead supports native "keydown" event, or is some other way documented.

**Comment by ericgio** [comment]
Hi @brancooo1 you can apply an `onKeyDown` handler to the input using `inputProps`. However, that sounds separate from your core issue of wanting to set the value of the input programmatically. Unfortunately, there's no API for that and I don't have plans to add one, as described in the issue you reference.

**Comment by brancooo1** [comment]
Ok, thanks for reply. 
Leaving [this](https://stackoverflow.com/questions/66170215/update-input-text-in-react-bootstrap-typeahead-from-javascript-react) here for others, it helped me to hack input value update in Typeahead.
