### ISSUE TITLE
There is no support of icon as placeholder

### ISSUE THREAD

**Issue by bhupendra7** [ericgio/react-bootstrap-typeahead#709]

**Comment by ericgio** [comment]
Hi @bhupendra7 please describe your issue in detail, thanks!

**Comment by bhupendra7** [comment]
Typehead property for placeholder is string.. if I want to use place an icon and as a placeholder, how can we keep it. In case if we change the property to reactNode, it will allow to place any icon over there.

**Comment by ericgio** [comment]
The `placeholder` prop is passed down to the input element, so [it needs to be a string](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-placeholder). You can choose not to use `placeholder` and instead use the components child render prop to render your own custom placeholder using an icon. See the [example for rendering a custom loading indicator](https://codesandbox.io/s/rbt-custom-aux-components-gn3kn).
