### ISSUE TITLE
How to add "aria-label" for hidden input : <input aria-hidden="true" class="rbt-input-hint" readonly="" tabindex="-1" value="" style="...">

### ISSUE THREAD

**Issue by rbarfa11** [ericgio/react-bootstrap-typeahead#710]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**How is this solution useful to others?**
Does your feature address a common use case? Does it provide a more generalized way to solve the type of problem you're encountering?

**Describe alternatives you've considered**

**Additional context**
Add any other context, sample code, or screenshots about the feature request here.

**Comment by ericgio** [comment]
Hi @rbarfa11, thanks for the feature request. Please be sure to provide the requested information!
