### ISSUE TITLE
Default filtering uses `Option` string even when `labelKey` is provided

### ISSUE THREAD

**Issue by jakajancar** [ericgio/react-bootstrap-typeahead#714]
### Version

6.0.0-alpha.11

### Reproduction

 1. Use `string[]` (e.g. UUIDs) as `options`

 2. Define `labelKey={option => someExternalMap[option].label}`

 3. Perform a search. You will see rows where the label matches, but also where the `option` itself (in this case a UUID) just so happens to match. From the user's perspective, there is no logic why these would be showing.

### Expected

Do not match `options` string values if `labelKey` is defined, i.e. [`defaultFilterBy`](https://github.com/ericgio/react-bootstrap-typeahead/blob/814f1e83e5d6543d7a3a7c05439159898a56949b/src/utils/defaultFilterBy.ts#L48-L50) should be changed from:

```
if (isFunction(labelKey) && isMatch(text, labelKey(option), props)) {
  return true;
}
```

to:

```
if (isFunction(labelKey)) {
  return isMatch(text, labelKey(option), props);
}
```

**Comment by ericgio** [comment]
Thanks @jakajancar, I think this makes sense. Could you please provide a small example data set (options + map) so I can reproduce the issue and write tests? Thank you!
