### ISSUE TITLE
Clicking typeahead rendered to shadow DOM hides menu

### ISSUE THREAD

**Issue by charlesroelli** [ericgio/react-bootstrap-typeahead#717]
### Version

`react@17.0.2`
`react-dom@17.0.2`
`react-bootstrap-typeahead@6.0.0-alpha.11`

### Steps to reproduce

I tried to render the Typeahead to a shadow root and noticed this issue.

1. Open https://codepen.io/forthadena/pen/jOZmzyX
2. Click the typeahead.

### Expected Behavior

The menu opens showing the list of options.

### Actual Behavior

The menu briefly opens and then disappears.

**Comment by charlesroelli** [comment]
This should be fixed now in `react-overlays@5.2.0`.

**Comment by ericgio** [comment]
Fixed in v6.0.0-rc.1
