### ISSUE TITLE
Add option for custom rendering of the selected item in single-selection mode

### ISSUE THREAD

**Issue by dmitru** [ericgio/react-bootstrap-typeahead#72]
The same as #64, but for single-selection mode.

**Comment by ericgio** [comment]
I'll look into how best to implement this. The single-selection inout currently uses an actual `input` for simplicity, but that obviously doesn't accept children.

**Comment by cdtinguria** [comment]
I too need the functionality to show extra information like in tokenizer in case of single-selection. Otherwise, a `maxSelected` prop for multi-selection.
BTW, is there any specific reason to use different input type in case of single and multi-select?

**Comment by ericgio** [comment]
> is there any specific reason to use different input type in case of single and multi-select?

At the time I originally wrote the component, it seemed easier to just use an `input` for single-selection. This wasn't possible for multi-selection, since an input can't have children, hence the 2 different ways of rendering. v2.0 uses the same lower-level component to render both.

**Comment by cdtinguria** [comment]
In v2.0-alpha3, if I keep 'multiple' as false, then 'renderToken' is not used, so not able to show extra information in case of single-selection.

**Comment by ericgio** [comment]
Closing in favor of #316
