### ISSUE TITLE
Update peer deps to React 17/18

### ISSUE THREAD

**Issue by sethreidnz** [ericgio/react-bootstrap-typeahead#720]
I'm not sure what work would be involved in this and just raising it as I see the project is still active, but I don't see any issues  relating to updating the peer deps of react.

**Is your feature request related to a problem? Please describe.**

Cannot install without using `--legacy-peer-deps` in npm.

**Describe the solution you'd like**

Update peer dependencies to allow for a range of react versions ideally up to the latest

**How is this solution useful to others?**

Will stop others from having the same issue and keep the project up to date with the core dependencies.

**Describe alternatives you've considered**

Can using the legacy peer deps but I'd imagine that the project wants to stay up to date with React.

**Comment by ericgio** [comment]
Hey @sethreidnz sorry you've been running into issues during installation. The peer dependencies for this package are

```jsx
"peerDependencies": {
  "react": ">=16.8.0",
  "react-dom": ">=16.8.0"
},
```

I think that should include React 17 & 18. Can you be more specific about what errors you're running into?

**Comment by sethreidnz** [comment]
My apologies it was user error your all good!
