### ISSUE TITLE
ability to change the text value in the search input

### ISSUE THREAD

**Issue by jeran-urban** [ericgio/react-bootstrap-typeahead#722]
### Version
 5.2.2

### Issue 
I am trying to check when a user pastes a value into the search box, does that value have bad characters? if so, I want to maintain the previously valid characters in the input. I know I can clear the input altogether, and when typing on key down, I can prevent default to not allow the character to be entered, but when a user pastes a value, I don't see a way to check and prevent that from being successful, only an after the fact check and if not valid a full clear. 

### Question
Is there a way to check and prevent bad values on paste? or is there a way to preserve previous search input value and reload that on bad search values?

### Steps to reproduce

```
const [typeAheadPreviousTextValue, setTypeAheadPreviousTextValue] = useState('')
const [selectOption, setSelectOption] = useState([]);

const onTypeAheadValueChange = (input) => {
        let hasBadCharacters = checkForBadCharacters(input);
        if (hasBadCharacters){
            // trying to change the value on the input (to block against pasted value with bad characters)
            // inputRef.current.getInput().value = typeAheadPreviousTextValue
            // inputRef.current.value = typeAheadPreviousTextValue;
            inputRef.current.clear();  //works (clears the search input value)
        }
        else{
            setTypeAheadPreviousTextValue(input)
            let exactMatch = props.registerOrgs.find(org => org.name.toLowerCase() === input.toLowerCase())
            if (exactMatch != null) {
                console.log('yay', exactMatch)
                setSelectOption([exactMatch])
            }
            else{
                setSelectOption([])
            }
        }
    }



<Typeahead 
    id="single-select-example"
    options={props.listForOptions|| []}
    labelKey="name"
    name="optionId"
    onChange={setSelectOption}
    onInputChange={onTypeAheadValueChange}
    ref={inputRef}
    clearButton
  />
```

### Expected Behavior
I can prevent paste with bad characters or I can use a previous state as the input value 

### Actual Behavior
I can only clear all or nothing if a user pastes a bad value

**Comment by ericgio** [comment]
Hey @jeran-urban thanks for the feature request. I think what you want is `onPaste`, which will allow you to check the clipboard value _before_ it actually gets pasted into the input and therefore prevent the paste action if the value is invalid.

```jsx
<Typeahead
  ...
  inputProps={{
    onPaste: (e) => {
      const text = e.clipboardData.getData('Text');
      if (checkForBadCharacters(text)) {
        // If the pasted value is invalid, prevent it from being pasted.
        e.preventDefault();
      }
    },
  }}
/>
```
