### ISSUE TITLE
Click and Enter work on selection menu list but not Tab

### ISSUE THREAD

**Issue by toggenation** [ericgio/react-bootstrap-typeahead#726]
Hi, Firstly thank you for this package. 

I am using the AsyncTypeahead to request options and entering a substring e.g. "Wool"

I am using it uncontrolled but capturing the selection or input in redux state

If I enter a substring and then arrow down to an option and press enter the value appears in the text input. If I scroll down the option list and click the value the same value appears in the text input. (and I can then commit the value to state using a number of on* events).

![2022-07-18 17_47_25-React App](https://user-images.githubusercontent.com/4483692/179467074-6735b633-fc47-488e-8ed0-1a1d7ed69f69.png)

![2022-07-18 17_47_34-React App](https://user-images.githubusercontent.com/4483692/179467089-5184681e-a1b2-44c9-9d26-056ae3242ef7.png)

However if I arrow down the option list and then press tab the text input reverts to the text string
![2022-07-18 17_47_48-React App](https://user-images.githubusercontent.com/4483692/179467123-a4c4d58c-c172-40a0-968c-f9c928e93552.png)

Is it possible to get the last highlighted menu item so when I keyDown on Tab with that item selected that I can capture this instead of it reverting to the search substring?

![2022-07-18 17_52_55-React App](https://user-images.githubusercontent.com/4483692/179467467-fc000b0e-ab6a-489b-95d3-d51da3a5ba80.png)

Am I missing some way grabbing the selected menu item programmatically when I press TAB?

PS. I have tried v5.x and 6 same and observed the same behaviour and also on the async demo page.

**Comment by ericgio** [comment]
Hi @toggenation, thanks for opening this issue! This is the expected behavior: pressing Tab blurs the input just as it would for a normal `input` element. The only exception is when there's a hint, in which case pressing tab will select the hint.

**Comment by toggenation** [comment]
Thanks @ericgio. appreciate you explaining that thankyou.

**Comment by donkeyDau** [comment]
The `input` behavior on blur is correct. But I regard this library more like a `select`. And there tab is regarded as selection. Is there any way to overwrite this behavior to have tab act as a selection like hitting enter? Either on a custom way or a prop to allow this way of usage (e.g. `tabSelect`)?

**Comment by ericgio** [comment]
Hi @donkeyDau unfortunately there's no way to do it through the library's API. You can hack the behavior, but it could potentially break if the internals change:

```tsx
const ref = useRef(null);
const [selected, setSelected] = useState([]);

return (
  <Typeahead
    ...
    onKeyDown={(e) => {
      // NOT RECOMMENDED, VERY FRAGILE
      // Get the active item from the component's internal state.
      const activeItem = ref.current?.state.activeItem;
      if (e.key === 'Tab' && activeItem) {
        // Prevent the input from blurring when selecting the item.
        e.preventDefault();
        setSelected([...selected, activeItem]);
      }
    }}
    onChange={setSelected}
    options={[...]}
    ref={ref}
    selected={selected}
  />
);
```
