### ISSUE TITLE
ability to have multiple-select UX with single-select functionality

### ISSUE THREAD

**Issue by atuttle** [ericgio/react-bootstrap-typeahead#73]
I love the appearance and UX of the multi-select mode, but I still want to limit the user to one selection. In particular, I think showing the selection as a sort of button with an "x" to clear it is better than making them delete the text to clear their selection.

It would be great if I could set a `maxSelected` prop with multiple to get this behavior:

```xml
<Typeahead multiple maxSelected={1} options={[...]} />
```

**Comment by ericgio** [comment]
Would simply having an "X" button to clear the input address your use-case?

```
-----------------------------------------
|  Selected Option                    x |
-----------------------------------------
```

**Comment by atuttle** [comment]
I guess that would depend on how it looked and worked. As I said, I really like the UX of the multi-select mode of operation.

**Comment by ericgio** [comment]
This feels like a duplicate of #72, eg: custom rendering of single-selections. The component already supports the functionality you need (eg: single-selection) but you want more control over the appearance.

**Comment by atuttle** [comment]
That would be fine as long as there was an easy path to reproducing the existing rendering from multiple-select mode. :)

**Comment by ericgio** [comment]
By the way, you should already be able to achieve what you want by doing something like:
```
<Typeahead
  onChange={selected => {
    this.setState({
      options: selected.length === 1 ? selected : this.state.options,
      selected: selected,
    });
  }}
  options={this.state.options}
  selected={this.state.selected}
/>
```

**Comment by ericgio** [comment]
Note that a `clearButton` prop was added in v1.0. You could then style the input however you want via CSS.
