### ISSUE TITLE
when applying filterBy in multiple Typeahead options are not getting tracked which is  allowing options to be select multiple times

### ISSUE THREAD

**Issue by SailleshPawar** [ericgio/react-bootstrap-typeahead#730]
### Steps to reproduce
When we are applying filterBy in multiple selection Typeahead the options are not getting removed and this allows the user to select the options multiple times.

```
import { Typeahead } from 'react-bootstrap-typeahead';
import React, { useState, useEffect, useRef } from 'react';
import { useFormContext } from 'react-hook-form';
import { Form } from 'reactstrap';
import { countriesList } from 'cpr-form-components';
import './index.css';
import 'react-bootstrap-typeahead/css/Typeahead.css';

const MultipleSelection = ({ placeholder, readonly, name }) => {
  const { prefix: sectionPrefix } = useFormSection();
  const prefixWithName = [...sectionPrefix, name];
  const defaultValue = useRef(get(state, prefixWithName, []));
  const [multiSelections, setMultiSelections] = useState(defaultValue.current);
  const customerList = countriesList
    .filter(x => x.description !== 'United Kingdom')
    .map(country => ({
      name: country.description,
      id: country.id
    }));

    const filterByCallback = (option, props) => (
      option.name.toLowerCase().startsWith(props.text.toLowerCase())
    );

  return (
    <Form style={{ marginTop: '20px' }}>
      <Typeahead
        filterBy={filterByCallback }
        disabled={readonly}
        name={name}
        id="basic-typeahead-multiple"
        labelKey="name"
        multiple
        onChange={setMultiSelections}
        options={customerList}
        placeholder={placeholder}
        selected={multiSelections}
        tokenColor="primary"
      />
    </Form>
  );
};

```
export default MultipleSelection;

### Expected Behavior

The options should be automatically removed from the options the way it was before implementing filterBy. 

### Actual Behavior
Options are still coming despite being already selected
![typeHeadIssue](https://user-images.githubusercontent.com/16855395/180488527-2d3336d4-fb22-459d-859d-8669c2a83b43.gif)

**Comment by ericgio** [comment]
Hi @SailleshPawar, thanks for the question. By defining your own `filterBy` callback, you're completely overriding the internal one, so it's up to you to filter out the selected options. You'll need to add something [like this](https://github.com/ericgio/react-bootstrap-typeahead/blob/main/src/utils/defaultFilterBy.ts#L44) to your function.

**Comment by SailleshPawar** [comment]
@ericgio Thank you so much replying, appreciate that :)
