### ISSUE TITLE
defaultFilterBy export in v6

### ISSUE THREAD

**Issue by MattFanto** [ericgio/react-bootstrap-typeahead#733]
### Version
v6.0.0-rc3

### Steps to reproduce

In version v5 I was able to import `defaultFilterBy` method from the library with
```
import { defaultFilterBy } from "react-bootstrap-typeahead/lib/utils"
```
To create a wrapped version of it and minimize code repetition e.g.
```
export function filterByCer(option, props) {
  const text = someTextNormalization(props.text)
  const _props = {
    ...props,
    ...{
      filterBy: [props.labelKey],
      text: text
    }
  }
  return defaultFilterBy(option, _props)
}
```
Starting from v6 this method is not exported anymore forcing me to copy the logic

### Expected Behavior

Being able to import `defaultFilterBy`

**Comment by ericgio** [comment]
The `lib/` directory was renamed to `cjs/` in v6.0.0-alpha.3, so you can still access `defaultFilterBy` from 

```tsx
import { defaultFilterBy } from "react-bootstrap-typeahead/cjs/utils"
```
or
```tsx
import { defaultFilterBy } from "react-bootstrap-typeahead/es/utils"
```

Note that `defaultFilterBy` is not a top-level export of the library and should be considered private. It's therefore probably better that you do copy the functionality into your own codebase.

**Comment by MattFanto** [comment]
@ericgio thanks for your reply, importing it from "react-bootstrap-typeahead/cjs/utils" raise several warning in the console, but good point if is not meant to be exported I should copy it.
