### ISSUE TITLE
Ability to add onPress to the emptyLabel

### ISSUE THREAD

**Issue by chadk1** [ericgio/react-bootstrap-typeahead#735]
I'm interested if there already is, or is any way to make it so I can add an onPress to the emptyLabel area.
If there are no results that return from a search I want users to be able to click "Not found" and populate the typeahead with "not_found" or something along those lines. 
<img width="450" alt="Screen Shot 2022-08-26 at 1 34 54 PM" src="https://user-images.githubusercontent.com/12489237/186969861-b51dd5c7-3114-4a2d-88a5-3abe8453a6d9.png">

**Comment by ericgio** [comment]
@chadk1: You could use the `allowNew` property and custom menu rendering to do something like that:

```tsx
<Typeahead
  allowNew
  options={[...]}
  renderMenu={(results, menuProps) => (
    <Menu {...menuProps}>
      {results.map((r, idx) => {
        if (r.customOption) {
          r.label = 'not_found';
        }

        return (
          <MenuItem key={idx} option={r} position={idx}>
            {r.label}
          </MenuItem>
        );
      })}
    </Menu>
  )}
/>
```
