### ISSUE TITLE
onchange in not working

### ISSUE THREAD

**Issue by saifyyy** [ericgio/react-bootstrap-typeahead#737]
onChange is not working when we click on the dropdown selection 
<img width="774" alt="Screenshot 2022-09-14 at 5 33 49 PM" src="https://user-images.githubusercontent.com/96548543/190155164-75fb5939-5286-4fcb-b813-5712244a9053.png">

**Comment by ericgio** [comment]
@saifyyy: I'm unable to repro this problem. Please provide the requested information for bug reports. Thanks!
