### ISSUE TITLE
Confirmation of the choice on the tablet

### ISSUE THREAD

**Issue by GABuryan** [ericgio/react-bootstrap-typeahead#739]
On the keyboard, you can type a value in the input field. And if it starts to match the desired value, you can confirm the selection by pressing the "right-arrow" key.

Isn't there a similar action for quick selection for a mobile device? Thanks

**Comment by GABuryan** [comment]
additional question.

is there an automatic selection option, if you paste from into a field from the clipboard and there is one matching value in the list? thanks

**Comment by ericgio** [comment]
> a similar action for quick selection for a mobile device?

You can use the [`selectHint` prop](https://github.com/ericgio/react-bootstrap-typeahead/blob/main/docs/Upgrading.md#shouldselecthint-replaced-by-top-level-selecthint) to customize the hint selection behavior.

> is there an automatic selection option, if you paste into a field from the clipboard and there is one matching value in the list?

You can probably add an `onPaste` handler directly to the input and check the value against the options being passed to the typeahead. If one of the matches you can set the selection in state and pass the value to the `selected` prop.
