### ISSUE TITLE
Support Multiple Datasets

### ISSUE THREAD

**Issue by nighto** [ericgio/react-bootstrap-typeahead#740]
Hello there, first of all thanks for your effort into writing react-bootstrap-typeahead.

I'm assigned a task at work to migrate a search component that uses the original jQuery based typeahead to react-bootstrap-typeahead. This search component queries multiple datasets. When the user types on the input, it queries different services and, if there are results, shows then grouped:

![multiple results](https://i.stack.imgur.com/FeSns.png)

(in this example, user typed "b", and there are results both from Addresses and Previous Results data sources)

The generated HTML by original typeahead in this example is as follows:

![image](https://user-images.githubusercontent.com/397851/194612591-c41d2bbc-d6dc-46b1-a4db-55acc150a5f8.png)

Notice other databases were queried but their result is empty.

Something like this is not possible like this at this moment, right? I'm thinking of an ugly workaround (i.e. making multiple queries on `handleSearch`, concatenate the results and inserting fake, dummy elements to create the titles) but I'm not sure that this would be the best approach.

**Comment by ericgio** [comment]
Hey @nighto, thanks for opening this issue. I've [answered your question](https://stackoverflow.com/questions/73990255/multiple-datasets-grouping-with-react-bootstrap-typeahead) about grouping the results over on StackOverflow.

As far as handling multiple datasets, it's entirely possible. The typeahead component doesn't care where data comes from, as long as it's ultimately passed in as a single array to the `options` prop. You could query multiple sources from `onSearch`, like a local cache as well as a remote endpoint.

**Comment by nighto** [comment]
Thanks a lot @ericgio, your response was really helpful <3
