### ISSUE TITLE
Option to disable showing first element in blurred text in case of exact match

### ISSUE THREAD

**Issue by ashutosharora31** [ericgio/react-bootstrap-typeahead#741]
**Is your feature request related to a problem? Please describe.**
yes. I want an option to not show the first element in blurred text in case of exact match

**Describe the solution you'd like**
The requirement is to not show the blurred text. 
![image](https://user-images.githubusercontent.com/108060133/196632289-8ea3d579-f7fa-4591-9424-06d11dbe2e35.png)

The actual issue is that, when we click on tab, the blurred text(or the first item) is getting selected. We want to restrict to select the first item when we press tab key

**How is this solution useful to others?**
This would restrict the first item getting selected

**Describe alternatives you've considered**
We tried to control tab key behavior on onKeyDown but didn't get the desired result.

**Comment by ashutosharora31** [comment]
Is there an existing way to restrict the blurred text or restricting to select the first element on pressing tab key?

**Comment by ericgio** [comment]
You can pass a callback to `selectHint` to define which keystrokes select the hint. [Here's an example](https://github.com/ericgio/react-bootstrap-typeahead/blob/main/docs/Upgrading.md#v6).
