### ISSUE TITLE
Import Module Error

### ISSUE THREAD

**Issue by tedgeving** [ericgio/react-bootstrap-typeahead#743]
Throwing this error with a basic example:
`export 'Typeahead' (imported as 'Typeahead') was not found in 'react-bootstrap-typeahead' (module has no exports)`

**Comment by ericgio** [comment]
Thanks for the bug report @tedgeving. Can you please provide a sandbox that reproduces the issue or more detailed repro steps? Thanks!

**Comment by ericgio** [comment]
Closing pending further repro steps.
