### ISSUE TITLE
Extended width for dropdown menu

### ISSUE THREAD

**Issue by vli1965** [ericgio/react-bootstrap-typeahead#749]
Is it possible to make the dropdown selection wider than the input text box (wider than using "justify") or have a horizontal scroll bar? I have a fix size input, but the options can be very long. The default seems to just clip off the end of the selection. I'd like to have either the dropdown menu wider than the input width or at least find a way to add a horizontal scroll bar, or perhaps make the text wrap on the item.

Thanks!

**Comment by vli1965** [comment]
Sorry, never mind, just need to align="left"

**Comment by mihow** [comment]
@vli1965 we have the same issue, most of our options are very long. Where did you apply `align=left`? Was that really all it took??

**Comment by mihow** [comment]
@vli1965 nevermind I found it! thanks for creating this issue.

**Comment by mihow** [comment]
@kante-srikanth add to the properties of the <Typeahead> component, for example:

```javascript
  return (
    <div>
      <AsyncTypeahead
        ref={ref}
        labelKey="species_name"
        align="left"
        minLength={3}
        maxHeight="400px"
        onSearch={handleSearch}
        options={options}
        placeholder={t("search_for_species")}
        defaultInputValue={props.defaultValue || undefined}
      />
    </div>
  );
```

**Comment by kante-srikanth** [comment]
Will this work only for AsyncTypeAhead ? I tried to add TypeAhead component but i still see the menu options width is same as the input width. Menu options content didn’t fit properly .. i am using my own component to render the menu options

**Comment by kante-srikanth** [comment]
Got it .. it only works if we use Menu component as the renderer
