### ISSUE TITLE
Bootstrap 5: close button missing btn class

### ISSUE THREAD

**Issue by carstenblt** [ericgio/react-bootstrap-typeahead#750]
### Version

react-bootstrap-typeahead: 6.0.0
react-bootstrap: 2.6.0
bootstrap: 5.2.2

### Steps to reproduce

Use `Typeahead` with the `multiple` option.

### Expected Behavior

<img width="129" alt="Bildschirm­foto 2022-11-18 um 12 39 13" src="https://user-images.githubusercontent.com/11031419/202697076-1470e387-3993-4202-a8f5-5f7afd8d2b5c.png">

### Actual Behavior

<img width="129" alt="Bildschirm­foto 2022-11-18 um 12 34 29" src="https://user-images.githubusercontent.com/11031419/202697091-885503ef-772a-4e10-9387-1309f8c0edf6.png">

Adding the `btn` class to the button element fixes the X. Removing `line-height` from `rbt-token` or changing `rbt-token-label` to     `padding: 0.5rem;` fixes the label padding.

**Comment by ericgio** [comment]
Hey @carstenblt, thanks for the report. Have you included the package CSS with your project?

**Comment by carstenblt** [comment]
I'm sorry, it's all me. I was missing the `close` css from bootstrap.
