### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

### ISSUE THREAD

**Issue by vikasg603** [ericgio/react-bootstrap-typeahead#753]
### Version
Latest ^6.0.0

### Steps to reproduce
Using the library on NextJS

### Expected Behavior

There should be no use of useLayoutEffect

### Actual Behavior

Library is using useLayoutEffect

**Comment by vikasg603** [comment]
@ericgio but may i know the reason of closing the issue?
I don’t think it is solved till now.

**Comment by ericgio** [comment]
@vikasg603: as I mentioned above, there's nothing inherently wrong about using `useLayoutEffect` in this library. The warning is related to your integration of the library in your codebase, which is something I can't control.
