### ISSUE TITLE
Avoid useLayoutEffect wairning in ssr

### ISSUE THREAD

**Issue by wdh2100** [ericgio/react-bootstrap-typeahead#756]
**Version**
Latest ^6.0.0

**Steps to reproduce**
Using the library on NextJS

**Expected Behavior**
Avoid useLayoutEffect wairning

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output form
..
```

ref : 
- https://github.com/ericgio/react-bootstrap-typeahead/issues/753
- https://github.com/facebook/react/issues/14927
- https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85

**Comment by ericgio** [comment]
Hi @wdh2100, thanks for opening this issue. As mentioned in #753, the library doesn't know if it's being rendered on the client or the server. You can probably just ignore the warning, but if you really want to suppress it, you can render a fallback UI while rendering on the server.

**Comment by wdh2100** [comment]
> Hi @wdh2100, thanks for opening this issue. As mentioned in #753, the library doesn't know if it's being rendered on the client or the server. You can probably just ignore the warning, but if you really want to suppress it, you can render a fallback UI while rendering on the server.

@ericgio Thanks reply
