### ISSUE TITLE
text color transparent

### ISSUE THREAD

**Issue by bloodykheeng** [ericgio/react-bootstrap-typeahead#758]
hei ive noted that react bootstrap type ahead has an issue in version 6.0.0 when you set the multiple attribute prop to true the text color becomes hidden or transparent am not sure but you dont view it while typing though when you highlight and select everything in the text input you see the text this is challanging ive  tried to force style it but ive failed but amaizingly if you set the input to single select the txt color reflects well bro we need help

**Comment by ericgio** [comment]
Hi @bloodykheeng, thanks for opening this issue. Please provide detailed repro steps or a sandbox reproducing the issue. Thanks!

**Comment by bloodykheeng** [comment]
am using react app installed with vite but when i set the multiple typeahead to accept multiple  i face this challange where by i cant view the text while am typing it in the input box but when  i change the input to single select there it works fine i can see the text while typing in the input box

**Comment by ericgio** [comment]
> Hi @bloodykheeng, thanks for opening this issue. Please provide detailed repro steps or a sandbox reproducing the issue. Thanks!

**Comment by bloodykheeng** [comment]
hei buddy here is the link to sunbox try setting multiple to true or false you will see how the type ahead behaves in a div of a white background so when i set  multiple true its wired for the text to change therefore i wish you add in a prop where by we can set styles for the color of the text in the input field https://codesandbox.io/p/github/bloodykheeng/react-bootstrap-type-ahead-bug/draft/festive-field?workspace=%257B%2522activeFileId%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522cldorlpk9000e356mv00h284h%2522%253A%257B%2522key%2522%253A%2522cldorlpk9000e356mv00h284h%2522%252C%2522name%2522%253A%2522Default%2522%252C%2522devtools%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cldorlpkc000g356mxk806mtx%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D%257D%252C%2522currentSpace%2522%253A%2522cldorlpk9000e356mv00h284h%2522%252C%2522spacesOrder%2522%253A%255B%2522cldorlpk9000e356mv00h284h%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D

**Comment by bloodykheeng** [comment]
hei @ericgio did you manage to see the issue i raised

**Comment by ericgio** [comment]
@bloodykheeng it looks like you're not including the Bootstrap styles in your project.

https://github.com/ericgio/react-bootstrap-typeahead#css
https://getbootstrap.com/
