### ISSUE TITLE
type ahead color changing on white background

### ISSUE THREAD

**Issue by bloodykheeng** [ericgio/react-bootstrap-typeahead#759]
hei bro i raised my issue but it was deleted without helping me i dono why? but the thing is when I use the type a head on a white background div and multiple prop set to true it comes with a color white so the text gets hidden or invisible a user cant view while typing but when I set multiple to false text works well on white backgrounds so what should I do to make the type ahead have multiple true and also make its color white or black note am talking about the color of the text being entered in the type ahead text input field ,
below is my repo u can test out that sample code and see how the type ahead is behaving   and I used vite to create that simple app

https://github.com/bloodykheeng/react-bootstrap-type-ahead-bug.git

**Comment by ericgio** [comment]
@bloodykheeng: I ran your test repo and I don't see anything wrong with the component. As noted in the other issue, you're not including the Bootstrap CSS, so the input is missing styling. In multi-select mode, the border of the input disappears but the text itself is still visible.

**Comment by bloodykheeng** [comment]
hei @ericgio ive added bootstrap and imported the styles but still the text is white on white background so its invisible i dono what to do now ive noted it only happens when i set the multiple attribute to true and i need the input to take in multiple values please help me if you can  let me show you screen shots. 
if your to view the images you see that text is only visible after highlighting it so its white therefore it camouflages in  a white background making it invisible i need help on this whereby text becomes black on white background or where i can manually set styles of the text in the inputfield

![Screenshot (384)](https://user-images.githubusercontent.com/69955065/217842972-bc944919-dcf5-44f2-aa5e-da85b2861ca9.png)
![Screenshot (386)](https://user-images.githubusercontent.com/69955065/217843026-1b930d8e-1bf2-4ebb-a2b8-41ffd86befdc.png)
![Screenshot (387)](https://user-images.githubusercontent.com/69955065/217843068-3ef9f526-1c07-488b-99b1-383e7d4344ba.png)
![Screenshot (389)](https://user-images.githubusercontent.com/69955065/217843092-7cf2c54f-54ef-4174-bdd8-ceddff13c962.png)

**Comment by ericgio** [comment]
@bloodykheeng I'm sorry but I can't help you with this issue. I'm unable to reproduce the problem you describe using the sandbox you provided. I suggest posting on StackOverflow to see if someone there might have an answer.

**Comment by bloodykheeng** [comment]
This is so sad for me bro am now yet to be fired just of using your component I had implemented it in a whole company system but now clients came with this feedback wanting a fix ive tried all possible solutions and ive failed that’s why I had to look for you the creator now if you just turn me down am dead  Sent from Mail for Windows From: Eric GiovanolaSent: 09 February 2023 19:28To: ericgio/react-bootstrap-typeaheadCc: bloodykheeng; MentionSubject: Re: [ericgio/react-bootstrap-typeahead] type ahead color changing on white background (Issue ***@***.*** I'm sorry but I can't help you with this issue. I'm unable to reproduce the problem you describe using the sandbox you provided. I suggest posting on StackOverflow to see if someone there might have an answer.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
