### ISSUE TITLE
Add `dropup` prop

### ISSUE THREAD

**Issue by bdunbar22** [ericgio/react-bootstrap-typeahead#76]
I was wondering if this was included with the typeahead as an option, but it doesn't seem like it is. In case anyone else has this concern, it isn't really a problem because with bootstrap v3 you can apply dropup to a div wrapped around the typeahead and it will still work correctly.
 
```
<div className="dropup">
    <Typeahead ... props ... />
</div>
```

**Comment by ericgio** [comment]
Seems worth adding a `dropup` prop, since it's explicit functionality provided by Bootstrap. React-Bootstrap [does this with dropdown buttons](http://react-bootstrap.github.io/components.html#btn-dropdowns-dropup).

**Comment by ericgio** [comment]
Added in v0.9.2
