### ISSUE TITLE
hei @ericgio ive added bootstrap and imported the styles but still the text is white on white background so its invisible i dono what to do now ive noted it only happens when i set the multiple attribute to true and i need the input to take in multiple values please help me if you can  let me show you screen shots.

### ISSUE THREAD

**Issue by bloodykheeng** [ericgio/react-bootstrap-typeahead#760]
hei @ericgio ive added bootstrap and imported the styles but still the text is white on white background so its invisible i dono what to do now ive noted it only happens when i set the multiple attribute to true and i need the input to take in multiple values please help me if you can  let me show you screen shots. 
if your to view the images you see that text is only visible after highlighting it so its white therefore it camouflages in  a white background
![Screenshot (388)](https://user-images.githubusercontent.com/69955065/217844022-55aef6b3-56fd-492b-87f7-523f6ae8e86f.png)
 making it invisible i need help on this whereby text becomes black on white background or where i can manually set styles of the text in the inputfield

![Screenshot (384)](https://user-images.githubusercontent.com/69955065/217842972-bc944919-dcf5-44f2-aa5e-da85b2861ca9.png)
![Screenshot (386)](https://user-images.githubusercontent.com/69955065/217843026-1b930d8e-1bf2-4ebb-a2b8-41ffd86befdc.png)
![Screenshot (387)](https://user-images.githubusercontent.com/69955065/217843068-3ef9f526-1c07-488b-99b1-383e7d4344ba.png)
![Screenshot (389)](https://user-images.githubusercontent.com/69955065/217843092-7cf2c54f-54ef-4174-bdd8-ceddff13c962.png)

_Originally posted by @bloodykheeng in https://github.com/ericgio/react-bootstrap-typeahead/issues/759#issuecomment-1424296417_

**Comment by ericgio** [comment]
@bloodykheeng please stop creating new issues for this problem, thanks.
