### ISSUE TITLE
Option type is not imported

### ISSUE THREAD

**Issue by tyren1995** [ericgio/react-bootstrap-typeahead#766]
### Version
6.0.0

### Steps to reproduce
After installing React-Bootstrap-Typeahead and it's @types, try referencing the Option type located in @types/react-bootstrap-typeahead/index.d.ts .

Sandbox which displays the issue : https://codesandbox.io/p/github/tyren1995/rbt-bugs/main?workspaceId=efff0876-8b9f-4692-904c-7834332cf415&file=%2Fsrc%2FApp.tsx
### Expected Behavior
Able to use Option type.

### Actual Behavior
Receives error 
```
'Option' refers to a value, but is being used as a type here. Did you mean 'typeof Option'?
``` 

I'm not sure what went wrong - but I've tried importing the type directly in the file and adding "react-bootstrap-typeahead" to the "types" option in tsconfig.json . Neither option solves the issue.
Thus far I've been explicitly defining the type in my own code to avoid ts errors.

**Comment by ericgio** [comment]
Hey @tyren1995, thanks for opening this issue. v6.0.0 was completely re-written in Typescript and provides its own types, so you shouldn't need the 3rd-party @types package. You can import the `Options` type as follows:

```tsx
import type { Option } from 'react-bootstrap-typeahead/types/types';
```

**Comment by tyren1995** [comment]
> ```tsx
> import type { Option } from 'react-bootstrap-typeahead/types/types';
> ```

@ericgio Thank you so much!
