### ISSUE TITLE
Unwanted OnChange are triggered during typing (onInputChange)

### ISSUE THREAD

**Issue by robozb** [ericgio/react-bootstrap-typeahead#767]
Dear Developers,

First of all, thanks for this great component!

I have a little problem with this: during the normal typing in the input(onInputChange) there are (randomly) triggered OnChange event as well. I don't understand why?!

Sandbox code:
https://codesandbox.io/s/cocky-carlos-136per?file=/src/App.jsx
Please type chars into the input and watch the console.

Thanks: Bela

**Comment by ericgio** [comment]
@robozb this is happening because you're setting the `selected` state via `onInputChange`. If you remove the `setState` call there, you'll see `onChange` is no longer triggered.

**Comment by robozb** [comment]
Thank you so mutch, I will check it out!
