### ISSUE TITLE
Can't catch any outside click event to close the dropdown

### ISSUE THREAD

**Issue by Amir-Inbar** [ericgio/react-bootstrap-typeahead#771]
I used the AsyncTypeahead, and I tried the use a multi-choice and keep the dropdown open until I press outside click, similar behavior  example:
https://codesandbox.io/s/rbt-keep-menu-open-during-multi-select-nr2y4?file=/src/index.js

OnBlur and onFocus don't work as well, please advice how to fix the issue or to support with another solution to keep the dropdown open until the user selects his options and clicks outside the dropdown.

Thanks

**Comment by ericgio** [comment]
Hey @Amir-Inbar, a similar approach should work for async. See [this example](https://codesandbox.io/s/rbt-async-example-lc0zsj?file=/src/index.js).

**Comment by Amir-Inbar** [comment]
> 

Amazing, thank you!
