### ISSUE TITLE
Add possibility to not display anything in menu if `emptyLabel` is `null`

### ISSUE THREAD

**Issue by kozborn** [ericgio/react-bootstrap-typeahead#777]
Hi, first of all, thank you for great component, we're using it in our project and we're very happy with how it works.
That being said, we've found one minor issue after random user testing.
We've found out that `no results` message doesn't work for us because it is not entirely true with our suggestions that we're displaying, and it is misleading for our user, because they think there is no results at all, which is not true.

![image](https://user-images.githubusercontent.com/382005/226460725-43d557da-1e0c-45a9-a2dd-42b84c56c4a7.png)

So we would like to have possibility to disable this feature, unfortunatelly passing `null` as `emptyLabel` results with
![image](https://user-images.githubusercontent.com/382005/226460536-2f2b3142-e399-4582-aac0-00f014f7166a.png)

Do you think it would be possible to not display anything here if `emptyLabel` is `null`?
From what I see it would have to only be changed in `Menu.tsx` line 57 and it would take less time than writing this issue :)
Let me know what you think.
Sorry if my English is not good enough and thanks in advance

**Comment by ericgio** [comment]
Hi @kozborn thanks for the feature request. The behavior you're describing used to exist, but was removed in v4.0 and isn't something I plan on bringing back. I'm not exactly sure what your use case is, but one option is to change the message being displayed to something more appropriate.

Alternatively, if you really want to hide the menu when there are no results you can do this pretty easily using the `renderMenu` prop:

```tsx
<Typeahead
  ...
  renderMenu={(results, menuProps, props) => {
    return results.length ? (
      <TypeaheadMenu
        {...menuProps}
        labelKey={props.labelKey}
        options={results}
        text={props.text}
      />
    ) : null;
  }}
/>
```

**Comment by kozborn** [comment]
Thank you, that works perfectly
