### ISSUE TITLE
Add Async HOC

### ISSUE THREAD

**Issue by helios-ag** [ericgio/react-bootstrap-typeahead#78]
This is a feature request mostly, i would like to have ability to set debounce delay while i type in. This feature, for example would give you ability to reduce api calls while you type. At this moment i wrap typeahead component in HOC, but i think it would be nice to  have this feature out of the box.

**Comment by ericgio** [comment]
I'd be curious to see your code, but basically I think you're doing it exactly right. My goal with this component isn't necessarily to provide _all_ the functionality out of the box. Instead I want to focus mainly on the rendering and interactions, and provide enough flexibility for others to adapt the component for their use as you have done.

**Comment by helios-ag** [comment]
Almost forgot it, sorry, here is component that i use (i omitted some not important parts):

```js
var React = require('react');
var Typeahead = require('react-bootstrap-typeahead').default;
var debounce = require('throttle-debounce/debounce');

var TypeAhead = React.createClass({
  componentWillMount: function() {
    this.handleSearchDebounced = debounce(SEARCH.TYPEAHEAD_DELAY, function() {
      this.props.handleSearch.apply(this, [this.state.query]);
    });
  },
  onChange: function(text) {
    this.setState({query: text});
    this.handleSearchDebounced();
  },
  render: function() {
    return (
      <Typeahead
        onInputChange={this.onChange}
        onChange={this.props.onChange}
        options={this.props.options}
        filterBy = {option => { return option[this.props.labelKey]; }}
        selected={this.props.selected}
        labelKey={this.props.labelKey }
        valueKey={this.props.valueKey}
        minLength={this.props.minLength}
        />
    );
  }
});

module.exports = TypeAhead;

```

**Comment by ericgio** [comment]
Yeah, that seems like the way to go if you ask me.

**Comment by helios-ag** [comment]
Also i think it would be nice to have ability to show loading spinner inside input box, that can be controlled externally via prop, for example, like it's done [here](https://github.com/JedWatson/react-select#async-options-loaded-externally)

**Comment by ericgio** [comment]
Actually, the way `react-select` has broken out functionality into higher-order components that can be used optionally is pretty nice. Seems like a good way to provide the functionality out of the box without making the base component too unwieldy.

**Comment by ericgio** [comment]
v1.0.0 is now available, including an `AsyncTypeahead` component or `asyncContainer` HoC.

**Comment by helios-ag** [comment]
Thanks @ericgio and congrats with v1.0
