### ISSUE TITLE
Warning: `withAsync` is deprecated and will be removed in the next major version. Use `useAsync` instead.

### ISSUE THREAD

**Issue by hakanolgun** [ericgio/react-bootstrap-typeahead#782]
### Version
6.1.0

### Steps to reproduce
Usage of this package in a Next.JS app.

### Expected Behavior
No warning.

### Actual Behavior
I'm getting this warning:
Warning: [react-bootstrap-typeahead] Warning: `withAsync` is deprecated and will be removed in the next major version. Use `useAsync` instead.

Thank you for this useful package. Everything works as expected. I just see the warning above on my console.

**Comment by ericgio** [comment]
Warning fixed in v6.1.1
