### ISSUE TITLE
Typescript error when passing ref to function based component

### ISSUE THREAD

**Issue by AlwaysBeCalm** [ericgio/react-bootstrap-typeahead#784]
Hi react-bootstrap-typeahead team, I'm using the library with typescript
### Version
6.1.2

### Steps to reproduce
I've created a function based component, and created a ref using `const myRef = useRef(null)`
and when I'm trying to use the passed `ref` to the prop of the `Typeahead` component
typescript is showing this warning 
```
`'ref.current' is possibly 'null'`
```
or
```
`property 'hideMenu' does not exist on type 'never'`
```

### Expected Behavior
the ref should be accepted as fine

### Actual Behavior
the build doesn't go fine, unless I ignore the typescript error

see the images
![image](https://user-images.githubusercontent.com/54927528/230758315-d54147e3-efac-43cc-9f80-f784a731f3a9.png)

![image](https://user-images.githubusercontent.com/54927528/230758365-f34bf425-67cf-4abd-bb4b-5ad0d015882e.png)

also added the my wrapper code with ignore comment

``` typescript
import React, { useRef } from "react";
import { Label } from "reactstrap";
import { Typeahead } from "react-bootstrap-typeahead";
import { TypeaheadComponentProps } from "react-bootstrap-typeahead/types/components/Typeahead";

interface Props extends TypeaheadComponentProps {
    labelText: string;
}

export const CATypeahead = ({ labelText, id, ...rest }: Props) => {
    const ref = useRef(null);
    return (
        <>
            <Label for={id}>{labelText}</Label>
            <Typeahead
                id={id}
                ref={ref}
                onBlur={() => {
                    // Abdullah: I know I'm ignoring errors, but there're no way around to pass this error in ref
                    // `'ref.current' is possibly 'null'` and/or `property 'hideMenu' does not exist on type 'never'`
                    // opened an issue in the library's repo: https://github.com/ericgio/react-bootstrap-typeahead/issues/784
                    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
                    // @ts-expect-error
                    ref.current?.hideMenu();
                }}
                {...rest}
            />
        </>
    );
};
```

**Comment by ericgio** [comment]
Hey @AlwaysBeCalm, the problem is you're initializing the `ref` as `null` without specifying the eventual ref type:

```tsx
import TypeaheadRef from 'react-bootstrap-typeahead/types/core/Typeahead';

...

const ref = useRef<TypeaheadRef>(null);
```

**Comment by AlwaysBeCalm** [comment]
Appreciate your clarification @ericgio 🌹
