### ISSUE TITLE
could "Type to search" label be removed?

### ISSUE THREAD

**Issue by savageqm** [ericgio/react-bootstrap-typeahead#787]
Any way to remove the "Type to search" label when I enter my first character using AsyncTypeahead?

**Comment by ericgio** [comment]
Hi @savageqm, thanks for the question. Please describe your feature request in more detail. If this is a usage question, please post instead to [Discussions](https://github.com/ericgio/react-bootstrap-typeahead/discussions) or on [StackOverflow](https://stackoverflow.com/questions/ask?tags=react-bootstrap-typeahead) so I can keep the issues queue limited to bugs and feature requests. Thanks!
