### ISSUE TITLE
Inconsistent behaviour on tab

### ISSUE THREAD

**Issue by maon-fp** [ericgio/react-bootstrap-typeahead#788]
### Version
6.1.2

### Steps to reproduce
Default installation with an `<Typeahead>` with multiple options as seen in e.g. https://codesandbox.io/s/9jq9jyzmry

### Expected Behavior
Tab should select option when selected with ArrowDown the same way as suggestions are accepted in the input.

### Actual Behavior
Depending on the selection position tab behaves differently:

1. Entering the Typeahead and seeing all options: ![01_empty](https://user-images.githubusercontent.com/78473803/233308808-ad1d6785-4e6b-4d1b-ad9c-ab369806b79f.png)<hr />

2. Typing characters matching an option: ![02_typed](https://user-images.githubusercontent.com/78473803/233308811-7cfa675c-dd65-47c8-b2b5-7dff7471c0a0.png)<hr />

3. Pressing tab selects the option matching: ![03_tab](https://user-images.githubusercontent.com/78473803/233308812-02ec3b93-159a-46b6-9f19-3c0eada58aca.png)<hr />

4. Going back to the field, typing the same characters again, then selecting the option with ArrowDown: ![04_selected](https://user-images.githubusercontent.com/78473803/233308816-58cafef5-0b9c-4042-9b0f-fa65770cd8fe.png)<hr />

5. Pressing tab does not select the option: 
![05_tab](https://user-images.githubusercontent.com/78473803/233308820-78b71433-661a-47c4-bb2d-ebb88e0cfaf1.png)

**Comment by maon-fp** [comment]
Hello @ericgio,

thanks for the link. I've seen the issue but was not sure about the "hint". Now reading it again I see that you were referring to 2. in my list.

But I still don't quite understand: why is there an exception for the Hint and not for the selection with ArrowDown? Why is there no second exception? Or no prop to de/activate that? It's the inconsistency in operation that bothers me most.

**Comment by ericgio** [comment]
Hey @maon-fp I understand your frustration. Unfortunately I don't really have a satisfying answer for you. The behavior you're referring to has been part of the library since I first wrote it, probably because it was the behavior of the original Twitter typeahead this component was modeled after. It seems reasonable to allow developers using the library to control this behavior as they see fit, but I don't know how much work that would take or when I'd get around to implementing it.

**Comment by ericgio** [comment]
I posted [a workaround](https://github.com/ericgio/react-bootstrap-typeahead/issues/726#issuecomment-1519108356) on the original issue, though it's not recommended.

**Comment by maon-fp** [comment]
We could pass in something like the `event` on an `onClick`. User can either run a `event.preventDefault()` on that and decided by themself which action to be performed. Or perform an action and let the default kick in afterwards (closing the dropdown, ...). But then additional parameters are needed as well: `hideMenu`, `selectItem`, ... maybe that's overkill ....
