### ISSUE TITLE
API for setting input-specific props

### ISSUE THREAD

**Issue by gilm31** [ericgio/react-bootstrap-typeahead#79]
title :)

**Comment by iyoukeyyewei** [comment]
+1

**Comment by ericgio** [comment]
As suggested in the original title, an `inputProps` prop that passes any attributes on to the input is probably the easiest solution here.

**Comment by stevenqzhang** [comment]
Related question, is there a workaround to set the input value in the textbox (not the placeholder text) on initial render?

**Comment by ericgio** [comment]
@stevenqzhang: I'm assuming you mean just setting the input's text value and not the component's `selected` value. If so, the answer is currently no; more discussion [here](https://github.com/ericgio/react-bootstrap-typeahead/pull/172).

**Comment by stevenqzhang** [comment]
@ericgio Actually, setting the selected value is exactly what I wanted. It wasn't clear to me at first that I could set the selected value to an arbitrary value not in the autocomplete list. Thanks!

**Comment by jasxir** [comment]
I have this exact requirement when using it as a controlled component.
If there's text present in the input when it's rendered again, even with new list and/or selected values, the input text is not cleared.

**Comment by ericgio** [comment]
> I have this exact requirement

@jasxir: not sure which requirement you're referring to, but you can clear the input with the [`clear`](https://github.com/ericgio/react-bootstrap-typeahead/blob/master/docs/Methods.md#clear) method.

**Comment by BillOTei** [comment]
any new on this? I'd really need to be able to restrict the user input to only letters for ex. Suggestions?
I try to use `onInputChange={this.props.method}` but how to change the input value form there?
Thx!

**Comment by ericgio** [comment]
Reading through @jasxir's issue again, it seems potentially related to #198. I should hopefully have a fix for that out soon-ish. As far as the ability to set the input props, that's going to take some work so I don't want to make any promises on a timeline.

**Comment by ericgio** [comment]
`inputProps` prop added in v2.0.0-alpha.1. However, it does not allow you to set the input `value`, since that is controlled by the top-level component.
