### ISSUE TITLE
toggleMenu doesn't work with AsyncTypeahead

### ISSUE THREAD

**Issue by zefirka** [ericgio/react-bootstrap-typeahead#795]
### Steps to reproduce

Example:  https://codesandbox.io/s/gracious-germain-676x7z?file=/src/App.tsx:0-2531

1. Create `AsyncTypeahed` component with ref
2. Call `ref.current?.toggleMenu()` on any action
3. Nothing happens

### Expected Behavior

Calling `.toggleMenu()` method will actually toggle dropdown menu. 

### Actual Behavior

Nothing happens.

**Comment by ericgio** [comment]
Hey @zefirka, thanks for opening this issue! The behavior you describe is working as expected. By default, `AsyncTypeahead` doesn't display the menu until at least two characters have been typed (`minLength={2}`), to minimize unnecessary requests. If you enter 2 or more characters in the input, you'll see that the toggle method works just fine. You can override the behavior by changing `minLength` to `0`.
