### ISSUE TITLE
add custom headers above the menu options 

### ISSUE THREAD

**Issue by kante-srikanth** [ericgio/react-bootstrap-typeahead#797]
how to add custom header above the menu option like below 
![image](https://github.com/ericgio/react-bootstrap-typeahead/assets/10942377/2e255413-6c1d-4d9a-8c65-f24725e2a9c7)

**Comment by TomHiller-swd** [comment]
@kante-srikanth This can likely be done in a similar way as the ["Custom Menu" option under Rendering in the examples](http://ericgio.github.io/react-bootstrap-typeahead/#rendering)  where 'region' can be replaced with a count of the filtered results.

This is not my project, but I am annoyed by this type of issue being created.  First off, this is not a bug, you are asking a question.  Second, what you are asking how to implement a feature that is clearly defined in another project in here.  Why not use the other project?  How much time did you devote to researching this on your own without taking the time of maintainer who, obviously has devoted a lot of time to this amazing component.  Please, in the future, invest your own time before asking what ultimately are frivolous questions.

**Comment by ericgio** [comment]
@kante-srikanth the custom menu rendering example mentioned above should be a good resource for helping you understand how to customize your menu. Thanks @TomHiller-swd for chiming in.
