### ISSUE TITLE
Max Results causes the results comes out-of-dated in the renderMenu

### ISSUE THREAD

**Issue by LuisValgoi** [ericgio/react-bootstrap-typeahead#799]
### Version

- any

### Steps to reproduce

- Use the allowNew + maxResults + renderMenu. 
- If you control the `options` based on the handler of the render menu item click, the `maxResults` property will cause an issue if enabled where the `results` argument hoisted by the `renderMenu` method will come out-of-date.
- https://codesandbox.io/s/react-bootstrap-typeahead-buggy-options-xp85zd <- LINE 80

### Expected Behavior

`results` args come updated.

### Actual Behavior

`results` args come out-of-date.

**Comment by ericgio** [comment]
Hi @LuisValgoi thanks for opening this issue. Can you please provide more details on the behavior you're observing and what you expect to happen? I'm having some trouble understanding exactly what the bug is.

**Comment by ericgio** [comment]
Closing, pending repro steps. Happy to re-open once those are provided.
