### ISSUE TITLE
Allow for drag-and-drop re-ordering of multi selections

### ISSUE THREAD

**Issue by chultquist** [ericgio/react-bootstrap-typeahead#80]
I have an application where users can choose multiple elements from a list of available options, and this typeahead component works great for this purpose. However, the ordering of these selections is also important. It would be nice if the typeahead component allowed users to drag the selections around in the input box to re-order them, rather than having ordering be specified using a separate component. Would this be possible to support?

**Comment by ericgio** [comment]
Can you describe your use case a bit more? I'd say that this is probably not something I'd want to do out of the box, but would definitely like to update the component so that developers have the flexibility to do it themselves if they want.

**Comment by chultquist** [comment]
Sure (sorry about the delay in reply...). I'm basically using the component for users to choose columns from a table that they would like to see data for, and using the ordering of the columns to provide the order in which grouping happens. So for example, say I have the following data:

```
FIRSTNAME LASTNAME  AGE
Carl      Hultquist 35
Carl      Smith     28
Marc      Hultquist 32
```

The selection will allow the user to choose from FIRSTNAME, LASTNAME and AGE. If they choose LASTNAME and FIRSTNAME in that order, then they will get a table that looks like this:

```
LASTNAME |FIRSTNAME
---------+---------
Hultquist|Carl
         |---------
         |Marc
---------+---------
Smith    |Carl
```

but if they first choose FIRSTNAME and then LASTNAME, then the resulting table would look like:

```
FIRSTNAME|LASTNAME
---------+---------
Carl     |Hultquist
         |---------
         |Smith
---------+---------
Marc     |Hultquist
```

Does that make sense? Real examples get a bit more complicated with the ability to choose maybe ~10 or more different columns. So it would be helpful if the user could reorder the selections in some way.

**Comment by abdulrahman-khankan** [comment]
This!
@ericgio Is it possible to integrate it with react-dnd or something similar? If you know of any working drag & drop packages that I can integrate yours with, please do share! 🙂

**Comment by ericgio** [comment]
I don't see this getting implemented anytime soon, if at all. I can't see it being useful to very many people and it would add a lot of complexity (along with another lib) to the component. At best, it might become possible down the line through a `renderInput` method that allows the developer to customize the input behavior. There's no timeline on that, though.

**Comment by ericgio** [comment]
Closing in favor of #316
