### ISSUE TITLE
 AsyncTypeAhead goes from uncontrolled to controlled

### ISSUE THREAD

**Issue by jprosevear** [ericgio/react-bootstrap-typeahead#803]
### Version

6.2.3

### Steps to reproduce

https://stackblitz.com/edit/stackblitz-starters-jkwnhp

### Expected Behavior

Value for the input should be '' when selected is []

### Actual Behavior

Value for the input is undefined

<img width="1371" alt="Screenshot 2023-07-12 at 4 47 24 PM" src="https://github.com/ericgio/react-bootstrap-typeahead/assets/699616/5d0ab9a8-54f3-4b5d-bbea-124f21dbb630">

I believe this is only in the case of the async version

**Comment by ericgio** [comment]
Hey @jprosevear, thanks for the report. I'm not seeing any issues in the sandbox you included. Can you please provide a more detailed explanation?

**Comment by jprosevear** [comment]
The console warning won't show in a prod build - but see highlight line (open the app in a separate window and use inspector) - value is undefined (meaning uncontrolled) even though selected=[].  When an item is picked value will be the value selected (controlled).

**Comment by jprosevear** [comment]
You are correct, this is not the issue I thought it was.
