### ISSUE TITLE
Wrong text is highlighted if Japanese diacritics present

### ISSUE THREAD

**Issue by laug** [ericgio/react-bootstrap-typeahead#806]
### Version
6.2.3

### Steps to reproduce
In example data, replace "Nevada" with "ネバダ州 Nevada".
Then run the example and search for 'Nev'.

### Expected Behavior
'Nev' should be bold: ネバダ州 **Nev**ada

### Actual Behavior
'vad' is bold: ネバダ州 Ne**vad**a

<img width="638" alt="Nevada wrong highlight" src="https://github.com/ericgio/react-bootstrap-typeahead/assets/5089281/7d4b28be-be4d-480f-b081-03c1f10770e4">

The bold text is offset by 2 characters, due to the Japanese text preceding it having 2 diacritics, which are not properly removed in `stripDiacritics()`.

To fix this issue, line 117 of stripDiacritics.s should be changed from
`      .replace(/[\u0300-\u036F]/g, '') // Remove combining diacritics`
to
`      .replace(/[\u0300-\u036F\u3099\u309A]/g, '') // Remove combining diacritics`

**Comment by ericgio** [comment]
Fixed in v6.3.2
