### ISSUE TITLE
onInputChange is not fired when an option is selected

### ISSUE THREAD

**Issue by samfundev** [ericgio/react-bootstrap-typeahead#809]
### Version

6.2.3

### Steps to reproduce

1. Start typing out an option.
2. Select an option.

### Expected Behavior

1. Start typing out an option, each keystroke fires onInputChange.
2. Select an option, onInputChange fired.

### Actual Behavior

1. Start typing out an option, each keystroke fires onInputChange.
2. Select an option, no onInputChange fired.

I am trying to provide suggestions that the user may edit, so I want access to the actual value of the text field.

### Sandbox
https://codesandbox.io/s/reverent-cookies-cnfnhy

In this sandbox, the input's text is displayed above the text box as the user types. But will not update when the user selects an option.

**Comment by ericgio** [comment]
Hey @samfundev, thanks for opening this issue! What you describe is the intended behavior of the component and has been raised in a couple other issues. Setting the value of the input programmatically — which is what happens during a selection — does not trigger the input's change handler. Try this with a plain input, you should see that's the case there as well.

To address you use case, you'll need to add an `onChange` handler and also set the text value when a selection is made. Something like

```tsx
<Typeahead
  ...
  onChange={(selected) => {
    if (selected.length) {
      setValue(selected[0].label);
    }
  }}
  onInputChange={(text) => setValue(text)}
  defaultInputValue={value}
/>
```
