### ISSUE TITLE
Add bootstrap sizes for the input

### ISSUE THREAD

**Issue by janka** [ericgio/react-bootstrap-typeahead#81]
When trying to adjust input size by adding i.e. .input-sm, this: `<Typeahead className="input-sm" />` will not work.

The class needs to go on the input.bootstrap-typeahead-input-main and input.bootstrap-typeahead-input-hint, and to NOT go on the div.bootstrap-typeahead to have the desired effect.

Maybe an "inputSize"-prop would be an idea?

Work around:
Add another class i.e. "input-small", and a bit of CSS:

``` css
.bootstrap-typeahead.input-small input {
    .input-sm;
}
```

**Comment by ericgio** [comment]
Added a `bsSize` prop in v0.10.3 to address this.
