### ISSUE TITLE
return all the data properties inside the option of a particular option

### ISSUE THREAD

**Issue by ranidu-harshana** [ericgio/react-bootstrap-typeahead#810]
I want to get all properties of a particular input option. For an example lets think my options list is

const options = [
        { id: 1, state: 'AL' },
        { id: 2, state: 'AK' },
        { id: 3, state: 'AZ' },
        { id: 4, state: 'AR' },
        { id: 5, state: 'CA' }
      ]

By using ref I can access input node of typehead as ref.current.getInput(). Ans also I can take the selected value by using  ref.current.getInput().value. But how can I take the id attribute in the options list. So if there is any functionality take all the attributes of a particular selected options it would be really helpful

**Comment by ericgio** [comment]
Hey @ranidu-harshana, you can use `onChange` to get the selected options. Check out [the documentation](https://github.com/ericgio/react-bootstrap-typeahead/blob/main/docs/Usage.md#controlled-recommended) for more.

**Comment by ranidu-harshana** [comment]
Ohh how did I miss that. Thank you very much @ericgio
