### ISSUE TITLE
Feature Request: Remove hardcoded style tag from hint

### ISSUE THREAD

**Issue by nikischin** [ericgio/react-bootstrap-typeahead#811]
https://github.com/ericgio/react-bootstrap-typeahead/blob/999f64451bed319030ca76e4f6304ecb237e9534/src/components/Hint/Hint.tsx#L67-L72

I would suggest moving the hardcoded style from the hint to the CSS with a new css-class. I don't understand too much what it is needed for, though this would add some flexibility to the user in overwrite the default behavior what might behave different than the standard bootstrap components in some rare cases (see #622). Moving the style to the css would add a lot more flexibility to customizing.

Also while the Hint component has the option to take a className prop, it is not something to be accesses without using a full custom renderInput. So for rather light customization there might be the need to do quite a lot of custom modification.

Same might also apply for other components including hardcoded style tags.

Thank you so much!

**Comment by ericgio** [comment]
@nikischin the inline styles in a few components are there to ensure reasonable behavior for the majority of common use cases. As you note, in some relatively rare cases there may be a need for more control or customization. In those cases, you're free to create your own `Hint` component to suit your needs (or omit it altogether). It's actually a [pretty thin component](https://github.com/ericgio/react-bootstrap-typeahead/blob/main/src/components/Hint/Hint.tsx#L61) and the main functionality is available in the `useHint` hook.
