### ISSUE TITLE
Typeahead copy/paste value in field results in undefined when not selecting from list

### ISSUE THREAD

**Issue by ocappelle** [ericgio/react-bootstrap-typeahead#813]
### Version
6.1.2

### Steps to reproduce
- start typing in the input field
- select value 'Alabama'
- copy value 'Alabama' to clipboard
- remove 'Alabama' and select other value from list, fe. 'Arizona'
- select value in field and paste your value from clipboard
- click outside of the input field to lose focus

Starter sandbox: https://codesandbox.io/s/react-bootstrap-typeahead-6dn3sz

### Expected Behavior
- value should be equal to 'Alabama'

### Actual Behavior
- value is undefined now
![Screenshot 2023-08-29 at 15 35 07](https://github.com/ericgio/react-bootstrap-typeahead/assets/10130171/b06c9a7a-12be-4e42-8e99-b213a4ce6e31)
![Screenshot 2023-08-29 at 15 36 24](https://github.com/ericgio/react-bootstrap-typeahead/assets/10130171/6687d276-0935-477c-9640-d6a891da0e36)
![Screenshot 2023-08-29 at 15 36 44](https://github.com/ericgio/react-bootstrap-typeahead/assets/10130171/7a855a4d-5599-48ec-a229-111b14f1044d)

**Comment by ericgio** [comment]
Hey @ocappelle that's the expected behavior. Pasting text into the input doesn't automatically select any options. It's the same as typing out "Alabama" and not selecting the option from the dropdown.
