### ISSUE TITLE
Scrolling gets "stuck", bound by keeping the active item in view

### ISSUE THREAD

**Issue by halljus** [ericgio/react-bootstrap-typeahead#816]
### Version

6.2.3

### Steps to reproduce

1. Type a partial match in a typeahead with enough results to create a scrollbar.
2. Use the keyboard to arrow down to a result somewhere in the middle.
3. Scroll up and down with the mouse wheel.
4. Observe you cannot scroll up or down beyond the highlighted option.

This can be reproduced in the Asynchronous Searching example:

http://ericgio.github.io/react-bootstrap-typeahead/#asynchronous-searching

And here is a GIF of it happening:

![repro](https://github.com/ericgio/react-bootstrap-typeahead/assets/102833203/6a2427f6-427f-41a5-b83d-84071a2ded5a)

### Expected Behavior

It would scroll normally.

### Actual Behavior

It gets "stuck".

**Comment by ericgio** [comment]
Thanks for the report @halljus! Fixed in v6.3.0
