### ISSUE TITLE
Options with a falsey "disabled" property get skipped on keyboard navigation

### ISSUE THREAD

**Issue by dleavitt** [ericgio/react-bootstrap-typeahead#818]
Options with a disabled property with a falsey value can still be selected but not via keyboard navigation.

### Version

6.1.2

### Steps to reproduce

1. Go to the code sandbox*: https://codesandbox.io/s/infallible-allen-sqzwlh
2. Click on the state typeahead
3. Press the down arrow on your keyboard.

### Expected Behavior

As you hIt the down arrow, it should:
- select Alabama (`disabled: false`)
- skip Alaska (`disabled: true`)
- select Arizona (`disabled: undefined`)
- select Wyoming (no `disabled` attribute)

### Actual Behavior

- It selects Wyoming, skipping Alabama and Arizona

*Or use the below:

```typescript
<Typeahead
  id="basic-example"
  options={[
    { disabled: false, label: 'Alabama' },
    { disabled: true, label: 'Alaska' },
    { disabled: undefined, label: 'Arizona' },
    { label: 'Wyoming' },
  ]}
/>
```

**Comment by ericgio** [comment]
Thanks for the PR, @dleavitt! Included in v6.3.0 release.
