### ISSUE TITLE
6.3.0 defaults isLoading to true

### ISSUE THREAD

**Issue by razor-1** [ericgio/react-bootstrap-typeahead#828]
### Version
6.3.0

### Steps to reproduce
Set up a Typeahead without specifying `isLoading`

### Expected Behavior
The documented default of `isLoading` would continue to be false.

### Actual Behavior
Every Typeahead I have now shows the loading spinner.

**Comment by ericgio** [comment]
Thanks for the report @razor-1! Fixed in v6.3.1
