### ISSUE TITLE
How to Customize react-bootstrap-typeahead to remove the default filtering of case-insensitive string match.

### ISSUE THREAD

**Issue by dPramod** [ericgio/react-bootstrap-typeahead#83]
Firstly , wanted to thank for such an awesome component. While working on this i came across a situation where we need to pass our call back that would not compare string match. Can we override the default behavior.

**Comment by ericgio** [comment]
Yes, you can use the [`filterBy`](https://github.com/ericgio/react-bootstrap-typeahead#filtering-data) prop to pass your own callback.

**Comment by dPramod** [comment]
Thank you !! My mistake, I was using older version and that caused  the confusion.

**Comment by Rugal** [comment]
How can I disable the filter feature at all?
