### ISSUE TITLE
Allow component in `labelKey`

### ISSUE THREAD

**Issue by brettdewoody** [ericgio/react-bootstrap-typeahead#832]
**Is your feature request related to a problem? Please describe.**
No, it is clearly documented that `labelKey` should return a `string`. This request is to enable `labelKey` to return JSX so the selected item can be formatted. Similar to how `renderToken` works.

**Describe the solution you'd like**
Enable `labelKey` to return JSX so the selected item can be formatted. Similar to how `renderToken` works.

**How is this solution useful to others?**
Displaying a `renderLabel` (or ability to return JSX in `labelKey`) would beconsistent with `renderToken`.

**Describe alternatives you've considered**
It might be possible to use `renderInput` to achieve this but that adds complexity.

**Comment by ericgio** [comment]
The `labelKey` property has to return a string because it's used to filter results. You can format the output any way you want when rendering. I'm not sure what your particular use case is, but there should already be a way to achieve what you want.
