### ISSUE TITLE
IE backspace Issue : Using "backspace" key on the component take to previous page rather than deleting the selected option

### ISSUE THREAD

**Issue by dPramod** [ericgio/react-bootstrap-typeahead#84]
Hi, 
Can you please help me fix the IE backspace issue on this component. 

Thank's a lot !!

**Comment by dPramod** [comment]
I am planning to add the following piece in  _handleKeydown (Typeahead.react.js)

    if(document.documentMode<=11  && this.state.text == "" && e.keyCode === 8 ){
        e.stopPropagation();
        e.preventDefault();
    }else{
        // switch
}

**Comment by ericgio** [comment]
Can you please provide more info about the bug? Which versions of IE? Does this only happen when there is no text? Does this happen for both single- and multi-select versions?

I'll need to take a closer look, but off the top of my head the input components probably just need to catch the backspace keystroke and prevent default behavior as you're sort of doing above.

**Comment by dPramod** [comment]
The issue is currently reproducible  on IE 11 on multi-select version.

Please find the steps to reproduce below,
1. Select one/many states from typeahead options with 'Allow multiple selections (tokenizer)' checked.
2. Select the backspace button on the keyboard to remove the code selected.

Expect: The option will be removed from the field.
Actual: The user is put back on the previous page.

Can you please let me know on when can you expect the fix to be published. Thank you !

**Comment by ericgio** [comment]
I can repro, thanks.

**Comment by dPramod** [comment]
Please let me know if there is anything that I can assist you ...

**Comment by ericgio** [comment]
Should be fixed in v0.9.3. Let me know if the problem persists.

**Comment by dPramod** [comment]
Hi, Due to this fix, the  backspace is not working on IE...

**Comment by dPramod** [comment]
Sorry to trouble you but will you be looking into the above behavior too.?

**Comment by ericgio** [comment]
Ok, should be fixed for real now in 0.9.4. Sorry about that.

**Comment by dPramod** [comment]
This issue got resolved now. Thank's a lot for looking into this promptly !!
