### ISSUE TITLE
Clear button has small duplicate x (extra span)

### ISSUE THREAD

**Issue by ctgbarcalow** [ericgio/react-bootstrap-typeahead#843]
CodeSandbox.io Example
https://codesandbox.io/p/sandbox/react-bootstrap-typeahead-close-button-bug-rhdgwt?file=%2Fsrc%2FApp.tsx%3A7%2C1-11%2C9

![image](https://github.com/ericgio/react-bootstrap-typeahead/assets/85701261/c35b4bfb-cca1-48bc-92f5-38e8d8a32942)

### Version

6.3.2

### Steps to reproduce

Set clearButton=true

      <Typeahead
        options={["one", "two", "three"]}
        selected={["one"]}
        clearButton={true}
      />

### Expected Behavior

The clear button to appear without a duplicate span creating a second smaller x.

### Actual Behavior

Adds a button with a second smaller x.

**Comment by ericgio** [comment]
Be sure to include the CSS from the package:

```tsx
import "react-bootstrap-typeahead/css/Typeahead.css";
import "react-bootstrap-typeahead/css/Typeahead.bs5.css";
```
