### ISSUE TITLE
Copy pasting any value with spaces should remove spaces.

### ISSUE THREAD

**Issue by sgokhru** [ericgio/react-bootstrap-typeahead#849]
I'm using the AsyncTypeahead component as a input field:

So the when a user copy paste some string which contain trailing space then I want to remove the space and update the AsyncTypeahead value.

I have tried few ways:
1. I am storing the typeahead value by using state variable and using that value but updated value is not getting reflected.
2. I am creating a ref and trying to update value by using inputRef.current.getInput().value = trimmedValue.

Both the ways are not working.

**Comment by ericgio** [comment]
Hey @sgokhru, [there isn't a clean way](https://github.com/ericgio/react-bootstrap-typeahead/issues/266) to set the string value of the input once the component has mounted. One workaround might be to force the component to re-mount using a different `key` and then set the `defaultInputValue` with the trimmed value. Hope that helps.
