### ISSUE TITLE
Updating labelKey simultaneously throws exception

### ISSUE THREAD

**Issue by dgarwin** [ericgio/react-bootstrap-typeahead#85]
This appears to be bug that seems to have surfaced somewhere between upgrading from 0.5.2 to 0.9.4, as I did not have the following issue until I upgraded

In my use case, I use the same `Typeahead` component for lists of elements with different `labelKey`s. To manage this, I'm regularly switching the `labelKey` and options at the same time. When I do this, `selected` remains in state, erroneously, and I get the following exception.

> Uncaught Error: One or more options does not have a valid label string. Please check the `labelKey` prop to ensure that it matches the correct option key and provides a string for filtering and display.

I believe a simple and logical fix for this would be to add a call to `clear()` in `componentWillReceiveProps` in `Typeahead.react.js`, if changes to `labelKey` and/or options are made. My current workaround is to manually call `clear()` right before I make my update.

**Comment by ericgio** [comment]
Can you please post an example of your code? This component should ideally be pretty dumb and simply render what is passed in. Modifying `componentWillReceiveProps` to anticipate this case leads down a slippery slope of accounting for all kinds of edge cases and pushes complexity into the component. Based on your description, I think requiring the developer (you) to clear the selected options is pretty reasonable. Better yet, I would normalize your data before passing it in, but I obviously don't have insight into this particular case.

**Comment by ericgio** [comment]
Closing for lack of further context. Feel free to reopen if you want to provide additional information. Note that `labelKey` now accepts a callback and may help in this case where your data changes shapes.
