### ISSUE TITLE
clearButton not shown with defaultInputValue

### ISSUE THREAD

**Issue by maon-fp** [ericgio/react-bootstrap-typeahead#853]
### Version
6.3.2

### Steps to reproduce
```JS
    <Typeahead
      options={['a', 'b', 'c']}
      defaultInputValue='a'
      clearButton
    />
```

### Expected Behavior
The clear button should be displayed if there a default input value given.

### Actual Behavior
No clear button is shown initially if `defaultInputValue` is given. After a selection the clear button shows up.

**Comment by ericgio** [comment]
That is the intended behavior. `defaultInputValue` passes a default string value to the input, but doesn't actually make a selection, thus the clear button doesn't show up. Use `selected` or `defaultSelected` to set a selection.
