### ISSUE TITLE
app.component.html

### ISSUE THREAD

**Issue by fida2013** [ericgio/react-bootstrap-typeahead#858]
<ul *ngFor="let userlist of userlists">
    <li>{{userlist.name}}</li>
    <li>{{userlist.phone}}</li>

    <ul *ngFor="let account of userlists.socialAccount"> 
        <li>{{account}}</li> 
    </ul>

 </ul>

app.component.ts  -----------file
userlists = [
    { name: 'bilal', phone: '99999', socialAccount:['fcebook', 'insta', 'gmail'] },
    { name: 'sahim', phone: '77777' , socialAccount:['youtube', 'Tiktok', 'hbl banking']},
    { name: 'tayyab', phone: '2238' , socialAccount:['yahoo', 'indeed', 'likee'] },
    { name: 'sohaib', phone: '66666' , socialAccount:['linkedin', 'rozee', 'whatsapp'] }
  ];

**Comment by ericgio** [comment]
Hey @fida2013, I'm unclear on the problem you're encountering here. It doesn't seem to be related to the typeahead code itself; is it a TS issue? It's hard for me to diagnose your issue based on the information you provided, but it looks like the type is an array of objects and TS is looking for the object property, which would indeed be absent.
