### ISSUE TITLE
Disabled Options

### ISSUE THREAD

**Issue by mxmtsk** [ericgio/react-bootstrap-typeahead#86]
Hi,

I don't think it's possible yet to disable certain options. For example I have a list of products  but only certain ones are in stock, so I'd like them to show up in the typeahead but they shouldn't be selectable. 

Would you consider adding this? I'd appreciate it!

**Comment by ericgio** [comment]
I think the easiest thing given the current API is to allow developers to set a `disabled` property in the data passed in and have that control whether the item was disabled or not. Does that work?

**Comment by mxmtsk** [comment]
Sure, something like this would be perfect!

**Comment by ericgio** [comment]
Added in v0.10.0. Still undocumented, but works as described above, eg:
```jsx
var myData = [
  {label: 'This option is not disabled'},
  {label: 'This option is also not disabled'},
  {label: 'This option is disabled!', disabled: true},
];
```
