### ISSUE TITLE
Typeahead menu remains opened onBlur when rendered inside a Modal

### ISSUE THREAD

**Issue by Michele-Masciave** [ericgio/react-bootstrap-typeahead#860]
The Typeahead menu is not working properly when it is rendered inside a reactstrap Modal: the menu remains open `onBlur`, while in any other context it automatically closes.

### Version

```
"react-bootstrap-typeahead": "6.1.2"
"reactstrap": "9.1.5"
"bootstrap": "5.3.3"
```

### Steps to reproduce

1. Render the Typeahead inside a reactstrap Modal.
2. Open the modal
3. Click on the Typeahead for showing the options
4. Click elsewhere

**Starter sandbox:**  https://codesandbox.io/p/sandbox/react-typeahead-in-a-reactstrap-modal-7gpcjt

### Expected Behavior

I expect the typeahead menu to be closed `onBlur`, as it behave in any other context.

### Actual Behavior

The typeahead menu remains opened `onBlur` when it is rendered inside a reactstrap Modal.

**Comment by ericgio** [comment]
This appears to be a known issue with React 17+; please see #703 and #775. There are a couple workarounds mentioned in those threads. Unfortunately, this doesn't seem to be something I can fix in the typeahead library itself.
