### ISSUE TITLE
Disabled option is still selectable accepting hint on Tab

### ISSUE THREAD

**Issue by Michele-Masciave** [ericgio/react-bootstrap-typeahead#865]
A disabled option is still selectable accepting an hint on Tab.

### Version

```
"react-bootstrap-typeahead": "6.3.2"
"reactstrap": "9.2.3"
"bootstrap": "5.3.3"
"react": "18.2"
```

**Sandbox:** https://codesandbox.io/p/sandbox/select-disabled-options-ontab-8kq3mn?file=%2Fsrc%2FApp.tsx%3A8%2C42

### Expected Behavior

Disabled options **not** selectable when accepting the hint on Tab.

### Actual Behavior

Disabled options are selectable on Tab even if they are disabled.

**Comment by ericgio** [comment]
Fixed in v6.3.4
