### ISSUE TITLE
Add hinting for multiple-selection mode

### ISSUE THREAD

**Issue by viridia** [ericgio/react-bootstrap-typeahead#88]
This can be seen in the demo page: if you are typing while multiple selection is disabled, you can see the grayed out name of the first suggestion under your cursor, but if you turn on multiple selection this no longer displays.

**Comment by ericgio** [comment]
Yes, that's currently the expected behavior. Unfortunately I haven't had a chance to implement hinting for the multi-select version.

**Comment by ericgio** [comment]
Added in v3.0.0
