### ISSUE TITLE
Option to supress empty list indicator

### ISSUE THREAD

**Issue by viridia** [ericgio/react-bootstrap-typeahead#89]
My use case is for an 'autosuggest' input field which provides suggestions of strings that you have previously typed in that field. In this case, telling the user that there's nothing to suggest, or that this is a new item, is a distraction to the user and I'd like to suppress it.

You wouldn't even need to add new options: simply check if 'emptyLabel' and 'newSelectionPrefix' are falsey (either empty string or the value 'false') and if so don't create menu items for them, and also don't show the menu if there are no items.

**Comment by ericgio** [comment]
Yeah, there's currently no nice way to do this as written. You might be able hack something together using a combination of the user's input and the `minLength` prop to manually suppress the menu if there are no results.

**Comment by ericgio** [comment]
With #102, you'd have complete control over rendering of the menu, which should address this.
