### ISSUE TITLE
ES6 babel compilation problem

### ISSUE THREAD

**Issue by dmk23** [ericgio/react-bootstrap-typeahead#9]
I'm trying to add this module my my Babel/Webpack project and getting this error on compilation:

```
ERROR in ./~/react-bootstrap-typeahead/css/Typeahead.css
Module parse failed: /root/node_modules/react-bootstrap-typeahead/css/Typeahead.css Line 1: Unexpected token .
You may need an appropriate loader to handle this file type.
| .bootstrap-typeahead .dropdown-menu {
|   overflow: scroll;
| }
 @ ./~/react-bootstrap-typeahead/lib/Typeahead.react.js 33:0-31

ERROR in ./~/react-bootstrap-typeahead/css/Token.css
Module parse failed: /root/node_modules/react-bootstrap-typeahead/css/Token.css Line 2: Unexpected token .
You may need an appropriate loader to handle this file type.
| /* Token */
| .bootstrap-tokenizer .token {
|   background-color: #e7f4ff;
|   border: 0;
 @ ./~/react-bootstrap-typeahead/lib/Token.react.js 27:0-27
```

Seems to me the issue is about how CSS is loaded/complied, but I'm not quite sure what is the best way to handle it for this module. It would be great to have some clear instructions for use with ES6...

**Comment by ericgio** [comment]
You need to use `[css-loader](https://www.npmjs.com/package/css-loader)` and/or `[style-loader](https://www.npmjs.com/package/style-loader)` in your webpack config:

```
// webpack.config.js
module: {
  loaders: [
    {test: /\.(css|scss})$/, loader: 'style-loader!css-loader'},
    ...
  ],
},
```

Fair point about adding documentation. If I don't end up pulling the CSS out of the JS files, I will definitely add documentation.

**Comment by dmk23** [comment]
Your code fixed the compilation problem and I was able to get the component working!

**Comment by ericgio** [comment]
The README now has documentation about the CSS, fyi.
