### ISSUE TITLE
Strange warning using multiple selection

### ISSUE THREAD

**Issue by krembo** [ericgio/react-bootstrap-typeahead#90]
I got this strange warning on my typeahead components, with multiple selection:

![image](https://cloud.githubusercontent.com/assets/3259644/19125691/b8046f7a-8b40-11e6-87a3-836e13764d6a.png)

Does anyone have any idea what is causing this?

**Comment by ericgio** [comment]
Can you post your code?

**Comment by ericgio** [comment]
Also, what version of the component are you using? This appears to be a React warning due to the `react-onclick-outside` HOC applying invalid props to a div.

**Comment by krembo** [comment]
0.9.4 looks like it's the latest version.

Simple usage:

```JavaScript
				<Row>
					<Col xs={12} sm={6}>
						<FormGroup>
							<ControlLabel>Dances</ControlLabel>
								<Typeahead
										multiple
										options={dances}
										selected={editingLevel.dances}
										onChange={updateLevelForm}
									 />
						</FormGroup>
					</Col>
				</Row>
```

**dances** is array with strings, 
**editingLevel.dances** is array that come from store object that holds form state
Nothing really special here.

**Comment by davidostermann** [comment]
I had the same problem. I fix it forcing react-onclickoutside version under 5.4.
npm install react-onclickoutside@5.3.3 --save fix the probleme for me

**Comment by krembo** [comment]
Cool, thanks! Will try that.

**Comment by ericgio** [comment]
`react-bootstrap-typeahead` uses `react-onclickoutside`@5.3.3. Is your app using a higher version?

**Comment by ericgio** [comment]
I'm going to close this out, since I'm pretty sure it's just a package conflict. Will look into upgrading the package at some point.

**Comment by krembo** [comment]
Hi, didn't see you replied too. I used the default versions of `react-bootstrap-typeahead`. 
But due to semantic versioning syntax it installs latest major version under 6.0.0, that is 5.7.2 currenly.

**Comment by ericgio** [comment]
@evinak submitted [a fix](https://github.com/ericgio/react-bootstrap-typeahead/pull/100) for this issue. Will publish as 0.10.2.
