### ISSUE TITLE
Support for filtering on ID

### ISSUE THREAD

**Issue by herecydev** [ericgio/react-bootstrap-typeahead#91]
It would be good if the ID could be included in the filtering. This is very useful in scenarios, like business processes, bus routes, flight numbers etc. Where they usually have a description associated to them but are often know or aliased by their ID.

I appreciate you have a mechanism of allowing user-provided filtering, but it would be ideal not to duplicate what is already in place. I would envision that the option would feel similar to the following:

```HTML
<Typeahead
  onChange={this._handleChange}
  options={myData}
  selected={selected}
  idFilterable={true}
/>
```

**Comment by ericgio** [comment]
So what would the behavior be? From your description, it sounds like you'd be able to enter an id, but the name would still show up in the dropdown and upon selection, is that right?

Given that there is already a way to do this — as you point out — I'm not really inclined to add it by default. My goal with this component is to provide basic functionality and behaviors out of the box, and give developers a flexible API to customize it for their needs. I don't want to explicitly account for every use case, since that would result in a bloated component.

**Comment by herecydev** [comment]
I totally agree with your concepts, it should be extensible and I can understand your stance. Perhaps there's a better way to provide that extensibility? If I have to copy your algorithm just so I can **add** to it then something feels wrong there; if you release a patch that needs to be rebased, etc. Could the filter function take either an array (of columns to search) or a function (complete override) and work with that?

**Comment by ericgio** [comment]
> Could the filter function take ... a function (complete override) and work with that?

`filterBy` is currently a complete override of the internal filtering algorithm. So whatever you pass in will be used and the default will be ignored. Or am I misunderstanding your question?

**Comment by herecydev** [comment]
I was asking for the option to accept **either** an array **or** a function. Where the array would extend the searchable columns, and the function would the complete override.

**Comment by ericgio** [comment]
I see, thanks for clarifying. I think I've seen that kind of thing before, so it certainly seems possible. I'd have to look into it a bit more, though. If you have any good examples let me know.

**Comment by herecydev** [comment]
Sure, I'll gather some thoughts and try and find something. I think it's best for something to be extensible before being pluggable/replaceable so hopefully we'll find something that fits well.

**Comment by herecydev** [comment]
Typescript has a section about [union types](https://www.typescriptlang.org/docs/handbook/advanced-types.html) which was what I was describing, they have a small example there. I appreciate your not writing in TS but I'm sure you can see the parallels.

**Comment by ericgio** [comment]
Added this in v0.10.0. Let me know what you think of the API and how it works for you.

https://github.com/ericgio/react-bootstrap-typeahead#filterby-prop

**Comment by herecydev** [comment]
It certainly looks promising. I'll try and test that over the next week or so.
