### ISSUE TITLE
Typeahead shows up as two boxes

### ISSUE THREAD

**Issue by nareshbhatia** [ericgio/react-bootstrap-typeahead#92]
I have been using the react-bootstrap-typeahead in my application - it's been working extremely well. Love it!

However, today I tried to place it in a new screen (same application) and it is showing up as two overlapping boxes (see below). Has anyone experienced this? Any clues on how to fix this?

![image](https://cloud.githubusercontent.com/assets/1220198/19179832/398ec088-8c2f-11e6-9bc1-5fae7b7b294b.png)

**Comment by ericgio** [comment]
Looks like you have some css on your page that is modifying `input` elements or possibly the Bootstrap `.form-control` class.

**Comment by nareshbhatia** [comment]
@ericgio, you hit it on the head. Yes, there is a `.form-control` coming from a css file which I have not included on this page - I need to figure out how it is getting there. However, can you please clarify if this typeahead can or cannot be wrapped in a `.form-control`?

**Comment by nareshbhatia** [comment]
@ericgio, I think I figured out the answer to my question above. The typeahead adds `.form-control` to its input boxes internally. Hence there should **not** be a `.form-control` in any higher level elements. The moment I removed the extraneous `.form-control`, the component strated working normally. Thanks for all your help.

**Comment by ericgio** [comment]
No problem, glad you solved the issue.
